In [434]:
from mootdx.quotes import Quotes
import pandas as pd
import plotly.express as px
import re

StockCode = '600166'
qf10='经营分析'
client = Quotes.factory(market='std')
txtRaw = client.F10(StockCode, qf10)
txt = txtRaw[116:]

In [289]:
StockName = re.findall(r'\b'+StockCode+'\s+([^\s]*)',txtRaw)[0]

In [381]:
hc = re.findall(r'\d+.\d+|\d+%',re.findall(r'前5大客户[^\s]*',txt)[0])

In [391]:
pd.DataFrame(hc+hp).T

        0      1       2      3
0  136.99  24.42  159.38  32.06

In [382]:
hp = re.findall(r'\d+\.\d+|\d+%',re.findall(r'前5大供应商[^\s]*',txt)[0])

In [392]:
csdf = pd.DataFrame(hc+hp).T
csdf.columns = ["营收额","营收占比",'采购额',"采购占比"]

In [394]:
csdf['StockCode'] = StockCode
csdf['StockName'] = StockName

In [395]:
csdf

      营收额   营收占比     采购额   采购占比 StockCode StockName
0  136.99  24.42  159.38  32.06    600166      福田汽车

In [435]:
fi = txt[txt.find('【2.主营构成分析】'):]
ff = fi[:fi.find('【3.前5名客户营业收入表】')]
datetimes=re.findall(r'截止日期:([^\s]*)', ff)

In [320]:
# re.findall(r'截止日期:([^\s]*)', ff)
# re.findall(r'截止日期:(\S{10})', ff)

['2024-06-30', '2023-12-31', '2023-06-30', '2022-12-31']

In [436]:
dd = ff.replace('─','').splitlines(keepends=False)

In [437]:

# Data = pd.DataFrame(columns=("股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"))
Data = pd.DataFrame(columns=())
i = 0
while i < len(dd):
    lis = re.split(r"\s+", dd[i])[-6:]
    if len(lis)!=6:
        i = i+1
        # pass
    else:
        df = pd.DataFrame(lis).T
        # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
        Data = pd.concat([Data, df],axis=0)
        i=i+1
Data.reset_index(drop=True,inplace=True)
Data = Data.replace('---',pd.NA)
# ddf  = Data.apply(pd.to_numeric, errors='ignore')

In [439]:
ddf = Data

In [440]:
ddfindex = ddf[ddf[0]=='项目名'].index

In [441]:
ddfindex

Int64Index([0, 8, 24, 32], dtype='int64')

In [442]:
i = 0
raDF = pd.DataFrame(columns=['日期',"项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"])

In [443]:
for i in [0,1,2]:
    dfd = ddf.loc[(ddfindex[i]+1):(ddfindex[i+1]-1)].reset_index(drop=True)
    dfd.columns = ["项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]
    dfd['日期'] = datetimes[i]
    raDF = pd.concat([raDF,dfd], axis=0)

In [444]:
raDF['StockCode'] = StockCode
raDF['StockName'] = StockName

In [446]:
raDF.set_index('日期')

,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%),StockCode,StockName
日期,,,,,,,,
2024-06-30,轻型车分部(产品),268.83亿,112.16,13.74亿,45.82,5.11,600166,福田汽车
2024-06-30,海外分部(产品),71.31亿,29.75,8.59亿,28.67,12.05,600166,福田汽车
2024-06-30,管理及研发分部(产品),62.42亿,26.04,10.07亿,33.59,16.13,600166,福田汽车
2024-06-30,大中客分部(产品),34.53亿,14.41,1.69亿,5.65,4.90,600166,福田汽车
2024-06-30,发动机分部(产品),14.22亿,5.93,2.75亿,9.18,19.34,600166,福田汽车
2024-06-30,其他分部(产品),4841.52万,0.20,3962.62万,1.32,81.85,600166,福田汽车
2024-06-30,分部间抵销(产品),-212.11亿,-88.50,-7.26亿,-24.21,3.42,600166,福田汽车
2023-12-31,汽车行业(行业),534.35亿,95.26,57.72亿,90.41,10.80,600166,福田汽车
2023-12-31,其他业务(行业),26.62亿,4.74,6.12亿,9.59,22.99,600166,福田汽车
2023-12-31,轻卡(产品),266.37亿,47.48,23.88亿,37.40,8.96,600166,福田汽车
2023-12-31,发动机(产品),68.91亿,12.28,2.45亿,3.85,3.56,600166,福田汽车
2023-12-31,中重卡(产品),67.34亿,12.00,13.57亿,21.25,20.15,600166,福田汽车
2023-12-31,轻客(产品),50.69亿,9.04,7.92亿,12.40,15.62,600166,福田汽车
2023-12-31,大中客(产品),41.29亿,7.36,5.12亿,8.02,12.41,600166,福田汽车
2023-12-31,配件(产品),39.05亿,6.96,4.68亿,7.32,11.97,600166,福田汽车
2023-12-31,其他(产品),26.62亿,4.74,6.12亿,9.59,22.99,600166,福田汽车
2023-12-31,冲压件(产品),5623.20万,0.10,876.87万,0.14,15.59,600166,福田汽车
2023-12-31,重型机械(产品),1483.79万,0.03,170.30万,0.03,11.48,600166,福田汽车
2023-12-31,中国大陆境内(地区),429.07亿,76.49,41.78亿,65.45,9.74,600166,福田汽车
2023-12-31,其他国家及地区(地区),131.89亿,23.51,22.06亿,34.55,16.72,600166,福田汽车
2023-12-31,代理销售(销售模式),466.07亿,83.08,52.31亿,81.94,11.22,600166,福田汽车
2023-12-31,其他(销售模式),94.90亿,16.92,11.53亿,18.06,12.15,600166,福田汽车
2023-06-30,轻型车分部(产品),297.36亿,103.09,-5.73亿,-16.95,-1.93,600166,福田汽车
2023-06-30,海外分部(产品),95.38亿,33.07,7.40亿,21.91,7.76,600166,福田汽车
2023-06-30,管理及研发分部(产品),69.42亿,24.07,6838.89万,2.02,0.99,600166,福田汽车
2023-06-30,大中客分部(产品),60.53亿,20.98,8703.48万,2.58,1.44,600166,福田汽车
2023-06-30,发动机分部(产品),10.87亿,3.77,-2943.88万,-0.87,-2.71,600166,福田汽车
2023-06-30,其他分部(产品),6038.45万,0.21,2980.56万,0.88,49.36,600166,福田汽车
2023-06-30,分部间抵销(产品),-245.72亿,-85.18,7337.14万,2.17,-0.30,600166,福田汽车

In [346]:
dfd.set_index('日期')

                    项目名   营业收入(元) 收入比例(%)   营业利润(元) 利润比例(%) 毛利率(%)
日期
2024-06-30    轻型车分部(产品)   268.83亿  112.16    13.74亿   45.82   5.11
2024-06-30     海外分部(产品)    71.31亿   29.75     8.59亿   28.67  12.05
2024-06-30  管理及研发分部(产品)    62.42亿   26.04    10.07亿   33.59  16.13
2024-06-30    大中客分部(产品)    34.53亿   14.41     1.69亿    5.65   4.90
2024-06-30    发动机分部(产品)    14.22亿    5.93     2.75亿    9.18  19.34
2024-06-30     其他分部(产品)  4841.52万    0.20  3962.62万    1.32  81.85
2024-06-30    分部间抵销(产品)  -212.11亿  -88.50    -7.26亿  -24.21   3.42

In [331]:
dfd[dfd['项目名'].str.contains('行业', na=False)]

Empty DataFrame
Columns: [项目名, 营业收入(元), 收入比例(%), 营业利润(元), 利润比例(%), 毛利率(%), 日期]
Index: []

In [330]:
dfd[dfd['项目名'].str.contains('产品', na=False)]

           项目名   营业收入(元) 收入比例(%)   营业利润(元) 利润比例(%) 毛利率(%)          日期
0    轻型车分部(产品)   268.83亿  112.16    13.74亿   45.82   5.11  2024-06-30
1     海外分部(产品)    71.31亿   29.75     8.59亿   28.67  12.05  2024-06-30
2  管理及研发分部(产品)    62.42亿   26.04    10.07亿   33.59  16.13  2024-06-30
3    大中客分部(产品)    34.53亿   14.41     1.69亿    5.65   4.90  2024-06-30
4    发动机分部(产品)    14.22亿    5.93     2.75亿    9.18  19.34  2024-06-30
5     其他分部(产品)  4841.52万    0.20  3962.62万    1.32  81.85  2024-06-30
6    分部间抵销(产品)  -212.11亿  -88.50    -7.26亿  -24.21   3.42  2024-06-30

In [329]:
dfd[dfd['项目名'].str.contains('产品', na=False)]['利润比例(%)'].astype(float).sum()

100.02000000000001

In [400]:
def getBiz(StockCode):
    qf10='经营分析'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)
    txt = txtRaw[116:]

    StockName = re.findall(r'\b'+StockCode+'\s+([^\s]*)',txtRaw)[0]
    try:
        hc = re.findall(r'\d+.\d+|\d+%',re.findall(r'前5大客户[^\s]*',txt)[0])
        hp = re.findall(r'\d+\.\d+|\d+%',re.findall(r'前5大供应商[^\s]*',txt)[0])
        csdf = pd.DataFrame(hc+hp).T
        csdf.columns = ["营收额","营收占比",'采购额',"采购占比"]
        csdf['StockCode'] = StockCode
        csdf['StockName'] = StockName


    except:
        pass

    fi = txt[txt.find('【2.主营构成分析】'):]
    ff = fi[:fi.find('【3.前5名客户营业收入表】')]
    datetimes=re.findall(r'截止日期:([^\s]*)', ff)
    dd = ff.replace('─','').splitlines(keepends=False)

    Data = pd.DataFrame(columns=())
    i = 0
    while i < len(dd):
        lis = re.split(r"\s+", dd[i])[-6:]
        if len(lis)!=6:
            i = i+1
            # pass
        else:
            df = pd.DataFrame(lis).T
            # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
            Data = pd.concat([Data, df],axis=0)
            i=i+1
    Data.reset_index(drop=True,inplace=True)
    Data = Data.replace('---',0)
    ddf  = Data.apply(pd.to_numeric, errors='ignore')

    ddfindex = ddf[ddf[0]=='项目名'].index
    raDF = pd.DataFrame(columns=['日期',"项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"])

    for i in [0,1,2]:
        dfd = ddf.loc[(ddfindex[i]+1):(ddfindex[i+1]-1)].reset_index(drop=True)
        dfd.columns = ["项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]
        dfd['日期'] = datetimes[i]
        raDF = pd.concat([raDF,dfd], axis=0)

    raDF['StockCode'] = StockCode
    raDF['StockName'] = StockName
    # raDF.set_index('日期').to_sql('Biz', eng, if_exists='append')
    return(raDF,csdf)

In [409]:
from sqlalchemy import create_engine
engs = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxStocks')

In [429]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [448]:
StockList.iloc[0,0]

'000001'

In [428]:
pd.read_sql('StocksList', engs)[['code','name']].loc[0][1]

'平安银行'

In [433]:

StockList.loc[15][1]

'深科技'