In [605]:
from mootdx.quotes import Quotes
import pandas as pd
import plotly.express as px
import re

StockCode = '600166'
qf10='经营分析'
client = Quotes.factory(market='std')
txtRaw = client.F10(StockCode, qf10)
txt = txtRaw[116:]

In [ ]:
txt

In [289]:
StockName = re.findall(r'\b'+StockCode+'\s+([^\s]*)',txtRaw)[0]

In [381]:
hc = re.findall(r'\d+.\d+|\d+%',re.findall(r'前5大客户[^\s]*',txt)[0])

In [391]:
pd.DataFrame(hc+hp).T

In [382]:
hp = re.findall(r'\d+\.\d+|\d+%',re.findall(r'前5大供应商[^\s]*',txt)[0])

In [392]:
csdf = pd.DataFrame(hc+hp).T
csdf.columns = ["营收额","营收占比",'采购额',"采购占比"]

In [394]:
csdf['StockCode'] = StockCode
csdf['StockName'] = StockName

In [395]:
csdf

In [607]:
fi = txt[txt.find('【2.主营构成分析】'):]
ff = fi[:fi.find('【3.前5名客户营业收入表】')]
datetimes=re.findall(r'截止日期:([^\s]*)', ff)

In [ ]:
ff

In [320]:
# re.findall(r'截止日期:([^\s]*)', ff)
# re.findall(r'截止日期:(\S{10})', ff)

In [609]:
dd = ff.replace('─','').splitlines(keepends=False)

In [ ]:
dd

In [437]:

# Data = pd.DataFrame(columns=("股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"))
Data = pd.DataFrame(columns=())
i = 0
while i < len(dd):
    lis = re.split(r"\s+", dd[i])[-6:]
    if len(lis)!=6:
        i = i+1
        # pass
    else:
        df = pd.DataFrame(lis).T
        # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
        Data = pd.concat([Data, df],axis=0)
        i=i+1
Data.reset_index(drop=True,inplace=True)
Data = Data.replace('---',pd.NA)
# ddf  = Data.apply(pd.to_numeric, errors='ignore')

In [439]:
ddf = Data

In [440]:
ddfindex = ddf[ddf[0]=='项目名'].index

In [441]:
ddfindex

In [442]:
i = 0
raDF = pd.DataFrame(columns=['日期',"项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"])

In [443]:
for i in [0,1,2]:
    dfd = ddf.loc[(ddfindex[i]+1):(ddfindex[i+1]-1)].reset_index(drop=True)
    dfd.columns = ["项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]
    dfd['日期'] = datetimes[i]
    raDF = pd.concat([raDF,dfd], axis=0)

In [444]:
raDF['StockCode'] = StockCode
raDF['StockName'] = StockName

In [446]:
raDF.set_index('日期')

In [346]:
dfd.set_index('日期')

In [331]:
dfd[dfd['项目名'].str.contains('行业', na=False)]

In [330]:
dfd[dfd['项目名'].str.contains('产品', na=False)]

In [329]:
dfd[dfd['项目名'].str.contains('产品', na=False)]['利润比例(%)'].astype(float).sum()

In [650]:
def getBiz(StockCode):
    qf10='经营分析'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)[116:]   
    # txt = txtRaw[116:]

    StockName = re.findall(r'\b'+StockCode+'\s+([^\s]*)',txtRaw)[0]
    try:
        hc = re.findall(r'\d+.\d+|\d+%',re.findall(r'前5大客户[^\s]*',txt)[0])
        hp = re.findall(r'\d+\.\d+|\d+%',re.findall(r'前5大供应商[^\s]*',txt)[0])
        csdf = pd.DataFrame(hc+hp).T
        csdf.columns = ["营收额","营收占比",'采购额',"采购占比"]
        csdf['StockCode'] = StockCode
        csdf['StockName'] = StockName


    except:
        pass

    fi = txt[txt.find('【2.主营构成分析】'):]
    ff = fi[:fi.find('【3.前5名客户营业收入表】')]
    datetimes=re.findall(r'截止日期:([^\s]*)', ff)
    dd = ff.replace('─','').splitlines(keepends=False)

    Data = pd.DataFrame(columns=())
    i = 0
    while i < len(dd):
        lis = re.split(r"\s+", dd[i])[-6:]
        if len(lis)!=6:
            i = i+1
            # pass
        else:
            df = pd.DataFrame(lis).T
            # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
            Data = pd.concat([Data, df],axis=0)
            i=i+1
    Data.reset_index(drop=True,inplace=True)
    Data = Data.replace('---',0)
    ddf  = Data.apply(pd.to_numeric, errors='ignore')

    ddfindex = ddf[ddf[0]=='项目名'].index
    raDF = pd.DataFrame(columns=['日期',"项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"])

    for i in [0,1,2]:
        dfd = ddf.loc[(ddfindex[i]+1):(ddfindex[i+1]-1)].reset_index(drop=True)
        dfd.columns = ["项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]
        dfd['日期'] = datetimes[i]
        raDF = pd.concat([raDF,dfd], axis=0)

    raDF['StockCode'] = StockCode
    raDF['StockName'] = StockName
    # raDF.set_index('日期').to_sql('Biz', eng, if_exists='append')
    return(raDF,csdf)

In [651]:
a,b = getBiz('000005')

In [ ]:
list(a['项目名'])[2]

In [409]:
from sqlalchemy import create_engine
engs = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxStocks')

In [429]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [448]:
StockList.iloc[0,0]

In [428]:
pd.read_sql('StocksList', engs)[['code','name']].loc[0][1]

In [433]:

StockList.loc[15][1]

================== 热点题材

In [592]:
from mootdx.quotes import Quotes
import pandas as pd
import plotly.express as px
import re


qf10='热点题材'
client = Quotes.factory(market='std')
txt = client.F10(StockCode, qf10)[116:]

In [546]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [564]:
n = 100

In [565]:
StockCode = StockList.iloc[n,0]
StockName = StockList.iloc[n,1]

In [567]:
ftxt = re.findall(r'│(.*)│(关联度.*☆{4,})',txt)

In [568]:
ftdf = pd.DataFrame(ftxt)

In [569]:
ftdf = ftdf.applymap(lambda x: x.rstrip() if isinstance(x, str) else x)

In [570]:
ftdf[1]=ftdf[1].str.len()-4

In [571]:
ftdf

In [572]:
ftdf.columns=['题材','相关度']

In [573]:
ftdf['StockCode']=StockCode
ftdf['StockName']=StockName

In [694]:
def getTop(StockCode, StockName):
    qf10='热点题材'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)[116:]

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)

    txt = re.findall(r'│(.*)│(关联度.*☆{4,})',txtRaw)
    txDF = pd.DataFrame(txt)
    txDF = txDF.applymap(lambda x: x.rstrip() if isinstance(x, str) else x)
    txDF[1]=txDF[1].str.len()-4
    txDF.columns=['题材','相关度']
    txDF['StockCode'] = StockCode
    txDF['StockName'] = StockName
    # txDF.set_index('StockCode').to_sql('Top', eng, if_exist='append')
    return(txDF)

In [ ]:
getTop(StockCode,StockName)

======================= 价值分析

In [660]:
from mootdx.quotes import Quotes
import pandas as pd
import re
from sqlalchemy import create_engine

eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/StockBas')
engs = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxStocks')

StockList = pd.read_sql('StocksList', engs)[['code','name']]
n = 1

StockCode = StockList.iloc[n,0]
StockName = StockList.iloc[n,1]


qf10='价值分析'
client = Quotes.factory(market='std')
txtRaw = client.F10(StockCode, qf10)[116:]
txt = txtRaw.replace('│',' ')                
txt = re.sub('([\u2500-\u25f7])','',txt)

In [673]:
ftxt = txt[txt.find('【2.盈利预测统计】'):]
etxt = ftxt[:ftxt.find('【3.盈利预测明细】')]
dd = etxt.splitlines(keepends=False)

In [ ]:
dd

In [675]:
Data = pd.DataFrame(columns=())
i = 0
while i < len(dd):
    lis = dd[i].split()
    if len(lis)!=7:
        i = i+1
        # pass
    else:
        df = pd.DataFrame(lis).T
        # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
        Data = pd.concat([Data, df],axis=0)
        i=i+1
Data.reset_index(drop=True,inplace=True)
Data = Data.replace('---',pd.NA)

In [ ]:
Data.loc[0]

In [677]:
Data.columns=list(Data.loc[0])

In [ ]:
Data

In [679]:
Data['StockCode'] = StockCode
Data['StockName'] = StockName

In [ ]:
Data

In [692]:
def getFcast(StockCode, StockName):
    qf10='价值分析'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)[116:]

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)
    
    ftxt = txt[txt.find('【2.盈利预测统计】'):]
    etxt = ftxt[:ftxt.find('【3.盈利预测明细】')]
    dd = etxt.splitlines(keepends=False)

    Data = pd.DataFrame(columns=())
    i = 0
    while i < len(dd):
        lis = dd[i].split()
        if len(lis)!=7:
            pass
        else:
            df = pd.DataFrame(lis).T
            Data = pd.concat([Data, df],axis=0)
        i=i+1
    Data.reset_index(drop=True,inplace=True)
    Data = Data.replace('---',pd.NA)

    Data.columns=list(Data.loc[0])
    Data['StockCode'] = StockCode
    Data['StockName'] = StockName

    return(Data.tail(-1))

====================== 数据库数据分析 StockBas
1、BizP  前5大商业合作营业占比
2、Fcast 3年预测
3、Top   题材相似度
4、mBiz  主营业务产品占比

In [5]:
import pandas as pd
from sqlalchemy import create_engine
import plotly.express as px

eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/StockBas')

In [55]:
df = pd.read_sql('Top', eng)

In [ ]:
df['题材'].str.contains('券商', na=False)

In [125]:
df = pd.read_sql('mBiz', eng)

In [126]:
df

,日期,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%),StockCode,StockName
0,2024-06-30,房地产开发及相关资产经营业务(行业),1233.99亿,86.43,89.42亿,77.17,7.25,000002,万科A
1,2024-06-30,物业服务(行业),159.99亿,11.21,21.84亿,18.85,13.65,000002,万科A
2,2024-06-30,其他业务(行业),33.81亿,2.37,4.61亿,3.98,13.63,000002,万科A
3,2024-06-30,上海区域(地区),443.25亿,31.04,None,None,None,000002,万科A
4,2024-06-30,南方区域(地区),276.22亿,19.35,None,None,None,000002,万科A
...,...,...,...,...,...,...,...,...,...
165468,2023-06-30,境内(地区),22.89亿,52.25,None,None,None,689009,九号公司-WD
165469,2023-06-30,境外(地区),20.91亿,47.75,None,None,None,689009,九号公司-WD
165470,2023-06-30,自主品牌销售(销售模式),32.20亿,73.52,None,None,None,689009,九号公司-WD
165471,2023-06-30,ToB产品销售(销售模式),7.98亿,18.21,None,None,None,689009,九号公司-WD
165472,2023-06-30,定制产品分销(销售模式),3.62亿,8.27,None,None,None,689009,九号公司-WD

In [ ]:
df['项目名']

In [130]:
ddf = df[df['项目名'].str.endswith('(行业)')][df[df['项目名'].str.endswith('(行业)')]['日期']=='2023-12-31'].reset_index(drop=True)

In [132]:
ddf

,日期,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%),StockCode,StockName
0,2023-12-31,房地产开发及相关资产经营业务(行业),4297.46亿,92.27,662.32亿,93.34,15.41,000002,万科A
1,2023-12-31,物业服务(行业),294.27亿,6.32,44.02亿,6.20,14.96,000002,万科A
2,2023-12-31,其他业务(行业),65.66亿,1.41,3.20亿,0.45,4.88,000002,万科A
3,2023-12-31,移动网络安全业务(行业),1.05亿,95.01,None,None,None,000004,国华网安
4,2023-12-31,应急业务(行业),453.64万,4.12,142.13万,2.24,31.33,000004,国华网安
...,...,...,...,...,...,...,...,...,...
13213,2023-12-31,其他业务(行业),24.37亿,5.10,1.49亿,1.77,6.10,688819,天能股份
13214,2023-12-31,集成电路行业(行业),445.93亿,98.55,98.90亿,99.86,22.18,688981,中芯国际
13215,2023-12-31,其他业务(行业),6.57亿,1.45,1387.90万,0.14,2.11,688981,中芯国际
13216,2023-12-31,智能短交通(行业),99.36亿,97.20,25.98亿,94.47,26.14,689009,九号公司-WD
13217,2023-12-31,智能服务机器人(行业),2.86亿,2.80,1.52亿,5.53,53.15,689009,九号公司-WD

In [113]:
dddf = df[df['项目名'].str.endswith('(产品)')][df[df['项目名'].str.endswith('(产品)')]['日期']=='2023-12-31'].reset_index(drop=True)

In [ ]:
ddf

In [ ]:
dddf

In [137]:
dddf[dddf['收入比例(%)'].astype(float)>20]

,日期,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%),StockCode,StockName
0,2023-12-31,安全加固检测类(产品),4681.25万,42.54,2756.77万,43.49,58.89,000004,国华网安
1,2023-12-31,安全检测类产品(产品),2727.18万,24.78,1664.46万,26.26,61.03,000004,国华网安
12,2023-12-31,房产销售(产品),26.49亿,94.24,10.13亿,92.12,38.23,000006,深振业A
16,2023-12-31,汽车销售及相关服务(产品),1.33亿,61.40,416.75万,8.94,3.14,000007,全新好
23,2023-12-31,轨道交通运营检修装备(产品),22.94亿,91.32,5.51亿,89.89,24.03,000008,神州高铁
...,...,...,...,...,...,...,...,...,...
23235,2023-12-31,新能源连接器(产品),13.67亿,87.92,3.43亿,88.01,25.10,688800,瑞可达
23239,2023-12-31,铅蓄电池(产品),444.07亿,93.00,83.65亿,99.83,18.84,688819,天能股份
23242,2023-12-31,集成电路晶圆制造代工(产品),408.75亿,90.33,82.32亿,83.11,20.14,688981,中芯国际
23245,2023-12-31,电动两轮车(产品),42.32亿,41.40,8.15亿,29.65,19.27,689009,九号公司-WD
23246,2023-12-31,电动平衡车和电动滑板车(产品),34.88亿,34.12,10.27亿,37.35,29.45,689009,九号公司-WD

In [ ]:
ddf[ddf['StockCode']=='000002']

In [135]:
ddf['项目名'] = ddf['项目名'].str.replace('\(行业\)', '')

/tmp/ipykernel_415528/416867705.py:1: FutureWarning: The default value of regex will change from True to False in a future version.
  ddf['项目名'] = ddf['项目名'].str.replace('\(行业\)', '')

In [136]:
ddf

,日期,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%),StockCode,StockName
0,2023-12-31,房地产开发及相关资产经营业务,4297.46亿,92.27,662.32亿,93.34,15.41,000002,万科A
1,2023-12-31,物业服务,294.27亿,6.32,44.02亿,6.20,14.96,000002,万科A
2,2023-12-31,其他业务,65.66亿,1.41,3.20亿,0.45,4.88,000002,万科A
3,2023-12-31,移动网络安全业务,1.05亿,95.01,None,None,None,000004,国华网安
4,2023-12-31,应急业务,453.64万,4.12,142.13万,2.24,31.33,000004,国华网安
...,...,...,...,...,...,...,...,...,...
13213,2023-12-31,其他业务,24.37亿,5.10,1.49亿,1.77,6.10,688819,天能股份
13214,2023-12-31,集成电路行业,445.93亿,98.55,98.90亿,99.86,22.18,688981,中芯国际
13215,2023-12-31,其他业务,6.57亿,1.45,1387.90万,0.14,2.11,688981,中芯国际
13216,2023-12-31,智能短交通,99.36亿,97.20,25.98亿,94.47,26.14,689009,九号公司-WD
13217,2023-12-31,智能服务机器人,2.86亿,2.80,1.52亿,5.53,53.15,689009,九号公司-WD

In [ ]:
df[df['StockCode']=='688653']['项目名'].str.contains('行业', na=False)

In [ ]:
df[df['题材'].str.contains('券商', na=False)].sort_values(by=['相关度','StockCode'], ascending=False).reset_index(drop=True)

In [7]:
gg  = df.groupby('题材')

In [ ]:
df[df["StockCode"]=='002161']

In [735]:
df

In [ ]:
gg.groups

In [10]:
gDF = gg.count().sort_values('StockCode')

In [ ]:
gDF

In [ ]:
gg.get_group('食品溯源')

In [ ]:
import json

from pyecharts import options as opts
from pyecharts.charts import Graph

with open("weibo.json", "r", encoding="utf-8") as f:
    j = json.load(f)
    nodes, links, categories, cont, mid, userl = j
c = (
    Graph()
    .add(
        "",
        nodes,
        links,
        categories,
        repulsion=50,
        linestyle_opts=opts.LineStyleOpts(curve=0.2),
        label_opts=opts.LabelOpts(is_show=False),
    )
    .set_global_opts(
        legend_opts=opts.LegendOpts(is_show=False),
        title_opts=opts.TitleOpts(title="Graph-微博转发关系图"),
    )
    .render("graph_weibo.html")
)

In [ ]:
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB


from pyecharts.charts import Bar
from pyecharts import options as opts
# 内置主题类型可查看 pyecharts.globals.ThemeType
from pyecharts.globals import ThemeType

bar = (
    Bar(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
    .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    .add_yaxis("商家B", [15, 6, 45, 20, 35, 66])
    .set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
)
bar.load_javascript()

In [ ]:
bar.render_notebook()