In [ ]:
import requests

modls = requests.get("http://10.3.68.3:11434/v1/models").json()['data']

In [ ]:
ls = []
n = 0
while n < len(modls):
    ls.append(modls[n]['id'])
    n = n + 1

In [ ]:
from mootdx.quotes import Quotes

历史财务数据列表的读取

In [ ]:
from mootdx.affair import Affair

Affair.files()

In [ ]:
f10 = ['最新提示','公司概况','财务分析','股本结构','股东研究','机构持股','分红融资','高管治理','资金动向','资本运作','热点题材','公司公告','公司报道','经营分析','行业分析','价值分析',]
stockCode = '000001'

In [ ]:
client = Quotes.factory(market='std')
txt = client.F10(stockCode, f10[1])

In [ ]:
txt[:txt.find('〖免责条款〗')]

In [ ]:
from mootdx.quotes import Quotes
from mootdx.consts import MARKET_SH

client = Quotes.factory(market='ext')
client.bars(frequency=9,market=62,symbol='930740')
# client = Quotes.factory(market='std')
# client.index(frequency=9,symbol='000815')

In [ ]:
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
import pandas as pd

eapi =  TdxExHq_API()
api = TdxHq_API()

In [ ]:
api.connect('121.37.183.82', 7709)

In [ ]:
eapi.connect('47.112.95.207', 7720)

In [ ]:
api.to_df(api.get_index_bars(9, 1, '000001', 0, 1))

In [ ]:
api.to_df(api.get_security_bars(9, 0, '000837', 0, 1))

In [ ]:
eapi.to_df(eapi.get_instrument_bars(9, 62, "H30184", 0, 3))

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text

In [ ]:
eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
con = eng.connect()

In [ ]:
con.commit()
con.close()

In [ ]:
l = pd.read_sql('EmpIndex', eng)['IndexCode'].to_list()

In [ ]:

for i in l:
    try:
        con.execute(text('DROP TABLE IF EXISTS "'+i+'";'))
        con.commit()
    except:
        pass

con.close()

In [ ]:
tdxIndex = pd.read_sql('tdxIndexs', eng)
empIndex = pd.read_sql('EmpIndex', eng)

In [ ]:
empIndex['EMP']=1

In [ ]:
df = pd.merge(tdxIndex,empIndex,on='IndexCode',how='outer').drop('index',axis=1)

In [ ]:
df[~(df.EMP==1)].drop('EMP',axis=1)

#===================== 数据分析  ================

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxFS')

============ FSCode 更新 ================

In [ ]:
df = pd.read_excel('g:/gitee/app/stocksic/sort.xlsx')
df.set_index('Index').to_sql('FSCode',eng,if_exists='replace')

In [ ]:
df = pd.read_excel('/home/ts/app/StocksIC/sort.xlsx')
df.set_index('Index').to_sql('FSCode',eng,if_exists='replace')

In [ ]:
finRAW = pd.read_sql('000009', eng,)
finRAW['report_date']=finRAW['report_date'].astype(object)

In [ ]:
finRAW = pd.concat([finRAW,finRAW['report_date'].rename('Index')],axis=1)
trsfin = finRAW.set_index('Index').T
trsfin = trsfin.reset_index().rename(columns={'index':'Code'})

In [ ]:
trsfin

In [ ]:
FSCode = pd.read_sql('FSCode',eng)

In [ ]:
FSCode

In [ ]:
sfin = pd.merge(FSCode,trsfin,on='Code',how='inner')

In [ ]:
sfin

In [ ]:
s1 = pd.read_excel('/home/ts/App/StocksIC/ff.xlsx')

In [ ]:
day = 20231231
ll = ['Index','L1Code','L1Name','L2Code','L2Name','L3Code','L3Name','Code','cnName']

In [ ]:
fin = pd.concat([sfin[ll],sfin[day].rename('vol')],axis=1)

In [ ]:
items = fin.cnName.to_list()

In [ ]:
sumite = [item for item in items if any(substr in item for substr in "万")]

In [ ]:
for ite in sumite:
    fin.loc[fin.cnName==ite,"vol"] = fin[fin.cnName==ite]["vol"]*10000

In [ ]:
zcfz = fin.query('L1Code=="ZCFZ" and L3Code!="EMP" and L3Code!="HJ"')

In [ ]:
zcfz = zcfz[~(zcfz["vol"]==0)].reset_index(drop=True)

In [ ]:
zcfz

In [ ]:
for i,ite in enumerate(zcfz.vol.to_list()):
    if ite < 0:
        zcfz.loc[i,'cnName'] ='负：'+ zcfz.loc[i,'cnName']
        zcfz.loc[i,'vol'] = abs(ite) 
    else:
        pass

In [ ]:
fin.query('L1Code=="ZCFZ" and (L3Code == "HJ" or L3Code=="SSGD")')

In [ ]:
zzcfz = fin.query('L1Code=="ZCFZ" and (L3Code=="HJ" or L3Code=="SSGD")')
zzcfz = zzcfz[~(zzcfz["vol"]==0)].reset_index(drop=True)

In [ ]:
for i,ite in enumerate(zzcfz.vol.to_list()):
    if ite < 0:
        zzcfz.loc[i,'cnName'] ='负：'+ zzcfz.loc[i,'cnName']
        zzcfz.loc[i,'vol'] = abs(ite) 
    else:
        pass

In [ ]:
zzcfz

In [ ]:
import plotly.express as px
# import numpy as np
# df = px.data.gapminder().query("year == 2007")
fig = px.sunburst(zcfz, path=['L2Name','cnName'], values="vol"
# fig = px.pie(ssss, values=0,names='L2Name'
                #   color='lifeExp', hover_data=['iso_alpha'],
                #   color_continuous_scale='RdBu',
                #   color_continuous_midpoint=np.average(df['lifeExp'], weights=df['pop']))
)
config = {'scrollZoom': True}
fig.show(config=config)

In [ ]:
s1[sel.Code].loc[92].to_list()

In [ ]:
LDZC = sel[sel.L3Code=='LDZC']
FLDZC = sel[sel.L3Code=='FLDZC']
SYZQY = sel[sel.L3Code=='SYZQY']

In [ ]:

ssss = sss[sss.L1Code=='ZCFZ']

In [ ]:
ssss['voll']=

In [ ]:
s1[LDZC.Code.to_list()].loc[92]

In [ ]:
s1.col21.loc[92]

In [ ]:
from  datetime import date
mon = date.today().strftime('%m')
year = date.today().strftime('%Y')
match mon:
    case mon if mon == '12':
        filename='gpcw'+year+'1231.zip'
    case mon if mon < '03':
        filename='gpcw'+year+'1231.zip'
    case mon if '03'<= mon < '06':
        filename='gpcw'+year+'0331.zip'
    case mon if '06'<= mon < '09':
        filename='gpcw'+year+'0630.zip'
    case mon if '09'<= mon < '12':
        filename='gpcw'+year+'0930.zip'

In [ ]:
import plotly.express as px
fig = px.bar(x=["a", "b", "c"], y=[1, 3, 2])
fig.show()

In [ ]:
import plotly.graph_objects as go

fig =go.Figure(go.Sunburst(
    labels=sel.cnName.to_list(),
    parents=sel.L3Name.to_list(),
    values=s1[sel.Code].loc[92].to_list(),
))
# Update layout for tight margin
# See https://plotly.com/python/creating-and-updating-figures/
fig.update_layout(margin = dict(t=0, l=0, r=0, b=0))
fig.show()

In [ ]:
df = px.data.tips()

In [ ]:
zcfz = fin.query('L1Code=="ZCFZ" and L3Code!="EMP" and L3Code!="HJ"')

In [ ]:
import plotly.graph_objects as go

config = {'displayModeBar': True,'scrollZoom': True,'displaylogo': True,'modeBarButtonsToAdd':['drawline']}

fig = go.Figure(data=[go.Sankey(
    node = dict(
    thickness = 5,
    label = ["Ads", "Net profit", "Total income", "ROI", "Paid services", "Investment", "Expenses", "Maintaining website", "Paying employes", "Advertising", "Personal expenses", "Savings"],
    color = "cyan"
    ),
    link = dict(

    # indices correspond to labels
    source = [0, 1, 4, 2, 3, 2, 6, 6, 6, 1, 1],
    target = [2, 5, 2, 1, 2, 6, 7, 8, 9, 10, 11],
    value = [60000, 40000, 90000, 100000, 10000, 60000, 10000, 30000, 20000, 20000, 40000]
))])

fig.update_layout(
    title="DatavizWRLD.com monthly income and income management of 2021( in USD )",
    font=dict(size = 12, color = 'black')
)

# fig.update_layout(modebar_remove=[''])
fig.show(config=config)

In [ ]:
import plotly.graph_objects as go

fig = go.Figure(go.Sankey(
    arrangement = "snap",
    node = {
        "label": ["A", "B", "C", "D", "E", "F"],
        "x": [0.2, 0.1, 0.5, 0.7, 0.3, 0.5],
        "y": [0.8, 0.5, 0.2, 0.4, 0.2, 0.3],
        'pad':10},  # 10 Pixels
    link = {
        "source": [0, 0, 1, 2, 5, 4, 3, 5],
        "target": [4, 3, 4, 3, 0, 2, 2, 3],
        "value": [1, 2, 1, 1, 1, 1, 1, 2]}))

fig.show()

In [ ]:
node = fin.query('L1Code=="XJLL" and L3Code!="EMP"')
node = node[~(node["vol"]==0)].reset_index(drop=True).reset_index()

In [ ]:
node

In [ ]:
link = pd.DataFrame()

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="TZHD" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="TZHD" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="TZHD" and L3Code=="LRHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="TZHD" and L3Code=="LC"')['index']
mid['V'] = node.query('L2Code=="TZHD" and L3Code=="LC"')['vol']
mid['T'] = node.query('L2Code=="TZHD" and L3Code=="LCHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="TZHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['index']
mid['V'] = node.query('L2Code=="TZHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['vol']
mid['T'] = node.query('L2Code=="TZHD" and L3Code=="JE"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="JYHD" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="JYHD" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="JYHD" and L3Code=="LRHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="JYHD" and L3Code=="LC"')['index']
mid['V'] = node.query('L2Code=="JYHD" and L3Code=="LC"')['vol']
mid['T'] = node.query('L2Code=="JYHD" and L3Code=="LCHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="JYHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['index']
mid['V'] = node.query('L2Code=="JYHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['vol']
mid['T'] = node.query('L2Code=="JYHD" and L3Code=="JE"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CZHD" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="CZHD" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="CZHD" and L3Code=="LRHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CZHD" and L3Code=="LC"')['index']
mid['V'] = node.query('L2Code=="CZHD" and L3Code=="LC"')['vol']
mid['T'] = node.query('L2Code=="CZHD" and L3Code=="LCHJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="CZHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['index']
mid['V'] = node.query('L2Code=="CZHD" and (L3Code=="LRHJ" or L3Code=="LCHJ")')['vol']
mid['T'] = node.query('L2Code=="CZHD" and L3Code=="JE"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="BCXM" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="BCXM" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="BCXM" and L3Code=="JEJJ"').values[0][0]
link = pd.concat([link, mid])

mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="BCXM" and L3Code=="LC"')['index']
mid['V'] = node.query('L2Code=="BCXM" and L3Code=="LC"')['vol']
mid['T'] = node.query('L2Code=="BCXM" and L3Code=="JEJJ"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L2Code=="BCXMDJW" and L3Code=="LR"')['index']
mid['V'] = node.query('L2Code=="BCXMDJW" and L3Code=="LR"')['vol']
mid['T'] = node.query('L2Code=="BCXMDJW" and L3Code=="ZJEJJ"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
mid = pd.DataFrame()
mid['S'] = node.query('L3Code=="JE"')['index']
mid['V'] = node.query('L3Code=="JE"')['vol']
mid['T'] = node.query('L2Code=="DJW" and L3Code=="ZJE"').values[0][0]
link = pd.concat([link, mid])

In [ ]:
link

In [ ]:
import plotly.graph_objects as go
# override gray link colors with 'source' colors
# change 'magenta' to its 'rgba' value to add opacity


fig = go.Figure(data=[go.Sankey(

    node = dict(
      pad = 15,
      thickness = 15,
      line = dict(color = "black", width = 0.5),
      label =  node['cnName'].tolist(),
      # color =  data['data'][0]['node']['color']
    ),
    # Add links
    link = dict(
      source =  link['S'].tolist(),
      target =  link['T'].tolist(),
      value =  abs(link['V']).tolist(),
      # label =  data['data'][0]['link']['label'],
      # color =  data['data'][0]['link']['color']
))])

fig.update_layout(title_text="Sankey分析<br>"+"Code: "+str(day),
                  font_size=10)
fig.show()

In [ ]:
import plotly.graph_objects as go
import urllib, json

url = 'https://raw.githubusercontent.com/plotly/plotly.js/master/test/image/mocks/sankey_energy.json'
response = urllib.request.urlopen(url)
data = json.loads(response.read())

# override gray link colors with 'source' colors
opacity = 0.4
# change 'magenta' to its 'rgba' value to add opacity
data['data'][0]['node']['color'] = ['rgba(255,0,255, 0.8)' if color == "magenta" else color for color in data['data'][0]['node']['color']]
data['data'][0]['link']['color'] = [data['data'][0]['node']['color'][src].replace("0.8", str(opacity))
                                    for src in data['data'][0]['link']['source']]

fig = go.Figure(data=[go.Sankey(
    valueformat = ".0f",
    valuesuffix = "TWh",
    # Define nodes
    node = dict(
      pad = 15,
      thickness = 15,
      line = dict(color = "black", width = 0.5),
      label =  data['data'][0]['node']['label'],
      color =  data['data'][0]['node']['color']
    ),
    # Add links
    link = dict(
      source =  data['data'][0]['link']['source'],
      target =  data['data'][0]['link']['target'],
      value =  data['data'][0]['link']['value'],
      label =  data['data'][0]['link']['label'],
      color =  data['data'][0]['link']['color']
))])

fig.update_layout(title_text="Energy forecast for 2050<br>Source: Department of Energy & Climate Change, Tom Counsell via <a href='https://bost.ocks.org/mike/sankey/'>Mike Bostock</a>",
                  font_size=10)
fig.show()

==================   绘制瀑布图 =================

In [148]:
waterfin = node.query('L2Code=="HLBD" or (L3Code!="EMP" and L3Code!="LR" and L3Code!="LC" and L3Code!="JEY")')

In [149]:
lis = waterfin.query('L3Code=="LCHJ"').index.tolist()

In [150]:
for i in lis:
    waterfin.loc[i,'vol'] = -waterfin.loc[i,'vol']

In [151]:
waterfin

,index,Index,L1Code,L1Name,L2Code,L2Name,L3Code,L3Name,Code,cnName,vol
0,0,113,XJLL,现金流量表,TZHD,投资活动,LRHJ,合计,col113,投资活动现金流入小计,5466569728.0
1,1,118,XJLL,现金流量表,TZHD,投资活动,LCHJ,合计,col118,投资活动现金流出小计,-8073699328.0
2,2,119,XJLL,现金流量表,TZHD,投资活动,JE,净额,col119,投资活动产生的现金流量净额,-2607129344.0
12,12,129,XJLL,现金流量表,HLBD,汇率变动,LC,流出,col129,汇率变动对现金的影响,-1967315.5
13,13,131,XJLL,现金流量表,DJW,现金及现金等价物,ZJE,总净额,col131,现金及现金等价物净增加额,802263360.0
16,16,309,XJLL,现金流量表,XJLL,现金流量表,ZJE,总净额,col310,近一年现金净流量（万元）,802263300.0
17,17,123,XJLL,现金流量表,CZHD,筹资活动,LRHJ,合计,col123,筹资活动现金流入小计,10588354560.0
18,18,127,XJLL,现金流量表,CZHD,筹资活动,LCHJ,合计,col127,筹资活动现金流出小计,-13138664448.0
19,19,128,XJLL,现金流量表,CZHD,筹资活动,JE,净额,col128,筹资活动产生的现金流量净额,-2550310144.0
27,27,101,XJLL,现金流量表,JYHD,经营活动,LRHJ,合计,col101,经营活动现金流入小计,29280997376.0
28,28,106,XJLL,现金流量表,JYHD,经营活动,LCHJ,合计,col106,经营活动现金流出小计,-23319326720.0
29,29,107,XJLL,现金流量表,JYHD,经营活动,JE,净额,col107,经营活动产生的现金流量净额,5961670144.0
40,40,150,XJLL,现金流量表,BCXM,补充项目,JEJJ,净额（间接法）,col150,经营活动产生的现金流量净额（间接法）,5961670144.0
41,41,158,XJLL,现金流量表,BCXMDJW,补充项目等价物,ZJEJJ,总净额（间接法）,col158,现金及现金等价物净增加额（间接法）,802263360.0

In [152]:
addd = waterfin.query('L3Code=="ZJE"')

In [153]:
waterfin = waterfin.drop(waterfin.query('L3Code=="ZJE"')['index'].tolist())

In [163]:
waterfin = pd.concat([waterfin, addd]).head(10)

In [161]:
waterfin

,index,Index,L1Code,L1Name,L2Code,L2Name,L3Code,L3Name,Code,cnName,vol
0,0,113,XJLL,现金流量表,TZHD,投资活动,LRHJ,合计,col113,投资活动现金流入小计,5466569728.0
1,1,118,XJLL,现金流量表,TZHD,投资活动,LCHJ,合计,col118,投资活动现金流出小计,-8073699328.0
2,2,119,XJLL,现金流量表,TZHD,投资活动,JE,净额,col119,投资活动产生的现金流量净额,-2607129344.0
12,12,129,XJLL,现金流量表,HLBD,汇率变动,LC,流出,col129,汇率变动对现金的影响,-1967315.5
17,17,123,XJLL,现金流量表,CZHD,筹资活动,LRHJ,合计,col123,筹资活动现金流入小计,10588354560.0
18,18,127,XJLL,现金流量表,CZHD,筹资活动,LCHJ,合计,col127,筹资活动现金流出小计,-13138664448.0
19,19,128,XJLL,现金流量表,CZHD,筹资活动,JE,净额,col128,筹资活动产生的现金流量净额,-2550310144.0
27,27,101,XJLL,现金流量表,JYHD,经营活动,LRHJ,合计,col101,经营活动现金流入小计,29280997376.0
28,28,106,XJLL,现金流量表,JYHD,经营活动,LCHJ,合计,col106,经营活动现金流出小计,-23319326720.0

In [164]:

import plotly.graph_objects as go

fig = go.Figure(go.Waterfall(
    x = waterfin.cnName.tolist(),
    measure = ["absolute", "relative", "total", "relative", "relative", "relative", "total", "relative", "relative","total"],
    y = waterfin["vol"].tolist(), base = 0,
    decreasing = {"marker":{"color":"Maroon", "line":{"color":"red", "width":2}}},
    increasing = {"marker":{"color":"Teal"}},
    totals = {"marker":{"color":"deep sky blue", "line":{"color":"blue", "width":3}}}
))

fig.update_layout(title = "Profit and loss statement", waterfallgap = 0.3)

fig.show()