In [119]:
from sqlalchemy import create_engine
import pandas as pd
import plotly.express as px

In [33]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/tdxIndex')
engT = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/tdxStocks')
IndexLists = pd.read_sql('optIndexs', eng).IndexCode.to_list()

In [147]:
Code = '881386'
nday = 144

In [148]:
D = pd.read_sql('IndexCons',eng)
# d = pd.DataFrame(columns=['code','PCB']).astype(dtype={'PCB':float})
Data = D.loc[D['IndexCode']== Code].reset_index(drop=True)
StockLists = Data[['StockCode','StockName']].values.tolist()

In [149]:
shDF = pd.read_sql('000001', eng)

In [150]:
plData = pd.DataFrame()
plData['datetime'] = shDF['datetime'].reset_index(drop=True)

In [151]:
plData = pd.merge(plData,shDF[['datetime','close']].rename(columns={'close':'上证指数'}),on='datetime',how='outer')

In [152]:
for Stock in StockLists:
    plData = pd.merge(plData,pd.read_sql(Stock[0],engT)[['datetime','close']].rename(columns={'close':Stock[1]}),on='datetime',how='outer')

In [153]:
def normalize(x):
    return (x - x.min()) / (x.max() - x.min())

In [154]:
ddd = plData.tail(144).set_index('datetime').apply(normalize, axis=0)

In [155]:
fig = px.line(ddd.reset_index(),x='datetime', y=plData.columns,line_shape='linear')
fig.show()

In [53]:
df = pd.DataFrame(columns=['StockCode', 'StockName','3D','5D','21D','55D']).astype(dtype={'3D':float,'5D':float,'21D':float,'55D':float})

In [56]:
DD = pd.read_sql(StockLists[0][0], engT)

In [58]:
dd = pd.DataFrame(columns=['StockCode', 'StockName','3D','5D','21D','55D']).astype(dtype={'3D':float,'5D':float,'21D':float,'55D':float})

In [69]:
dd['StockCode'] = StockLists[0][0]

In [67]:
dd['3D'] = [(DD.close.pct_change(1)*100).tail(3).sum().round(2)]

In [71]:
for Stock in StockLists:
    try:
        DD = pd.read_sql(Stock[0], engT)
        dd = pd.DataFrame(columns=['StockCode', 'StockName','3D','5D','21D','55D']).astype(dtype={'3D':float,'5D':float,'21D':float,'55D':float})
        dd['3D'] = [(DD.close.pct_change(1)*100).tail(3).sum().round(2)]
        dd['5D'] = [(DD.close.pct_change(1)*100).tail(5).sum().round(2)]
        dd['21D'] = [(DD.close.pct_change(1)*100).tail(21).sum().round(2)]
        dd['55D'] = [(DD.close.pct_change(1)*100).tail(55).sum().round(2)]
        dd['StockCode'] = Stock[0] 
        dd['StockName'] = Stock[1]
        dd.reset_index(drop=True, inplace =True)
        # d = d.append(dd[['code','PCB']])
        df = pd.concat([df, dd])
    except:
        pass

In [95]:
df.sort_values(by='21D', ascending=0).reset_index(drop=True, inplace=True)

In [96]:
df.reset_index(drop=True,inplace=True)

趋势数据分析

In [2]:
import plotly.express as px
import pandas as pd

from sqlalchemy import create_engine

In [3]:
engTDX = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/tdxIndex')

In [4]:
tdxData = pd.read_sql('tdxIndexsData', engTDX).sort_values('3D',ascending=False)
ptData = tdxData.style.background_gradient(cmap='Blues')
ptData = ptData.format('{:,.2f}', subset=list(tdxData.columns[2:]))

In [161]:
ddf55 = tdxData.sort_values(by='55D',ascending=0)
ddf55 = ddf55.head(int(ddf55.shape[0]*0.25))

In [162]:
ddf21 = tdxData.sort_values(by='21D',ascending=0)
ddf21 = ddf21.head(int(ddf21.shape[0]*0.25))

In [163]:
ddf5 = tdxData.sort_values(by='5D',ascending=0)
ddf5 = ddf5.head(int(ddf5.shape[0]*0.25))

In [164]:
ddf3 = tdxData.sort_values(by='3D',ascending=0)
ddf3 = ddf3.head(int(ddf3.shape[0]*0.25))

In [185]:
mdf = pd.merge(ddf55['IndexCode'],ddf21,on='IndexCode',how='inner')

In [188]:
mdf = pd.merge(mdf['IndexCode'],ddf5,on='IndexCode',how='inner')

In [186]:
mdf = pd.merge(mdf['IndexCode'],ddf3,on='IndexCode',how='inner')

In [192]:
mdf['3D'].rename('Index')

0    1.03
1    5.96
2   -0.40
3    1.52
4    0.19
5   -0.18
6   -0.28
7    2.46
8    0.46
9    0.12
Name: Index, dtype: float64

In [ ]:
fig = px.violin(df,y='vol',facet_col='周期',facet_col_spacing=0.03,box=True,violinmode='overlay',title='价格')

In [125]:

fig = px.violin(df,y='vol',box=True,points='all',hover_name=df.IndexCode+' : '+df.IndexName,facet_col='周期',facet_col_spacing=0.03,violinmode='overlay')
fig.show()

In [11]:
import plotly.figure_factory as ff

In [17]:
df = tdxData[['3D','5D','21D','55D']]

In [18]:
fig = ff.create_distplot([df[c] for c in df.columns], df.columns, bin_size=.25)
fig.show()

In [122]:
df=pd.DataFrame()

In [123]:
cl=['3D','5D','21D','55D']

In [124]:
for ls in cl:
    dff = pd.DataFrame()
    dff = tdxData[list(tdxData.columns[:2])+[ls]]
    dff.rename(columns={ls:'vol'},inplace=True)
    dff['周期'] = ls
    df = pd.concat([df,dff])

In [85]:
ls = cl[2]

In [86]:
dff = pd.DataFrame()
dff = tdxData[list(tdxData.columns[:2])+[ls]]

In [199]:
dff

    IndexCode IndexName    vol   周期
496    880822      昨收活跃  59.61  55D
667    881224      汽车服务  32.11  55D
505    880836       配股股  21.64  55D
728    881446      航空机场  19.47  55D
734    881470      环保设备  28.74  55D
..        ...       ...    ...  ...
702    881359       云服务  48.35  55D
506    880837       活跃股  21.78  55D
684    881289      航天装备  37.20  55D
346    880640      历史新高  19.18  55D
392    880690      昨日强势 -67.54  55D

[1013 rows x 4 columns]

In [205]:
dff.iloc[:,2]

496    59.61
667    32.11
505    21.64
728    19.47
734    28.74
       ...
702    48.35
506    21.78
684    37.20
346    19.18
392   -67.54
Name: vol, Length: 1013, dtype: float64

In [201]:
dff

    IndexCode IndexName    vol   周期  tes
496    880822      昨收活跃  59.61  55D  tes
667    881224      汽车服务  32.11  55D  tes
505    880836       配股股  21.64  55D  tes
728    881446      航空机场  19.47  55D  tes
734    881470      环保设备  28.74  55D  tes
..        ...       ...    ...  ...  ...
702    881359       云服务  48.35  55D  tes
506    880837       活跃股  21.78  55D  tes
684    881289      航天装备  37.20  55D  tes
346    880640      历史新高  19.18  55D  tes
392    880690      昨日强势 -67.54  55D  tes

[1013 rows x 5 columns]

In [66]:
df = pd.DataFrame()

In [67]:
df = tdxData[list(tdxData.columns[:2])+[ls]]

In [68]:
df['周期'] = ls

In [69]:
df

    IndexCode IndexName     3D  周期
496    880822      昨收活跃   5.96  3D
667    881224      汽车服务   3.49  3D
505    880836       配股股   3.17  3D
728    881446      航空机场   2.80  3D
734    881470      环保设备   2.67  3D
..        ...       ...    ...  ..
702    881359       云服务  -7.43  3D
506    880837       活跃股  -7.94  3D
684    881289      航天装备  -8.49  3D
346    880640      历史新高  -9.34  3D
392    880690      昨日强势 -15.14  3D

[1013 rows x 4 columns]