In [19]:
from sqlalchemy import create_engine
import pandas as pd
import plotly.express as px

In [20]:
# eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/tdxIndex')
# engT = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/tdxStocks')
eng = create_engine('postgresql+psycopg://sa:11111111@111.61.77.88:65123/tdxIndex')
engT = create_engine('postgresql+psycopg://sa:11111111@111.61.77.88:65123/tdxStocks')
IndexLists = pd.read_sql('optIndexs', eng).IndexCode.to_list()

In [21]:
Code = '881386'
nday = 144

In [22]:
D = pd.read_sql('IndexCons',eng)
# d = pd.DataFrame(columns=['code','PCB']).astype(dtype={'PCB':float})
Data = D.loc[D['IndexCode']== Code].reset_index(drop=True)
StockLists = Data[['StockCode','StockName']].values.tolist()

In [23]:
shDF = pd.read_sql('000001', eng)

In [24]:
plData = pd.DataFrame()
plData['datetime'] = shDF['datetime'].reset_index(drop=True)

In [25]:
plData = pd.merge(plData,shDF[['datetime','close']].rename(columns={'close':'上证指数'}),on='datetime',how='outer')

In [26]:
for Stock in StockLists:
    plData = pd.merge(plData,pd.read_sql(Stock[0],engT)[['datetime','close']].rename(columns={'close':Stock[1]}),on='datetime',how='outer')

In [27]:
def normalize(x):
    return (x - x.min()) / (x.max() - x.min())

In [28]:
ddd = plData.tail(144).set_index('datetime').apply(normalize, axis=0)

In [29]:
fig = px.line(ddd.reset_index(),x='datetime', y=plData.columns,line_shape='linear')
fig.show()

In [30]:
df = pd.DataFrame(columns=['StockCode', 'StockName','3D','5D','21D','55D']).astype(dtype={'3D':float,'5D':float,'21D':float,'55D':float})

In [35]:
StockLists[0][0]

'000001'

In [36]:
DD = pd.read_sql(StockLists[0][0], engT)

In [37]:
dd = pd.DataFrame(columns=['StockCode', 'StockName','3D','5D','21D','55D']).astype(dtype={'3D':float,'5D':float,'21D':float,'55D':float})

In [38]:
dd['StockCode'] = StockLists[0][0]

In [39]:
dd['3D'] = [(DD.close.pct_change(1)*100).tail(3).sum().round(2)]

In [40]:
for Stock in StockLists:
    try:
        DD = pd.read_sql(Stock[0], engT)
        dd = pd.DataFrame(columns=['StockCode', 'StockName','3D','5D','21D','55D']).astype(dtype={'3D':float,'5D':float,'21D':float,'55D':float})
        dd['3D'] = [(DD.close.pct_change(1)*100).tail(3).sum().round(2)]
        dd['5D'] = [(DD.close.pct_change(1)*100).tail(5).sum().round(2)]
        dd['21D'] = [(DD.close.pct_change(1)*100).tail(21).sum().round(2)]
        dd['55D'] = [(DD.close.pct_change(1)*100).tail(55).sum().round(2)]
        dd['StockCode'] = Stock[0] 
        dd['StockName'] = Stock[1]
        dd.reset_index(drop=True, inplace =True)
        # d = d.append(dd[['code','PCB']])
        df = pd.concat([df, dd])
    except:
        pass

In [41]:
df.sort_values(by='21D', ascending=0).reset_index(drop=True, inplace=True)

In [42]:
df.reset_index(drop=True,inplace=True)

趋势数据分析

In [43]:
import plotly.express as px
import pandas as pd

from sqlalchemy import create_engine

In [44]:
# engTDX = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/tdxIndex')
engTDX = create_engine('postgresql+psycopg://sa:11111111@111.61.77.88:65123/tdxIndex')

In [45]:
tdxData = pd.read_sql('tdxIndexsData', engTDX).sort_values('3D',ascending=False)
ptData = tdxData.style.background_gradient(cmap='Blues')
ptData = ptData.format('{:,.2f}', subset=list(tdxData.columns[2:]))

In [46]:
ddf55 = tdxData.sort_values(by='55D',ascending=0)
ddf55 = ddf55.head(int(ddf55.shape[0]*0.25))

In [48]:
ddf21 = tdxData.sort_values(by='21D',ascending=0)
ddf21 = ddf21.head(int(ddf21.shape[0]*0.25))

In [49]:
ddf5 = tdxData.sort_values(by='5D',ascending=0)
ddf5 = ddf5.head(int(ddf5.shape[0]*0.25))

In [50]:
ddf3 = tdxData.sort_values(by='3D',ascending=0)
ddf3 = ddf3.head(int(ddf3.shape[0]*0.25))

In [51]:
mdf = pd.merge(ddf55['IndexCode'],ddf21,on='IndexCode',how='inner')

In [52]:
mdf = pd.merge(mdf['IndexCode'],ddf5,on='IndexCode',how='inner')

In [53]:
mdf = pd.merge(mdf['IndexCode'],ddf3,on='IndexCode',how='inner')

In [54]:
mdf['3D'].rename('Index')

0     3.67
1     3.45
2     5.20
3     5.25
4     7.28
      ...
70    2.41
71    4.05
72    4.41
73    3.03
74    5.60
Name: Index, Length: 75, dtype: float64

In [56]:
df

   StockCode StockName    3D    5D    21D    55D
0     000001      平安银行  2.43  3.39   7.35   2.09
1     600000      浦发银行  2.61  4.02  14.90  22.40
2     600015      华夏银行  3.73  3.60  -2.42   8.73
3     600016      民生银行  4.62  6.52  12.22   9.05
4     600036      招商银行  0.67  0.40   4.74   1.64
5     601166      兴业银行  5.17  4.82  12.28  11.36
6     601288      农业银行  0.91  1.27  -0.24   9.38
7     601328     XD交通银  1.58  0.93   1.78   7.42
8     601398      工商银行  0.85  0.85  -2.11   5.01
9     601658      邮储银行  1.88  1.89   1.28   2.96
10    601818      光大银行  1.77  1.77   3.68   7.73
11    601916      浙商银行  1.87  4.73   8.36  13.97
12    601939      建设银行  0.11  0.22  -3.16   6.84
13    601988      中国银行 -0.18  0.19  -3.10   2.78
14    601998      中信银行  6.52  7.56  13.68  15.88

In [55]:
fig = px.violin(df,y='vol',facet_col='周期',facet_col_spacing=0.03,box=True,violinmode='overlay',title='价格')

ValueError: Value of 'y' is not the name of a column in 'data_frame'. Expected one of ['StockCode', 'StockName', '3D', '5D', '21D', '55D'] but received: vol

In [57]:

fig = px.violin(df,y='vol',box=True,points='all',hover_name=df.IndexCode+' : '+df.IndexName,facet_col='周期',facet_col_spacing=0.03,violinmode='overlay')
fig.show()

AttributeError: 'DataFrame' object has no attribute 'IndexCode'

In [58]:
import plotly.figure_factory as ff

In [59]:
df = tdxData[['3D','5D','21D','55D']]

In [60]:
fig = ff.create_distplot([df[c] for c in df.columns], df.columns, bin_size=.25)
fig.show()

In [61]:
df=pd.DataFrame()

In [62]:
cl=['3D','5D','21D','55D']

In [63]:
for ls in cl:
    dff = pd.DataFrame()
    dff = tdxData[list(tdxData.columns[:2])+[ls]]
    dff.rename(columns={ls:'vol'},inplace=True)
    dff['周期'] = ls
    df = pd.concat([df,dff])

In [64]:
ls = cl[2]

In [65]:
dff = pd.DataFrame()
dff = tdxData[list(tdxData.columns[:2])+[ls]]

In [66]:
dff

    IndexCode IndexName    21D
370    880652       创新药  15.89
581    880920      免疫治疗  17.36
441    880729     CXO概念  13.91
616    880967      数字货币  11.79
737    881427        体育  10.38
..        ...       ...    ...
53     000911     300可选   1.04
522    880837       活跃股   0.36
407    880690      昨日强势 -20.41
483    880784      昨日较弱  -9.09
669    881184      白色家电   1.03

[1100 rows x 3 columns]

In [67]:
dff.iloc[:,2]

370    15.89
581    17.36
441    13.91
616    11.79
737    10.38
       ...
53      1.04
522     0.36
407   -20.41
483    -9.09
669     1.03
Name: 21D, Length: 1100, dtype: float64

In [68]:
dff

    IndexCode IndexName    21D
370    880652       创新药  15.89
581    880920      免疫治疗  17.36
441    880729     CXO概念  13.91
616    880967      数字货币  11.79
737    881427        体育  10.38
..        ...       ...    ...
53     000911     300可选   1.04
522    880837       活跃股   0.36
407    880690      昨日强势 -20.41
483    880784      昨日较弱  -9.09
669    881184      白色家电   1.03

[1100 rows x 3 columns]

In [69]:
df = pd.DataFrame()

In [70]:
df = tdxData[list(tdxData.columns[:2])+[ls]]

In [71]:
df['周期'] = ls

In [72]:
df

    IndexCode IndexName    21D   周期
370    880652       创新药  15.89  21D
581    880920      免疫治疗  17.36  21D
441    880729     CXO概念  13.91  21D
616    880967      数字货币  11.79  21D
737    881427        体育  10.38  21D
..        ...       ...    ...  ...
53     000911     300可选   1.04  21D
522    880837       活跃股   0.36  21D
407    880690      昨日强势 -20.41  21D
483    880784      昨日较弱  -9.09  21D
669    881184      白色家电   1.03  21D

[1100 rows x 4 columns]