==== 行业分析

In [92]:
from mootdx.quotes import Quotes
import pandas as pd
import plotly.express as px
import re
from sqlalchemy import create_engine

eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')

StockList = pd.read_sql('StocksList', eng)[['code','name']]
# import streamlit as st

qf10='行业分析'
anCode = '估值水平排名'
StockCode = '000002'

client = Quotes.factory(market='std')
txt = client.F10(StockCode, qf10)[116:]
txt = txt.replace('│',' ')                
txt = re.sub('([\u2500-\u25f7])','',txt)

In [93]:
StockList.columns=['股票编码','股票名称']
list(StockList[StockList['股票编码'] == StockCode]['股票名称'])[0]

'万科A'

In [94]:
titlCode = re.findall(r'所属研究行业\S+', txt)[0]

In [95]:

def getFind(anCode):
    match anCode:
        case "市场表现排名":
            lsCode = ['【2.市场表现排名】','【3.公司规模排名】',["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]]
            return(lsCode)
        case "公司规模排名":
            lsCode = ['【3.公司规模排名】','【4.估值水平排名】',["股票名称","A股总市值(亿)","A股流通市值(亿)","实际流通A股(亿)","总股本(亿)","股价(元)"]]
            return(lsCode)
        case "估值水平排名":
            lsCode = ['【4.估值水平排名】','【5.财务状况排名】',['股票名称','市盈率(TTM)','市盈率(LYR)','市净率(MRQ)','市销率(TTM)','市现率(TTM)']]
            return(lsCode)
        case "财务状况排名":
            lsCode = ['【5.财务状况排名】','EOF',["股票名称","每股收益(元)","每股净资产(元)","每股现金流(元)","销售净利率%","净利润增长率%"]]
            return(lsCode)

In [96]:
lsCode =  getFind(anCode)

fi = txt[txt.find(lsCode[0]):]
ff = fi[:fi.find(lsCode[1])]
dd = ff.replace('─','').splitlines(keepends=False)
Data = pd.DataFrame(columns=lsCode[2])
i = 3
while i < len(dd):
    lis = re.split(r"\s{3,}", dd[i])[-6:]
    if len(lis)!=6:
        i = i+1
        # pass
    else:
        df = pd.DataFrame(lis).T
        df.columns=lsCode[2]
        Data = pd.concat([Data, df],axis=0)
        i=i+1
Data.reset_index(drop=True,inplace=True)
Data = Data.replace('---',0)

In [97]:
Data

     股票名称 市盈率(TTM) 市盈率(LYR) 市净率(MRQ) 市销率(TTM) 市现率(TTM)
0     新华联     6.05    37.71     2.41     3.83  -105.42
1    南京高科     7.86     8.71     0.71     6.76    -9.98
2    京基智农     8.86     5.53     2.33     1.36    12.05
3    津滨发展     9.75     7.43     1.27     1.54   -30.34
4    中新集团    11.98     8.83     0.83     3.97    12.16
5    衢州发展    15.64    15.91     0.59     0.94    65.00
6    滨江集团    15.74    10.52     1.00     0.41     7.95
7    保利发展    16.34     8.92     0.55     0.32   -12.12
8    华发股份    16.82     8.85     0.78     0.29     2.05
9    招商蛇口    17.94    14.62     0.95     0.52     4.95
10    外高桥    18.24    14.64     1.09     1.85    -5.01
11   中国国贸    19.12    19.37     2.59     6.17    13.51
12   城建发展    20.79    18.83     0.51     0.65     1.49
13   浦东金桥    21.42     6.93     0.89     3.88   -55.22
14   天保基建    26.26   170.60     0.63     1.10   -14.98
15   上海临港    28.04    24.57     1.40     3.37    -6.91
16   ST广物    30.90    19.91     1.68     3.11     7.60
17   沙河股份    36.80     5.19     1.64     5.56    28.55
18   苏州高新    45.93    37.77     1.02     0.91    -2.78
19    陆家嘴    48.33    46.51     2.07     4.41     6.07
20   苏宁环球    48.68    40.99     0.77     3.13   -36.69
21  渝 开 发    53.90    33.28     0.95     2.55    16.15
22   张江高科    61.84    45.35     3.42    21.91   -18.94
23   中国武夷    62.03   113.95     0.85     0.45   -11.38
24   信达地产    77.34    24.49     0.50     1.13    -4.11
25   卧龙地产    81.40    17.13     0.74     0.99    23.18
26   华联控股    89.91    75.63     1.21    12.79   -25.67
27   珠江股份    93.36        0     6.11     1.78    80.56
28   华丽家族    95.05    73.24     1.17    14.75    -7.04
29  万  科Ａ        0     7.22     0.38     0.22   -75.01
30   行业平均   -16.62   842.13     0.71     0.51    31.66
31   市场平均   -40.15   -34.74     2.18     2.59    37.97

In [98]:
StockList['']

KeyError: ''

In [99]:
Data['股票名称'] = Data['股票名称'].str.strip().str.replace(r'\s+', '', regex=True).str.replace('Ａ','A')

In [100]:
Data

    股票名称 市盈率(TTM) 市盈率(LYR) 市净率(MRQ) 市销率(TTM) 市现率(TTM)
0    新华联     6.05    37.71     2.41     3.83  -105.42
1   南京高科     7.86     8.71     0.71     6.76    -9.98
2   京基智农     8.86     5.53     2.33     1.36    12.05
3   津滨发展     9.75     7.43     1.27     1.54   -30.34
4   中新集团    11.98     8.83     0.83     3.97    12.16
5   衢州发展    15.64    15.91     0.59     0.94    65.00
6   滨江集团    15.74    10.52     1.00     0.41     7.95
7   保利发展    16.34     8.92     0.55     0.32   -12.12
8   华发股份    16.82     8.85     0.78     0.29     2.05
9   招商蛇口    17.94    14.62     0.95     0.52     4.95
10   外高桥    18.24    14.64     1.09     1.85    -5.01
11  中国国贸    19.12    19.37     2.59     6.17    13.51
12  城建发展    20.79    18.83     0.51     0.65     1.49
13  浦东金桥    21.42     6.93     0.89     3.88   -55.22
14  天保基建    26.26   170.60     0.63     1.10   -14.98
15  上海临港    28.04    24.57     1.40     3.37    -6.91
16  ST广物    30.90    19.91     1.68     3.11     7.60
17  沙河股份    36.80     5.19     1.64     5.56    28.55
18  苏州高新    45.93    37.77     1.02     0.91    -2.78
19   陆家嘴    48.33    46.51     2.07     4.41     6.07
20  苏宁环球    48.68    40.99     0.77     3.13   -36.69
21   渝开发    53.90    33.28     0.95     2.55    16.15
22  张江高科    61.84    45.35     3.42    21.91   -18.94
23  中国武夷    62.03   113.95     0.85     0.45   -11.38
24  信达地产    77.34    24.49     0.50     1.13    -4.11
25  卧龙地产    81.40    17.13     0.74     0.99    23.18
26  华联控股    89.91    75.63     1.21    12.79   -25.67
27  珠江股份    93.36        0     6.11     1.78    80.56
28  华丽家族    95.05    73.24     1.17    14.75    -7.04
29   万科A        0     7.22     0.38     0.22   -75.01
30  行业平均   -16.62   842.13     0.71     0.51    31.66
31  市场平均   -40.15   -34.74     2.18     2.59    37.97

In [101]:
dd

['【4.估值水平排名】(前30) 截止日期:2024-12-30',
 '排名     股票名称      市盈率(TTM)    市盈率(LYR)    市净率(MRQ)    市销率(TTM)    市现率(TTM)',
 '',
 '1        新华联               6.05          37.71           2.41           3.83        -105.42',
 '2        南京高科             7.86           8.71           0.71           6.76          -9.98',
 '3        京基智农             8.86           5.53           2.33           1.36          12.05',
 '4        津滨发展             9.75           7.43           1.27           1.54         -30.34',
 '5        中新集团            11.98           8.83           0.83           3.97          12.16',
 '6        衢州发展            15.64          15.91           0.59           0.94          65.00',
 '7        滨江集团            15.74          10.52           1.00           0.41           7.95',
 '8        保利发展            16.34           8.92           0.55           0.32         -12.12',
 '9        华发股份            16.82           8.85           0.78           0.29           2.05',
 '10       招商蛇口            17.94          14.62           0.95           0.52           4.95',
 '11       外高桥              18.24          14.64           1.09           1.85          -5.01',
 '12       中国国贸            19.12          19.37           2.59           6.17          13.51',
 '13       城建发展            20.79          18.83           0.51           0.65           1.49',
 '14       浦东金桥            21.42           6.93           0.89           3.88         -55.22',
 '15       天保基建            26.26         170.60           0.63           1.10         -14.98',
 '16       上海临港            28.04          24.57           1.40           3.37          -6.91',
 '17       ST广物              30.90          19.91           1.68           3.11           7.60',
 '18       沙河股份            36.80           5.19           1.64           5.56          28.55',
 '19       苏州高新            45.93          37.77           1.02           0.91          -2.78',
 '20       陆家嘴              48.33          46.51           2.07           4.41           6.07',
 '21       苏宁环球            48.68          40.99           0.77           3.13         -36.69',
 '22       渝 开 发            53.90          33.28           0.95           2.55          16.15',
 '23       张江高科            61.84          45.35           3.42          21.91         -18.94',
 '24       中国武夷            62.03         113.95           0.85           0.45         -11.38',
 '25       信达地产            77.34          24.49           0.50           1.13          -4.11',
 '26       卧龙地产            81.40          17.13           0.74           0.99          23.18',
 '27       华联控股            89.91          75.63           1.21          12.79         -25.67',
 '28       珠江股份            93.36            ---           6.11           1.78          80.56',
 '29       华丽家族            95.05          73.24           1.17          14.75          -7.04',
 '83       万  科Ａ              ---           7.22           0.38           0.22         -75.01',
 '',
 '行业平均                    -16.62         842.13           0.71           0.51          31.66',
 '市场平均                    -40.15         -34.74           2.18           2.59          37.97',
 '',
 '']

In [102]:
def to_numeric_safe(value):
    try:
        return pd.to_numeric(value)
    except (ValueError, TypeError):
        return value

ddf  = Data.map(to_numeric_safe)

In [103]:
StockList[StockList['股票名称'].isin(ddf['股票名称'])]

        股票编码  股票名称
1     000002   万科A
10    000014  沙河股份
26    000036  华联控股
32    000048  京基智农
99    000514   渝开发
176   000620   新华联
239   000718  苏宁环球
287   000797  中国武夷
347   000897  津滨发展
396   000965  天保基建
514   001979  招商蛇口
746   002244  滨江集团
2849  600007  中国国贸
2878  600048  保利发展
2893  600064  南京高科
2977  600173  卧龙地产
3006  600208  衢州发展
3049  600266  城建发展
3091  600325  华发股份
3218  600503  华丽家族
3303  600603  ST广物
3332  600639  浦东金桥
3339  600648   外高桥
3346  600657  信达地产
3351  600663   陆家嘴
3367  600684  珠江股份
3413  600736  苏州高新
3509  600848  上海临港
3548  600895  张江高科
3721  601512  中新集团

In [104]:
dtt

NameError: name 'dtt' is not defined

In [105]:
dtt['text'].str.strip().str.replace(r'\s+', '', regex=True)

NameError: name 'dtt' is not defined

In [106]:
StockList

        股票编码     股票名称
0     000001     平安银行
1     000002      万科A
2     000004     国华网安
3     000006     深振业A
4     000007      全新好
...      ...      ...
5115  688799     华纳药厂
5116  688800      瑞可达
5117  688819     天能股份
5118  688981     中芯国际
5119  689009  九号公司-WD

[5120 rows x 2 columns]

In [107]:
meddf = pd.merge(StockList,ddf,how='inner', on='股票名称')

In [108]:
dddf = pd.concat([meddf,ddf]).drop_duplicates(subset=['股票名称']).reset_index(drop=True)

In [109]:
dddf

      股票编码  股票名称  市盈率(TTM)  市盈率(LYR)  市净率(MRQ)  市销率(TTM)  市现率(TTM)
0   000002   万科A      0.00      7.22      0.38      0.22    -75.01
1   000014  沙河股份     36.80      5.19      1.64      5.56     28.55
2   000036  华联控股     89.91     75.63      1.21     12.79    -25.67
3   000048  京基智农      8.86      5.53      2.33      1.36     12.05
4   000514   渝开发     53.90     33.28      0.95      2.55     16.15
5   000620   新华联      6.05     37.71      2.41      3.83   -105.42
6   000718  苏宁环球     48.68     40.99      0.77      3.13    -36.69
7   000797  中国武夷     62.03    113.95      0.85      0.45    -11.38
8   000897  津滨发展      9.75      7.43      1.27      1.54    -30.34
9   000965  天保基建     26.26    170.60      0.63      1.10    -14.98
10  001979  招商蛇口     17.94     14.62      0.95      0.52      4.95
11  002244  滨江集团     15.74     10.52      1.00      0.41      7.95
12  600007  中国国贸     19.12     19.37      2.59      6.17     13.51
13  600048  保利发展     16.34      8.92      0.55      0.32    -12.12
14  600064  南京高科      7.86      8.71      0.71      6.76     -9.98
15  600173  卧龙地产     81.40     17.13      0.74      0.99     23.18
16  600208  衢州发展     15.64     15.91      0.59      0.94     65.00
17  600266  城建发展     20.79     18.83      0.51      0.65      1.49
18  600325  华发股份     16.82      8.85      0.78      0.29      2.05
19  600503  华丽家族     95.05     73.24      1.17     14.75     -7.04
20  600603  ST广物     30.90     19.91      1.68      3.11      7.60
21  600639  浦东金桥     21.42      6.93      0.89      3.88    -55.22
22  600648   外高桥     18.24     14.64      1.09      1.85     -5.01
23  600657  信达地产     77.34     24.49      0.50      1.13     -4.11
24  600663   陆家嘴     48.33     46.51      2.07      4.41      6.07
25  600684  珠江股份     93.36      0.00      6.11      1.78     80.56
26  600736  苏州高新     45.93     37.77      1.02      0.91     -2.78
27  600848  上海临港     28.04     24.57      1.40      3.37     -6.91
28  600895  张江高科     61.84     45.35      3.42     21.91    -18.94
29  601512  中新集团     11.98      8.83      0.83      3.97     12.16
30     NaN  行业平均    -16.62    842.13      0.71      0.51     31.66
31     NaN  市场平均    -40.15    -34.74      2.18      2.59     37.97

In [20]:
dddf.columns[2:]

Index(['市盈率(TTM)', '市盈率(LYR)', '市净率(MRQ)', '市销率(TTM)', '市现率(TTM)'], dtype='object')

In [110]:
fig = px.bar(dddf, y=dddf.columns[1], x=dddf.columns[2:], title=anCode,
             barmode='relative', hover_name=dddf.columns[1],text_auto='')
# fig.update_layout(dragmode='pan',legend_itemclick='toggleothers',)
fig.update_layout(dragmode='pan',)
# fig.show(config={'scrollZoom':True})

In [111]:
fig.show(config={'scrollZoom':True})

In [112]:
stta = ddf.style.background_gradient(cmap='Blues')
stta = stta.format('{:,.2f}', subset=list(ddf.columns[1:]))

=== 经营分析

In [113]:
from mootdx.quotes import Quotes
import pandas as pd
import plotly.express as px
import re

StockCode = '600166'
qf10='经营分析'
client = Quotes.factory(market='std')
txtRaw = client.F10(StockCode, qf10)
txt = txtRaw[116:]

In [114]:
txt

'评述】\r\n\r\n【1.主营业务】\r\n 从事农用车、柴油汽车、轻钢房屋构件的生产、销售。                                             \r\n\r\n【2.主营构成分析】\r\n截止日期:2024-06-30\r\n项目名                             营业收入(元)  收入比例(%) 营业利润(元)  利润比例(%)  毛利率(%)\r\n─────────────────────────────────────────────────\r\n轻型车分部(产品)                       268.83亿       112.16      13.74亿        45.82       5.11\r\n海外分部(产品)                          71.31亿        29.75       8.59亿        28.67      12.05\r\n管理及研发分部(产品)                    62.42亿        26.04      10.07亿        33.59      16.13\r\n大中客分部(产品)                        34.53亿        14.41       1.69亿         5.65       4.90\r\n发动机分部(产品)                        14.22亿         5.93       2.75亿         9.18      19.34\r\n其他分部(产品)                        4841.52万         0.20    3962.62万         1.32      81.85\r\n分部间抵销(产品)                      -212.11亿       -88.50      -7.26亿       -24.21       3.42\r\n─────────────────────────────────────────────────\r\n\r\n截止日期:2023-12-31\r\n项目名                             营业收入(元)  收入比例(%) 营业利润(元)  利润比例(%)  毛利率(%)\r\n─────────────────────────────────────────────────\r\n汽车行业(行业)                         534.35亿        95.26      57.72亿        90.41      10.80\r\n其他业务(行业)                          26.62亿         4.74       6.12亿         9.59      22.99\r\n─────────────────────────────────────────────────\r\n轻卡(产品)                             266.37亿        47.48      23.88亿        37.40       8.96\r\n发动机(产品)                            68.91亿        12.28       2.45亿         3.85       3.56\r\n中重卡(产品)                            67.34亿        12.00      13.57亿        21.25      20.15\r\n轻客(产品)                              50.69亿         9.04       7.92亿        12.40      15.62\r\n大中客(产品)                            41.29亿         7.36       5.12亿         8.02      12.41\r\n配件(产品)                              39.05亿         6.96       4.68亿         7.32      11.97\r\n其他(产品)                              26.62亿         4.74       6.12亿         9.59      22.99\r\n冲压件(产品)                          5623.20万         0.10     876.87万         0.14      15.59\r\n重型机械(产品)                        1483.79万         0.03     170.30万         0.03      11.48\r\n─────────────────────────────────────────────────\r\n中国大陆境内(地区)                     429.07亿        76.49      41.78亿        65.45       9.74\r\n其他国家及地区(地区)                   131.89亿        23.51      22.06亿        34.55      16.72\r\n─────────────────────────────────────────────────\r\n代理销售(销售模式)                     466.07亿        83.08      52.31亿        81.94      11.22\r\n其他(销售模式)                          94.90亿        16.92      11.53亿        18.06      12.15\r\n─────────────────────────────────────────────────\r\n\r\n截止日期:2023-06-30\r\n项目名                             营业收入(元)  收入比例(%) 营业利润(元)  利润比例(%)  毛利率(%)\r\n─────────────────────────────────────────────────\r\n轻型车分部(产品)                       297.36亿       103.09      -5.73亿       -16.95      -1.93\r\n海外分部(产品)                          95.38亿        33.07       7.40亿        21.91       7.76\r\n管理及研发分部(产品)                    69.42亿        24.07    6838.89万         2.02       0.99\r\n大中客分部(产品)                        60.53亿        20.98    8703.48万         2.58       1.44\r\n发动机分部(产品)                        10.87亿         3.77   -2943.88万        -0.87      -2.71\r\n其他分部(产品)                        6038.45万         0.21    2980.56万         0.88      49.36\r\n分部间抵销(产品)                      -245.72亿       -85.18    7337.14万         2.17      -0.30\r\n─────────────────────────────────────────────────\r\n\r\n截止日期:2022-12-31\r\n项目名                             营业收入(元)  收入比例(%) 营业利润(元)  利润比例(%)  毛利率(%)\r\n─────────────────────────────────────────────────\r\n汽车行业(行业)                         430.29亿        92.64      45.64亿        86.36      10.61\r\n其他(补充)(行业)                        34.18亿         7.36       7.21亿        13.64      21.10\r\n─────────────────────────────────────────────────\r\n轻卡(产品)                             243.24亿        52.37      21.91亿        41.45       9.01\r\n大中客(产品)                            56.75亿        12.22       7.40亿        14.01      13.04\r\n中重卡(产品)                            45.77亿         9.85       5.76亿        10.90      12.59\r\n轻客(产品)                              36.25亿         7.80       6.64亿        12.56      18.31\r\n其他(产品)                              34.18亿         7.36       7.21亿        13.64      21.10\r\n发动机(产品)                            24.43亿         5.26    1671.94万         0.32       0.68\r\n配件(产品)                              23.13亿         4.98       3.68亿         6.96      15.89\r\n冲压件(产品)                          6854.15万         0.15     672.37万         0.13       9.81\r\n重型机械(产品)                         377.77万         0.01     236.79万         0.04      62.68\r\n─────────────────────────────────────────────────\r\n中国大陆境内(地区)                     340.18亿        73.24      36.81亿        69.64      10.82\r\n其他国家及地区(地区)                   124.29亿        26.76      16.05亿        30.36      12.91\r\n─────────────────────────────────────────────────\r\n代理销售(销售模式)                     372.48亿        80.19      40.42亿        76.48      10.85\r\n其他(销售模式)                          57.81亿        12.45       5.22亿         9.88       9.03\r\n其他(补充)(销售模式)                    34.18亿         7.36       7.21亿        13.64      21.10\r\n─────────────────────────────────────────────────\r\n\r\n【3.前5名客户营业收入表】\r\n 截止日期:2023-12-31\r\n 前5大客户共销售136.99亿元，占营业收入的24.42%\r\n┌───────────────────────┬───────────┬───────────┐\r\n│客户名称                                      │          营收额(万元)│               占比(%)│\r\n├───────────────────────┼───────────┼───────────┤\r\n│合计                                          │            1369912.62│                 24.42│\r\n└───────────────────────┴───────────┴───────────┘\r\n\r\n【4.前5名供应商采购表】\r\n 截止日期:2023-12-31\r\n 前5大供应商共采购159.38亿元，占总采购额的32.06%\r\n┌───────────────────────┬───────────┬───────────┐\r\n│供应商名称                                    │          采购额(万元)│               占比(%)│\r\n├───────────────────────┼───────────┼───────────┤\r\n│合计                                          │            1593837.32│                 32.06│\r\n└───────────────────────┴───────────┴───────────┘\r\n\r\n【5.经营情况评述】\r\n截止日期:2024-06-30                                                                           \r\n●发展回顾:\r\n一、报告期内公司所属行业及主营业务情况说明                                                    \r\n    （一）公司主营业务及经营模式                                                              \r\n    福田汽车是一家国有控股上市公司，始终秉持“以客户为中心”的初心使命，坚持科技创新发展，已构\r\n建了车辆与移动装备、零部件、数字科技和商业生态四大业务体系，可以为用户提供线上线下一体化的“人\r\n车货场”高效互联和全场景服务。                                                                \r\n    在车辆及移动装备布局上，福田汽车品类最全，已经覆盖253个场景，提供人和货自由移动全场景解决 \r\n方案。同时，福田汽车不断加快新能源汽车产品布局，目前已形成涵盖纯电、混动、氢燃料全技术路线、覆\r\n盖全场景的商用车全系产品矩阵。在重卡、轻卡、微卡、皮卡、VAN、客车、专用车等全系列产品上得以应 \r\n用。                                                                                          \r\n    在研发布局上，福田汽车以北京为中心，全球布局16个技术创新研发中心（包括1个北京创新中心、7个\r\n国内整车应用开发中心、3个智能网联科技公司/事业部、2个海外研发中心、3个合资公司技术中心），构建\r\n了以新能源汽车技术、智能网联技术、节能技术和轻量化技术四个领域为核心的技术创新体系。          \r\n    在生产制造上，福田汽车全面布局智能制造，覆盖商用车整车及零部件全产业链。其中，国内布局10个\r\n整车基地（含福田戴姆勒）和6个零部件基地（含福田康明斯、福康后处理、采埃孚福田），海外已建设24 \r\n个KD工厂，实现全球化产业布局。                                                                \r\n    在销售服务上，国内一网经销商2425家，二网经销商9076家，平均服务半径小于40公里。海外销售网络\r\n遍布130多个国家和地区，开拓1000多家销售网点、1200多家服务网点，销售服务遍布全球。             \r\n    在数字科技上，福田汽车拥有国内最大的商用车车联网平台之一，为多行业提供数字化解决方案。平台\r\n目前接入车辆已超260万辆，每日接入数据85亿条以上。可以为车队、车企、供应商、分销商、金融风控、 \r\n二手车、政府等服务赋能，提供一体化车联网解决方案。                                            \r\n    后市场生态围绕人、车、货、场，以车联网、金融科技、大数据、互联网技术为基础，建立以客户为中\r\n心的智能互联生态，为客户提供安心用车、无忧养车、便捷换车与智能管车的全生命周期解决方案。在新能\r\n源生态建设中，2025年将构建起“车+桩+光+储+荷+智”的新能源产业和商业生态闭环体系。             \r\n    福田汽车坚持“成为绿色科技和市场领先的国际化企业”的企业愿景，以高质量发展为主线，坚持“绿\r\n色科技驱动能源革命，数字变革深化价值创造”的经营理念，未来，公司将继续围绕“抓住双碳战略机遇，\r\n深化价值创造体系”，持续推进“二次创业”，实现竞争性增长。                                    \r\n    （二）行业情况说明                                                                        \r\n    根据《国民经济行业分类》（GB/T4754-2017）和中国上市公司协会《上市公司行业统计分类指引》（2\r\n023年5月1日实施），公司所处行业为“汽车制造业”。                                             \r\n    2024年上半年，我国汽车行业全年汽车产销分别完成1389.1万辆和1404.7万辆，同比分别增长4.85%和6\r\n.10%。其中，乘用车产销分别完成1188.6万辆和1197.9万辆，同比分别增长5.36%和6.31%；商用车产销分别\r\n完成200.5万辆和206.8万辆，同比分别增长1.96%和4.94%。                                          \r\n    二、报告期内核心竞争力分析?                                                               \r\n    坚持战略引领，强化战略落实                                                                \r\n    中国汽车行业周期已经进入高质量、低成本新周期，商用车行业正面临剧烈变革，公司将紧紧抓住新能\r\n源和海外战略增长机遇，聚焦“二次创业”，坚定战略引领，加快理论创新落地和改革调整步伐。今年上半\r\n年公司坚定执行“一擎两翼”战略，持续推进战略落地，“新能源第一战略”提速发展、“国际化核心战略\r\n”纵深布局、“南方竞争性战略”破局突围、数字化变革和营销生态全面推进、全价值链降本增效持续深化\r\n，以扎实推进市场化改革与提升自主创新能力获评国务院国资委地方标杆级“科改企业”。              \r\n    公司坚持“规模领先战略”，围绕“市场占有率”和“利润率”两个核心指标及“新能源”和“出口”\r\n两个战略指标，全面提升管理能力，增强企业核心竞争力，进一步巩固和提升商用车业务的主体地位，以能\r\n力成长为核心，全价值链纵深推向一线，推动业务高质量发展。战略高度抢抓新能源发展机遇，加大资源投\r\n入，提速发展。公司紧抓海外出口机遇，稳步推进国际化战略，纵深推进海外产业化布局，升级国际合作模\r\n式。同时实现规模化、效益化，加快业务、产品和市场结构调整，持续推进降本增效，全力提升盈利能力，\r\n盘活存量资产，布局、延伸黄金产业链，打造新的利润增长点。                                      \r\n    十四五期间公司将继续坚持“绿色科技驱动能源革命，数字变革深化价值创造”的核心经营理念，坚持\r\n高质量发展，在聚焦商用车主业的基础上，进一步聚焦商用车核心业务、流程与数字化变革下的精益运营，\r\n持续推进降本增效，实现有价值的良性增长，深入稳妥地推进国际化，三线并举大力发展新能源及核心零部\r\n件，拓展汽车后市场业务，到2025年实现“打造商用车第一品牌，实现有价值的良性增长”的战略目标，改\r\n变福田汽车增长曲线，实现换挡增长——成为绿色科技和市场领先的国际化企业。                      \r\n    深化理论创新实践构建新质生产力                                                            \r\n    公司坚持走科技创新、商业模式创新及管理创新之路，通过创新转换新动能，驱动公司向上发展。一是\r\n继续实施技术与产品创新驱动发展战略，加快推进新能源、智能驾驶和混动核心技术自主可控，持续加大研\r\n发投入。二是构建全新商业模式，从“摆缸”理论向“价值环”理论升级，构建以客户为中心的生态聚合环\r\n、业务耦合环、资源融合环，形成新营销生态价值环，深化转型与调整，挖掘业务的价值增长点，带动业务\r\n良性发展。三是管理创新，从“1+N”管理架构向“矩阵式”管理架构升级，聚焦新能源转型和新生态聚变 \r\n，加快推进营销领域创新变革，全价值链纵深推向一线，提升企业竞争力，推动公司实现有价值的增长。  \r\n    端到端流程变革与数字化转型                                                                \r\n    福田汽车数字化紧密围绕“绿色科技驱动能源革命，数字变革深化价值创造”的经营理念，并结合国家\r\n高质量发展战略，构建具备“云化、移动化、共享化、互联化、快速迭代化”数字化转型顶层架构，借助工\r\n业互联网平台的数据流动、模型算法、人工智能、高性能计算加工和挖掘，构建全要素全价值链数字化服务\r\n体系，从而驱动福田汽车“价值链全业务”数字化，形成快速响应、快速决策、快速执行的数字化服务能力\r\n，打造高效“头脑”，实现“高效率”取得“高价值”。依托端到端流程变革与数字化转型，最终建立起面\r\n向用户的“实时Real-time”、“按需On-demand”、“全在线All-online”、“自助DIY”、“社交Social \r\n”的ROADS数字化应用生态，持续推进福田汽车数字化转型愿景实现。                                 \r\n    打造国际水平的黄金价值链                                                                  \r\n    以资本和战略联盟为纽带，深化产业一体化。继续深化与戴姆勒、康明斯、采埃孚的合资合作，不断深\r\n化商用车全系列发动机、变速箱、后处理等核心零部件及新能源、智能化等未来关键技术的布局，产品性能\r\n得到提升的同时，创造新的利润增长点，形成公司核心竞争优势。                                    \r\n    优秀企业文化                                                                              \r\n    公司新文化理念体系以“为能源革命提供绿色解决方案”为使命，以“成为绿色科技和市场领先的国际\r\n化企业”为愿景；公司践行“敢闯、敢试、敢赢”的核心价值观，秉承开放、公正、勇敢、包容的企业奋斗\r\n精神，规范了“严谨、细致、专业、担当”的工作作风，坚持“绿色科技驱动能源革命、数字变革深化价值\r\n创造”的经营理念，以价值为衡量、以客户为中心、以质量为生命、以绩效为导向。公司坚持创新绩效政策\r\n和分配制度，搭建以价值为导向的绩效分配机制，以客户为中心进行价值分配，让员工共享企业发展成果，\r\n打造“自驱型”的发展企业。                                                                    \r\n    荣誉称号                                                                                  \r\n    2024年1月，第六届中国民族品牌影响力论坛，公司被授予“2023年度民族品牌最具影响力企业”，标 \r\n志着公司品牌影响力达到了新高度，企业创新与发展的效能提质加速，发展成果得到社会广泛认可。      \r\n    2024年6月，在“2024金蜜蜂企业社会责任?中国榜”评选中，公司获评“ESG竞争力典范?双碳先锋”，\r\n成功入选《2024金蜜蜂责任竞争力案例集》，成为企业践行社会责任的特色典范。                      \r\n    2024年6月，中国上市公司协会公布了《2024年度上市公司数字化转型最佳实践入围案例》。公司凭借 \r\n《端到端流程变革与数字化转型案例》，入选“场景创新”数字化转型优秀案例。                      \r\n    2024年6月，公司再获由国家工业和信息化部组织认定的国家级“制造业单项冠军企业”。标志着公司 \r\n先进的产品技术、卓越的质量效益、领先的市场份额再获国家认可。                                  \r\n    2024年6月，《董事会》杂志发布公告颁发第十九届中国上市公司董事会“金圆桌奖”公司奖，公司被 \r\n评为“董事会价值创造奖”。                                                                    \r\n    期后：2024年7月，公司获得中国信息通信研究院“安全大模型优秀案例”，是汽车制造业智能安全运 \r\n营的标杆实践。                                                                                \r\n    2024年7月，中国汽车工业协会主办的第14届中国汽车论坛上发布了“2024中国汽车行业可持续发展实 \r\n践案例”，公司凭借“全面实施‘EPMES’工程保障双碳战略落地”案例成功入选并荣获“绿色发展”称号 \r\n，成为企业践行可持续发展理念的特色典范。                                                      \r\n    2024年7月，国务院国资委公布地方“双百企业”“科改企业”2023年度专项评估结果，公司获评标杆 \r\n等级“科改企业”，标志着福田汽车市场化改革成果再获行业及社会认可。                            \r\n    三、经营情况的讨论与分析                                                                  \r\n    1、汽车产品经营情况进入2024年，中国经济进入高质量增长阶段，经济增速换挡，基建投资增速放缓 \r\n，房地产回调，需求收缩和预期减弱的压力仍制约着商用车市场周期性复苏节奏，2024上半年中国商用车市\r\n场实现销量206.8万辆，同比增长4.9%。从结构上来看，行业销量增长主要来自国内市场新能源和海外出口 \r\n的增长，其中出口完成销量45.4万辆，同比增长25.7%；新能源完成销量24.6万辆，同比增长46.9%；国内市\r\n场上半年完成161.4万辆，销量同比基本持平。                                                     \r\n    福田汽车坚定执行“一擎两翼”战略，夯实巩固商用车第一行业地位，但受康明斯气体机事件、新能源\r\n商业模式和营销变革落地不到位、价格战冲击等因素影响，上半年市场表现有所波动，累计完成销量30万辆\r\n，占有率14.5%，同比下滑0.9个百分点，但二季度以来，随着产品和营销策略快速调整到位，占有率已呈现\r\n稳步回升势头。其中：                                                                          \r\n    重型卡车：受气体机事件及价格战冲击的影响，2024年上半年累计销售38170辆，同比下降19.1%，占有\r\n率7.6%。公司上半年大力推进直销业务，实现新能源跃升，南方区域市场份额持续提升；持续优化渠道质量\r\n，加快导入后市场业务，打造新的业务利润增长点。下一步将持续发力新产品，做好2024款产品推广、重卡\r\n混动产品发布，天然气车、油车全面发力；持续提升直销能力，推进营销变革，快速拓展后市场生态，挖掘\r\n价值。                                                                                        \r\n    中型卡车：受当前物流运价持续低位运行以及从业者收入下降、车辆更新周期延长的影响，2024年上半\r\n年累计销售15981辆，同比下降2.7%，占有率22.8%。公司上半年充分利用多品牌间的业务协同优势，满足客\r\n户的多元化需求，其中专用车业务取得初步突破。下一步将完善产品矩阵，加快天然气产品、纯电物流车产\r\n品投放；同时做好数字化营销体系建设，推动整体销量持续增长。                                    \r\n    轻型卡车（含微卡）：2024年上半年累计销售215461辆，同比增长3.7%，占有率17.2%。上半年紧抓经 \r\n济型市场机会，以奥铃V卡为代表的新产品市场表现强劲，进一步强化细分市场领导地位；新能源小电量、 \r\n经济型产品布局到位，产品矩阵基本形成；气体机产品提前布局，占有率保持高位。下一步将加快产品结构\r\n调整，加大价值型燃油车及新能源产品销量比重，提升专用车销量；加快传统渠道的新能源转型，推动整体\r\n销量提升。                                                                                    \r\n    大中型客车：随着经济缓慢复苏，消费者旅游需求持续释放，带动旅游车市场增长。2024年上半年累计\r\n销售3038辆，同比增长5.8%，占有率6%。公司坚持聚焦价值客户战略的理念，以实现持续盈利为目标，聚焦\r\n价值客户，聚焦重点区域。下一步将深化客户精细化管理，推动全价值链的深度协同，紧抓旅游市场更新契\r\n机，拓展客户基盘。                                                                            \r\n    轻型客车：受数字化和新能源生态转型慢的影响，2024年上半年累计销售26030辆，同比下降5.09%，市\r\n场占有率13.47%。上半年新能源销量同比提升，大VAN市场基本稳定，但大V新品销量未达预期。下一步将通\r\n过网络协同和营销生态创新，全力突破新能源核心市场；做好线上营销，聚焦主力市场，实现大V产品上量 \r\n。                                                                                            \r\n    2、其中产品出口情况                                                                       \r\n    报告期内出口整车78736辆，较去年同期增长30%。海外业务坚定不移地加快全球化战略落地，坚持战略\r\n引领，持续提升产品力，完善产品布局。加快产业化市场开发和深入属地化运营，持续推进产业市场属地化\r\n项目，完成基盘市场渠道提能及后市场能力建设，加快弱势市场渠道开发及产品导入。加强网系建设，实现\r\n业务分网，协同直销业务开发，聚焦核心市场构建后市场生态。                                      \r\n    3、发动机产品经营情况                                                                     \r\n    报告期内公司销售发动机134350台，同比降低2%。其中，福田康明斯(50:50合资公司)发动机销量83708\r\n台，同比降低14.7%；福田发动机销量50642台，同比提高27.8%。                                     \r\n    （以上数据来源于：中国汽车工业协会2024年第7期《中国汽车产销快讯》）。                     \r\n\r\n〖免责条款〗\r\n 1、本公司力求但不保证提供的任何信息的真实性、准确性、完整性及原创性等，投资者使\r\n 用前请自行予以核实，如有错漏请以中国证监会指定上市公司信息披露媒体为准，本公司\r\n 不对因上述信息全部或部分内容而引致的盈亏承担任何责任。\r\n 2、本公司无法保证该项服务能满足用户的要求，也不担保服务不会受中断，对服务的及时\r\n 性、安全性以及出错发生都不作担保。\r\n 3、本公司提供的任何信息仅供投资者参考，不作为投资决策的依据，本公司不对投资者依\r\n 据上述信息进行投资决策所产生的收益和损失承担任何责任。投资有风险，应谨慎至上。'

In [115]:
StockName = re.findall(r'\b'+StockCode+'\s+([^\s]*)',txtRaw)[0]

In [116]:
hc = re.findall(r'\d+.\d+|\d+%',re.findall(r'前5大客户[^\s]*',txt)[0])

In [117]:
pd.DataFrame(hc+hp).T

        0      1       2      3
0  136.99  24.42  159.38  32.06

In [118]:
hp = re.findall(r'\d+\.\d+|\d+%',re.findall(r'前5大供应商[^\s]*',txt)[0])

In [119]:
csdf = pd.DataFrame(hc+hp).T
csdf.columns = ["营收额","营收占比",'采购额',"采购占比"]

In [120]:
csdf['StockCode'] = StockCode
csdf['StockName'] = StockName

In [121]:
csdf

      营收额   营收占比     采购额   采购占比 StockCode StockName
0  136.99  24.42  159.38  32.06    600166      福田汽车

In [122]:
fi = txt[txt.find('【2.主营构成分析】'):]
ff = fi[:fi.find('【3.前5名客户营业收入表】')]
datetimes=re.findall(r'截止日期:([^\s]*)', ff)

In [123]:
ff

'【2.主营构成分析】\r\n截止日期:2024-06-30\r\n项目名                             营业收入(元)  收入比例(%) 营业利润(元)  利润比例(%)  毛利率(%)\r\n─────────────────────────────────────────────────\r\n轻型车分部(产品)                       268.83亿       112.16      13.74亿        45.82       5.11\r\n海外分部(产品)                          71.31亿        29.75       8.59亿        28.67      12.05\r\n管理及研发分部(产品)                    62.42亿        26.04      10.07亿        33.59      16.13\r\n大中客分部(产品)                        34.53亿        14.41       1.69亿         5.65       4.90\r\n发动机分部(产品)                        14.22亿         5.93       2.75亿         9.18      19.34\r\n其他分部(产品)                        4841.52万         0.20    3962.62万         1.32      81.85\r\n分部间抵销(产品)                      -212.11亿       -88.50      -7.26亿       -24.21       3.42\r\n─────────────────────────────────────────────────\r\n\r\n截止日期:2023-12-31\r\n项目名                             营业收入(元)  收入比例(%) 营业利润(元)  利润比例(%)  毛利率(%)\r\n─────────────────────────────────────────────────\r\n汽车行业(行业)                         534.35亿        95.26      57.72亿        90.41      10.80\r\n其他业务(行业)                          26.62亿         4.74       6.12亿         9.59      22.99\r\n─────────────────────────────────────────────────\r\n轻卡(产品)                             266.37亿        47.48      23.88亿        37.40       8.96\r\n发动机(产品)                            68.91亿        12.28       2.45亿         3.85       3.56\r\n中重卡(产品)                            67.34亿        12.00      13.57亿        21.25      20.15\r\n轻客(产品)                              50.69亿         9.04       7.92亿        12.40      15.62\r\n大中客(产品)                            41.29亿         7.36       5.12亿         8.02      12.41\r\n配件(产品)                              39.05亿         6.96       4.68亿         7.32      11.97\r\n其他(产品)                              26.62亿         4.74       6.12亿         9.59      22.99\r\n冲压件(产品)                          5623.20万         0.10     876.87万         0.14      15.59\r\n重型机械(产品)                        1483.79万         0.03     170.30万         0.03      11.48\r\n─────────────────────────────────────────────────\r\n中国大陆境内(地区)                     429.07亿        76.49      41.78亿        65.45       9.74\r\n其他国家及地区(地区)                   131.89亿        23.51      22.06亿        34.55      16.72\r\n─────────────────────────────────────────────────\r\n代理销售(销售模式)                     466.07亿        83.08      52.31亿        81.94      11.22\r\n其他(销售模式)                          94.90亿        16.92      11.53亿        18.06      12.15\r\n─────────────────────────────────────────────────\r\n\r\n截止日期:2023-06-30\r\n项目名                             营业收入(元)  收入比例(%) 营业利润(元)  利润比例(%)  毛利率(%)\r\n─────────────────────────────────────────────────\r\n轻型车分部(产品)                       297.36亿       103.09      -5.73亿       -16.95      -1.93\r\n海外分部(产品)                          95.38亿        33.07       7.40亿        21.91       7.76\r\n管理及研发分部(产品)                    69.42亿        24.07    6838.89万         2.02       0.99\r\n大中客分部(产品)                        60.53亿        20.98    8703.48万         2.58       1.44\r\n发动机分部(产品)                        10.87亿         3.77   -2943.88万        -0.87      -2.71\r\n其他分部(产品)                        6038.45万         0.21    2980.56万         0.88      49.36\r\n分部间抵销(产品)                      -245.72亿       -85.18    7337.14万         2.17      -0.30\r\n─────────────────────────────────────────────────\r\n\r\n截止日期:2022-12-31\r\n项目名                             营业收入(元)  收入比例(%) 营业利润(元)  利润比例(%)  毛利率(%)\r\n─────────────────────────────────────────────────\r\n汽车行业(行业)                         430.29亿        92.64      45.64亿        86.36      10.61\r\n其他(补充)(行业)                        34.18亿         7.36       7.21亿        13.64      21.10\r\n─────────────────────────────────────────────────\r\n轻卡(产品)                             243.24亿        52.37      21.91亿        41.45       9.01\r\n大中客(产品)                            56.75亿        12.22       7.40亿        14.01      13.04\r\n中重卡(产品)                            45.77亿         9.85       5.76亿        10.90      12.59\r\n轻客(产品)                              36.25亿         7.80       6.64亿        12.56      18.31\r\n其他(产品)                              34.18亿         7.36       7.21亿        13.64      21.10\r\n发动机(产品)                            24.43亿         5.26    1671.94万         0.32       0.68\r\n配件(产品)                              23.13亿         4.98       3.68亿         6.96      15.89\r\n冲压件(产品)                          6854.15万         0.15     672.37万         0.13       9.81\r\n重型机械(产品)                         377.77万         0.01     236.79万         0.04      62.68\r\n─────────────────────────────────────────────────\r\n中国大陆境内(地区)                     340.18亿        73.24      36.81亿        69.64      10.82\r\n其他国家及地区(地区)                   124.29亿        26.76      16.05亿        30.36      12.91\r\n─────────────────────────────────────────────────\r\n代理销售(销售模式)                     372.48亿        80.19      40.42亿        76.48      10.85\r\n其他(销售模式)                          57.81亿        12.45       5.22亿         9.88       9.03\r\n其他(补充)(销售模式)                    34.18亿         7.36       7.21亿        13.64      21.10\r\n─────────────────────────────────────────────────\r\n\r\n'

In [320]:
# re.findall(r'截止日期:([^\s]*)', ff)
# re.findall(r'截止日期:(\S{10})', ff)

In [34]:
dd = ff.replace('─','').splitlines(keepends=False)

In [124]:
dd

['【4.估值水平排名】(前30) 截止日期:2024-12-30',
 '排名     股票名称      市盈率(TTM)    市盈率(LYR)    市净率(MRQ)    市销率(TTM)    市现率(TTM)',
 '',
 '1        新华联               6.05          37.71           2.41           3.83        -105.42',
 '2        南京高科             7.86           8.71           0.71           6.76          -9.98',
 '3        京基智农             8.86           5.53           2.33           1.36          12.05',
 '4        津滨发展             9.75           7.43           1.27           1.54         -30.34',
 '5        中新集团            11.98           8.83           0.83           3.97          12.16',
 '6        衢州发展            15.64          15.91           0.59           0.94          65.00',
 '7        滨江集团            15.74          10.52           1.00           0.41           7.95',
 '8        保利发展            16.34           8.92           0.55           0.32         -12.12',
 '9        华发股份            16.82           8.85           0.78           0.29           2.05',
 '10       招商蛇口            17.94          14.62           0.95           0.52           4.95',
 '11       外高桥              18.24          14.64           1.09           1.85          -5.01',
 '12       中国国贸            19.12          19.37           2.59           6.17          13.51',
 '13       城建发展            20.79          18.83           0.51           0.65           1.49',
 '14       浦东金桥            21.42           6.93           0.89           3.88         -55.22',
 '15       天保基建            26.26         170.60           0.63           1.10         -14.98',
 '16       上海临港            28.04          24.57           1.40           3.37          -6.91',
 '17       ST广物              30.90          19.91           1.68           3.11           7.60',
 '18       沙河股份            36.80           5.19           1.64           5.56          28.55',
 '19       苏州高新            45.93          37.77           1.02           0.91          -2.78',
 '20       陆家嘴              48.33          46.51           2.07           4.41           6.07',
 '21       苏宁环球            48.68          40.99           0.77           3.13         -36.69',
 '22       渝 开 发            53.90          33.28           0.95           2.55          16.15',
 '23       张江高科            61.84          45.35           3.42          21.91         -18.94',
 '24       中国武夷            62.03         113.95           0.85           0.45         -11.38',
 '25       信达地产            77.34          24.49           0.50           1.13          -4.11',
 '26       卧龙地产            81.40          17.13           0.74           0.99          23.18',
 '27       华联控股            89.91          75.63           1.21          12.79         -25.67',
 '28       珠江股份            93.36            ---           6.11           1.78          80.56',
 '29       华丽家族            95.05          73.24           1.17          14.75          -7.04',
 '83       万  科Ａ              ---           7.22           0.38           0.22         -75.01',
 '',
 '行业平均                    -16.62         842.13           0.71           0.51          31.66',
 '市场平均                    -40.15         -34.74           2.18           2.59          37.97',
 '',
 '']

In [125]:

# Data = pd.DataFrame(columns=("股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"))
Data = pd.DataFrame(columns=())
i = 0
while i < len(dd):
    lis = re.split(r"\s+", dd[i])[-6:]
    if len(lis)!=6:
        i = i+1
        # pass
    else:
        df = pd.DataFrame(lis).T
        # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
        Data = pd.concat([Data, df],axis=0)
        i=i+1
Data.reset_index(drop=True,inplace=True)
Data = Data.replace('---',pd.NA)
# ddf  = Data.apply(pd.to_numeric, errors='ignore')

In [126]:
ddf = Data

In [127]:
ddfindex = ddf[ddf[0]=='项目名'].index

In [128]:
ddfindex

Index([], dtype='int64')

In [129]:
i = 0
raDF = pd.DataFrame(columns=['日期',"项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"])

In [130]:
for i in [0,1,2]:
    dfd = ddf.loc[(ddfindex[i]+1):(ddfindex[i+1]-1)].reset_index(drop=True)
    dfd.columns = ["项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]
    dfd['日期'] = datetimes[i]
    raDF = pd.concat([raDF,dfd], axis=0)

IndexError: index 0 is out of bounds for axis 0 with size 0

In [42]:
raDF['StockCode'] = StockCode
raDF['StockName'] = StockName

In [43]:
raDF.set_index('日期')

,项目名,营业收入(元),收入比例(%),营业利润(元),利润比例(%),毛利率(%),StockCode,StockName
日期,,,,,,,,
2024-06-30,轻型车分部(产品),268.83亿,112.16,13.74亿,45.82,5.11,600166,福田汽车
2024-06-30,海外分部(产品),71.31亿,29.75,8.59亿,28.67,12.05,600166,福田汽车
2024-06-30,管理及研发分部(产品),62.42亿,26.04,10.07亿,33.59,16.13,600166,福田汽车
2024-06-30,大中客分部(产品),34.53亿,14.41,1.69亿,5.65,4.90,600166,福田汽车
2024-06-30,发动机分部(产品),14.22亿,5.93,2.75亿,9.18,19.34,600166,福田汽车
2024-06-30,其他分部(产品),4841.52万,0.20,3962.62万,1.32,81.85,600166,福田汽车
2024-06-30,分部间抵销(产品),-212.11亿,-88.50,-7.26亿,-24.21,3.42,600166,福田汽车
2023-12-31,汽车行业(行业),534.35亿,95.26,57.72亿,90.41,10.80,600166,福田汽车
2023-12-31,其他业务(行业),26.62亿,4.74,6.12亿,9.59,22.99,600166,福田汽车
2023-12-31,轻卡(产品),266.37亿,47.48,23.88亿,37.40,8.96,600166,福田汽车
2023-12-31,发动机(产品),68.91亿,12.28,2.45亿,3.85,3.56,600166,福田汽车
2023-12-31,中重卡(产品),67.34亿,12.00,13.57亿,21.25,20.15,600166,福田汽车
2023-12-31,轻客(产品),50.69亿,9.04,7.92亿,12.40,15.62,600166,福田汽车
2023-12-31,大中客(产品),41.29亿,7.36,5.12亿,8.02,12.41,600166,福田汽车
2023-12-31,配件(产品),39.05亿,6.96,4.68亿,7.32,11.97,600166,福田汽车
2023-12-31,其他(产品),26.62亿,4.74,6.12亿,9.59,22.99,600166,福田汽车
2023-12-31,冲压件(产品),5623.20万,0.10,876.87万,0.14,15.59,600166,福田汽车
2023-12-31,重型机械(产品),1483.79万,0.03,170.30万,0.03,11.48,600166,福田汽车
2023-12-31,中国大陆境内(地区),429.07亿,76.49,41.78亿,65.45,9.74,600166,福田汽车
2023-12-31,其他国家及地区(地区),131.89亿,23.51,22.06亿,34.55,16.72,600166,福田汽车
2023-12-31,代理销售(销售模式),466.07亿,83.08,52.31亿,81.94,11.22,600166,福田汽车
2023-12-31,其他(销售模式),94.90亿,16.92,11.53亿,18.06,12.15,600166,福田汽车
2023-06-30,轻型车分部(产品),297.36亿,103.09,-5.73亿,-16.95,-1.93,600166,福田汽车
2023-06-30,海外分部(产品),95.38亿,33.07,7.40亿,21.91,7.76,600166,福田汽车
2023-06-30,管理及研发分部(产品),69.42亿,24.07,6838.89万,2.02,0.99,600166,福田汽车
2023-06-30,大中客分部(产品),60.53亿,20.98,8703.48万,2.58,1.44,600166,福田汽车
2023-06-30,发动机分部(产品),10.87亿,3.77,-2943.88万,-0.87,-2.71,600166,福田汽车
2023-06-30,其他分部(产品),6038.45万,0.21,2980.56万,0.88,49.36,600166,福田汽车
2023-06-30,分部间抵销(产品),-245.72亿,-85.18,7337.14万,2.17,-0.30,600166,福田汽车

In [44]:
dfd.set_index('日期')

                    项目名   营业收入(元) 收入比例(%)    营业利润(元) 利润比例(%) 毛利率(%)
日期
2023-06-30    轻型车分部(产品)   297.36亿  103.09     -5.73亿  -16.95  -1.93
2023-06-30     海外分部(产品)    95.38亿   33.07      7.40亿   21.91   7.76
2023-06-30  管理及研发分部(产品)    69.42亿   24.07   6838.89万    2.02   0.99
2023-06-30    大中客分部(产品)    60.53亿   20.98   8703.48万    2.58   1.44
2023-06-30    发动机分部(产品)    10.87亿    3.77  -2943.88万   -0.87  -2.71
2023-06-30     其他分部(产品)  6038.45万    0.21   2980.56万    0.88  49.36
2023-06-30    分部间抵销(产品)  -245.72亿  -85.18   7337.14万    2.17  -0.30

In [45]:
dfd[dfd['项目名'].str.contains('行业', na=False)]

Empty DataFrame
Columns: [项目名, 营业收入(元), 收入比例(%), 营业利润(元), 利润比例(%), 毛利率(%), 日期]
Index: []

In [46]:
dfd[dfd['项目名'].str.contains('产品', na=False)]

           项目名   营业收入(元) 收入比例(%)    营业利润(元) 利润比例(%) 毛利率(%)          日期
0    轻型车分部(产品)   297.36亿  103.09     -5.73亿  -16.95  -1.93  2023-06-30
1     海外分部(产品)    95.38亿   33.07      7.40亿   21.91   7.76  2023-06-30
2  管理及研发分部(产品)    69.42亿   24.07   6838.89万    2.02   0.99  2023-06-30
3    大中客分部(产品)    60.53亿   20.98   8703.48万    2.58   1.44  2023-06-30
4    发动机分部(产品)    10.87亿    3.77  -2943.88万   -0.87  -2.71  2023-06-30
5     其他分部(产品)  6038.45万    0.21   2980.56万    0.88  49.36  2023-06-30
6    分部间抵销(产品)  -245.72亿  -85.18   7337.14万    2.17  -0.30  2023-06-30

In [47]:
dfd[dfd['项目名'].str.contains('产品', na=False)]['利润比例(%)'].astype(float).sum()

np.float64(11.740000000000002)

In [48]:
def getBiz(StockCode):
    qf10='经营分析'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)[116:]   
    # txt = txtRaw[116:]

    StockName = re.findall(r'\b'+StockCode+'\s+([^\s]*)',txtRaw)[0]
    try:
        hc = re.findall(r'\d+.\d+|\d+%',re.findall(r'前5大客户[^\s]*',txt)[0])
        hp = re.findall(r'\d+\.\d+|\d+%',re.findall(r'前5大供应商[^\s]*',txt)[0])
        csdf = pd.DataFrame(hc+hp).T
        csdf.columns = ["营收额","营收占比",'采购额',"采购占比"]
        csdf['StockCode'] = StockCode
        csdf['StockName'] = StockName


    except:
        pass

    fi = txt[txt.find('【2.主营构成分析】'):]
    ff = fi[:fi.find('【3.前5名客户营业收入表】')]
    datetimes=re.findall(r'截止日期:([^\s]*)', ff)
    dd = ff.replace('─','').splitlines(keepends=False)

    Data = pd.DataFrame(columns=())
    i = 0
    while i < len(dd):
        lis = re.split(r"\s+", dd[i])[-6:]
        if len(lis)!=6:
            i = i+1
            # pass
        else:
            df = pd.DataFrame(lis).T
            # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
            Data = pd.concat([Data, df],axis=0)
            i=i+1
    Data.reset_index(drop=True,inplace=True)
    Data = Data.replace('---',0)
    ddf  = Data.apply(pd.to_numeric, errors='ignore')

    ddfindex = ddf[ddf[0]=='项目名'].index
    raDF = pd.DataFrame(columns=['日期',"项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"])

    for i in [0,1,2]:
        dfd = ddf.loc[(ddfindex[i]+1):(ddfindex[i+1]-1)].reset_index(drop=True)
        dfd.columns = ["项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]
        dfd['日期'] = datetimes[i]
        raDF = pd.concat([raDF,dfd], axis=0)

    raDF['StockCode'] = StockCode
    raDF['StockName'] = StockName
    # raDF.set_index('日期').to_sql('Biz', eng, if_exists='append')
    return(raDF,csdf)

In [49]:
a,b = getBiz('000005')

/tmp/ipykernel_3132393/1655987227.py:42: FutureWarning:

errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead

In [50]:
list(a['项目名'])[2]

'其他业务(行业)'

In [51]:
from sqlalchemy import create_engine
engs = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')

In [52]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [53]:
StockList.iloc[0,0]

'000001'

In [54]:
pd.read_sql('StocksList', engs)[['code','name']].iloc[0,1]

'平安银行'

In [55]:
StockList.iloc[15,1]

'深科技'

================== 热点题材

In [56]:
StockCode = '688338'

In [57]:
from mootdx.quotes import Quotes
import pandas as pd
import plotly.express as px
import re


qf10='热点题材'
client = Quotes.factory(market='std')
txt = client.F10(StockCode, qf10)[116:]

In [58]:
txt = txt.replace('│',' ')
txt = re.sub('([\u2500-\u25f7])','',txt)

In [59]:
txt

'                                                             \r\n风格:融资融券、回购计划、专精特新                                                   \r\n指数:无                                                                             \r\n\r\n【2.主题投资】\r\n\r\n  2021-11-26 新冠检测     关联度：☆☆☆☆                                        \r\n\r\n    公司的SF系列凝血仪器位列《关于推荐新冠肺炎疫情防治急需医学装备的通知》所附的全自\r\n动凝血仪设备名目中                                                                  \r\n\r\n\r\n  2022-01-14 体外诊断     关联度：☆☆☆☆☆                                      \r\n\r\n    致力于血栓与止血体外诊断领域的检测仪器、试剂及耗材的研发、生产和销售，为医疗机构\r\n提供凝血、血液流变、血沉压积、血小板聚集等自动化检测仪器及配套的试剂和耗材，是血栓与\r\n止血体外诊断领域领先的国内生产商                                                    \r\n\r\n\r\n  2022-01-06 医疗器械概念 关联度：☆☆☆                                          \r\n\r\n    公司自主研发的血栓与止血体外诊断产品已取得21项医疗器械产品注册证书              \r\n\r\n\r\n         --- 不可减持(新  关联度：☆☆☆☆                                        \r\n             规)                                                                  \r\n\r\n    公司近20个交易日内跌破发行价，依照减持新规，控股股东和实际控制人不可减持。      \r\n\r\n\r\n  2024-12-02 回购计划     关联度：☆☆☆                                          \r\n\r\n    公司拟回购不超过10000万元(289.855万股),回购期:2024-06-26至2025-06-25            \r\n\r\n\r\n  2024-11-28 专精特新     关联度：☆☆☆                                          \r\n\r\n    公司已入选工信部专精特新小巨人企业名单。                                        \r\n\r\n【3.事件驱动】\r\n\r\n  2023-10-10 英国科学家研制出新方法，一次检测数十种生物标志物                      \r\n\r\n    英国帝国理工学院的科学家与牛津纳米孔技术公司合作研制出一种新方法，可同时分析数十\r\n种不同类型的生物标志物，改变了对心脏病和癌症等疾病的检测，从而让临床医生收集到有关患\r\n者疾病的更多信息。研究成果25日发表在《自然?纳米技术》杂志上。                       \r\n\r\n\r\n  2022-10-17 财政贴息政策火速在医疗领域推进落地 千亿医疗器械市场需求或释放         \r\n\r\n    备受关注的财政贴息政策火速在医疗健康领域推进落地。据媒体公开报道，十一国庆假期前\r\n后，已有多笔医疗设备更新改造贴息贷款陆续发放。                                      \r\n\r\n【4.信息面面观】\r\n\r\n 栏目名称                                  栏目内容                              \r\n\r\n 产品业务     致力于血栓与止血体外诊断领域的检测仪器、试剂及耗材的研发、 生产和  \r\n              销售，为医疗机构提供凝血、血液流变、血沉压积、血小板聚集等自动化检 \r\n              测仪器及配套的试剂和耗材，是血栓与止血体外诊断领域领先的国内生产商 \r\n              。                                                                 \r\n\r\n 经营模式     采购模式：公司原材料的采购均由生产中心下属物资部统一负责，物资部按 \r\n              照《采购控制程序》执行采购。对于危险化学品，严格按照《危险化学品管 \r\n              理制度》执行采购。批量物料的采购，由生产总监根据库存情况及销售计划 \r\n              下达《批量产品投产令》，发放给物资部，由物资部根据产品物料清单编制 \r\n              《采购计划》，经生产总监审批，物资部负责采购计划的执行。其中：生产 \r\n              使用的辅助物料，物资部确定                                         \r\n              库存下限，实际库存低于下限时，由物资部直接采购；关键物料和一般物料 \r\n              也会按照产品销售计划和市场价格情况进行采购，通过提高采购数量降低采 \r\n              购成本。临时或零散物资采购，由需求者提出采购需求，经所在部门总监批 \r\n              准后，提交物资部执行采购。                                         \r\n              生产模式：公司实行以销定产的生产模式。销售部负责制定年度销售计划， \r\n              生产中心根据销售计划制定生产计划，并根据市场情况、库存情况和销售量 \r\n              情况随时调整季度、月度生产计划，最后由生产中心组织生产。           \r\n              研发模式：体外诊断行业属于技术密集型行业，公司注重技术研发与创新， \r\n              从组织结构、研发机制、人员配备、知识产权保护、加强保密等多方面保障 \r\n              技术创新能力。同时为提高技术创新效率，公司建立了以市场为导向的技术 \r\n              创新体系，并与医疗机构深入合作，搭建学术交流平台，推动血栓与止血体 \r\n              外诊断在临床上的应用。研发中心作为承担公司科技创新及技术管理的部门 \r\n              ，主要负责编制设计计划、技术研究、新产品开发和产品重大改进的设计、 \r\n              收集国内外同行业先进技术进行理论实践研究、编制设计文件及关键工艺等 \r\n              工作。                                                             \r\n              销售模式：公司采用“经销与直销相结合，以经销为主”的销售模式，占营 \r\n              业收入 98%左右的产品通过经销商销售给终端用户，也有少部分产品直接销 \r\n              售给终端客户。目前，公司的经销网络已经覆盖国内除港澳台、青海、西藏 \r\n              外的 29 个省、直辖市、自治区。                                     \r\n\r\n 行业地位     将公司打造成为行业领先的血栓与止血体外诊断专业品牌                 \r\n\r\n 核心竞争力   体外诊断结果反映患者的机体功能和疾病状况，为疾病的筛查、诊断等提供 \r\n              依据，系统的有效溯源作为质量管理体系最关键的指标，是体外诊断产品的 \r\n              核心竞争力之一                                                     \r\n\r\n 经营指标     公司作为国内主要的血栓与止血体外诊断产品生产厂家之一，2018年市场份 \r\n              额占比约为 4%。截至 2019 年 12 月 31 日，公司主要产品已经进入到国  \r\n              内 8,000 多家终端医疗机构，包括 800 多家三级医院，能够满足终端医疗 \r\n              机构在血栓与止血体外诊断领域的检测需求。                           \r\n\r\n 竞争对手     希森美康株式会社、思塔高集团、美国国家仪器实验室、深圳迈瑞生物医疗 \r\n              电子股份有限公司、深圳雷杜生命科学股份有限公司、上海太阳生物技术有 \r\n              限公司、北京众驰伟业科技发展有限公司                               \r\n\r\n 品牌/专利/经 SF-8200 全自动凝血测试仪、SF-8100 全自动凝血测试仪、SF-8050 全自动 \r\n 营权         凝血测试仪、SF-8000 全自动凝血测试仪、活化部分凝血活酶时间测定试剂 \r\n              盒、纤维蛋白原含量测定试剂盒、凝血酶原时间测定试剂盒、凝血酶时间测 \r\n              定试剂盒、纤维蛋白（原）降解产物测定试剂盒、D-二聚体测定试剂盒、D- \r\n              二聚体质控品试剂盒、凝血质控品试剂盒、SFT特殊清洗液、SFW清洗液、凝 \r\n              血测试仪用反应杯、SA-9800 全自动血流变测试仪、SA-9000 全自动血流变 \r\n              测试仪、SA-7000 全自动血流变测试仪、SA-6900 全自动血流变测试仪、SA \r\n              -6600 全自动血流变测试仪、SA-6000 全自动血流变测试仪、SA-5600 全自 \r\n              动血流变测试仪                                                     \r\n\r\n 核心风险     经营风险：国外品牌在国内血栓与止血体外诊断市场尤其是三级医院的竞争 \r\n              优势明显，公司面临较大的国内市场拓展风险；公司试剂产品覆盖面较小可 \r\n              能对未来持续发展造成不利影响；公司存在重要原材料由国外单一供应商供 \r\n              应的进口依赖风险；公司的原材料成本占营业成本的比例较高，若原材料价 \r\n              格大幅上升，公司面临毛利率下降的风险；公司可能面临因产品结构单一、 \r\n              应用领域集中、产品注册证书较少导致无法满足未来市场需求的风险；公司 \r\n              面临血流变检测产品市场空间有限的风险；新型冠状病毒疫情进一步持续可 \r\n              能导致发行人 2020 年度经营业绩较 2019年度下滑的风险；公司可能面临  \r\n              因产品质量问题引起索赔或者发生法律诉讼、仲裁，甚至受到行政处罚的风 \r\n              险；公司可能因不能及时适应行业监管政策及标准变化，将对公司的持续经 \r\n              营造成不利影响；若“两票制” 在体外诊断领域全面推行，而公司不能及  \r\n              时做出应对措施，公司的经营业绩将受到不利影响；境外市场不确定性较高 \r\n              ，导致公司存在一定的境外市场开拓风险；发行人采取区域经销商模式，若 \r\n              区域经销商与发行人不再合作或对发行人产品推广不力，可能对发行人的经 \r\n              营业绩带来不利影响；若公司研发投入和学术推广不足，可能对公司在国内 \r\n              血栓与止血体外诊断市场的业务发展带来不利影响                       \r\n              技术风险：如果未来血栓与止血体外诊断产品技术发生重大变化或革命性迭 \r\n              代，公司将面临技术迭代风险；体外诊断产品研发周期长，且特殊及创新型 \r\n              检测试剂的研发存在较高壁垒，公司产品存在研发失败的风险；公司可能因 \r\n              核心技术人员流失导致研发和生产经营受到不利影响；公司可能因核心技术 \r\n              泄密导致竞争优势受损，并对公司的生产经营产生不利影响               \r\n\r\n 投资逻辑     国内主要的血栓与止血体外诊断产品生产厂家之一                       \r\n\r\n 消费群体     需要进行血栓性及出血性疾病的预防、筛查、诊断和监测的人群           \r\n\r\n 消费市场     华东地区、西南地区、华中地区、华北地区、华南地区、东北地区、西北地 \r\n              区、海外地区                                                       \r\n\r\n 公司发展战略 秉承“成功源自专一，服务创造价值”的核心价值观，公司将继续推进细分 \r\n              领域专业化的发展战略，保持核心业务竞争优势。以科技创新为导向，依托 \r\n              在血栓与止血体外诊断领域的技术研发优势，公司将持续布局技术含量高、 \r\n              市场前景广阔的系列化诊断产品的研发；同时向产业链上下游拓展，提供一 \r\n              体化的血栓与止血体外诊断解决方案，将公司打造成为行业领先的血栓与止 \r\n              血体外诊断专业品牌。                                               \r\n\r\n 公司日常经营 自成立以来一直致力于血栓与止血体外诊断领域的检测仪器、试剂及耗材的 \r\n              研发、 生产和销售，为医疗机构提供凝血、血液流变、血沉压积、血小板  \r\n              聚集等自动化检测仪器及配套的试剂和耗材，是血栓与止血体外诊断领域领 \r\n              先的国内生产商。                                                   \r\n\r\n 公司经营计划 研发计划：公司将依托已有核心技术平台，进一步加大研发投入，不断提升 \r\n              现有凝血测试仪、血流变测试仪的测量技术水平和自动化程度。同时公司将 \r\n              研发各类凝血流水线、高速全自动凝血测试仪、高速全自动血流变测试仪、 \r\n              全自动血小板功能分析仪以及血栓弹力图等产品，来满足中国医疗市场的需 \r\n              求。                                                               \r\n              生产基地建设计划：公司拟通过子公司赛诺希德实施生产基地建设项目，通 \r\n              过新增3,500㎡生产厂房、增加生产设备、扩充人员来扩大体外诊断仪器、  \r\n              试剂及耗材等产能，解决公司产能瓶颈问题，进一步扩大生产规模、提升产 \r\n              品质量和技术水平，提高公司的盈利水平。项目建成后，预计新增 2,200   \r\n              台仪器、 28,000 升试剂、 2,700,000 升耗材（清洗液）产能。          \r\n              市场开拓计划：国内市场开拓计划，公司将加快营销网络建设，在北京建立 \r\n              营销中心以及在全国 24 个省（直辖市）建设省级办事处，通过强化营销团 \r\n              队培训及建设，增加营销团队的市场覆盖能力和渗透能力，依托办事处建立 \r\n              区域服务中心和推广中心，最终形成覆盖全国的市场营销网络。公司将充分 \r\n              发挥产品和服务的专业优势，通过学术推广和专业服务，提升品牌形象和口 \r\n              碑， 促进销售增长，保持在国产品牌中的领先优势。公司将持续强化大客  \r\n              户营销团队建设，依托公司产品和服务的专业优势，进一步拓展大型公立医 \r\n              院、医联体、第三方检验机构、连锁医院等客户，适应医改后市场格局的变 \r\n              化，以提高公司产品的市场占有率海外市场拓展计划：为适应全球体外诊断 \r\n              产品市场规模不断扩大的局面，公司将积极拓展海外市场。在中东、亚非拉 \r\n              等发展中国家，血栓与止血体外诊断市场发展还处于起步阶段，但当地人口 \r\n              增长较快，未来随着收入水平的提高，市场需求也会逐渐释放。而公司体外 \r\n              诊断产品在发展中国家市场具备性价比优势，适应其当前发展阶段。在未来 \r\n              三到五年，公司将继续配合国家“一带一路”政策，遵从“重点突破、以点 \r\n              带面”的原则，选择重点市场区域进行集中营销。拓展计划主要包括：第一 \r\n              ，在中东、东南亚、南亚等有市场基础的区域设置海外联络处，加强当地市 \r\n              场覆盖和渗透程度，提升市场份额；第二，重点开发拉美、北非新市场，积 \r\n              极推进产品在海外市场准入注册及认证工作，通过加强重点市场的品牌推广 \r\n              和渠道建设，获取业务增长的驱动力。                                 \r\n              人力资源发展计划：体外诊断具有多学科交叉融合的技术特点，在研发、生 \r\n              产、服务领域都需要大量复合型、专业化人才。公司践行“以人为本”战略 \r\n              思想，积极推动人才队伍建设，将通过                                 \r\n\r\n 公司资金需求 生产基地建设项目；研发中心建设项目；营销网络建设项目               \r\n\r\n 可能面对风险 内控及管理风险：公司未来规模扩张导致的经营管理风险；控股股东和实际 \r\n              控制人风险                                                         \r\n              财务风险：公司毛利率低于同行业上市公司平均水平，若不能持续推出盈利 \r\n              能力较强的新产品，公司可能存在毛利率下降的风险；税收优惠政策可能发 \r\n              生变化或存在公司到期后不能持续享受税收优惠的风险；汇率变动可能导致 \r\n              公司汇兑损益增大的风险                                             \r\n              法律风险：部分经销商使用“赛科希德”字样的风险；公司可能面临因环境 \r\n              保护力度不足而受到主管部门处罚的风险                               \r\n              募集资金投资项目风险：公司可能面临募集资金投资项目无法顺利实施或者 \r\n              不能达到预期效益， 导致公司的整体技术水平和核心竞争力也无法进一步  \r\n              提升，并对公司经营产生不利影响；公司可能面临募集资金投资项目实施后 \r\n              新增产能难以消化、新研发产品市场拓展不达预期的风险；募投项目实施导 \r\n              致的折旧摊销、研发支出、销售费用的增长将影响公司未来的经营业绩；公 \r\n              司即期回报被摊薄的风险                                             \r\n\r\n 股东回报规划 根据《公司法》等有关法律法规及《公司章程》的规定，公司制定未来三年 \r\n              （2024—2026年）股东回报规划：公司可以采取现金、股票、现金与股票相 \r\n              结合或法律、法规允许的其他方式分配利润。在满足现金分红的条件下，公 \r\n              司应当进行现金分红，且每年以现金方式分配的利润应当不少于当年实现的 \r\n              可分配利润的10%。公司经营情况良好，并且董事会认为发放股票股利有利  \r\n              于维护公司及股东整体利益时，可以在满足上述现金分红的条件下，提出股 \r\n              票股利分配预案，并经股东大会审议通过后实施。公司采用股票股利进行利 \r\n              润分配的，应当具有公司成长性、每股净资产的摊薄等真实合理因素。     \r\n\r\n\r\n〖免责条款〗\r\n 1、本公司力求但不保证提供的任何信息的真实性、准确性、完整性及原创性等，投资者使\r\n 用前请自行予以核实，如有错漏请以中国证监会指定上市公司信息披露媒体为准，本公司\r\n 不对因上述信息全部或部分内容而引致的盈亏承担任何责任。\r\n 2、本公司无法保证该项服务能满足用户的要求，也不担保服务不会受中断，对服务的及时\r\n 性、安全性以及出错发生都不作担保。\r\n 3、本公司提供的任何信息仅供投资者参考，不作为投资决策的依据，本公司不对投资者依\r\n 据上述信息进行投资决策所产生的收益和损失承担任何责任。投资有风险，应谨慎至上。'

In [60]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [61]:
n = 100

In [62]:
StockCode = StockList.iloc[n,0]
StockName = StockList.iloc[n,1]

In [63]:
ftxt = re.findall(r'│(.*)│(关联度:.*☆{4,})',txt)

In [64]:
re.findall(r'│(.*)│(关联度.*☆{4,})',txt)

[]

In [65]:
txtt = re.findall(r'(\S+)\s+(\S+)\s+(关联度.☆{4,})',txt)

In [66]:
re.findall(r'(\S+)\s+(\S+)\s+(关联度.☆{4,})',txt)

[('2021-11-26', '新冠检测', '关联度：☆☆☆☆'),
 ('2022-01-14', '体外诊断', '关联度：☆☆☆☆☆'),
 ('---', '不可减持(新', '关联度：☆☆☆☆')]

In [67]:
txDF = pd.DataFrame(txtt)

In [68]:
ftdf = pd.DataFrame(ftxt)

In [69]:
ftdf

Empty DataFrame
Columns: []
Index: []

In [70]:
ftdf = ftdf.map(lambda x: x.rstrip() if isinstance(x, str) else x)

In [71]:
ftdf[1]=ftdf[1].str.len()-4

KeyError: 1

In [72]:
ftdf.columns=['题材','相关度']

ValueError: Length mismatch: Expected axis has 0 elements, new values have 2 elements

In [62]:
ftdf['StockCode']=StockCode
ftdf['StockName']=StockName

In [74]:
def getTop(StockCode, StockName):
    qf10='热点题材'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)[116:]

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)
    txt = re.findall(r'(\S+)\s+(\S+)\s+(关联度.☆{4,})',txt)
    # txt = re.findall(r'│(.*)│(关联度.*☆{4,})',txtRaw)
    txDF = pd.DataFrame(txt)
    # txDF = txDF.map(lambda x: x.rstrip() if isinstance(x, str) else x)
    txDF[2]=txDF[2].str.len()-4
    txDF.columns=['日期','题材','相关度']
    txDF['StockCode'] = StockCode
    txDF['StockName'] = StockName
    # txDF.set_index('StockCode').to_sql('Top', eng, if_exist='append')
    return(txDF)

In [75]:
getTop(StockCode,StockName)

           日期      题材  相关度 StockCode StockName
0  2021-11-01    智能医疗    4    000516      国际医学
1  2021-10-12    民营医院    5    000516      国际医学
2  2021-09-17   兜底式增持    5    000516      国际医学
3         ---  不可减持(新    4    000516      国际医学
4  2024-10-24    连续亏损    4    000516      国际医学

======================= 价值分析

In [77]:
from mootdx.quotes import Quotes
import pandas as pd
import re
from sqlalchemy import create_engine

eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
engs = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')

StockList = pd.read_sql('StocksList', engs)[['code','name']]
n = 1

StockCode = StockList.iloc[n,0]
StockName = StockList.iloc[n,1]


qf10='价值分析'
client = Quotes.factory(market='std')
txtRaw = client.F10(StockCode, qf10)[116:]
txt = txtRaw.replace('│',' ')                
txt = re.sub('([\u2500-\u25f7])','',txt)

In [78]:
ftxt = txt[txt.find('【2.盈利预测统计】'):]
etxt = ftxt[:ftxt.find('【3.盈利预测明细】')]
dd = etxt.splitlines(keepends=False)

In [79]:
dd

['【2.盈利预测统计】(近6个月)',
 '',
 ' 财务指标                 2021年     2022年     2023年 2024年预测 2025年预测 2026年预测 ',
 '',
 ' 每股收益(元)               1.94       1.94       1.02      -0.76       0.07       0.29 ',
 ' 每股净资产(元)            20.30      21.00      21.15      20.26      20.06      20.11 ',
 ' 净资产收益率%              9.55       9.32       4.85      -3.82       0.26       1.25 ',
 ' 归母净利润(百万元)     22524.03   22617.78   12162.68   -9061.07     821.13    3329.41 ',
 ' 营业收入(百万元)      452797.77  503838.37  465739.08  357712.61  337893.21  323265.38 ',
 ' 营业利润(百万元)       52531.00   52006.94   29251.70  -13218.61    3169.93    7383.50 ',
 '',
 '']

In [81]:
Data = pd.DataFrame(columns=())
i = 0
while i < len(dd):
    lis = dd[i].split()
    if len(lis)!=7:
        i = i+1
        # pass
    else:
        df = pd.DataFrame(lis).T
        # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
        Data = pd.concat([Data, df],axis=0)
        i=i+1
Data.reset_index(drop=True,inplace=True)
Data = Data.replace('---',pd.NA)

In [82]:
Data.loc[0]

0       财务指标
1      2021年
2      2022年
3      2023年
4    2024年预测
5    2025年预测
6    2026年预测
Name: 0, dtype: object

In [83]:
Data.columns=list(Data.loc[0])

In [84]:
Data

,财务指标,2021年,2022年,2023年,2024年预测,2025年预测,2026年预测
0,财务指标,2021年,2022年,2023年,2024年预测,2025年预测,2026年预测
1,每股收益(元),1.94,1.94,1.02,-0.76,0.07,0.29
2,每股净资产(元),20.30,21.00,21.15,20.26,20.06,20.11
3,净资产收益率%,9.55,9.32,4.85,-3.82,0.26,1.25
4,归母净利润(百万元),22524.03,22617.78,12162.68,-9061.07,821.13,3329.41
5,营业收入(百万元),452797.77,503838.37,465739.08,357712.61,337893.21,323265.38
6,营业利润(百万元),52531.00,52006.94,29251.70,-13218.61,3169.93,7383.50

In [85]:
Data['StockCode'] = StockCode
Data['StockName'] = StockName

In [86]:
Data

,财务指标,2021年,2022年,2023年,2024年预测,2025年预测,2026年预测,StockCode,StockName
0,财务指标,2021年,2022年,2023年,2024年预测,2025年预测,2026年预测,000002,万科A
1,每股收益(元),1.94,1.94,1.02,-0.76,0.07,0.29,000002,万科A
2,每股净资产(元),20.30,21.00,21.15,20.26,20.06,20.11,000002,万科A
3,净资产收益率%,9.55,9.32,4.85,-3.82,0.26,1.25,000002,万科A
4,归母净利润(百万元),22524.03,22617.78,12162.68,-9061.07,821.13,3329.41,000002,万科A
5,营业收入(百万元),452797.77,503838.37,465739.08,357712.61,337893.21,323265.38,000002,万科A
6,营业利润(百万元),52531.00,52006.94,29251.70,-13218.61,3169.93,7383.50,000002,万科A

In [87]:
def getFcast(StockCode, StockName):
    qf10='价值分析'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)[116:]

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)
    
    ftxt = txt[txt.find('【2.盈利预测统计】'):]
    etxt = ftxt[:ftxt.find('【3.盈利预测明细】')]
    dd = etxt.splitlines(keepends=False)

    Data = pd.DataFrame(columns=())
    i = 0
    while i < len(dd):
        lis = dd[i].split()
        if len(lis)!=7:
            pass
        else:
            df = pd.DataFrame(lis).T
            Data = pd.concat([Data, df],axis=0)
        i=i+1
    Data.reset_index(drop=True,inplace=True)
    Data = Data.replace('---',pd.NA)

    Data.columns=list(Data.loc[0])
    Data['StockCode'] = StockCode
    Data['StockName'] = StockName

    return(Data.tail(-1))

==== 数据库数据分析 StockBas
1、BizP  前5大商业合作营业占比
2、Fcast 3年预测
3、Top   题材相似度
4、mBiz  主营业务产品占比

In [89]:
import pandas as pd
from sqlalchemy import create_engine
import plotly.express as px

eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')

In [90]:
pd.read_sql('Fcast', eng)[['StockCode','StockName', '财务指标', '2021年', '2022年', '2023年', '2024年预测', '2025年预测','2026年预测' ]]

,StockCode,StockName,财务指标,2021年,2022年,2023年,2024年预测,2025年预测,2026年预测
0,000001,平安银行,每股收益(元),1.87,2.35,2.39,2.36,2.45,2.57
1,000001,平安银行,每股净资产(元),16.77,18.80,20.74,22.41,24.30,26.31
2,000001,平安银行,净资产收益率%,9.19,10.47,9.84,10.68,10.26,9.98
3,000001,平安银行,归母净利润(百万元),36336.00,45516.00,46455.00,47285.56,48889.63,51336.10
4,000001,平安银行,营业收入(百万元),169383.00,179895.00,164699.00,150409.10,151597.21,157626.83
...,...,...,...,...,...,...,...,...,...
16441,689009,九号公司-WD,每股净资产(元),6.04,6.87,7.57,8.84,10.56,12.85
16442,689009,九号公司-WD,净资产收益率%,9.61,9.20,10.96,15.45,17.91,19.64
16443,689009,九号公司-WD,归母净利润(百万元),410.60,450.55,597.99,979.15,1350.08,1787.86
16444,689009,九号公司-WD,营业收入(百万元),9146.05,10124.32,10222.08,14026.84,17991.33,22239.79
16445,689009,九号公司-WD,营业利润(百万元),510.75,565.44,563.87,1090.40,1506.61,2017.97

In [ ]:
['StockCode', '财务指标', '2021年', '2022年', '2023年', '2024年预测', '2025年预测','2026年预测', 'StockName']

In [ ]:
df

In [ ]:
df[['StockCode','StockName','日期','题材','相关度']].set_index('日期')

In [ ]:
df['题材'].str.contains('券商', na=False)

In [4]:
df = pd.read_sql('mBiz', eng)

In [5]:
df

In [ ]:
df['项目名']

In [130]:
ddf = df[df['项目名'].str.endswith('(行业)')][df[df['项目名'].str.endswith('(行业)')]['日期']=='2023-12-31'].reset_index(drop=True)

In [25]:
df[df['营业收入(元)'].str.endswith('(万)')]

In [6]:
dddf = df[df['项目名'].str.endswith('(产品)')][df[df['项目名'].str.endswith('(产品)')]['日期']=='2023-12-31'].reset_index(drop=True)

In [23]:
dddf[dddf['营业收入(元)'].str.endswith('万')]

In [28]:
dddf[dddf['营业收入(元)'].isnull()]

In [ ]:
dddf[dddf['StockCode'].isin(['000004','600168'])]

In [2]:
dddf[dddf['收入比例(%)'].astype(float)>20]

In [ ]:
ddf[ddf['StockCode']=='000002']

In [135]:
ddf['项目名'] = ddf['项目名'].str.replace('\(行业\)', '')

In [136]:
ddf

In [ ]:
df[df['StockCode']=='688653']['项目名'].str.contains('行业', na=False)

In [ ]:
df[df['题材'].str.contains('券商', na=False)].sort_values(by=['相关度','StockCode'], ascending=False).reset_index(drop=True)

In [7]:
gg  = df.groupby('题材')

In [ ]:
df[df["StockCode"]=='002161']

In [735]:
df

In [ ]:
gg.groups

In [10]:
gDF = gg.count().sort_values('StockCode')

In [ ]:
gDF

In [ ]:
gg.get_group('食品溯源')

In [ ]:
import json

from pyecharts import options as opts
from pyecharts.charts import Graph

with open("weibo.json", "r", encoding="utf-8") as f:
    j = json.load(f)
    nodes, links, categories, cont, mid, userl = j
c = (
    Graph()
    .add(
        "",
        nodes,
        links,
        categories,
        repulsion=50,
        linestyle_opts=opts.LineStyleOpts(curve=0.2),
        label_opts=opts.LabelOpts(is_show=False),
    )
    .set_global_opts(
        legend_opts=opts.LegendOpts(is_show=False),
        title_opts=opts.TitleOpts(title="Graph-微博转发关系图"),
    )
    .render("graph_weibo.html")
)

In [ ]:
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB


from pyecharts.charts import Bar
from pyecharts import options as opts
# 内置主题类型可查看 pyecharts.globals.ThemeType
from pyecharts.globals import ThemeType

bar = (
    Bar(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
    .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    .add_yaxis("商家B", [15, 6, 45, 20, 35, 66])
    .set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
)
bar.load_javascript()

In [ ]:
bar.render_notebook()

============== 3dplt替换

In [34]:
from sqlalchemy import create_engine

eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56:5432/tdxIndex')

In [36]:
df = pd.read_sql('000001', eng)
df['datetime'] = df['datetime'].astype('datetime64[ns]')

In [37]:
import plotly.express as px

In [ ]:
fig = px.scatter(df, x='datetime', y='close',size='amount',color='open')
# fig = px.scatter(df, x='datetime', y='close',size='amount',color='open',marginal_y='violin',trendline='ewm',trendline_options={'ignore_na': True,'span':5, 'min_periods':21})
# fig.update_xaxes(rangeslider_visible=True)
fig.show(config={'scrollZoom': True,'displaylogo':False})

In [ ]:
fig = px.line(df, x='datetime', y='close',line_shape='spline',title='text')
fig.update_xaxes(rangeslider_visible=True)
fig.show(config={'scrollZoom': True,'displaylogo':False})

======== 加权密度图

In [40]:
import numpy as np

In [72]:
def norm(df, column_name):
    min_val = df[column_name].min()
    max_val = df[column_name].max()
    normalized_column = (df[column_name] - min_val) / (max_val - min_val)
    scaled_column = normalized_column * (89 - 1) + 1
    discrete_scaled_column = scaled_column.round().astype(int)
    return discrete_scaled_column

In [73]:
n = [5,21,55]
n =5
weights = norm(df.tail(n),'amount')
weighted_data = np.repeat(df['close'].tail(n), repeats=weights)

In [74]:
weights

6030     5
6031     1
6032    60
6033    89
6034    68
Name: amount, dtype: int64

In [75]:
weighted_data

6030    3000.95
6030    3000.95
6030    3000.95
6030    3000.95
6030    3000.95
         ...
6034    3258.86
6034    3258.86
6034    3258.86
6034    3258.86
6034    3258.86
Name: close, Length: 223, dtype: float64

In [76]:
fig = px.violin(weighted_data,box=True)
fig.show()