==== 行业分析

In [22]:
from mootdx.quotes import Quotes
import pandas as pd
import plotly.express as px
import re
from sqlalchemy import create_engine

eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')

StockList = pd.read_sql('StocksList', eng)[['code','name']]
# import streamlit as st

qf10='行业分析'
anCode = '估值水平排名'
StockCode = '000002'

client = Quotes.factory(market='std')
txt = client.F10(StockCode, qf10)[116:]
txt = txt.replace('│',' ')                
txt = re.sub('([\u2500-\u25f7])','',txt)

In [23]:
StockList.columns=['股票编码','股票名称']
list(StockList[StockList['股票编码'] == StockCode]['股票名称'])[0]

'万科A'

In [24]:
titlCode = re.findall(r'所属研究行业\S+', txt)[0]

In [7]:

def getFind(anCode):
    match anCode:
        case "市场表现排名":
            lsCode = ['【2.市场表现排名】','【3.公司规模排名】',["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]]
            return(lsCode)
        case "公司规模排名":
            lsCode = ['【3.公司规模排名】','【4.估值水平排名】',["股票名称","A股总市值(亿)","A股流通市值(亿)","实际流通A股(亿)","总股本(亿)","股价(元)"]]
            return(lsCode)
        case "估值水平排名":
            lsCode = ['【4.估值水平排名】','【5.财务状况排名】',['股票名称','市盈率(TTM)','市盈率(LYR)','市净率(MRQ)','市销率(TTM)','市现率(TTM)']]
            return(lsCode)
        case "财务状况排名":
            lsCode = ['【5.财务状况排名】','EOF',["股票名称","每股收益(元)","每股净资产(元)","每股现金流(元)","销售净利率%","净利润增长率%"]]
            return(lsCode)

In [8]:
lsCode =  getFind(anCode)

fi = txt[txt.find(lsCode[0]):]
ff = fi[:fi.find(lsCode[1])]
dd = ff.replace('─','').splitlines(keepends=False)
Data = pd.DataFrame(columns=lsCode[2])
i = 3
while i < len(dd):
    lis = re.split(r"\s{3,}", dd[i])[-6:]
    if len(lis)!=6:
        i = i+1
        # pass
    else:
        df = pd.DataFrame(lis).T
        df.columns=lsCode[2]
        Data = pd.concat([Data, df],axis=0)
        i=i+1
Data.reset_index(drop=True,inplace=True)
Data = Data.replace('---',0)

In [ ]:
Data

In [ ]:
StockList['']

In [10]:
Data['股票名称'] = Data['股票名称'].str.strip().str.replace(r'\s+', '', regex=True).str.replace('Ａ','A')

In [ ]:
Data

In [ ]:
dd

In [12]:
def to_numeric_safe(value):
    try:
        return pd.to_numeric(value)
    except (ValueError, TypeError):
        return value

ddf  = Data.map(to_numeric_safe)

In [ ]:
StockList[StockList['股票名称'].isin(ddf['股票名称'])]

In [ ]:
dtt

In [ ]:
dtt['text'].str.strip().str.replace(r'\s+', '', regex=True)

In [ ]:
StockList

In [15]:
meddf = pd.merge(StockList,ddf,how='inner', on='股票名称')

In [17]:
dddf = pd.concat([meddf,ddf]).drop_duplicates(subset=['股票名称']).reset_index(drop=True)

In [ ]:
dddf

In [ ]:
dddf.columns[2:]

In [ ]:
fig = px.bar(dddf, y=dddf.columns[1], x=dddf.columns[2:], title=anCode,
             barmode='relative', hover_name=dddf.columns[1],text_auto='')
# fig.update_layout(dragmode='pan',legend_itemclick='toggleothers',)
fig.update_layout(dragmode='pan',)
# fig.show(config={'scrollZoom':True})

In [ ]:
fig.show(config={'scrollZoom':True})

In [6]:
stta = ddf.style.background_gradient(cmap='Blues')
stta = stta.format('{:,.2f}', subset=list(ddf.columns[1:]))

=== 经营分析

In [605]:
from mootdx.quotes import Quotes
import pandas as pd
import plotly.express as px
import re

StockCode = '600166'
qf10='经营分析'
client = Quotes.factory(market='std')
txtRaw = client.F10(StockCode, qf10)
txt = txtRaw[116:]

In [ ]:
txt

In [289]:
StockName = re.findall(r'\b'+StockCode+'\s+([^\s]*)',txtRaw)[0]

In [381]:
hc = re.findall(r'\d+.\d+|\d+%',re.findall(r'前5大客户[^\s]*',txt)[0])

In [391]:
pd.DataFrame(hc+hp).T

In [382]:
hp = re.findall(r'\d+\.\d+|\d+%',re.findall(r'前5大供应商[^\s]*',txt)[0])

In [392]:
csdf = pd.DataFrame(hc+hp).T
csdf.columns = ["营收额","营收占比",'采购额',"采购占比"]

In [394]:
csdf['StockCode'] = StockCode
csdf['StockName'] = StockName

In [395]:
csdf

In [607]:
fi = txt[txt.find('【2.主营构成分析】'):]
ff = fi[:fi.find('【3.前5名客户营业收入表】')]
datetimes=re.findall(r'截止日期:([^\s]*)', ff)

In [ ]:
ff

In [320]:
# re.findall(r'截止日期:([^\s]*)', ff)
# re.findall(r'截止日期:(\S{10})', ff)

In [609]:
dd = ff.replace('─','').splitlines(keepends=False)

In [ ]:
dd

In [437]:

# Data = pd.DataFrame(columns=("股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"))
Data = pd.DataFrame(columns=())
i = 0
while i < len(dd):
    lis = re.split(r"\s+", dd[i])[-6:]
    if len(lis)!=6:
        i = i+1
        # pass
    else:
        df = pd.DataFrame(lis).T
        # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
        Data = pd.concat([Data, df],axis=0)
        i=i+1
Data.reset_index(drop=True,inplace=True)
Data = Data.replace('---',pd.NA)
# ddf  = Data.apply(pd.to_numeric, errors='ignore')

In [439]:
ddf = Data

In [440]:
ddfindex = ddf[ddf[0]=='项目名'].index

In [441]:
ddfindex

In [442]:
i = 0
raDF = pd.DataFrame(columns=['日期',"项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"])

In [443]:
for i in [0,1,2]:
    dfd = ddf.loc[(ddfindex[i]+1):(ddfindex[i+1]-1)].reset_index(drop=True)
    dfd.columns = ["项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]
    dfd['日期'] = datetimes[i]
    raDF = pd.concat([raDF,dfd], axis=0)

In [444]:
raDF['StockCode'] = StockCode
raDF['StockName'] = StockName

In [446]:
raDF.set_index('日期')

In [346]:
dfd.set_index('日期')

In [331]:
dfd[dfd['项目名'].str.contains('行业', na=False)]

In [330]:
dfd[dfd['项目名'].str.contains('产品', na=False)]

In [329]:
dfd[dfd['项目名'].str.contains('产品', na=False)]['利润比例(%)'].astype(float).sum()

In [650]:
def getBiz(StockCode):
    qf10='经营分析'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)[116:]   
    # txt = txtRaw[116:]

    StockName = re.findall(r'\b'+StockCode+'\s+([^\s]*)',txtRaw)[0]
    try:
        hc = re.findall(r'\d+.\d+|\d+%',re.findall(r'前5大客户[^\s]*',txt)[0])
        hp = re.findall(r'\d+\.\d+|\d+%',re.findall(r'前5大供应商[^\s]*',txt)[0])
        csdf = pd.DataFrame(hc+hp).T
        csdf.columns = ["营收额","营收占比",'采购额',"采购占比"]
        csdf['StockCode'] = StockCode
        csdf['StockName'] = StockName


    except:
        pass

    fi = txt[txt.find('【2.主营构成分析】'):]
    ff = fi[:fi.find('【3.前5名客户营业收入表】')]
    datetimes=re.findall(r'截止日期:([^\s]*)', ff)
    dd = ff.replace('─','').splitlines(keepends=False)

    Data = pd.DataFrame(columns=())
    i = 0
    while i < len(dd):
        lis = re.split(r"\s+", dd[i])[-6:]
        if len(lis)!=6:
            i = i+1
            # pass
        else:
            df = pd.DataFrame(lis).T
            # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
            Data = pd.concat([Data, df],axis=0)
            i=i+1
    Data.reset_index(drop=True,inplace=True)
    Data = Data.replace('---',0)
    ddf  = Data.apply(pd.to_numeric, errors='ignore')

    ddfindex = ddf[ddf[0]=='项目名'].index
    raDF = pd.DataFrame(columns=['日期',"项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"])

    for i in [0,1,2]:
        dfd = ddf.loc[(ddfindex[i]+1):(ddfindex[i+1]-1)].reset_index(drop=True)
        dfd.columns = ["项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]
        dfd['日期'] = datetimes[i]
        raDF = pd.concat([raDF,dfd], axis=0)

    raDF['StockCode'] = StockCode
    raDF['StockName'] = StockName
    # raDF.set_index('日期').to_sql('Biz', eng, if_exists='append')
    return(raDF,csdf)

In [651]:
a,b = getBiz('000005')

In [ ]:
list(a['项目名'])[2]

In [26]:
from sqlalchemy import create_engine
engs = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')

In [27]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [28]:
StockList.iloc[0,0]

'000001'

In [44]:
pd.read_sql('StocksList', engs)[['code','name']].iloc[0,1]

'平安银行'

In [45]:
StockList.iloc[15,1]

'深科技'

================== 热点题材

In [2]:
StockCode = '688338'

In [110]:
from mootdx.quotes import Quotes
import pandas as pd
import plotly.express as px
import re


qf10='热点题材'
client = Quotes.factory(market='std')
txt = client.F10(StockCode, qf10)[116:]

In [111]:
txt = txt.replace('│',' ')
txt = re.sub('([\u2500-\u25f7])','',txt)

In [123]:
txt

'、智能医疗、医美概念、人脑工程、辅助生殖           \r\n风格:融资融券、回购计划、连续亏损、MSCI中盘                                         \r\n指数:无                                                                             \r\n\r\n【2.主题投资】\r\n\r\n  2023-10-27 人脑工程     关联度：☆☆☆                                          \r\n\r\n    公司旗下医疗机构已组织脑机接口领域的专项课题研究。                              \r\n\r\n\r\n  2022-06-07 医美概念     关联度：☆☆☆                                          \r\n\r\n    西安国际医学高新医院设有医学美容部，下设整形外科、激光美容科、注射美容科和抗衰老\r\n科。                                                                                \r\n\r\n\r\n  2022-01-07 辅助生殖     关联度：☆☆☆                                          \r\n\r\n    公司下属西安高新医院获陕西省卫健委批复，高新医院获准开展常规体外受精-胚胎移植及 \r\n卵胞浆内单精子显微注射技术（IVF/ICSI-ET），试运行期限一年。                         \r\n\r\n\r\n  2021-11-01 智能医疗     关联度：☆☆☆☆                                        \r\n\r\n    公司与东华软件、阿里云签署了《战略合作协议》，将在云计算、大数据、未来医院、智慧\r\n商业、移动支付等领域进行产品与技术、解决方案与服务、市场营销与拓展等全方位的研发与实\r\n施，以共同推进线上医疗领域、商业领域等云计算、大数据业务的发展。协议从生效日起有效期\r\n3年。                                                                               \r\n\r\n\r\n  2021-10-22 基因概念     关联度：☆☆                                            \r\n\r\n    公司与中国药物临床试验机构联盟签署《精准医学战略合作协议》。                    \r\n\r\n\r\n  2021-10-14 阿里概念     关联度：☆☆☆                                          \r\n\r\n    公司积极打造线上线下相结合的互联网医疗服务网络，由公司与阿里健康合作打造的国际医\r\n学互联网医院自2019年4月2日开通网络诊疗服务                                          \r\n\r\n\r\n  2021-10-12 民营医院     关联度：☆☆☆☆☆                                      \r\n\r\n    公司以大健康医疗服务和现代医学技术转化应用为主业                                \r\n\r\n\r\n  2022-11-16 高压氧舱     关联度：☆☆☆                                          \r\n\r\n    公司商洛国际医学中心医院是公司继西安高新医院、西安国际医学中心医院之后，按三级甲\r\n等医院标准重点建设的服务陕南地区患者的大型现代化区域性医疗中心。设有医学影像科、核医\r\n学科、放射治疗、高压氧舱等10个医技科室。                                            \r\n\r\n\r\n  2022-01-05 毛发医疗     关联度：☆☆☆                                          \r\n\r\n    公司旗下西安国际医学中心整形医院下设植发中心                                    \r\n\r\n\r\n  2021-11-02 健康中国     关联度：☆☆☆                                          \r\n\r\n    和阿里云、东华软件签署战略合作协议共同打造中国第一家实体的“未来医院”--西安国际\r\n医学中心，这也是国内第一家以数据驱动精准医疗、健康管理的实体医疗机构。              \r\n\r\n\r\n  2021-10-22 基因测序     关联度：☆☆                                            \r\n\r\n    公司与中国药物临床试验机构联盟签署《精准医学战略合作协议》。                    \r\n\r\n\r\n  2021-09-26 罗素中盘     关联度：☆☆☆                                          \r\n\r\n    公司符合罗素中盘股标准                                                          \r\n\r\n\r\n  2021-09-17 兜底式增持   关联度：☆☆☆☆☆                                      \r\n\r\n    国际医学(000516.SZ)公布，公司收到实际控制人刘建申提交的《关于向公司全体员工发出 \r\n增持公司股票的倡议书》，具体内容如下：鉴于西安国际医学投资股份有限公司良好的发展局面\r\n，以及刘建申本人对公司管理团队与公司未来持续发展的信心，刘建申倡议：公司和公司的全资\r\n子公司及控股子公司的全体员工积极买入国际医学股票(股票简称：国际医学；股票代码：00051\r\n6)。刘建申承诺，按照本倡议的相关操作细则，凡2021年9月17日至10月11日期间通过员工本人 \r\n证券账户以二级市场竞价交易方式净买入国际医学的股票，且连续持有12个月以上并在职的员工\r\n，若因在前述时间期间内增持国际医学股票产生的亏损，刘建申或其指定的下属公司将以自有资\r\n金予以补偿；若有股票增值收益则归员工个人所有。                                      \r\n\r\n\r\n  2020-12-03 陕西自贸区   关联度：☆☆☆                                          \r\n\r\n    公司位于陕西省西安市碑林区，以大健康医疗服务和现代医学技术转化应用为主业。      \r\n\r\n\r\n  2019-12-31 干细胞       关联度：☆☆                                            \r\n\r\n    2019年03月11日在互动平台表示，公司参股的北京汉氏联合生物技术股份有限公司研发的干\r\n细胞1类新药人胎盘间充质干细胞凝胶，适应症为慢性创面（糖尿病溃疡等）。               \r\n\r\n\r\n         --- 不可减持(新  关联度：☆☆☆☆                                        \r\n             规)                                                                  \r\n\r\n    公司近三年未分红，依照减持新规，控股股东和实际控制人不可减持。                  \r\n\r\n\r\n  2024-11-01 回购计划     关联度：☆☆☆                                          \r\n\r\n    公司拟回购不超过15000万元(1637.55万股),回购期:2024-05-20至2025-05-19            \r\n\r\n\r\n  2024-10-24 连续亏损     关联度：☆☆☆☆                                        \r\n\r\n    截止2023-12-31公司连续两年归母净利润为负且2024-09-30财报归母净利润均为负        \r\n\r\n\r\n  2023-02-10 MSCI中盘     关联度：☆☆☆                                          \r\n\r\n    公司符合MSCI中盘股标准                                                          \r\n\r\n【3.事件驱动】\r\n\r\n  2024-10-29 国办：强化生育服务支持，建立生育补贴制度                              \r\n\r\n    国务院办公厅日前印发《关于加快完善生育支持政策体系推动建设生育友好型社会的若干措\r\n施》，措施提到，强化生育服务支持。增强生育保险保障功能，指导有条件的地方将参加职工基\r\n本医疗保险的灵活就业人员、农民工、新就业形态人员纳入生育保险。完善生育休假制度，保障\r\n法律法规规定的产假、生育奖励假、陪产假、育儿假等生育假期落实到位。建立生育补贴制度，\r\n指导地方做好政策衔接，积极稳妥抓好落实。加强生殖健康服务，指导各地将适宜的分娩镇痛以\r\n及辅助生殖技术项目纳入医保报销范围。                                                \r\n\r\n\r\n  2023-10-27 工信部推进医疗装备与人工智能、物联网等融合发展                        \r\n\r\n    工信部消费品工业司司长在2023中国医药工业发展大会新闻发布会上表示，深化转型升级，\r\n持续推动医药工业提质增效。以高端化、智能化、绿色化为引领，提升关键技术与装备生产制造\r\n水平，扩大高端产品和优质产品供给，推动产业数字化转型，促进全产业链绿色低碳发展。推进\r\n医疗装备与5G、人工智能、大数据、物联网等融合发展，培育远程医疗、智慧医疗、移动医疗等\r\n新模式新业态。完善医药工业绿色生产标准体系和评价机制，推广应用合成生物学等先进技术。\r\n\r\n\r\n  2023-08-07 量子计算机首次识别出单个核苷酸，智能医疗产业有望加速发展              \r\n\r\n    日本科学家使用量子计算机，将单磷酸腺苷核苷酸与其他3种核苷酸分子区分开来，这是量 \r\n子计算机首次应用于单分子测量，证明了其在基因组分析中大有潜力。最新研究有望使超快速基\r\n因组分析在药物发现、癌症诊断和传染病研究等领域大显身手。相关论文刊发于最新一期《物理\r\n化学杂志B》杂志。                                                                   \r\n\r\n\r\n  2023-05-17 华为手表将支持高血糖风险评估，或将推动智能医疗行业加速发展            \r\n\r\n    华为将在血糖健康领域迈出第一步。华为手表将率先支持高血糖风险评估研究，首次将在5 \r\n月18日即将发布的华为WATCH4系列上线。                                                \r\n\r\n\r\n  2023-05-10 辅助生殖新一代技术发布，大幅提升试管婴儿活产率                        \r\n\r\n    中国科学院北京基因组研究所（国家生物信息中心）联合中国多家医院和高校，在辅助生殖\r\n领域“十年磨一剑”，研发新一代试管婴儿技术——使用表观遗传信息即DNA甲基化指标来优选 \r\n胚胎的方法（PIMS），甲基化水平优良的胚胎的临床检验活产率达到72%，远高于当前全球辅助 \r\n生殖活产率不足30%的指标。                                                           \r\n\r\n\r\n  2023-03-24 中办、国办提出发展互联网+医疗健康，AI+医疗发展前景广阔                \r\n\r\n    中共中央办公厅、国务院办公厅印发《关于进一步完善医疗卫生服务体系的意见》。意见提\r\n出，发展“互联网+医疗健康”，建设面向医疗领域的工业互联网平台，加快推进互联网、区块 \r\n链、物联网、人工智能、云计算、大数据等在医疗卫生领域中的应用，加强健康医疗大数据共享\r\n交换与保障体系建设。建立跨部门、跨机构公共卫生数据共享调度机制和智慧化预警多点触发机\r\n制。推进医疗联合体内信息系统统一运营和互联互通，加强数字化管理。加快健康医疗数据安全\r\n体系建设，强化数据安全监测和预警，提高医疗卫生机构数据安全防护能力，加强对重要信息的\r\n保护。                                                                              \r\n\r\n\r\n  2023-02-24 我国将完善乡村医疗卫生体系，推进互联网+医疗健康                       \r\n\r\n    近日，中共中央办公厅、国务院办公厅印发《关于进一步深化改革促进乡村医疗卫生体系健\r\n康发展的意见》，目标到2025年，乡村医疗卫生机构基础设施条件明显改善，智能化、数字化应\r\n用逐步普及，中医药特色优势进一步发挥，乡村重大疫情和突发公共卫生事件应对处置能力不断\r\n增强。将在有条件的乡镇中心卫生院建立标准化的发热门诊，配备负压救护车。大力推进“互联\r\n网+医疗健康”，构建乡村远程医疗服务体系。                                           \r\n\r\n\r\n  2023-02-06 辅助生殖将逐步纳入医保，多地出台相关政策                              \r\n\r\n    2月5日，央视新闻消息称，针对建议将不孕不育治疗纳入免费医疗的提案，国家医保局近日\r\n答复，将逐步把适宜的分娩镇痛和辅助生殖技术项目纳入基金支付范围，并鼓励中医医院开设优\r\n生优育门诊，提供不孕不育诊疗服务。券商推算，2018-2023年的辅助生殖市场年复合率为9.64%\r\n，至2023年，试管婴儿市场规模有望增加到400亿元，长期有望突破千亿。                   \r\n\r\n\r\n  2023-01-11 多地出台生育补贴新政，母婴行业御风而上                                \r\n\r\n    近日，深圳市卫生健康委公开征求《深圳市育儿补贴管理办法》意见，初步拟定深圳市育儿\r\n补贴标准，生育第三孩累计补贴1.9万元。此前，济南拟按照生育政策于1月1日以后出生的二孩 \r\n、三孩家庭，每孩每月发放600元育儿补贴。除了济南外，还有黑河、衡水、长沙等都相继推出 \r\n相应的生育补贴政策。机构指出，在政策和市场需求的双轮驱动下，母婴行业御风而上，其中辅\r\n助生殖行业的渗透率和市场规模有望得到加速提升。                                      \r\n\r\n\r\n  2022-11-28 辅助生殖技术纳入医保报销政策落地                                      \r\n\r\n    继今年8月，国家卫健委等十七部门发布进一步完善和落实积极生育支持措施的指导意见后 \r\n，辅助生殖技术纳入医疗保险报销政策终于落地。明年起，参加杭州市商业补充医疗保险“西湖\r\n益联保”的居民，在2023年度实施辅助生育的参保市民，将可获得最高3000元的报销。        \r\n\r\n\r\n  2021-10-14 我国将积极应对老龄化                                                  \r\n\r\n    据报道，我国将贯彻落实积极应对人口老龄化国家战略，加大制度创新、政策供给、财政投\r\n入力度，健全完善老龄工作体系，强化基层力量配备，加快健全社会保障体系、养老服务体系、\r\n健康支撑体系。                                                                      \r\n根据第七次人口普查数据，65岁以上老龄人口占比已达13.5%，该比例未来可能继续提升。不久 \r\n前发布的《深化医药卫生体制改革2021年重点工作任务》也提出十四五期间积极支持社会办医发\r\n展。                                                                                \r\n\r\n\r\n  2020-02-07 互联网医疗：助力对抗疫情，行业快速发展                                \r\n\r\n    在当前特殊的疫情阶段，互联网医疗的重要性日益凸显，线上医疗平台迎来访问峰值。阿里\r\n健康数据显示，截至1月30日，在线义诊累计访问用户数超280万，医生数量超1000名，参加线上\r\n义诊的在线医生人均日接诊量超100单。                                                 \r\n远程诊疗在此次抗击肺炎中发挥了重要作用，在武汉火神山和雷神山医院已经建设了5G通信网络\r\n，即可用作远程诊疗。四川、广东、重庆等多省市均已开始通过远程专家会诊方式治疗肺炎患者\r\n。机构认为，疫情过后，互联网医疗渗透率还将有所提升。                                \r\n\r\n\r\n  2019-10-08 今年诺贝尔生理医学奖公布 花落细胞感知氧气领域                         \r\n\r\n    北京时间10月7日17：30， 2019年诺贝尔生理学或医学奖公布：威廉?凯林(William G. Kae\r\nlin Jr)彼得?拉特克利夫(Sir Peter J. Ratcliffe) 以及格雷格?塞门扎(Gregg L. Semenza)获\r\n得这一奖项，以表彰他们发现细胞如何感知和适应氧可用性。分析人士指出，今年的诺贝尔奖获\r\n得者的开创性发现揭示了生命中最重要的适应过程的机制，为我们理解氧水平如何影响细胞代谢\r\n和生理功能奠定了基础。他们的发现也为抗击贫血、癌症和许多其他疾病的新策略铺平了道路。\r\n\r\n\r\n  2019-05-23 国务院部署推动社会办医 民营医院受关注                                 \r\n\r\n    国务院总理李克强2019年5月22日主持召开国务院常务会议，部署进一步推动社会办医持续 \r\n健康规范发展，增加医疗服务供给、促进民生改善。我国医疗消费市场是个快速扩张具有巨大潜\r\n力的市场，随着新医改的深化和市场医疗服务资源配置机制逐步建立，民营医院市场份额还将继\r\n续提升。目前民营医院占据半壁江山，但是，民营医院诊疗人次数依然很低。随着政策不断完善\r\n，民营医院潜在增长空间巨大，相关公司有望受益。                                      \r\n\r\n\r\n  2019-04-10 阿里云支付宝联手研发 区块链医疗解决方案落地应用                       \r\n\r\n    2019年4月8日，首届世界大健康博览会举行期间，阿里云宣布其联合支付宝共同研发的区块\r\n链医疗解决方案已经正式应用于武汉中心医院的电子处方，武汉市中心医院也成为首家应用该技\r\n术方案的“未来医院”。在智慧医疗广阔前景的吸引下，以BAT为首的互联网企业纷纷对医疗行 \r\n业展开布局，医疗信息化已接近爆炸式增长的临界点。相关公司包括：卫宁健康、万东医疗、国\r\n际医学等。                                                                          \r\n\r\n\r\n  2018-10-23 央行精准滴灌民营经济 引导设立民企债券融资支持工具                     \r\n\r\n    2018年10月23日消息，支持民营企业债券融资，人民银行昨日又出新招。人民银行官网22日\r\n晚间发布消息，引导设立民营企业债券融资支持工具，稳定和促进民营企业债券融资。同时宣布\r\n新添再贷款和再贴现额度1500亿元，支持小微、民营企业融资。                            \r\n    同时，人民银行积极支持商业银行、保险公司以及债券信用增进公司等机构，在加强风险识\r\n别和风险控制的基础上，运用信用风险缓释工具等多种手段，支持民营企业债券融资。充分发挥\r\n地方政府在改善营商环境、督导民营企业规范经营中的作用。                              \r\n    不仅有“新招”，货币政策工具也持续发力。人民银行昨日还公布，为改善小微企业和民营\r\n企业融资环境，人民银行今年6月增加了再贷款和再贴现额度1500亿元，现决定在此基础上，再 \r\n增加再贷款和再贴现额度1500亿元，发挥其定向调控、精准滴灌功能，支持金融机构扩大对小微\r\n、民营企业的信贷投放。                                                              \r\n    对于资本充足率达标、符合宏观审慎要求、监管合规的金融机构，若小微和民营企业贷款占\r\n比高、存贷比指标较高、借用再贷款后能够增加信贷投放的，可向当地人民银行分支行申请再贷\r\n款和再贴现。人民银行分支行要加大政策支持力度，符合条件的及时发放。                  \r\n\r\n\r\n  2018-09-25 阿里健康与阿里云医疗AI整合 共建ET医疗大脑2.0                          \r\n\r\n    2018年9月24日据中证资讯报道，阿里健康董事会主席吴泳铭与阿里云总裁胡晓明9月21日联\r\n合宣布共建阿里医疗人工智能系统——ET医疗大脑，并将其升级为2.0版本。这意味着，经过内 \r\n部整合，阿里健康将与阿里云全面协同，深耕医疗AI业务。相关概念股主要有迪安诊断(300244)\r\n、万东医疗(600055)等。                                                              \r\n\r\n\r\n  2018-07-20 制成“全自动干细胞诱导培养设备” 干细胞装备领域现突破                 \r\n\r\n    2018年7月20日报道，干细胞研究与应用技术是目前全球生命科技领域最顶尖的技术之一， \r\n也是我国在全球处于“并跑”地位的领域之一。国家重大科研装备研制项目“全自动干细胞诱导\r\n培养设备”近日由中科院研制成功。该装备将实现规模化、自动化、智能化诱导干细胞制备，对\r\n世界再生医学及其相关的细胞治疗领域产生重大影响。                                    \r\n\r\n\r\n  2017-12-29 中国启动十万人基因组计划                                              \r\n\r\n    2017年12月28日，我国启动“中国十万人基因组计划”，这是我国在人类基因组研究领域实\r\n施的首个重大国家计划，也是目前世界最大规模的人类基因组计划。                        \r\n\r\n\r\n  2017-11-23 国内首个干细胞通用标准发布                                            \r\n\r\n    2017年11月22日，国内首个干细胞通用标准《干细胞通用要求》由中国细胞生物学会干细胞\r\n生物学分会发布。《通用要求》围绕干细胞制剂的安全性、有效性及稳定性等关键问题，明确了\r\n干细胞的供者筛查，组织采集，细胞分离、培养、冻存及检测等方面的通用要求。干细胞生物学\r\n分会会长周琪院士表示，该文件的出台将推动干细胞行业的规范化和标准化发展，对促进干细胞\r\n转化研究等方面有重要作用。                                                          \r\n\r\n\r\n  2017-11-09 支付宝推“信用就医”                                                  \r\n\r\n    2017年11月7日，在蚂蚁金服未来医院峰会上，支付宝联合芝麻信用、花呗与上海联空网络 \r\n科技有限公司共同发布了创新医疗产品“信用就医”，上海复旦大学附属华山医院成为全国首家\r\n应用“信用就医”服务的医院。                                                        \r\n\r\n\r\n  2017-10-16 阿里拟打造示范型“智慧医院”                                          \r\n\r\n    在2017年10月13日杭州举行的云栖大会智慧医疗专场，由阿里健康牵头，阿里巴巴正式与上\r\n海交通大学医学院附属新华医院（简称上海新华医院）签订战略合作协议，共同探索“智慧医院\r\n”新样板。                                                                          \r\n    合作协议显示，阿里巴巴和新华医院将致力于搭建医院混合云平台、云儿科医联体平台，开\r\n发医生智能培训系统、医学科研数据平台，实现院内就诊全流程移动支付等，从而打造出一个示\r\n范型的“智慧医院”。                                                                \r\n\r\n\r\n  2017-09-28 超级干细胞临床试验望明后年展开                                        \r\n\r\n    2017年9月28日消息，造血干细胞可用于白血病的治疗，主要缺点是供体来源有限，以及因 \r\n免疫配型问题移植后的排斥和感染。如果身边有一种干细胞，只需几毫升左右的血样本即可制得\r\n无限数量，而且还能解决临床中的免疫排斥问题。                                        \r\n    在安徽合肥，乐金健康参股的中盛溯源生物科技有限公司就在淬炼这项了不起的技术，这种\r\n被称为iPSC的人类诱导多功能干细胞已经诞生。其发明者之一美国宾夕法尼亚大学博士俞君英日\r\n前接受了上证报记者专访。据她预计，临床试验有望明后年展开。                          \r\n\r\n\r\n  2017-05-24 国务院鼓励社会办医                                                    \r\n\r\n    2017年5月23日，国务院办公厅印发《关于支持社会力量提供多层次多样化医疗服务的意见 \r\n》。《意见》提出，要进一步激发医疗领域社会投资活力，调动社会办医积极性，支持社会力量\r\n提供多层次多样化医疗服务，力争到2020年，打造一大批有较强服务竞争力的社会办医疗机构，\r\n服务供给基本满足国内需求，逐步形成多层次多样化医疗服务新格局。                      \r\n\r\n\r\n  2016-11-15 扎克伯格投资启动“细胞地图”项目                                      \r\n\r\n    2016年11月15日消息，克伯格夫妇不久前宣布，10年内捐资30亿美元帮助科研人员攻克各种\r\n难以治愈的疾病。这一举措使他们成为继霍华德·休斯医学研究所之后第二大私人基础生物学研\r\n究投资方。据麻省理工学院《技术评论》杂志网站近日报道，这一宏伟医学目标启动了首个项目\r\n：出资6亿美元，创建一家全新的“生物中心（BioHub）”，帮助绘制人类“细胞地图”。     \r\n    相关概念股：香雪制药、千山药机、达安基因、国际医学、北陆药业等。                \r\n\r\n\r\n  2016-09-20 十三五干细胞及转化研究项目启动                                        \r\n\r\n    2016年9月19日，青岛国际（生物谷）健康产业先行试验区授牌仪式暨“十三五”国家重点 \r\n研发计划“干细胞及转化研究”重点专项项目启动会召开。                                \r\n    据人民日报9月20日报道，该试验区是国内第一个以干细胞再生医学为龙头、具有自我知识 \r\n产权的生物产业发展集群示范区。授牌的试验区将在免疫性疾病新策略研究的基础上，发挥承接\r\n国家各类科研计划项目成果转化落地和产业化的引导试点作用。                            \r\n    川财证券认为，干细胞产业将有序前行，重心正向中下游转移。目前我国干细胞产业主要集\r\n中在产业链上游，此部分的增长已趋于平缓，而中下游的市场空间更大，在政策的不断成熟和推\r\n动下，有实力的研究机构干细胞项目开始被合法化的推进，意味着未来2-5年内将陆续有研究机 \r\n构输出成果并进行产业化，同时干细胞制剂也将加速进入主流的制药行业，优质的企业在规范化\r\n环境中将获得更大发展。建议关注在干细胞存储业务基础上拥有中下游技术储备的公司，包括中\r\n源协和、国际医学、南华生物、南京新百、冠昊生物、新日恒力等。                        \r\n\r\n\r\n  2016-07-07 新一轮医疗服务价格改革全面启动                                        \r\n\r\n    发改委网站2016年7月6日消息，近日，经国务院同意，国家发展改革委会同国家卫生计生委\r\n、人力资源社会保障部、财政部发出《关于印发推进医疗服务价格改革意见的通知》，全面推进\r\n医疗服务价格改革，提出到2020年基本理顺医疗服务比价关系。                            \r\n    《通知》要求，各地要围绕公立医院综合改革，统筹考虑取消药品加成及当地政府补偿政策\r\n，按照总量控制、结构调整的原则，同步调整医疗服务价格，重点降低大型医用设备检查治疗和\r\n检验等价格，提高诊疗、手术、康复、护理、中医等体现医务人员技术劳务价值的医疗服务价格\r\n；在此基础上，通过规范诊疗行为，降低药品、耗材等费用腾出空间，动态调整医疗服务价格。\r\n要改革医疗服务项目管理和定价方式，国家负责制定医疗服务项目技术规范，指导医疗机构规范\r\n开展服务，地方确定医疗服务收费的具体项目，逐步减少按项目收费数量，扩大按病种、按服务\r\n单元收费范围。要加强医疗服务价格监管和医药费用控制，严肃查处医疗机构违规收费行为，确\r\n保区域内医疗费用不合理增长得到有效控制。                                            \r\n    中泰证券认为，医疗服务价格改革的推进是降低药占比、回归医疗价值体现的必经之路，是\r\n医改进程中的关键一环，公立医院的医疗价格体系亟需逐步理顺，以服务占优、机制灵活的民营\r\n机构有望获得更快发展。                                                              \r\n\r\n\r\n  2016-07-04 生物医药十三五规划下半年出台                                          \r\n\r\n    据经济参考报2016年7月4日消息，生物医药“十三五”规划已基本制定完成，按照相关工作\r\n流程，这一规划将在今年下半年正式出台。根据规划，“十三五”期间我国生物医药产业将重点\r\n发展重大疾病化学药物、生物技术药物、新疫苗、新型细胞治疗制剂等多个创新药物品类，同时\r\n发展生物3D打印技术等重大医疗技术。                                                  \r\n    根据规划，抗肿瘤、抗抑郁、糖尿病、肾病、心脑血管病等药物将是“十三五”期间重点发\r\n展的新药品类；在临床中有巨大应用前景的蛋白及多肽药物、新型细胞制剂等生物医药制剂也将\r\n得到优先发展；此外，生物3D打印、大分子药物、干细胞、基因等前沿性生物医药技术，在未来\r\n五年也将得到长足发展。                                                              \r\n    此外规划还提出，加快专利到期药物仿制上市。针对防治重大疾病或突发疫情等用药需求，\r\n仿创结合、系统集成，研制20到30个临床需求巨大的药物品类，并切实解决产业化问题，满足临\r\n床用药的急迫需求，到2020年国际专利到期的重要药物90%以上实现仿制生产。               \r\n    太平洋证券认为，在生物技术领域，未来干细胞研究和基因测序是最热门的两大细分行业。\r\n相关公司值得重点布局。                                                              \r\n\r\n\r\n  2016-05-03 CAR-T引领癌症新革命                                                   \r\n\r\n    2016年5月3日消息，据媒体报道，日前，从美国著名癌症研究中心Fred Hutchinson CAncer\r\n Research Center（弗雷德·哈金森癌症研究中心）传出捷报。由他们领导的CAR-T治疗急性淋 \r\n巴细胞白血病（ALL）临床I/II期实验取得骄人成绩。29名晚期ALL患者中27名病情完全缓解，缓\r\n解率高达93%。他们的临床试验结果刊登在著名临床研究杂志JCI上。                        \r\n    CAR-T是一种全新的生物免疫治疗方法。这种新的细胞免疫治疗模式通过提取患者体内T淋巴\r\n细胞，经过体外10至14天的培养改造，通过载体整合进入到正常T细胞基因序列，形成嵌合抗原 \r\n受体T细胞（CAR-T）。被重新编码的T细胞就能获得特异性识别和攻击杀伤肿瘤细胞的能力，犹 \r\n如“细胞导弹”，能精确“点射”肿瘤细胞，但又不会伤及正常细胞。由于是诱导、激'

In [46]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [48]:
n = 100

In [49]:
StockCode = StockList.iloc[n,0]
StockName = StockList.iloc[n,1]

In [ ]:
ftxt = re.findall(r'│(.*)│(关联度:.*☆{4,})',txt)

In [122]:
re.findall(r'│(.*)│(关联度.*☆{4,})',txt)

[]

In [144]:
txtt = re.findall(r'(\S+)\s+(\S+)\s+(关联度.☆{4,})',txt)

In [145]:
txtt

[('2021-11-01', '智能医疗', '关联度：☆☆☆☆'),
 ('2021-10-12', '民营医院', '关联度：☆☆☆☆☆'),
 ('2021-09-17', '兜底式增持', '关联度：☆☆☆☆☆'),
 ('---', '不可减持(新', '关联度：☆☆☆☆'),
 ('2024-10-24', '连续亏损', '关联度：☆☆☆☆')]

In [141]:
re.findall(r'(\S+)\s+(\S+)\s+(关联度.☆{4,})',txt)

[('2021-11-01', '智能医疗', '关联度：☆☆☆☆'),
 ('2021-10-12', '民营医院', '关联度：☆☆☆☆☆'),
 ('2021-09-17', '兜底式增持', '关联度：☆☆☆☆☆'),
 ('---', '不可减持(新', '关联度：☆☆☆☆'),
 ('2024-10-24', '连续亏损', '关联度：☆☆☆☆')]

In [146]:
txDF = pd.DataFrame(txtt)

In [67]:
ftdf = pd.DataFrame(ftxt)

In [70]:
ftdf

        0          1
0    智能医疗   关联度：☆☆☆☆
1    民营医院  关联度：☆☆☆☆☆
2   兜底式增持  关联度：☆☆☆☆☆
3  不可减持(新   关联度：☆☆☆☆
4    连续亏损   关联度：☆☆☆☆

In [69]:
ftdf = ftdf.map(lambda x: x.rstrip() if isinstance(x, str) else x)

In [72]:
ftdf[1]=ftdf[1].str.len()-4

In [61]:
ftdf.columns=['题材','相关度']

In [62]:
ftdf['StockCode']=StockCode
ftdf['StockName']=StockName

In [152]:
def getTop(StockCode, StockName):
    qf10='热点题材'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)[116:]

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)
    txt = re.findall(r'(\S+)\s+(\S+)\s+(关联度.☆{4,})',txt)
    # txt = re.findall(r'│(.*)│(关联度.*☆{4,})',txtRaw)
    txDF = pd.DataFrame(txt)
    # txDF = txDF.map(lambda x: x.rstrip() if isinstance(x, str) else x)
    txDF[2]=txDF[2].str.len()-4
    txDF.columns=['日期','题材','相关度']
    txDF['StockCode'] = StockCode
    txDF['StockName'] = StockName
    # txDF.set_index('StockCode').to_sql('Top', eng, if_exist='append')
    return(txDF)

In [153]:
getTop(StockCode,StockName)

           日期      题材  相关度 StockCode StockName
0  2021-11-01    智能医疗    4    000516      国际医学
1  2021-10-12    民营医院    5    000516      国际医学
2  2021-09-17   兜底式增持    5    000516      国际医学
3         ---  不可减持(新    4    000516      国际医学
4  2024-10-24    连续亏损    4    000516      国际医学

======================= 价值分析

In [660]:
from mootdx.quotes import Quotes
import pandas as pd
import re
from sqlalchemy import create_engine

eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/StockBas')
engs = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/tdxStocks')

StockList = pd.read_sql('StocksList', engs)[['code','name']]
n = 1

StockCode = StockList.iloc[n,0]
StockName = StockList.iloc[n,1]


qf10='价值分析'
client = Quotes.factory(market='std')
txtRaw = client.F10(StockCode, qf10)[116:]
txt = txtRaw.replace('│',' ')                
txt = re.sub('([\u2500-\u25f7])','',txt)

In [673]:
ftxt = txt[txt.find('【2.盈利预测统计】'):]
etxt = ftxt[:ftxt.find('【3.盈利预测明细】')]
dd = etxt.splitlines(keepends=False)

In [ ]:
dd

In [675]:
Data = pd.DataFrame(columns=())
i = 0
while i < len(dd):
    lis = dd[i].split()
    if len(lis)!=7:
        i = i+1
        # pass
    else:
        df = pd.DataFrame(lis).T
        # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
        Data = pd.concat([Data, df],axis=0)
        i=i+1
Data.reset_index(drop=True,inplace=True)
Data = Data.replace('---',pd.NA)

In [ ]:
Data.loc[0]

In [677]:
Data.columns=list(Data.loc[0])

In [ ]:
Data

In [679]:
Data['StockCode'] = StockCode
Data['StockName'] = StockName

In [ ]:
Data

In [692]:
def getFcast(StockCode, StockName):
    qf10='价值分析'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)[116:]

    txt = txtRaw.replace('│',' ')                
    txt = re.sub('([\u2500-\u25f7])','',txt)
    
    ftxt = txt[txt.find('【2.盈利预测统计】'):]
    etxt = ftxt[:ftxt.find('【3.盈利预测明细】')]
    dd = etxt.splitlines(keepends=False)

    Data = pd.DataFrame(columns=())
    i = 0
    while i < len(dd):
        lis = dd[i].split()
        if len(lis)!=7:
            pass
        else:
            df = pd.DataFrame(lis).T
            Data = pd.concat([Data, df],axis=0)
        i=i+1
    Data.reset_index(drop=True,inplace=True)
    Data = Data.replace('---',pd.NA)

    Data.columns=list(Data.loc[0])
    Data['StockCode'] = StockCode
    Data['StockName'] = StockName

    return(Data.tail(-1))

==== 数据库数据分析 StockBas
1、BizP  前5大商业合作营业占比
2、Fcast 3年预测
3、Top   题材相似度
4、mBiz  主营业务产品占比

In [1]:
import pandas as pd
from sqlalchemy import create_engine
import plotly.express as px

eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56/StockBas')

In [ ]:
pd.read_sql('Fcast', eng)[['StockCode','StockName', '财务指标', '2021年', '2022年', '2023年', '2024年预测', '2025年预测','2026年预测' ]]

In [ ]:
['StockCode', '财务指标', '2021年', '2022年', '2023年', '2024年预测', '2025年预测','2026年预测', 'StockName']

In [ ]:
df

In [ ]:
df[['StockCode','StockName','日期','题材','相关度']].set_index('日期')

In [ ]:
df['题材'].str.contains('券商', na=False)

In [4]:
df = pd.read_sql('mBiz', eng)

In [5]:
df

In [ ]:
df['项目名']

In [130]:
ddf = df[df['项目名'].str.endswith('(行业)')][df[df['项目名'].str.endswith('(行业)')]['日期']=='2023-12-31'].reset_index(drop=True)

In [25]:
df[df['营业收入(元)'].str.endswith('(万)')]

In [6]:
dddf = df[df['项目名'].str.endswith('(产品)')][df[df['项目名'].str.endswith('(产品)')]['日期']=='2023-12-31'].reset_index(drop=True)

In [23]:
dddf[dddf['营业收入(元)'].str.endswith('万')]

In [28]:
dddf[dddf['营业收入(元)'].isnull()]

In [ ]:
dddf[dddf['StockCode'].isin(['000004','600168'])]

In [2]:
dddf[dddf['收入比例(%)'].astype(float)>20]

In [ ]:
ddf[ddf['StockCode']=='000002']

In [135]:
ddf['项目名'] = ddf['项目名'].str.replace('\(行业\)', '')

In [136]:
ddf

In [ ]:
df[df['StockCode']=='688653']['项目名'].str.contains('行业', na=False)

In [ ]:
df[df['题材'].str.contains('券商', na=False)].sort_values(by=['相关度','StockCode'], ascending=False).reset_index(drop=True)

In [7]:
gg  = df.groupby('题材')

In [ ]:
df[df["StockCode"]=='002161']

In [735]:
df

In [ ]:
gg.groups

In [10]:
gDF = gg.count().sort_values('StockCode')

In [ ]:
gDF

In [ ]:
gg.get_group('食品溯源')

In [ ]:
import json

from pyecharts import options as opts
from pyecharts.charts import Graph

with open("weibo.json", "r", encoding="utf-8") as f:
    j = json.load(f)
    nodes, links, categories, cont, mid, userl = j
c = (
    Graph()
    .add(
        "",
        nodes,
        links,
        categories,
        repulsion=50,
        linestyle_opts=opts.LineStyleOpts(curve=0.2),
        label_opts=opts.LabelOpts(is_show=False),
    )
    .set_global_opts(
        legend_opts=opts.LegendOpts(is_show=False),
        title_opts=opts.TitleOpts(title="Graph-微博转发关系图"),
    )
    .render("graph_weibo.html")
)

In [ ]:
from pyecharts.globals import CurrentConfig, NotebookType
CurrentConfig.NOTEBOOK_TYPE = NotebookType.JUPYTER_LAB


from pyecharts.charts import Bar
from pyecharts import options as opts
# 内置主题类型可查看 pyecharts.globals.ThemeType
from pyecharts.globals import ThemeType

bar = (
    Bar(init_opts=opts.InitOpts(theme=ThemeType.LIGHT))
    .add_xaxis(["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"])
    .add_yaxis("商家A", [5, 20, 36, 10, 75, 90])
    .add_yaxis("商家B", [15, 6, 45, 20, 35, 66])
    .set_global_opts(title_opts=opts.TitleOpts(title="主标题", subtitle="副标题"))
)
bar.load_javascript()

In [ ]:
bar.render_notebook()

============== 3dplt替换

In [34]:
from sqlalchemy import create_engine

eng = create_engine('postgresql+psycopg2://sa:11111111@10.3.18.56:5432/tdxIndex')

In [36]:
df = pd.read_sql('000001', eng)
df['datetime'] = df['datetime'].astype('datetime64[ns]')

In [37]:
import plotly.express as px

In [ ]:
fig = px.scatter(df, x='datetime', y='close',size='amount',color='open')
# fig = px.scatter(df, x='datetime', y='close',size='amount',color='open',marginal_y='violin',trendline='ewm',trendline_options={'ignore_na': True,'span':5, 'min_periods':21})
# fig.update_xaxes(rangeslider_visible=True)
fig.show(config={'scrollZoom': True,'displaylogo':False})

In [ ]:
fig = px.line(df, x='datetime', y='close',line_shape='spline',title='text')
fig.update_xaxes(rangeslider_visible=True)
fig.show(config={'scrollZoom': True,'displaylogo':False})

======== 加权密度图

In [40]:
import numpy as np

In [72]:
def norm(df, column_name):
    min_val = df[column_name].min()
    max_val = df[column_name].max()
    normalized_column = (df[column_name] - min_val) / (max_val - min_val)
    scaled_column = normalized_column * (89 - 1) + 1
    discrete_scaled_column = scaled_column.round().astype(int)
    return discrete_scaled_column

In [73]:
n = [5,21,55]
n =5
weights = norm(df.tail(n),'amount')
weighted_data = np.repeat(df['close'].tail(n), repeats=weights)

In [74]:
weights

6030     5
6031     1
6032    60
6033    89
6034    68
Name: amount, dtype: int64

In [75]:
weighted_data

6030    3000.95
6030    3000.95
6030    3000.95
6030    3000.95
6030    3000.95
         ...
6034    3258.86
6034    3258.86
6034    3258.86
6034    3258.86
6034    3258.86
Name: close, Length: 223, dtype: float64

In [76]:
fig = px.violin(weighted_data,box=True)
fig.show()