In [11]:
from mootdx.quotes import Quotes
std = Quotes.factory(market='std')
ext = Quotes.factory(market='ext')

2025-08-25 14:44:41,751 - mootdx - WARNING - 目前扩展市场行情接口已经失效, 后期有望修复.

In [16]:
print(std.stock_count(0))
print(std.stock_count(1))

21221
25458

In [22]:
szdf = std.stocks(0)
shdf = std.stocks(1)

100%|##########| 22/22 [00:02<00:00,  8.40it/s]
100%|##########| 26/26 [00:02<00:00,  9.32it/s]

In [25]:
shdf[shdf['decimal_point']==2]

         code  volunit  decimal_point  name     pre_close
0      999999      100              2  上证指数  3.825759e+03
1      999998      100              2  Ａ股指数  4.010367e+03
2      999997      100              2  Ｂ股指数  2.666790e+02
3      000001      100              2  上证指数  3.825759e+03
4      000002      100              2  Ａ股指数  4.010367e+03
...       ...      ...            ...   ...           ...
25392  799970      100              2  资金控制  5.877472e-39
25393  799991      100              2  中登认证  5.877472e-39
25394  799998      100              2  指定撤销  5.877472e-39
25395  799999      100              2  指定登记  5.877472e-39
25437  603370      100              2  华新精科  5.877472e-39

[3634 rows x 5 columns]

In [24]:
szdf[szdf['decimal_point']==2]

         code  volunit  decimal_point    name     pre_close
0      395001      100              2    主板Ａ股  1.485000e+03
1      395002      100              2    主板Ｂ股  1.440000e+02
2      395004      100              2   创业板    1.385000e+03
3      395005      100              2  主板DR    5.877472e-39
4      395006      100              2   创业板DR  5.877472e-39
...       ...      ...            ...     ...           ...
18894  301662      100              2    宏工科技  1.065200e+02
18895  301665      100              2    泰禾股份  3.100000e+01
18896  301678      100              2   新恒汇    8.636000e+01
18897  302132      100              2    中航成飞  9.936000e+01
21202  301575      100              2   艾芬达    5.877472e-39

[3285 rows x 5 columns]

In [3]:
std.bars(symbol='600036', frequency=9, offset=10)

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime,volume
datetime,,,,,,,,,,,,,
2025-08-12 15:00:00,44.13,44.00,44.48,44.00,5.622520e+05,2.482689e+09,2025,8,12,15,0,2025-08-12 15:00,5.622520e+05
2025-08-13 15:00:00,44.14,43.54,44.25,43.49,8.767370e+05,3.837406e+09,2025,8,13,15,0,2025-08-13 15:00,8.767370e+05
2025-08-14 15:00:00,43.55,43.78,43.94,43.50,6.763510e+05,2.959764e+09,2025,8,14,15,0,2025-08-14 15:00,6.763510e+05
2025-08-15 15:00:00,43.66,43.30,43.74,43.30,9.329560e+05,4.051326e+09,2025,8,15,15,0,2025-08-15 15:00,9.329560e+05
2025-08-18 15:00:00,43.10,43.51,43.67,42.89,9.263970e+05,4.005819e+09,2025,8,18,15,0,2025-08-18 15:00,9.263970e+05
2025-08-19 15:00:00,43.45,43.40,43.70,43.29,5.741180e+05,2.493609e+09,2025,8,19,15,0,2025-08-19 15:00,5.741180e+05
2025-08-20 15:00:00,43.30,43.45,43.63,43.15,5.472400e+05,2.374776e+09,2025,8,20,15,0,2025-08-20 15:00,5.472400e+05
2025-08-21 15:00:00,43.50,43.47,43.59,43.23,5.785400e+05,2.512170e+09,2025,8,21,15,0,2025-08-21 15:00,5.785400e+05
2025-08-22 15:00:00,43.47,43.26,43.48,43.04,7.944960e+05,3.432029e+09,2025,8,22,15,0,2025-08-22 15:00,7.944960e+05
2025-08-25 15:00:00,43.26,43.26,43.26,43.26,5.877472e-39,5.877472e-39,2025,8,25,15,0,2025-08-25 15:00,5.877472e-39

In [2]:
ext.markets()

    market  category      name short_name unknown_bytes
0        1         1       临时股         TP   b'\x00\x00'
1        7        12     中金所期权         OJ   b'\x00\x00'
2        8        12      个股期权         QQ   b'\x00\x00'
3        9        12      深圳期权         SQ   b'\x00\x00'
4       27         5      香港指数         FH   b'\x00\x00'
5       28         3      郑州商品         QZ   b'\x00\x00'
6       29         3      大连商品         QD   b'\x00\x00'
7       30         3      上海期货         QS   b'\x00\x00'
8       31         2      香港主板         KH   b'\x00\x00'
9       33         8     开放式基金         FU   b'\x00\x00'
10      34         9     货币型基金         FB   b'\x00\x00'
11      35         8    银河理财产品         LC   b'\x00\x00'
12      37        11  全球指数(静态)         FW   b'\x00\x00'
13      38        10      宏观指标         HG   b'\x00\x00'
14      40        11     中国概念股         CH   b'\x00\x00'
15      43         1     B股转H股         HB   b'\x00\x00'
16      44         1      股份转让         SB   b'\x00\x00'
17      47         3     中金所期货         CZ   b'\x00\x00'
18      48         2     香港创业板         KG   b'\x00\x00'
19      49         2      香港基金         KT   b'\x00\x00'
20      54         6     国债预发行         GY   b'\x00\x00'
21      56         8    阳光私募基金         TA   b'\x00\x00'
22      57         8    券商集合理财         TB   b'\x00\x00'
23      58         9    券商货币理财         TC   b'\x00\x00'
24      60         3    主力期货合约         MA   b'\x00\x00'
25      62         5      中证指数         ZZ   b'\x00\x00'
26      65        12    广州套利期货         EG   b'\x00\x00'
27      66         3      广州期货         QG   b'\x00\x00'
28      71         2       港股通         GH   b'\x00\x00'
29      74        13      美国股票         US   b'\x00\x00'
30     102         5      国证指数         GZ   b'\x00\x00'

In [5]:
import pandas as pd

In [19]:
df = ext.instrument(start=0 , offset=1000)
i=1
while i <=68 :
    m = i*1000
    df1 = ext.instrument(start=m , offset=1000)
    df = pd.concat([df,df1])
    i = i+1

In [28]:
df[df['market']==62]

     category  market    code      name desc
108         5      62  000012      国债指数
109         5      62  000013      企债指数
110         5      62  000022      沪公司债
111         5      62  000061     沪企债30
112         5      62  000101      5年信用
..        ...     ...     ...       ...  ...
773         5      62  H50055      沪大农业
774         5      62  H50069       港股通
775         5      62  N00300  沪深300净收益
776         5      62  N00905  中证500净收益
777         5      62  SHHKSI      沪港精明

[670 rows x 5 columns]

In [84]:
dff = ext.instrument(start=68000 , offset=1000)

In [3]:
ext.instrument(start=68000 , offset=800)

     category  market    code          name       desc
0          13      74    XOMA  XOMA Royalty          
1          13      74   XOMAO       临床研究优先B          
2          13      74   XOMAP      标记临床研究优A          
3          13      74    XOMO     XOM期权收益策略          
4          13      74    XOMX    每日XOM2倍做多股          
..        ...     ...     ...           ...        ...
287         5     102  988006        CNTHKD
288         5     102  988007        CNTUSD
289         5     102  988106      CNTTRHKD
290         5     102  988107      CNTTRUSD
291         5     102  988201        湾创100R

[292 rows x 5 columns]

In [86]:
df = pd.concat([df, dff])

In [79]:
df[df['market']==62]

     category  market    code      name desc
106         5      62  000012      国债指数
107         5      62  000013      企债指数
108         5      62  000022      沪公司债
109         5      62  000061     沪企债30
110         5      62  000101      5年信用
..        ...     ...     ...       ...  ...
771         5      62  H50055      沪大农业
772         5      62  H50069       港股通
773         5      62  N00300  沪深300净收益
774         5      62  N00905  中证500净收益
775         5      62  SHHKSI      沪港精明

[670 rows x 5 columns]

In [87]:
df

     category  market    code      name desc
0           2      71   00001        长和
1           2      71   00002      中电控股
2           2      71   00003    香港中华煤气
3           2      71   00004     九龙仓集团
4           2      71   00005      汇丰控股
..        ...     ...     ...       ...  ...
285         5     102  988006    CNTHKD
286         5     102  988007    CNTUSD
287         5     102  988106  CNTTRHKD
288         5     102  988107  CNTTRUSD
289         5     102  988201    湾创100R

[68290 rows x 5 columns]

In [82]:
ext.instrument_count()

68329

In [3]:
crawler = HistoryFinancialListCrawler()
list_data = crawler.fetch_and_parse()
print(pd.DataFrame(data=list_data))

             filename                              hash  filesize
0    gpcw20250930.zip  1f43e000d0fd371127b8a68a3246308c       164
1    gpcw20250630.zip  7958c560453aac4fcada4861bd62fd8e       164
2    gpcw20250331.zip  39b36d0513446ab3e8a1fb49f5e25b4b   4856246
3    gpcw20241231.zip  317a8cc0a9f2ba5cf4f1e472c8e81a7d   5539530
4    gpcw20240930.zip  249d0ecb420ca1bb9554ce00861c8bf8   5195779
..                ...                               ...       ...
138  gpcw19910331.zip  1792cb5b47b6a1ae01794d3972b0adbf       165
139  gpcw19901231.zip  ae0b3a7b5754b7058a8fe02e8b016690     12934
140  gpcw19900630.zip  6bb4c75c61c7066d3a03b3e24008b33f       165
141  gpcw19891231.zip  b0ad534ba255a73fe9368b8a0d5551c6       333
142  gpcw19881231.zip  4fcec5f4cf87d4f97d7f39adbf58145d       164

[143 rows x 3 columns]