In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
from datetime import datetime

In [3]:
datetime.now().strftime("%Y-%m-%d")

'2025-08-21'

In [4]:
current_date = datetime.now().strftime("%Y-%m-%d")

In [5]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
dd = pd.read_sql('tdxIndexs', eng)

In [ ]:
indexM = pd.read_sql('indexM', eng)
empIndex = pd.read_sql('EmpIndex', eng)

In [ ]:
dd['dp'] = current_date

In [ ]:
dd

In [ ]:
pd.concat([indexM,empIndex]).drop_duplicates(subset=['IndexCode'], keep=False).drop('index', axis=1)

In [ ]:
pd.read_sql('tdxIndexs', eng)

In [ ]:
indexM = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/indexM.xlsx', dtype={'IndexCode':object})

In [ ]:
blk = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
zz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxZZIndexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
sh = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
sz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})

In [ ]:
indexM.set_index('IndexCode').to_sql('indexM', eng)

In [32]:
blk = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
zz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZindexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
sh = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
sz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})

In [33]:
zz.drop_duplicates(subset='IndexCode',inplace=True)
m3 = pd.concat([sh, sz])
m3.reset_index(drop=True, inplace=True)

In [34]:
blkm = pd.merge(blk,m3, on=['IndexCode','IndexName'],how='inner')
blkm.reset_index(drop=True, inplace=True)

In [56]:
pd.merge(cs,m3, on='IndexCode',how='inner')

,IndexCode,IndexName_x,MarketName_x,Num,IndexSTL,DP,From,IndexName_y,Market,MarketName_y,MarketCode
0,000001,上证指数,SH,2235,综合,1991-07-15,CS,上证指数,ST,SH,1
1,000002,Ａ股指数,SH,2193,规模,1992-02-21,CS,A股指数,ST,SH,1
2,000004,工业指数,SH,1674,行业,1993-05-03,CS,工业指数,ST,SH,1
3,000005,商业指数,SH,172,行业,1993-05-03,CS,商业指数,ST,SH,1
4,000006,地产指数,SH,23,行业,1993-05-03,CS,地产指数,ST,SH,1
...,...,...,...,...,...,...,...,...,...,...,...
214,399994,信息安全,ZZ,63,主题,2015-03-12,CS,信息安全,ST,SZ,0
215,399995,基建工程,ZZ,50,行业,2015-03-12,CS,基建工程,ST,SZ,0
216,399996,智能家居,ZZ,100,主题,2014-09-17,CS,智能家居,ST,SZ,0
217,399997,中证白酒,ZZ,19,主题,2015-01-21,CS,中证白酒,ST,SZ,0
218,399998,中证煤炭,ZZ,30,行业,2015-02-13,CS,中证煤炭,ST,SZ,0

In [35]:
zzm = pd.merge(cs,zz, on='IndexCode',how='inner')
zzm.reset_index(drop=True, inplace=True)

In [36]:
zm = pd.merge(m3,zzm[['IndexCode','IndexSTL','Num','From','DP']],on=['IndexCode'],how='inner')

In [37]:
m3zz = pd.concat([zm,zzm]).drop_duplicates(subset='IndexCode',keep='first')

In [38]:
zzm3 = pd.concat([m3zz,m3]).drop_duplicates(subset='IndexCode',keep='first').reset_index(drop=True)

In [47]:
dddf = pd.concat([blkm,zzm3]).drop_duplicates(subset='IndexCode',keep='first').sort_values(by=['IndexCode','MarketCode']).reset_index(drop=True)

In [48]:
dddf['IndexSTL'] = dddf['IndexSTL'].fillna('指数')

In [51]:
dddf

,IndexCode,IndexName,IndexSTL,Num,From,DP,Market,MarketName,MarketCode
0,000001,上证指数,综合,2235.0,CS,1991-07-15,ST,SH,1
1,000002,A股指数,指数,NaN,TDX,NaN,ST,SH,1
2,000003,Ｂ股指数,指数,NaN,TDX,NaN,ST,SH,1
3,000004,工业指数,指数,NaN,TDX,NaN,ST,SH,1
4,000005,商业指数,指数,NaN,TDX,NaN,ST,SH,1
...,...,...,...,...,...,...,...,...,...
2626,H50052,上国改革,主题,50.0,CS,2014-10-28,EX,SH,62
2627,H50053,上证移动,主题,46.0,CS,2014-07-11,EX,SH,62
2628,H50054,上证休闲,主题,50.0,CS,2014-07-21,EX,SH,62
2629,H50055,沪大农业,主题,50.0,CS,2014-07-22,EX,SH,62
2630,H50056,沪智家居,主题,50.0,CS,2014-09-17,EX,SH,62

In [49]:
dddf['From'].fillna('TDX', inplace=True)

G:\Local\Temp\ipykernel_34852\3538880420.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dddf['From'].fillna('TDX', inplace=True)

In [46]:
dddf

,IndexCode,IndexName,IndexSTL,Num,From,DP,Market,MarketName,MarketCode
0,000001,上证指数,综合,2235.0,CS,1991-07-15,ST,SH,1
1,000002,A股指数,指数,NaN,TDX,NaN,ST,SH,1
2,000003,Ｂ股指数,指数,NaN,TDX,NaN,ST,SH,1
3,000004,工业指数,指数,NaN,TDX,NaN,ST,SH,1
4,000005,商业指数,指数,NaN,TDX,NaN,ST,SH,1
...,...,...,...,...,...,...,...,...,...
2626,H50052,上国改革,主题,50.0,CS,2014-10-28,EX,SH,62
2627,H50053,上证移动,主题,46.0,CS,2014-07-11,EX,SH,62
2628,H50054,上证休闲,主题,50.0,CS,2014-07-21,EX,SH,62
2629,H50055,沪大农业,主题,50.0,CS,2014-07-22,EX,SH,62
2630,H50056,沪智家居,主题,50.0,CS,2014-09-17,EX,SH,62

In [14]:
finz = pd.concat([zzm,zm])
finz.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finz.drop_duplicates(subset='IndexCode',inplace=True)
finz.reset_index(drop=True, inplace=True)

finm = pd.concat([blkm,finz])
finm.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finm.drop_duplicates(subset='IndexCode',inplace=True)
finm.reset_index(drop=True, inplace=True)