In [7]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
from datetime import datetime

In [3]:
datetime.now().strftime("%Y-%m-%d")

'2025-08-21'

In [5]:
current_date = datetime.now().strftime("%Y-%m-%d")

In [10]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [11]:
dd = pd.read_sql('tdxIndexs', eng)

In [3]:
indexM = pd.read_sql('indexM', eng)
empIndex = pd.read_sql('EmpIndex', eng)

In [14]:
dd['dp'] = current_date

In [15]:
dd

,IndexCode,IndexName,IndexSTL,Num,From,Market,MarketName,MarketCode,DP,dp
0,000001,上证指数,综合,2235.0,CS,ST,SH,1.0,1991-07-15,2025-08-21
1,000009,上证380,指数,380.0,TDXBLK,ST,SH,1.0,None,2025-08-21
2,000010,上证180,指数,180.0,TDXBLK,ST,SH,1.0,None,2025-08-21
3,000015,红利指数,指数,50.0,TDXBLK,ST,SH,1.0,None,2025-08-21
4,000016,上证50,指数,50.0,TDXBLK,ST,SH,1.0,None,2025-08-21
...,...,...,...,...,...,...,...,...,...,...
1177,H50047,180反两,策略,180.0,CS,EX,SH,62.0,2014-06-19,2025-08-21
1178,H50052,上国改革,主题,50.0,CS,EX,SH,62.0,2014-10-28,2025-08-21
1179,H50053,上证移动,主题,46.0,CS,EX,SH,62.0,2014-07-11,2025-08-21
1180,H50054,上证休闲,主题,50.0,CS,EX,SH,62.0,2014-07-21,2025-08-21
1181,H50055,沪大农业,主题,50.0,CS,EX,SH,62.0,2014-07-22,2025-08-21

In [4]:
pd.concat([indexM,empIndex]).drop_duplicates(subset=['IndexCode'], keep=False).drop('index', axis=1)

,IndexCode,IndexName,IndexSTL,Num,From,Market,MarketName,MarketCode,DP
0,000001,上证指数,综合,2235.0,CS,ST,SH,1.0,1991-07-15
1,000009,上证380,指数,380.0,TDXBLK,ST,SH,1.0,None
2,000010,上证180,指数,180.0,TDXBLK,ST,SH,1.0,None
3,000015,红利指数,指数,50.0,TDXBLK,ST,SH,1.0,None
4,000016,上证50,指数,50.0,TDXBLK,ST,SH,1.0,None
...,...,...,...,...,...,...,...,...,...
1663,H50047,180反两,策略,180.0,CS,EX,SH,62.0,2014-06-19
1664,H50052,上国改革,主题,50.0,CS,EX,SH,62.0,2014-10-28
1665,H50053,上证移动,主题,46.0,CS,EX,SH,62.0,2014-07-11
1666,H50054,上证休闲,主题,50.0,CS,EX,SH,62.0,2014-07-21
1667,H50055,沪大农业,主题,50.0,CS,EX,SH,62.0,2014-07-22

In [5]:
pd.read_sql('tdxIndexs', eng)

,IndexCode,IndexName,IndexSTL,Num,From,Market,MarketName,MarketCode,DP
0,000001,上证指数,综合,2235.0,CS,ST,SH,1.0,1991-07-15
1,000009,上证380,指数,380.0,TDXBLK,ST,SH,1.0,None
2,000010,上证180,指数,180.0,TDXBLK,ST,SH,1.0,None
3,000015,红利指数,指数,50.0,TDXBLK,ST,SH,1.0,None
4,000016,上证50,指数,50.0,TDXBLK,ST,SH,1.0,None
...,...,...,...,...,...,...,...,...,...
1177,H50047,180反两,策略,180.0,CS,EX,SH,62.0,2014-06-19
1178,H50052,上国改革,主题,50.0,CS,EX,SH,62.0,2014-10-28
1179,H50053,上证移动,主题,46.0,CS,EX,SH,62.0,2014-07-11
1180,H50054,上证休闲,主题,50.0,CS,EX,SH,62.0,2014-07-21
1181,H50055,沪大农业,主题,50.0,CS,EX,SH,62.0,2014-07-22

In [ ]:
indexM = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/indexM.xlsx', dtype={'IndexCode':object})

In [9]:
blk = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
zz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxZZIndexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
sh = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
sz = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})

In [4]:
indexM.set_index('IndexCode').to_sql('indexM', eng)

-1

In [18]:
blk = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxIndexsBLK.xlsx', dtype={'IndexCode':object})
zz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxZZindexs.xlsx', dtype={'IndexCode':object})
cs = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/csIndex.xlsx', dtype={'IndexCode':object})
sh = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSHIndexs.xlsx', dtype={'IndexCode':object})
sz = pd.read_excel('G:/Gitee/App/TDXapp/tdxAppData/tdxSZIndexs.xlsx', dtype={'IndexCode':object})

In [10]:
zz.drop_duplicates(subset='IndexCode',inplace=True)
m3 = pd.concat([sh, sz])
m3.reset_index(drop=True, inplace=True)

In [11]:
blkm = pd.merge(blk,m3, on=['IndexCode','IndexName'],how='inner')
blkm.reset_index(drop=True, inplace=True)

In [12]:
zzm = pd.merge(cs,zz, on='IndexCode',how='inner')
zzm.reset_index(drop=True, inplace=True)

In [17]:
zm = pd.merge(m3,zzm[['IndexCode','IndexSTL','Num','From','DP']],on=['IndexCode'],how='inner')

In [18]:
finz = pd.concat([zzm,zm])
finz.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finz.drop_duplicates(subset='IndexCode',inplace=True)
finz.reset_index(drop=True, inplace=True)

finm = pd.concat([blkm,finz])
finm.sort_values(by=['IndexCode','MarketCode'],inplace=True)
finm.drop_duplicates(subset='IndexCode',inplace=True)
finm.reset_index(drop=True, inplace=True)