In [ ]:
from mootdx.quotes import Quotes
import pandas as pd
import re
from sqlalchemy import create_engine

In [ ]:
eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
engs = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')

In [ ]:
def getBiz(StockCode, StockName):
    qf10='经营分析'
    client = Quotes.factory(market='std')
    txtRaw = client.F10(StockCode, qf10)



    # # StockName = re.findall(r'\b'+StockCode+'\s+([^\s]*)',txtRaw)[0]
    try:
        hc = re.findall(r'\d+.\d+|\d+%',re.findall(r'前5大客户[^\s]*',txt)[0])
        hp = re.findall(r'\d+\.\d+|\d+%',re.findall(r'前5大供应商[^\s]*',txt)[0])
        csdf = pd.DataFrame(hc+hp).T
        csdf.columns = ["营收额","营收占比",'采购额',"采购占比"]
        csdf['StockCode'] = StockCode
        csdf['StockName'] = StockName
        # csdf[['StockCode','StockName',"营收额","营收占比",'采购额',"采购占比"]].set_index('StockCode').to_sql('BizP', eng, if_exists='append')

    except:
        pass

    fi = txt[txt.find('【2.主营构成分析】'):]
    ff = fi[:fi.find('【3.经营投资】')]
    # ff = fi[:fi.find('【3.前5名客户营业收入表】')]
    datetimes=re.findall(r'截止日期:([^\s]*)', ff)
    dd = ff.replace('─','').splitlines(keepends=False)

    Data = pd.DataFrame(columns=())
    i = 0
    while i < len(dd):
        lis = re.split(r"\s+", dd[i])[-6:]
        if len(lis)!=6:
            i = i+1
            # pass
        else:
            df = pd.DataFrame(lis).T
            # df.columns=["股票名称", "一周涨跌幅%","一月涨跌幅%","三月涨跌幅%","半年涨跌幅%","一年涨跌幅%"]
            Data = pd.concat([Data, df],axis=0)
            i=i+1
    Data.reset_index(drop=True,inplace=True)
    Data = Data.replace('---',pd.NA)
    ddf  = Data
    # ddf  = Data.apply(pd.to_numeric, errors='ignore')

    ddfindex = ddf[ddf[0]=='项目名'].index
    raDF = pd.DataFrame(columns=['日期',"项目名","营业收入(元)","收入比例","营业成本(元)","成本比例","营业利润(元)",""])

    for i in [0,1,2,3]:
        try:
            dfd = ddf.loc[(ddfindex[i]+1):(ddfindex[i+1]-1)].reset_index(drop=True)
            dfd.columns = ["项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]
            dfd['日期'] = datetimes[i]
            raDF = pd.concat([raDF,dfd], axis=0)
        except:
            continue

    raDF['StockCode'] = StockCode
    raDF['StockName'] = StockName
    return raDF

In [ ]:
StockList = pd.read_sql('StocksList', engs)[['code','name']]

In [ ]:
StockList[StockList['code']=='600761']

In [82]:
StockCode = '000001'
StockName = '平安银行'

In [67]:
getBiz(StockCode, StockName)

In [69]:
StockCode = '000001'
StockName = '安徽合力'

In [70]:
qf10='经营分析'
client = Quotes.factory(market='std')
txtRaw = client.F10(StockCode, qf10)

In [95]:
txt = txtRaw.replace('│',' ')                
txt = re.sub('([\u2500-\u25f7])','',txt)[116:]

In [105]:
txtRaw

'☆经营分析☆ ◇000001 平安银行 更新日期：2025-08-25◇ 港澳资讯 灵通V8.0\r\n★本栏包括【1.主营业务】【2.主营构成分析】【3.经营投资】【4.关联企业经营状况】★\r\n\r\n【1.主营业务】\r\n┌───────────────────────────────────────────────────────────┐\r\n｜人民币和外币储蓄存款；人民币和外币企事业单位存款；人民币和外币结算；人民币和外币放款；信托、租赁、见证、证券业务。    ｜\r\n└───────────────────────────────────────────────────────────┘\r\n\r\n【2.主营构成分析】\r\n【截止日期】2025-06-30\r\n┌───────────────┬───────┬────┬───────┬────┬───────┬────┬────┐\r\n｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜零售金融业务(行业)            ｜      310.81亿｜  44.80%｜      110.24亿｜  28.06%｜      200.57亿｜  66.63%｜  64.53%｜\r\n｜批发金融业务(行业)            ｜      304.25亿｜  43.85%｜       80.39亿｜  20.46%｜      223.86亿｜  74.37%｜  73.58%｜\r\n｜其他业务(行业)                ｜       78.79亿｜  11.36%｜         7.7亿｜   1.96%｜       71.09亿｜  23.62%｜  90.23%｜\r\n｜合计(行业)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜零售金融业务(产品)            ｜      310.81亿｜  44.80%｜      110.24亿｜  28.06%｜      200.57亿｜  66.63%｜  64.53%｜\r\n｜批发金融业务(产品)            ｜      304.25亿｜  43.85%｜       80.39亿｜  20.46%｜      223.86亿｜  74.37%｜  73.58%｜\r\n｜其他业务(产品)                ｜       78.79亿｜  11.36%｜         7.7亿｜   1.96%｜       71.09亿｜  23.62%｜  90.23%｜\r\n｜合计(产品)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜东区(地区)                    ｜       95.88亿｜  13.82%｜       28.47亿｜   7.25%｜       67.41亿｜  22.39%｜  70.31%｜\r\n｜南区(地区)                    ｜      100.43亿｜  14.47%｜       28.34亿｜   7.21%｜       72.09亿｜  23.95%｜  71.78%｜\r\n｜西区(地区)                    ｜       26.43亿｜   3.81%｜       10.16亿｜   2.59%｜       16.27亿｜   5.40%｜  61.56%｜\r\n｜北区(地区)                    ｜       64.04亿｜   9.23%｜       23.89亿｜   6.08%｜       40.15亿｜  13.34%｜  62.70%｜\r\n｜总部(地区)                    ｜      401.52亿｜  57.87%｜      106.15亿｜  27.02%｜      295.37亿｜  98.12%｜  73.56%｜\r\n｜境外(地区)                    ｜        5.55亿｜   0.80%｜        1.32亿｜   0.34%｜        4.23亿｜   1.41%｜  76.22%｜\r\n｜合计(地区)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜\r\n└───────────────┴───────┴────┴───────┴────┴───────┴────┴────┘\r\n\r\n【截止日期】2024-12-31\r\n┌───────────────┬───────┬────┬───────┬────┬───────┬────┬────┐\r\n｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜批发金融业务(行业)            ｜      638.41亿｜  43.52%｜       190.4亿｜  45.27%｜      448.01亿｜  42.82%｜  70.18%｜\r\n｜零售金融业务(行业)            ｜      712.55亿｜  48.57%｜      220.36亿｜  52.39%｜      492.19亿｜  47.04%｜  69.07%｜\r\n｜其他业务(行业)                ｜      115.99亿｜   7.91%｜        9.85亿｜   2.34%｜      106.14亿｜  10.14%｜  91.51%｜\r\n｜合计(行业)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜批发金融业务(产品)            ｜      638.41亿｜  43.52%｜       190.4亿｜  45.27%｜      448.01亿｜  42.82%｜  70.18%｜\r\n｜零售金融业务(产品)            ｜      712.55亿｜  48.57%｜      220.36亿｜  52.39%｜      492.19亿｜  47.04%｜  69.07%｜\r\n｜其他业务(产品)                ｜      115.99亿｜   7.91%｜        9.85亿｜   2.34%｜      106.14亿｜  10.14%｜  91.51%｜\r\n｜合计(产品)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜东区(地区)                    ｜      208.54亿｜  14.22%｜       75.21亿｜  17.88%｜      133.33亿｜  12.74%｜  63.93%｜\r\n｜南区(地区)                    ｜      225.55亿｜  15.38%｜       68.65亿｜  16.32%｜       156.9亿｜  15.00%｜  69.56%｜\r\n｜西区(地区)                    ｜       67.42亿｜   4.60%｜       26.51亿｜   6.30%｜       40.91亿｜   3.91%｜  60.68%｜\r\n｜北区(地区)                    ｜      146.64亿｜  10.00%｜        58.3亿｜  13.86%｜       88.34亿｜   8.44%｜  60.24%｜\r\n｜总部(地区)                    ｜      810.18亿｜  55.23%｜       188.6亿｜  44.84%｜      621.58亿｜  59.41%｜  76.72%｜\r\n｜境外(地区)                    ｜        8.62亿｜   0.59%｜        3.34亿｜   0.79%｜        5.28亿｜   0.50%｜  61.25%｜\r\n｜合计(地区)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜\r\n└───────────────┴───────┴────┴───────┴────┴───────┴────┴────┘\r\n\r\n【截止日期】2024-06-30\r\n┌───────────────┬───────┬────┬───────┬────┬───────┬────┬────┐\r\n｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜零售金融业务(行业)            ｜      390.91亿｜  50.68%｜      124.47亿｜  56.86%｜      266.44亿｜  48.23%｜  68.16%｜\r\n｜批发金融业务(行业)            ｜      330.96亿｜  42.91%｜       87.66亿｜  40.04%｜       243.3亿｜  44.04%｜  73.51%｜\r\n｜其他业务(行业)                ｜       49.45亿｜   6.41%｜        6.79亿｜   3.10%｜       42.66亿｜   7.72%｜  86.27%｜\r\n｜合计(行业)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜零售金融业务(产品)            ｜      390.91亿｜  50.68%｜      124.47亿｜  56.86%｜      266.44亿｜  48.23%｜  68.16%｜\r\n｜批发金融业务(产品)            ｜      330.96亿｜  42.91%｜       87.66亿｜  40.04%｜       243.3亿｜  44.04%｜  73.51%｜\r\n｜其他业务(产品)                ｜       49.45亿｜   6.41%｜        6.79亿｜   3.10%｜       42.66亿｜   7.72%｜  86.27%｜\r\n｜合计(产品)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜东区(地区)                    ｜      106.47亿｜  13.80%｜       31.46亿｜  14.37%｜       75.01亿｜  13.58%｜  70.45%｜\r\n｜南区(地区)                    ｜      124.03亿｜  16.08%｜        28.5亿｜  13.02%｜       95.53亿｜  17.29%｜  77.02%｜\r\n｜西区(地区)                    ｜       37.92亿｜   4.92%｜       10.73亿｜   4.90%｜       27.19亿｜   4.92%｜  71.70%｜\r\n｜北区(地区)                    ｜       78.68亿｜  10.20%｜       24.52亿｜  11.20%｜       54.16亿｜   9.80%｜  68.84%｜\r\n｜总部(地区)                    ｜      419.94亿｜  54.44%｜      122.11亿｜  55.78%｜      297.83亿｜  53.92%｜  70.92%｜\r\n｜境外(地区)                    ｜        4.28亿｜   0.55%｜         1.6亿｜   0.73%｜        2.68亿｜   0.49%｜  62.62%｜\r\n｜合计(地区)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜\r\n└───────────────┴───────┴────┴───────┴────┴───────┴────┴────┘\r\n\r\n【截止日期】2023-12-31\r\n┌───────────────┬───────┬────┬───────┬────┬───────┬────┬────┐\r\n｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜零售金融业务(行业)            ｜      961.61亿｜  58.39%｜      301.14亿｜  63.16%｜      660.47亿｜  56.44%｜  68.68%｜\r\n｜批发金融业务(行业)            ｜      535.81亿｜  32.53%｜      168.85亿｜  35.42%｜      366.96亿｜  31.36%｜  68.49%｜\r\n｜其他业务(行业)                ｜      149.57亿｜   9.08%｜        6.78亿｜   1.42%｜      142.79亿｜  12.20%｜  95.47%｜\r\n｜合计(行业)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜零售金融业务(产品)            ｜      961.61亿｜  58.39%｜      301.14亿｜  63.16%｜      660.47亿｜  56.44%｜  68.68%｜\r\n｜批发金融业务(产品)            ｜      535.81亿｜  32.53%｜      168.85亿｜  35.42%｜      366.96亿｜  31.36%｜  68.49%｜\r\n｜其他业务(产品)                ｜      149.57亿｜   9.08%｜        6.78亿｜   1.42%｜      142.79亿｜  12.20%｜  95.47%｜\r\n｜合计(产品)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜\r\n├───────────────┼───────┼────┼───────┼────┼───────┼────┼────┤\r\n｜东区(地区)                    ｜      251.11亿｜  15.25%｜       79.88亿｜  16.75%｜      171.23亿｜  14.63%｜  68.19%｜\r\n｜南区(地区)                    ｜      282.29亿｜  17.14%｜       77.89亿｜  16.34%｜       204.4亿｜  17.47%｜  72.41%｜\r\n｜西区(地区)                    ｜       93.39亿｜   5.67%｜       29.63亿｜   6.21%｜       63.76亿｜   5.45%｜  68.27%｜\r\n｜北区(地区)                    ｜      188.53亿｜  11.45%｜       66.28亿｜  13.90%｜      122.25亿｜  10.45%｜  64.84%｜\r\n｜总部(地区)                    ｜      826.79亿｜  50.20%｜      219.83亿｜  46.11%｜      606.96亿｜  51.87%｜  73.41%｜\r\n｜境外(地区)                    ｜        4.88亿｜   0.30%｜        3.26亿｜   0.68%｜        1.62亿｜   0.14%｜  33.20%｜\r\n｜合计(地区)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜\r\n└───────────────┴───────┴────┴───────┴────┴───────┴────┴────┘\r\n\r\n【3.经营投资】\r\n【公司经营情况评述】\r\n┌───────────────────────────────────────────────────────────┐\r\n｜【2025年半年报】                                                                                                      ｜\r\n｜    一、总体经营情况                                                                                                  ｜\r\n｜    2025年上半年，本行坚持党建引领，坚持金融工作的政治性、人民性，坚持以“中国最卓越、全球领先的智能化零售银行”为战略｜\r\n｜目标，坚持“零售做强、对公做精、同业做专”战略方针，持续升级零售、对公、资金同业业务经营策略，全力做好金融“五篇大文章｜\r\n｜”，持续强化风险管理，深化数字化转型，整体业务经营保持稳健。                                                          ｜\r\n｜    营收利润降幅收窄，持续推进降本增效。2025年上半年，本集团实现营业收入693.85亿元，同比下降10.0%，主要受市场利率下行 ｜\r\n｜、贷款业务结构调整等因素影响，净息差1.80%，较去年同期下降16个基点；受市场波动影响，债券投资等业务非利息净收入下降。通 ｜\r\n｜过数字化转型驱动降本增效，业务及管理费192.06亿元，同比下降9.0%；同时，加强资产质量管控，加大不良资产清收处置力度，信用｜\r\n｜及其他资产减值损失194.50亿元，同比下降16.0%。实现净利润248.70亿元，同比下降3.9%，降幅较第一季度有所收窄。             ｜\r\n｜    持续优化资产结构，支持服务实体经济。2025年6月末，本集团资产总额58,749.61亿元，较上年末增长1.8%；发放贷款和垫款本金｜\r\n｜总额34,084.98亿元，较上年末增长1.0%；本行持续加大实体经济支持力度，制造业、科技企业、绿色金融等领域贷款实现较好增长， ｜\r\n｜企业贷款余额较上年末增长4.7%；持续优化零售资产组合策略，提升住房按揭、持证抵押等基石类业务占比，个人贷款余额较上年末下｜\r\n｜降2.3%，抵押类贷款占个人贷款的比例为64.3%。                                                                           ｜\r\n｜    存款保持稳步增长，付息率显著优化。2025年6月末，本集团负债总额53,648.99亿元，较上年末增长1.7%；吸收存款本金余额36,9｜\r\n｜44.71亿元，较上年末增长4.6%。本行加强高成本存款产品管控，促进低成本存款沉淀，并敏捷调控存款和同业负债的吸收节奏，优化 ｜\r\n｜整体负债成本；2025年上半年，本集团计息负债平均付息率1.79%，较去年同期下降46个基点；吸收存款平均付息率1.76%，较去年同期｜\r\n｜下降42个基点。                                                                                                        ｜\r\n｜    强化全面风险管理，资产质量整体平稳。本行积极应对宏观经济环境变化，加强风险管控，持续优化资产和客群结构。2025年6月 ｜\r\n｜末，不良贷款率1.05%，较上年末下降0.01个百分点；逾期60天以上贷款偏离度及逾期90天以上贷款偏离度分别为0.79和0.67；拨备覆 ｜\r\n｜盖率238.48%，风险抵补能力保持良好。                                                                                   ｜\r\n｜    践行资本精细化管理，资本充足率提升。持续强化资本内生积累，提升资本精细化管理水平，2025年6月末，本集团核心一级资本 ｜\r\n｜充足率、一级资本充足率及资本充足率分别为9.31%、10.85%、13.26%，较上年末分别上升0.19、0.16、0.15个百分点。             ｜\r\n｜    二、下半年展望                                                                                                    ｜\r\n｜    （一）下半年形势展望                                                                                              ｜\r\n｜    2025年是“十四五”规划的收官之年，也是进一步全面深化改革的重要一年。我国将以习近平新时代中国特色社会主义思想为指导｜\r\n｜，坚持稳中求进工作总基调，完整、准确、全面贯彻新发展理念，加快构建新发展格局，扎实推动高质量发展，进一步全面深化改革，｜\r\n｜扩大高水平对外开放，推动经济持续回升向好，以中国式现代化全面推进强国建设、民族复兴伟业。                              ｜\r\n｜    2025年下半年，预计财政政策将会更加积极有为、货币政策将会保持适度宽松，产业政策将发展与安全并举，科技政策将聚焦自立｜\r\n｜自强，社会政策将兜牢民生底线，形成推动高质量发展的合力，预计宏观经济仍将保持稳健增长，经济回升向好态势将进一步巩固和增｜\r\n｜强。进一步全面深化改革将给银行业发展带来新的机遇，银行业将持续保持稳健经营，持续保持对宏观经济、市场变化与客户需求的敏｜\r\n｜锐洞察，持续提升服务实体经济的能力，持续强化金融风险防控，积极助力高质量发展，助力推进中国式现代化。                  ｜\r\n｜    （二）下半年主要工作                                                                                              ｜\r\n｜    2025年下半年，本行坚持党建引领，坚持金融工作的政治性、人民性，持续深化战略转型，持续提升金融服务实体经济的能力，持｜\r\n｜续强化金融风险防控，积极践行金融高质量发展。                                                                          ｜\r\n｜    一是持续深化党建引领。持续加强党的领导和党的建设，积极贯彻落实党中央重大决策部署，全面贯彻落实监管各项要求，推动党｜\r\n｜的领导融入公司治理、党的建设融入组织建设、党的精神融入文化发展，深化党业融合，落实全面从严治行，以高质量党建全面引领银｜\r\n｜行经营管理高质量发展。                                                                                                ｜\r\n｜    二是持续提升金融服务实体经济的能力。充分发挥自身资源禀赋和经营管理特色优势，积极做好金融“五篇大文章”。持续发展消｜\r\n｜费金融业务、私行财富业务，积极助力扩大内需。持续发展金融市场做市业务、企业客户避险业务，积极助力金融市场活跃，降低企业｜\r\n｜客户经营风险。                                                                                                        ｜\r\n｜    三是持续强化金融风险防控。将资产质量视为银行发展的“第一生命线”，聚焦重点领域潜在风险，压实重点行业、产品、客群和｜\r\n｜大户等领域风险防控；推进存量问题资产的风险化解，加强存量不良资产清收处置力度；优化客群和资产结构，稳步推进优质资产投放｜\r\n｜；深化科技赋能，持续升级智慧风控平台体系，全面提升风险管理效率和水平。全面强化合规风险管理，打造合规“网格化”治理新模｜\r\n｜式，全面提升合规治理、合规约束、合规文化“三大能力”。全面强化信访管理和金融消费者权益保护，聚焦重点领域，落实源头治理｜\r\n｜，切实维护消费者合法权益。                                                                                            ｜\r\n└───────────────────────────────────────────────────────────┘\r\n┌───────────────────────────────────────────────────────────┐\r\n｜【2024年年报】                                                                                                        ｜\r\n｜    一、总体经营情况                                                                                                  ｜\r\n｜    2024 年，本行坚持党建引领，坚持以“中国最卓越、全球领先的智能化零售银行”为战略目标，坚持“零售做强、对公做精、同 ｜\r\n｜业做专”战略方针，持续升级零售、对公、资金同业业务经营策略，全力做好金融“五篇大文章”，持续强化风险管理，深化数字化转｜\r\n｜型，助推高质量发展。                                                                                                  ｜\r\n｜    营收利润同比下降，业务经营保持稳健。2024 年，受市场变化、主动调整资产结构等因素的影响，本集团实现营业收入 1,466.95｜\r\n｜ 亿元，同比下降 10.9%。同时，通过数字化转型驱动经营降本增效，业务及管理费 405.82 亿元，同比下降 11.7%；加强资产质量管 ｜\r\n｜控，加大不良资产清收处置力度，信用及其他资产减值损失 494.28 亿元，同比下降 16.4%；实现净利润 445.08 亿元，同比下降 4.2｜\r\n｜%。                                                                                                                   ｜\r\n｜    主动调整业务结构，持续支持实体经济。2024 年末，本集团整体业务规模保持平稳，资产总额57,692.70 亿元，较上年末增长 3.｜\r\n｜3%；发放贷款和垫款本金总额 33,741.03 亿元，较上年末下降 1.0%，本行持续加大实体经济支持力度，制造业、科技企业、绿色金融｜\r\n｜等领域贷款实现较好增长，企业贷款余额较上年末增长 12.4%；顺应外部经营环境变化，主动优化零售贷款业务结构，促进“量、价、｜\r\n｜险”平衡发展，个人贷款余额较上年末下降 10.6%。负债总额 52,744.28 亿元，较上年末增长 3.1%；吸收存款本金余额 35,336.78  ｜\r\n｜亿元，较上年末增长 3.7%。                                                                                             ｜\r\n｜    强化全面风险管理，风险抵补能力保持良好。本行积极应对宏观经济环境变化，加强风险管控，主动优化资产和客群结构，资产质｜\r\n｜量保持平稳。2024 年末，不良贷款率 1.06%，与上年末持平；逾期 60 天以上贷款偏离度及逾期 90 天以上贷款偏离度分别为 0.80  ｜\r\n｜和 0.63；拨备覆盖率 250.71%，风险抵补能力保持良好。                                                                   ｜\r\n｜    践行资本精细化管理，资本充足率保持稳定。持续强化资本内生积累能力，提升资本精细化管理水平，兼顾股东回报与资本需求，｜\r\n｜2024 年末，本集团核心一级资本充足率、一级资本充足率、资本充足率分别为 9.12%、10.69%、13.11%。                         ｜\r\n｜    二、未来展望                                                                                                      ｜\r\n｜    1、宏观及行业环境展望                                                                                             ｜\r\n｜    2025 年是“十四五”规划的收官之年，也是进一步全面深化改革的关键之年。我国坚持以习近平新时代中国特色社会主义思想为 ｜\r\n｜指导，全面贯彻落实党的二十大和二十届二中、三中全会、中央金融工作会议、中央经济工作会议精神，坚持稳中求进工作总基调，完｜\r\n｜整、准确、全面贯彻新发展理念，加快构建新发展格局，扎实推动高质量发展，进一步全面深化改革，扩大高水平对外开放，建设现代｜\r\n｜化产业体系，推动经济持续回升向好。                                                                                    ｜\r\n｜    2025 年，预计财政政策将会更加积极、货币政策将会适度宽松，形成推动高质量发展的合力，宏观经济预计仍将持续保持稳健增 ｜\r\n｜长，经济回升向好态势将进一步巩固和增强。                                                                              ｜\r\n｜    2025 年，金融强国建设将加快推进，深化党建引领、加强党中央对金融工作的集中统一领导，做好金融“五篇大文章”、为经济 ｜\r\n｜社会发展提供高质量金融服务，强化全面风险管理、有效防范化解系统性金融风险，仍将是银行业的主旋律。                      ｜\r\n｜    2、经营计划                                                                                                       ｜\r\n｜    2025 年，本行坚持党建引领，坚持金融工作的政治性、人民性，持续深化战略转型，持续提升金融服务实体经济的能力，持续强 ｜\r\n｜化金融风险防控，积极践行金融高质量发展。                                                                              ｜\r\n｜    一是持续深化党建引领。持续加强党的领导和党的建设，全面贯彻落实党中央、国务院重大决策部署和监管部门各项要求，深化党｜\r\n｜的领导融入公司治理、党的建设融入组织建设、党的精神融入文化发展，深化党业融合，全面落实从严治党，以高质量党建全面引领银｜\r\n｜行经营管理高质量发展。                                                                                                ｜\r\n｜    二是持续提升金融服务实体经济的能力。充分发挥自身资源禀赋和经营管理特色优势，积极做好金融“五篇大文章”。持续发展消｜\r\n｜费金融业务、私行财富业务，积极助力扩大内需。持续发展金融市场做市业务、企业客户避险业务，积极助力金融市场活跃，降低企业｜\r\n｜客户经营风险。                                                                                                        ｜\r\n｜    三是持续强化金融风险防控。将资产质量视为银行发展的“第一生命线”，全面强化重点领域风险防控与体系化监控，防范化解房｜\r\n｜地产风险；推进存量问题资产的风险化解，加强存量不良清收处置；优化客群和资产结构，强化政策支持，稳步推进优质资产投放；深｜\r\n｜化科技赋能，升级智慧风控平台体系，完善风险配套，全面提升全流程风险管理效率和水平。完善制度、流程、机制，升级系统平台，｜\r\n｜全面强化利率风险管理。全面强化合规风险管理，打造合规“网格化”治理新模式，全面提升合规治理、合规约束、合规文化“三大能｜\r\n｜力”。全面强化信访管理和金融消费者权益保护，聚焦重点领域，落实源头治理，切实维护消费者合法权益。                      ｜\r\n└───────────────────────────────────────────────────────────┘\r\n\r\n【5.关联企业经营状况】\r\n暂无数据\r\n\r\n'

In [103]:
fi = txt[txt.find('【2.主营构成分析】'):]

In [110]:
ff = fi[:fi.find('【3.经营投资】')]

In [117]:
re.findall(r'【截止日期】([^\s]*)', ff)

['2025-06-30', '2024-12-31', '2024-06-30', '2023-12-31']

In [118]:
datetimes=re.findall(r'\b\d{4}-\d{2}-\d{2}\b', ff)

In [129]:
ff

'【2.主营构成分析】\r\n【截止日期】2025-06-30\r\n\r\n｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜\r\n\r\n｜零售金融业务(行业)            ｜      310.81亿｜  44.80%｜      110.24亿｜  28.06%｜      200.57亿｜  66.63%｜  64.53%｜\r\n｜批发金融业务(行业)            ｜      304.25亿｜  43.85%｜       80.39亿｜  20.46%｜      223.86亿｜  74.37%｜  73.58%｜\r\n｜其他业务(行业)                ｜       78.79亿｜  11.36%｜         7.7亿｜   1.96%｜       71.09亿｜  23.62%｜  90.23%｜\r\n｜合计(行业)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜\r\n\r\n｜零售金融业务(产品)            ｜      310.81亿｜  44.80%｜      110.24亿｜  28.06%｜      200.57亿｜  66.63%｜  64.53%｜\r\n｜批发金融业务(产品)            ｜      304.25亿｜  43.85%｜       80.39亿｜  20.46%｜      223.86亿｜  74.37%｜  73.58%｜\r\n｜其他业务(产品)                ｜       78.79亿｜  11.36%｜         7.7亿｜   1.96%｜       71.09亿｜  23.62%｜  90.23%｜\r\n｜合计(产品)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜\r\n\r\n｜东区(地区)                    ｜       95.88亿｜  13.82%｜       28.47亿｜   7.25%｜       67.41亿｜  22.39%｜  70.31%｜\r\n｜南区(地区)                    ｜      100.43亿｜  14.47%｜       28.34亿｜   7.21%｜       72.09亿｜  23.95%｜  71.78%｜\r\n｜西区(地区)                    ｜       26.43亿｜   3.81%｜       10.16亿｜   2.59%｜       16.27亿｜   5.40%｜  61.56%｜\r\n｜北区(地区)                    ｜       64.04亿｜   9.23%｜       23.89亿｜   6.08%｜       40.15亿｜  13.34%｜  62.70%｜\r\n｜总部(地区)                    ｜      401.52亿｜  57.87%｜      106.15亿｜  27.02%｜      295.37亿｜  98.12%｜  73.56%｜\r\n｜境外(地区)                    ｜        5.55亿｜   0.80%｜        1.32亿｜   0.34%｜        4.23亿｜   1.41%｜  76.22%｜\r\n｜合计(地区)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜\r\n\r\n\r\n【截止日期】2024-12-31\r\n\r\n｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜\r\n\r\n｜批发金融业务(行业)            ｜      638.41亿｜  43.52%｜       190.4亿｜  45.27%｜      448.01亿｜  42.82%｜  70.18%｜\r\n｜零售金融业务(行业)            ｜      712.55亿｜  48.57%｜      220.36亿｜  52.39%｜      492.19亿｜  47.04%｜  69.07%｜\r\n｜其他业务(行业)                ｜      115.99亿｜   7.91%｜        9.85亿｜   2.34%｜      106.14亿｜  10.14%｜  91.51%｜\r\n｜合计(行业)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜\r\n\r\n｜批发金融业务(产品)            ｜      638.41亿｜  43.52%｜       190.4亿｜  45.27%｜      448.01亿｜  42.82%｜  70.18%｜\r\n｜零售金融业务(产品)            ｜      712.55亿｜  48.57%｜      220.36亿｜  52.39%｜      492.19亿｜  47.04%｜  69.07%｜\r\n｜其他业务(产品)                ｜      115.99亿｜   7.91%｜        9.85亿｜   2.34%｜      106.14亿｜  10.14%｜  91.51%｜\r\n｜合计(产品)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜\r\n\r\n｜东区(地区)                    ｜      208.54亿｜  14.22%｜       75.21亿｜  17.88%｜      133.33亿｜  12.74%｜  63.93%｜\r\n｜南区(地区)                    ｜      225.55亿｜  15.38%｜       68.65亿｜  16.32%｜       156.9亿｜  15.00%｜  69.56%｜\r\n｜西区(地区)                    ｜       67.42亿｜   4.60%｜       26.51亿｜   6.30%｜       40.91亿｜   3.91%｜  60.68%｜\r\n｜北区(地区)                    ｜      146.64亿｜  10.00%｜        58.3亿｜  13.86%｜       88.34亿｜   8.44%｜  60.24%｜\r\n｜总部(地区)                    ｜      810.18亿｜  55.23%｜       188.6亿｜  44.84%｜      621.58亿｜  59.41%｜  76.72%｜\r\n｜境外(地区)                    ｜        8.62亿｜   0.59%｜        3.34亿｜   0.79%｜        5.28亿｜   0.50%｜  61.25%｜\r\n｜合计(地区)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜\r\n\r\n\r\n【截止日期】2024-06-30\r\n\r\n｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜\r\n\r\n｜零售金融业务(行业)            ｜      390.91亿｜  50.68%｜      124.47亿｜  56.86%｜      266.44亿｜  48.23%｜  68.16%｜\r\n｜批发金融业务(行业)            ｜      330.96亿｜  42.91%｜       87.66亿｜  40.04%｜       243.3亿｜  44.04%｜  73.51%｜\r\n｜其他业务(行业)                ｜       49.45亿｜   6.41%｜        6.79亿｜   3.10%｜       42.66亿｜   7.72%｜  86.27%｜\r\n｜合计(行业)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜\r\n\r\n｜零售金融业务(产品)            ｜      390.91亿｜  50.68%｜      124.47亿｜  56.86%｜      266.44亿｜  48.23%｜  68.16%｜\r\n｜批发金融业务(产品)            ｜      330.96亿｜  42.91%｜       87.66亿｜  40.04%｜       243.3亿｜  44.04%｜  73.51%｜\r\n｜其他业务(产品)                ｜       49.45亿｜   6.41%｜        6.79亿｜   3.10%｜       42.66亿｜   7.72%｜  86.27%｜\r\n｜合计(产品)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜\r\n\r\n｜东区(地区)                    ｜      106.47亿｜  13.80%｜       31.46亿｜  14.37%｜       75.01亿｜  13.58%｜  70.45%｜\r\n｜南区(地区)                    ｜      124.03亿｜  16.08%｜        28.5亿｜  13.02%｜       95.53亿｜  17.29%｜  77.02%｜\r\n｜西区(地区)                    ｜       37.92亿｜   4.92%｜       10.73亿｜   4.90%｜       27.19亿｜   4.92%｜  71.70%｜\r\n｜北区(地区)                    ｜       78.68亿｜  10.20%｜       24.52亿｜  11.20%｜       54.16亿｜   9.80%｜  68.84%｜\r\n｜总部(地区)                    ｜      419.94亿｜  54.44%｜      122.11亿｜  55.78%｜      297.83亿｜  53.92%｜  70.92%｜\r\n｜境外(地区)                    ｜        4.28亿｜   0.55%｜         1.6亿｜   0.73%｜        2.68亿｜   0.49%｜  62.62%｜\r\n｜合计(地区)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜\r\n\r\n\r\n【截止日期】2023-12-31\r\n\r\n｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜\r\n\r\n｜零售金融业务(行业)            ｜      961.61亿｜  58.39%｜      301.14亿｜  63.16%｜      660.47亿｜  56.44%｜  68.68%｜\r\n｜批发金融业务(行业)            ｜      535.81亿｜  32.53%｜      168.85亿｜  35.42%｜      366.96亿｜  31.36%｜  68.49%｜\r\n｜其他业务(行业)                ｜      149.57亿｜   9.08%｜        6.78亿｜   1.42%｜      142.79亿｜  12.20%｜  95.47%｜\r\n｜合计(行业)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜\r\n\r\n｜零售金融业务(产品)            ｜      961.61亿｜  58.39%｜      301.14亿｜  63.16%｜      660.47亿｜  56.44%｜  68.68%｜\r\n｜批发金融业务(产品)            ｜      535.81亿｜  32.53%｜      168.85亿｜  35.42%｜      366.96亿｜  31.36%｜  68.49%｜\r\n｜其他业务(产品)                ｜      149.57亿｜   9.08%｜        6.78亿｜   1.42%｜      142.79亿｜  12.20%｜  95.47%｜\r\n｜合计(产品)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜\r\n\r\n｜东区(地区)                    ｜      251.11亿｜  15.25%｜       79.88亿｜  16.75%｜      171.23亿｜  14.63%｜  68.19%｜\r\n｜南区(地区)                    ｜      282.29亿｜  17.14%｜       77.89亿｜  16.34%｜       204.4亿｜  17.47%｜  72.41%｜\r\n｜西区(地区)                    ｜       93.39亿｜   5.67%｜       29.63亿｜   6.21%｜       63.76亿｜   5.45%｜  68.27%｜\r\n｜北区(地区)                    ｜      188.53亿｜  11.45%｜       66.28亿｜  13.90%｜      122.25亿｜  10.45%｜  64.84%｜\r\n｜总部(地区)                    ｜      826.79亿｜  50.20%｜      219.83亿｜  46.11%｜      606.96亿｜  51.87%｜  73.41%｜\r\n｜境外(地区)                    ｜        4.88亿｜   0.30%｜        3.26亿｜   0.68%｜        1.62亿｜   0.14%｜  33.20%｜\r\n｜合计(地区)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜\r\n\r\n\r\n'

In [131]:
def parse_to_flat_table(text: str) -> pd.DataFrame:
    """
    将主营构成分析文本转换为扁平化 DataFrame，表头为：
    ['日期', '项目名', '营业收入(元)', '收入比例', '营业成本(元)', '成本比例', '营业利润(元)', '利润比例', '毛利率']
    
    - 日期：来自【截止日期】
    - 项目名：保留原始名称（如“零售金融业务(行业)”）
    - 所有金额单位为元（数值型），比例和毛利率为小数（0~1）
    """
    
    lines = [line.strip() for line in text.splitlines() if line.strip()]
    
    records = []
    current_date = None
    
    def parse_amount(s: str) -> float:
        s = s.replace(',', '').strip()
        if '亿' in s:
            return float(s.replace('亿', '')) * 1e8
        else:
            return float(s)
    
    def parse_percent(s: str) -> float:
        return float(s.replace('%', '')) / 100.0

    i = 0
    while i < len(lines):
        line = lines[i]
        
        # 捕获截止日期
        date_match = re.search(r'【截止日期】(\d{4}-\d{2}-\d{2})', line)
        if date_match:
            current_date = date_match.group(1)
            i += 1
            continue
        
        # 跳过表头行（包含“项目名”或“营业收入”等）
        if '项目名' in line or '营业收入' in line or line.startswith('｜') and any(kw in line for kw in ['收入比例', '成本比例']):
            i += 1
            continue
        
        # 处理数据行：以｜分隔，且包含至少8个数据字段
        if line.startswith('｜') and '｜' in line:
            parts = [p.strip() for p in line.split('｜') if p.strip()]
            # 预期结构：[项目名, 营业收入, 收入比例, 营业成本, 成本比例, 营业利润, 利润比例, 毛利率]
            if len(parts) == 8:
                item_name = parts[0]
                try:
                    record = {
                        '日期': current_date,
                        '项目名': item_name,
                        '营业收入(元)': parse_amount(parts[1]),
                        '收入比例': parse_percent(parts[2]),
                        '营业成本(元)': parse_amount(parts[3]),
                        '成本比例': parse_percent(parts[4]),
                        '营业利润(元)': parse_amount(parts[5]),
                        '利润比例': parse_percent(parts[6]),
                        '毛利率': parse_percent(parts[7])
                    }
                    records.append(record)
                except Exception:
                    pass  # 忽略解析失败的行（如合计行格式异常，但本逻辑已兼容）
        
        i += 1

    df = pd.DataFrame(records, columns=[
        '日期', '项目名',
        '营业收入(元)', '收入比例',
        '营业成本(元)', '成本比例',
        '营业利润(元)', '利润比例',
        '毛利率'
    ])
    
    df['日期'] = pd.to_datetime(df['日期'])
    return df.reset_index(drop=True)

In [132]:
parse_to_flat_table(ff)

,日期,项目名,营业收入(元),收入比例,营业成本(元),成本比例,营业利润(元),利润比例,毛利率
0,2025-06-30,零售金融业务(行业),3.108100e+10,0.4480,1.102400e+10,0.2806,2.005700e+10,0.6663,0.6453
1,2025-06-30,批发金融业务(行业),3.042500e+10,0.4385,8.039000e+09,0.2046,2.238600e+10,0.7437,0.7358
2,2025-06-30,其他业务(行业),7.879000e+09,0.1136,7.700000e+08,0.0196,7.109000e+09,0.2362,0.9023
3,2025-06-30,合计(行业),6.938500e+10,1.0000,3.928300e+10,1.0000,3.010200e+10,1.0000,0.4338
4,2025-06-30,零售金融业务(产品),3.108100e+10,0.4480,1.102400e+10,0.2806,2.005700e+10,0.6663,0.6453
5,2025-06-30,批发金融业务(产品),3.042500e+10,0.4385,8.039000e+09,0.2046,2.238600e+10,0.7437,0.7358
6,2025-06-30,其他业务(产品),7.879000e+09,0.1136,7.700000e+08,0.0196,7.109000e+09,0.2362,0.9023
7,2025-06-30,合计(产品),6.938500e+10,1.0000,3.928300e+10,1.0000,3.010200e+10,1.0000,0.4338
8,2025-06-30,东区(地区),9.588000e+09,0.1382,2.847000e+09,0.0725,6.741000e+09,0.2239,0.7031
9,2025-06-30,南区(地区),1.004300e+10,0.1447,2.834000e+09,0.0721,7.209000e+09,0.2395,0.7178
10,2025-06-30,西区(地区),2.643000e+09,0.0381,1.016000e+09,0.0259,1.627000e+09,0.0540,0.6156
11,2025-06-30,北区(地区),6.404000e+09,0.0923,2.389000e+09,0.0608,4.015000e+09,0.1334,0.6270
12,2025-06-30,总部(地区),4.015200e+10,0.5787,1.061500e+10,0.2702,2.953700e+10,0.9812,0.7356
13,2025-06-30,境外(地区),5.550000e+08,0.0080,1.320000e+08,0.0034,4.230000e+08,0.0141,0.7622
14,2025-06-30,合计(地区),6.938500e+10,1.0000,3.928300e+10,1.0000,3.010200e+10,1.0000,0.4338
15,2024-12-31,批发金融业务(行业),6.384100e+10,0.4352,1.904000e+10,0.4527,4.480100e+10,0.4282,0.7018
16,2024-12-31,零售金融业务(行业),7.125500e+10,0.4857,2.203600e+10,0.5239,4.921900e+10,0.4704,0.6907
17,2024-12-31,其他业务(行业),1.159900e+10,0.0791,9.850000e+08,0.0234,1.061400e+10,0.1014,0.9151
18,2024-12-31,合计(行业),1.466950e+11,1.0000,4.206100e+10,1.0000,1.046340e+11,1.0000,0.7133
19,2024-12-31,批发金融业务(产品),6.384100e+10,0.4352,1.904000e+10,0.4527,4.480100e+10,0.4282,0.7018
20,2024-12-31,零售金融业务(产品),7.125500e+10,0.4857,2.203600e+10,0.5239,4.921900e+10,0.4704,0.6907
21,2024-12-31,其他业务(产品),1.159900e+10,0.0791,9.850000e+08,0.0234,1.061400e+10,0.1014,0.9151
22,2024-12-31,合计(产品),1.466950e+11,1.0000,4.206100e+10,1.0000,1.046340e+11,1.0000,0.7133
23,2024-12-31,东区(地区),2.085400e+10,0.1422,7.521000e+09,0.1788,1.333300e+10,0.1274,0.6393
24,2024-12-31,南区(地区),2.255500e+10,0.1538,6.865000e+09,0.1632,1.569000e+10,0.1500,0.6956
25,2024-12-31,西区(地区),6.742000e+09,0.0460,2.651000e+09,0.0630,4.091000e+09,0.0391,0.6068
26,2024-12-31,北区(地区),1.466400e+10,0.1000,5.830000e+09,0.1386,8.834000e+09,0.0844,0.6024
27,2024-12-31,总部(地区),8.101800e+10,0.5523,1.886000e+10,0.4484,6.215800e+10,0.5941,0.7672
28,2024-12-31,境外(地区),8.620000e+08,0.0059,3.340000e+08,0.0079,5.280000e+08,0.0050,0.6125
29,2024-12-31,合计(地区),1.466950e+11,1.0000,4.206100e+10,1.0000,1.046340e+11,1.0000,0.7133
30,2024-06-30,零售金融业务(行业),3.909100e+10,0.5068,1.244700e+10,0.5686,2.664400e+10,0.4823,0.6816
31,2024-06-30,批发金融业务(行业),3.309600e+10,0.4291,8.766000e+09,0.4004,2.433000e+10,0.4404,0.7351
32,2024-06-30,其他业务(行业),4.945000e+09,0.0641,6.790000e+08,0.0310,4.266000e+09,0.0772,0.8627
33,2024-06-30,合计(行业),7.713200e+10,1.0000,2.189200e+10,1.0000,5.524000e+10,1.0000,0.7162
34,2024-06-30,零售金融业务(产品),3.909100e+10,0.5068,1.244700e+10,0.5686,2.664400e+10,0.4823,0.6816
35,2024-06-30,批发金融业务(产品),3.309600e+10,0.4291,8.766000e+09,0.4004,2.433000e+10,0.4404,0.7351
36,2024-06-30,其他业务(产品),4.945000e+09,0.0641,6.790000e+08,0.0310,4.266000e+09,0.0772,0.8627
37,2024-06-30,合计(产品),7.713200e+10,1.0000,2.189200e+10,1.0000,5.524000e+10,1.0000,0.7162
38,2024-06-30,东区(地区),1.064700e+10,0.1380,3.146000e+09,0.1437,7.501000e+09,0.1358,0.7045
39,2024-06-30,南区(地区),1.240300e+10,0.1608,2.850000e+09,0.1302,9.553000e+09,0.1729,0.7702
40,2024-06-30,西区(地区),3.792000e+09,0.0492,1.073000e+09,0.0490,2.719000e+09,0.0492,0.7170
41,2024-06-30,北区(地区),7.868000e+09,0.1020,2.452000e+09,0.1120,5.416000e+09,0.0980,0.6884
42,2024-06-30,总部(地区),4.199400e+10,0.5444,1.221100e+10,0.5578,2.978300e+10,0.5392,0.7092
43,2024-06-30,境外(地区),4.280000e+08,0.0055,1.600000e+08,0.0073,2.680000e+08,0.0049,0.6262
44,2024-06-30,合计(地区),7.713200e+10,1.0000,2.189200e+10,1.0000,5.524000e+10,1.0000,0.7162
45,2023-12-31,零售金融业务(行业),9.616100e+10,0.5839,3.011400e+10,0.6316,6.604700e+10,0.5644,0.6868
46,2023-12-31,批发金融业务(行业),5.358100e+10,0.3253,1.688500e+10,0.3542,3.669600e+10,0.3136,0.6849
47,2023-12-31,其他业务(行业),1.495700e+10,0.0908,6.780000e+08,0.0142,1.427900e+10,0.1220,0.9547
48,2023-12-31,合计(行业),1.646990e+11,1.0000,4.767700e+10,1.0000,1.170220e+11,1.0000,0.7105
49,2023-12-31,零售金融业务(产品),9.616100e+10,0.5839,3.011400e+10,0.6316,6.604700e+10,0.5644,0.6868
50,2023-12-31,批发金融业务(产品),5.358100e+10,0.3253,1.688500e+10,0.3542,3.669600e+10,0.3136,0.6849
51,2023-12-31,其他业务(产品),1.495700e+10,0.0908,6.780000e+08,0.0142,1.427900e+10,0.1220,0.9547
52,2023-12-31,合计(产品),1.646990e+11,1.0000,4.767700e+10,1.0000,1.170220e+11,1.0000,0.7105
53,2023-12-31,东区(地区),2.511100e+10,0.1525,7.988000e+09,0.1675,1.712300e+10,0.1463,0.6819
54,2023-12-31,南区(地区),2.822900e+10,0.1714,7.789000e+09,0.1634,2.044000e+10,0.1747,0.7241
55,2023-12-31,西区(地区),9.339000e+09,0.0567,2.963000e+09,0.0621,6.376000e+09,0.0545,0.6827
56,2023-12-31,北区(地区),1.885300e+10,0.1145,6.628000e+09,0.1390,1.222500e+10,0.1045,0.6484
57,2023-12-31,总部(地区),8.267900e+10,0.5020,2.198300e+10,0.4611,6.069600e+10,0.5187,0.7341
58,2023-12-31,境外(地区),4.880000e+08,0.0030,3.260000e+08,0.0068,1.620000e+08,0.0014,0.3320
59,2023-12-31,合计(地区),1.646990e+11,1.0000,4.767700e+10,1.0000,1.170220e+11,1.0000,0.7105

In [119]:
ff.replace('─','').splitlines(keepends=False)

['【2.主营构成分析】',
 '【截止日期】2025-06-30',
 '',
 '｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜',
 '',
 '｜零售金融业务(行业)            ｜      310.81亿｜  44.80%｜      110.24亿｜  28.06%｜      200.57亿｜  66.63%｜  64.53%｜',
 '｜批发金融业务(行业)            ｜      304.25亿｜  43.85%｜       80.39亿｜  20.46%｜      223.86亿｜  74.37%｜  73.58%｜',
 '｜其他业务(行业)                ｜       78.79亿｜  11.36%｜         7.7亿｜   1.96%｜       71.09亿｜  23.62%｜  90.23%｜',
 '｜合计(行业)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜',
 '',
 '｜零售金融业务(产品)            ｜      310.81亿｜  44.80%｜      110.24亿｜  28.06%｜      200.57亿｜  66.63%｜  64.53%｜',
 '｜批发金融业务(产品)            ｜      304.25亿｜  43.85%｜       80.39亿｜  20.46%｜      223.86亿｜  74.37%｜  73.58%｜',
 '｜其他业务(产品)                ｜       78.79亿｜  11.36%｜         7.7亿｜   1.96%｜       71.09亿｜  23.62%｜  90.23%｜',
 '｜合计(产品)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜',
 '',
 '｜东区(地区)                    ｜       95.88亿｜  13.82%｜       28.47亿｜   7.25%｜       67.41亿｜  22.39%｜  70.31%｜',
 '｜南区(地区)                    ｜      100.43亿｜  14.47%｜       28.34亿｜   7.21%｜       72.09亿｜  23.95%｜  71.78%｜',
 '｜西区(地区)                    ｜       26.43亿｜   3.81%｜       10.16亿｜   2.59%｜       16.27亿｜   5.40%｜  61.56%｜',
 '｜北区(地区)                    ｜       64.04亿｜   9.23%｜       23.89亿｜   6.08%｜       40.15亿｜  13.34%｜  62.70%｜',
 '｜总部(地区)                    ｜      401.52亿｜  57.87%｜      106.15亿｜  27.02%｜      295.37亿｜  98.12%｜  73.56%｜',
 '｜境外(地区)                    ｜        5.55亿｜   0.80%｜        1.32亿｜   0.34%｜        4.23亿｜   1.41%｜  76.22%｜',
 '｜合计(地区)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜',
 '',
 '',
 '【截止日期】2024-12-31',
 '',
 '｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜',
 '',
 '｜批发金融业务(行业)            ｜      638.41亿｜  43.52%｜       190.4亿｜  45.27%｜      448.01亿｜  42.82%｜  70.18%｜',
 '｜零售金融业务(行业)            ｜      712.55亿｜  48.57%｜      220.36亿｜  52.39%｜      492.19亿｜  47.04%｜  69.07%｜',
 '｜其他业务(行业)                ｜      115.99亿｜   7.91%｜        9.85亿｜   2.34%｜      106.14亿｜  10.14%｜  91.51%｜',
 '｜合计(行业)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜',
 '',
 '｜批发金融业务(产品)            ｜      638.41亿｜  43.52%｜       190.4亿｜  45.27%｜      448.01亿｜  42.82%｜  70.18%｜',
 '｜零售金融业务(产品)            ｜      712.55亿｜  48.57%｜      220.36亿｜  52.39%｜      492.19亿｜  47.04%｜  69.07%｜',
 '｜其他业务(产品)                ｜      115.99亿｜   7.91%｜        9.85亿｜   2.34%｜      106.14亿｜  10.14%｜  91.51%｜',
 '｜合计(产品)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜',
 '',
 '｜东区(地区)                    ｜      208.54亿｜  14.22%｜       75.21亿｜  17.88%｜      133.33亿｜  12.74%｜  63.93%｜',
 '｜南区(地区)                    ｜      225.55亿｜  15.38%｜       68.65亿｜  16.32%｜       156.9亿｜  15.00%｜  69.56%｜',
 '｜西区(地区)                    ｜       67.42亿｜   4.60%｜       26.51亿｜   6.30%｜       40.91亿｜   3.91%｜  60.68%｜',
 '｜北区(地区)                    ｜      146.64亿｜  10.00%｜        58.3亿｜  13.86%｜       88.34亿｜   8.44%｜  60.24%｜',
 '｜总部(地区)                    ｜      810.18亿｜  55.23%｜       188.6亿｜  44.84%｜      621.58亿｜  59.41%｜  76.72%｜',
 '｜境外(地区)                    ｜        8.62亿｜   0.59%｜        3.34亿｜   0.79%｜        5.28亿｜   0.50%｜  61.25%｜',
 '｜合计(地区)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜',
 '',
 '',
 '【截止日期】2024-06-30',
 '',
 '｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜',
 '',
 '｜零售金融业务(行业)            ｜      390.91亿｜  50.68%｜      124.47亿｜  56.86%｜      266.44亿｜  48.23%｜  68.16%｜',
 '｜批发金融业务(行业)            ｜      330.96亿｜  42.91%｜       87.66亿｜  40.04%｜       243.3亿｜  44.04%｜  73.51%｜',
 '｜其他业务(行业)                ｜       49.45亿｜   6.41%｜        6.79亿｜   3.10%｜       42.66亿｜   7.72%｜  86.27%｜',
 '｜合计(行业)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜',
 '',
 '｜零售金融业务(产品)            ｜      390.91亿｜  50.68%｜      124.47亿｜  56.86%｜      266.44亿｜  48.23%｜  68.16%｜',
 '｜批发金融业务(产品)            ｜      330.96亿｜  42.91%｜       87.66亿｜  40.04%｜       243.3亿｜  44.04%｜  73.51%｜',
 '｜其他业务(产品)                ｜       49.45亿｜   6.41%｜        6.79亿｜   3.10%｜       42.66亿｜   7.72%｜  86.27%｜',
 '｜合计(产品)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜',
 '',
 '｜东区(地区)                    ｜      106.47亿｜  13.80%｜       31.46亿｜  14.37%｜       75.01亿｜  13.58%｜  70.45%｜',
 '｜南区(地区)                    ｜      124.03亿｜  16.08%｜        28.5亿｜  13.02%｜       95.53亿｜  17.29%｜  77.02%｜',
 '｜西区(地区)                    ｜       37.92亿｜   4.92%｜       10.73亿｜   4.90%｜       27.19亿｜   4.92%｜  71.70%｜',
 '｜北区(地区)                    ｜       78.68亿｜  10.20%｜       24.52亿｜  11.20%｜       54.16亿｜   9.80%｜  68.84%｜',
 '｜总部(地区)                    ｜      419.94亿｜  54.44%｜      122.11亿｜  55.78%｜      297.83亿｜  53.92%｜  70.92%｜',
 '｜境外(地区)                    ｜        4.28亿｜   0.55%｜         1.6亿｜   0.73%｜        2.68亿｜   0.49%｜  62.62%｜',
 '｜合计(地区)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜',
 '',
 '',
 '【截止日期】2023-12-31',
 '',
 '｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜',
 '',
 '｜零售金融业务(行业)            ｜      961.61亿｜  58.39%｜      301.14亿｜  63.16%｜      660.47亿｜  56.44%｜  68.68%｜',
 '｜批发金融业务(行业)            ｜      535.81亿｜  32.53%｜      168.85亿｜  35.42%｜      366.96亿｜  31.36%｜  68.49%｜',
 '｜其他业务(行业)                ｜      149.57亿｜   9.08%｜        6.78亿｜   1.42%｜      142.79亿｜  12.20%｜  95.47%｜',
 '｜合计(行业)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜',
 '',
 '｜零售金融业务(产品)            ｜      961.61亿｜  58.39%｜      301.14亿｜  63.16%｜      660.47亿｜  56.44%｜  68.68%｜',
 '｜批发金融业务(产品)            ｜      535.81亿｜  32.53%｜      168.85亿｜  35.42%｜      366.96亿｜  31.36%｜  68.49%｜',
 '｜其他业务(产品)                ｜      149.57亿｜   9.08%｜        6.78亿｜   1.42%｜      142.79亿｜  12.20%｜  95.47%｜',
 '｜合计(产品)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜',
 '',
 '｜东区(地区)                    ｜      251.11亿｜  15.25%｜       79.88亿｜  16.75%｜      171.23亿｜  14.63%｜  68.19%｜',
 '｜南区(地区)                    ｜      282.29亿｜  17.14%｜       77.89亿｜  16.34%｜       204.4亿｜  17.47%｜  72.41%｜',
 '｜西区(地区)                    ｜       93.39亿｜   5.67%｜       29.63亿｜   6.21%｜       63.76亿｜   5.45%｜  68.27%｜',
 '｜北区(地区)                    ｜      188.53亿｜  11.45%｜       66.28亿｜  13.90%｜      122.25亿｜  10.45%｜  64.84%｜',
 '｜总部(地区)                    ｜      826.79亿｜  50.20%｜      219.83亿｜  46.11%｜      606.96亿｜  51.87%｜  73.41%｜',
 '｜境外(地区)                    ｜        4.88亿｜   0.30%｜        3.26亿｜   0.68%｜        1.62亿｜   0.14%｜  33.20%｜',
 '｜合计(地区)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜',
 '',
 '']

In [72]:
def extract_main_and_related_data(text):
    import pandas as pd
    import re

    def parse_value(val_str):
        """将带'亿'或数字字符串转为 float（单位：元）"""
        val_str = val_str.strip().replace(',', '')
        if '亿' in val_str:
            num = float(val_str.replace('亿', '')) * 1e8
            return num
        elif val_str == '-':
            return None
        else:
            try:
                return float(val_str)
            except ValueError:
                return None

    def parse_percent(pct_str):
        """解析百分比，如 '98.65%' -> 98.65"""
        pct_str = pct_str.strip()
        if pct_str in ('-', ''):
            return None
        if '%' in pct_str:
            try:
                return float(pct_str.replace('%', ''))
            except:
                return None
        else:
            return float(pct_str)

    # ======================
    # 1. 提取【2.主营构成分析】
    # ======================
    main_section_match = re.search(r'【2\.主营构成分析】\s*(.*?)(?:【3\.|$)', text, re.DOTALL)
    if not main_section_match:
        main_business_dfs = {}
    else:
        main_section = main_section_match.group(1)
        # 按截止日期分割
        date_blocks = re.split(r'【截止日期】(\d{4}-\d{2}-\d{2})', main_section)[1:]
        # date_blocks 是 [date1, block1, date2, block2, ...]
        main_business_dfs = {}

        for i in range(0, len(date_blocks), 2):
            date = date_blocks[i]
            block = date_blocks[i + 1]

            # 提取表格行（跳过表头）
            lines = block.strip().split('\n')
            rows = []
            for line in lines:
                if '│' in line and '项目名' not in line and '合计' not in line:
                    parts = [cell.strip() for cell in line.split('│')[1:-1]]
                    if len(parts) >= 8:
                        project = parts[0]
                        revenue = parse_value(parts[1])
                        rev_ratio = parse_percent(parts[2])
                        cost = parse_value(parts[3])
                        cost_ratio = parse_percent(parts[4])
                        profit = parse_value(parts[5])
                        profit_ratio = parse_percent(parts[6])
                        gross_margin = parse_percent(parts[7])
                        rows.append([project, revenue, rev_ratio, cost, cost_ratio, profit, profit_ratio, gross_margin])

            # 分类：行业、产品、地区
            df = pd.DataFrame(rows, columns=[
                '项目名', '营业收入(元)', '收入比例(%)', '营业成本(元)', '成本比例(%)',
                '营业利润(元)', '利润比例(%)', '毛利率(%)'
            ])

            # 判断类型
            if df['项目名'].str.contains(r'行业\)').any():
                category = '行业'
            elif df['项目名'].str.contains(r'产品\)').any():
                category = '产品'
            elif df['项目名'].str.contains(r'地区\)').any():
                category = '地区'
            else:
                category = '未知'

            # 清理项目名中的 (行业)/(产品)/(地区)
            df['项目名'] = df['项目名'].str.replace(r'\s*\(.*?\)\s*', '', regex=True)

            if date not in main_business_dfs:
                main_business_dfs[date] = {}
            main_business_dfs[date][category] = df

    # ======================
    # 2. 提取【4.关联企业经营状况】
    # ======================
    related_section_match = re.search(r'【4\.关联企业经营状况】\s*【截止日期】(\d{4}-\d{2}-\d{2})\s*(.*?)(?:\n\s*\n|\Z)', text, re.DOTALL)
    related_companies_df = pd.DataFrame()
    if related_section_match:
        cutoff_date = related_section_match.group(1)
        table_lines = related_section_match.group(2).strip().split('\n')
        data_rows = []
        for line in table_lines:
            if re.match(r'^[^\-]*\d+\.?\d*亿', line):
                # 示例：青岛啤酒西安汉斯集团有限公司                         18.9047亿                      6.4671亿                     34.5667亿
                parts = re.split(r'\s{2,}', line.strip())
                if len(parts) >= 4:
                    name = parts[0]
                    revenue = parse_value(parts[1])
                    net_profit = parse_value(parts[2])
                    total_assets = parse_value(parts[3])
                    data_rows.append([name, revenue, net_profit, total_assets, cutoff_date])

        related_companies_df = pd.DataFrame(data_rows, columns=[
            '关联企业名称', '营业收入(元)', '净利润(元)', '总资产(元)', '截止日期'
        ])

    return main_business_dfs, related_companies_df

In [121]:
dd = ff.replace('─','').splitlines(keepends=False)

In [122]:
dd

['【2.主营构成分析】',
 '【截止日期】2025-06-30',
 '',
 '｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜',
 '',
 '｜零售金融业务(行业)            ｜      310.81亿｜  44.80%｜      110.24亿｜  28.06%｜      200.57亿｜  66.63%｜  64.53%｜',
 '｜批发金融业务(行业)            ｜      304.25亿｜  43.85%｜       80.39亿｜  20.46%｜      223.86亿｜  74.37%｜  73.58%｜',
 '｜其他业务(行业)                ｜       78.79亿｜  11.36%｜         7.7亿｜   1.96%｜       71.09亿｜  23.62%｜  90.23%｜',
 '｜合计(行业)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜',
 '',
 '｜零售金融业务(产品)            ｜      310.81亿｜  44.80%｜      110.24亿｜  28.06%｜      200.57亿｜  66.63%｜  64.53%｜',
 '｜批发金融业务(产品)            ｜      304.25亿｜  43.85%｜       80.39亿｜  20.46%｜      223.86亿｜  74.37%｜  73.58%｜',
 '｜其他业务(产品)                ｜       78.79亿｜  11.36%｜         7.7亿｜   1.96%｜       71.09亿｜  23.62%｜  90.23%｜',
 '｜合计(产品)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜',
 '',
 '｜东区(地区)                    ｜       95.88亿｜  13.82%｜       28.47亿｜   7.25%｜       67.41亿｜  22.39%｜  70.31%｜',
 '｜南区(地区)                    ｜      100.43亿｜  14.47%｜       28.34亿｜   7.21%｜       72.09亿｜  23.95%｜  71.78%｜',
 '｜西区(地区)                    ｜       26.43亿｜   3.81%｜       10.16亿｜   2.59%｜       16.27亿｜   5.40%｜  61.56%｜',
 '｜北区(地区)                    ｜       64.04亿｜   9.23%｜       23.89亿｜   6.08%｜       40.15亿｜  13.34%｜  62.70%｜',
 '｜总部(地区)                    ｜      401.52亿｜  57.87%｜      106.15亿｜  27.02%｜      295.37亿｜  98.12%｜  73.56%｜',
 '｜境外(地区)                    ｜        5.55亿｜   0.80%｜        1.32亿｜   0.34%｜        4.23亿｜   1.41%｜  76.22%｜',
 '｜合计(地区)                    ｜      693.85亿｜ 100.00%｜      392.83亿｜ 100.00%｜      301.02亿｜ 100.00%｜  43.38%｜',
 '',
 '',
 '【截止日期】2024-12-31',
 '',
 '｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜',
 '',
 '｜批发金融业务(行业)            ｜      638.41亿｜  43.52%｜       190.4亿｜  45.27%｜      448.01亿｜  42.82%｜  70.18%｜',
 '｜零售金融业务(行业)            ｜      712.55亿｜  48.57%｜      220.36亿｜  52.39%｜      492.19亿｜  47.04%｜  69.07%｜',
 '｜其他业务(行业)                ｜      115.99亿｜   7.91%｜        9.85亿｜   2.34%｜      106.14亿｜  10.14%｜  91.51%｜',
 '｜合计(行业)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜',
 '',
 '｜批发金融业务(产品)            ｜      638.41亿｜  43.52%｜       190.4亿｜  45.27%｜      448.01亿｜  42.82%｜  70.18%｜',
 '｜零售金融业务(产品)            ｜      712.55亿｜  48.57%｜      220.36亿｜  52.39%｜      492.19亿｜  47.04%｜  69.07%｜',
 '｜其他业务(产品)                ｜      115.99亿｜   7.91%｜        9.85亿｜   2.34%｜      106.14亿｜  10.14%｜  91.51%｜',
 '｜合计(产品)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜',
 '',
 '｜东区(地区)                    ｜      208.54亿｜  14.22%｜       75.21亿｜  17.88%｜      133.33亿｜  12.74%｜  63.93%｜',
 '｜南区(地区)                    ｜      225.55亿｜  15.38%｜       68.65亿｜  16.32%｜       156.9亿｜  15.00%｜  69.56%｜',
 '｜西区(地区)                    ｜       67.42亿｜   4.60%｜       26.51亿｜   6.30%｜       40.91亿｜   3.91%｜  60.68%｜',
 '｜北区(地区)                    ｜      146.64亿｜  10.00%｜        58.3亿｜  13.86%｜       88.34亿｜   8.44%｜  60.24%｜',
 '｜总部(地区)                    ｜      810.18亿｜  55.23%｜       188.6亿｜  44.84%｜      621.58亿｜  59.41%｜  76.72%｜',
 '｜境外(地区)                    ｜        8.62亿｜   0.59%｜        3.34亿｜   0.79%｜        5.28亿｜   0.50%｜  61.25%｜',
 '｜合计(地区)                    ｜     1466.95亿｜ 100.00%｜      420.61亿｜ 100.00%｜     1046.34亿｜ 100.00%｜  71.33%｜',
 '',
 '',
 '【截止日期】2024-06-30',
 '',
 '｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜',
 '',
 '｜零售金融业务(行业)            ｜      390.91亿｜  50.68%｜      124.47亿｜  56.86%｜      266.44亿｜  48.23%｜  68.16%｜',
 '｜批发金融业务(行业)            ｜      330.96亿｜  42.91%｜       87.66亿｜  40.04%｜       243.3亿｜  44.04%｜  73.51%｜',
 '｜其他业务(行业)                ｜       49.45亿｜   6.41%｜        6.79亿｜   3.10%｜       42.66亿｜   7.72%｜  86.27%｜',
 '｜合计(行业)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜',
 '',
 '｜零售金融业务(产品)            ｜      390.91亿｜  50.68%｜      124.47亿｜  56.86%｜      266.44亿｜  48.23%｜  68.16%｜',
 '｜批发金融业务(产品)            ｜      330.96亿｜  42.91%｜       87.66亿｜  40.04%｜       243.3亿｜  44.04%｜  73.51%｜',
 '｜其他业务(产品)                ｜       49.45亿｜   6.41%｜        6.79亿｜   3.10%｜       42.66亿｜   7.72%｜  86.27%｜',
 '｜合计(产品)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜',
 '',
 '｜东区(地区)                    ｜      106.47亿｜  13.80%｜       31.46亿｜  14.37%｜       75.01亿｜  13.58%｜  70.45%｜',
 '｜南区(地区)                    ｜      124.03亿｜  16.08%｜        28.5亿｜  13.02%｜       95.53亿｜  17.29%｜  77.02%｜',
 '｜西区(地区)                    ｜       37.92亿｜   4.92%｜       10.73亿｜   4.90%｜       27.19亿｜   4.92%｜  71.70%｜',
 '｜北区(地区)                    ｜       78.68亿｜  10.20%｜       24.52亿｜  11.20%｜       54.16亿｜   9.80%｜  68.84%｜',
 '｜总部(地区)                    ｜      419.94亿｜  54.44%｜      122.11亿｜  55.78%｜      297.83亿｜  53.92%｜  70.92%｜',
 '｜境外(地区)                    ｜        4.28亿｜   0.55%｜         1.6亿｜   0.73%｜        2.68亿｜   0.49%｜  62.62%｜',
 '｜合计(地区)                    ｜      771.32亿｜ 100.00%｜      218.92亿｜ 100.00%｜       552.4亿｜ 100.00%｜  71.62%｜',
 '',
 '',
 '【截止日期】2023-12-31',
 '',
 '｜            项目名            ｜ 营业收入(元) ｜收入比例｜ 营业成本(元) ｜成本比例｜ 营业利润(元) ｜利润比例｜ 毛利率 ｜',
 '',
 '｜零售金融业务(行业)            ｜      961.61亿｜  58.39%｜      301.14亿｜  63.16%｜      660.47亿｜  56.44%｜  68.68%｜',
 '｜批发金融业务(行业)            ｜      535.81亿｜  32.53%｜      168.85亿｜  35.42%｜      366.96亿｜  31.36%｜  68.49%｜',
 '｜其他业务(行业)                ｜      149.57亿｜   9.08%｜        6.78亿｜   1.42%｜      142.79亿｜  12.20%｜  95.47%｜',
 '｜合计(行业)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜',
 '',
 '｜零售金融业务(产品)            ｜      961.61亿｜  58.39%｜      301.14亿｜  63.16%｜      660.47亿｜  56.44%｜  68.68%｜',
 '｜批发金融业务(产品)            ｜      535.81亿｜  32.53%｜      168.85亿｜  35.42%｜      366.96亿｜  31.36%｜  68.49%｜',
 '｜其他业务(产品)                ｜      149.57亿｜   9.08%｜        6.78亿｜   1.42%｜      142.79亿｜  12.20%｜  95.47%｜',
 '｜合计(产品)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜',
 '',
 '｜东区(地区)                    ｜      251.11亿｜  15.25%｜       79.88亿｜  16.75%｜      171.23亿｜  14.63%｜  68.19%｜',
 '｜南区(地区)                    ｜      282.29亿｜  17.14%｜       77.89亿｜  16.34%｜       204.4亿｜  17.47%｜  72.41%｜',
 '｜西区(地区)                    ｜       93.39亿｜   5.67%｜       29.63亿｜   6.21%｜       63.76亿｜   5.45%｜  68.27%｜',
 '｜北区(地区)                    ｜      188.53亿｜  11.45%｜       66.28亿｜  13.90%｜      122.25亿｜  10.45%｜  64.84%｜',
 '｜总部(地区)                    ｜      826.79亿｜  50.20%｜      219.83亿｜  46.11%｜      606.96亿｜  51.87%｜  73.41%｜',
 '｜境外(地区)                    ｜        4.88亿｜   0.30%｜        3.26亿｜   0.68%｜        1.62亿｜   0.14%｜  33.20%｜',
 '｜合计(地区)                    ｜     1646.99亿｜ 100.00%｜      476.77亿｜ 100.00%｜     1170.22亿｜ 100.00%｜  71.05%｜',
 '',
 '']

In [123]:
re.split(r"\s+", dd[1])[-6:]

['【截止日期】2025-06-30']

In [73]:
df1, df2 = extract_main_and_related_data(txtRaw)

In [127]:
df3= getBiz(StockCode , StockName)

In [128]:
df3

Empty DataFrame
Columns: [日期, 项目名, 营业收入(元), 收入比例, 营业成本(元), 成本比例, 营业利润(元), 利润比例, 毛利率, StockCode, StockName]
Index: []

In [75]:
df2

Empty DataFrame
Columns: []
Index: []

In [76]:
df2

Empty DataFrame
Columns: []
Index: []

In [ ]:
raDF[['StockCode','StockName','日期',"项目名","营业收入(元)","收入比例(%)","营业利润(元)","利润比例(%)","毛利率(%)"]].set_index('日期').to_sql('mBiz', eng, if_exists='append')