In [ ]:
import pandas as pd
from sqlalchemy import create_engine

In [ ]:
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
def compare_to_base(df1, df2, key_col='IndexCode', name_col='IndexName'):
    """
    以 df1 为基准，列出与 df2 中 IndexName 不同的记录
    差异类型：
      - '名称不同'：df2 中存在但名称不一致
      - 'df2缺失'：df2 中无此 IndexCode
    """
    # 1. 提取必要列并设置索引（CoW 安全）
    base = df1[[key_col, name_col]].set_index(key_col)
    other = df2[[key_col, name_col]].set_index(key_col)
    
    # 2. 左连接（以 df1 为基准）
    merged = base.join(other, lsuffix='_df1', rsuffix='_df2', how='left')
    
    # 3. 向量化判断差异（.ne() 安全处理 NaN）
    is_diff = merged[f'{name_col}_df1'].ne(merged[f'{name_col}_df2'])
    
    # 4. 仅保留差异项
    diff = merged[is_diff].copy()
    diff['差异类型'] = diff[f'{name_col}_df2'].isna().map({True: 'df2缺失', False: '名称不同'})
    
    # 5. 格式化输出
    result = diff.reset_index()[[key_col, f'{name_col}_df1', f'{name_col}_df2', '差异类型']]
    result.columns = ['IndexCode', 'IndexName_基准', 'IndexName_对比', '差异类型']
    
    # 6. 统计摘要
    total = len(df1)
    diff_cnt = len(result)
    print(f"📊 基准总数: {total} | 差异数量: {diff_cnt} ({diff_cnt/total:.1%})")
    print(f"   • 名称不同: {(result['差异类型'] == '名称不同').sum()} 条")
    print(f"   • df2缺失: {(result['差异类型'] == 'df2缺失').sum()} 条")
    
    return result

In [ ]:
df_AA  = pd.read_excel('/home/ts/app/AiStock/indexAA.xlsx')
df_RAW = pd.read_excel('/home/ts/app/TDXapp/tdxAppData/tdxIndexsRAW.xlsx')

In [ ]:
df_opt = pd.read_sql('optIndexs', engI)

In [ ]:
df_RAW[~df_RAW['IndexCode'].isin(df_opt['IndexCode'])]

In [ ]:
dd =pd.merge(df_opt,df_RAW, left_on='IndexCode', right_on='IndexCode',how='inner')

In [ ]:
df_AA.shape

In [ ]:
pd.merge(df_AA,dd, left_on='IndexCode', right_on='IndexCode',how='inner').sort_values(by='IndexCode')

In [ ]:
compare_to_base()

In [ ]:
df_RAW[df_RAW.duplicated(subset='IndexName', keep=False)].sort_values(by=['IndexName','MarketName']).head(40)

In [ ]:
df_re = compare_to_base(df_AA, df_RAW,key_col='IndexCode',name_col='IndexName')

In [ ]:
df_o = compare_to_base(df_AA, df_opt,key_col='IndexName',name_col='IndexCode')

In [ ]:
df_n = compare_to_base(df_AA, df_RAW,key_col='IndexName',name_col='IndexCode')

In [167]:
compare_to_base(dd, df_RAW,key_col='IndexCode',name_col='IndexName')

📊 基准总数: 176 | 差异数量: 1 (0.6%)
   • 名称不同: 0 条
   • df2缺失: 1 条

   IndexCode IndexName_基准 IndexName_对比   差异类型
0        NaN          NaN          NaN  df2缺失

In [168]:
compare_to_base(dd, df_RAW,key_col='IndexName',name_col='IndexCode')

📊 基准总数: 176 | 差异数量: 11 (6.2%)
   • 名称不同: 10 条
   • df2缺失: 1 条

   IndexCode IndexName_基准 IndexName_对比   差异类型
0       电子50       931461       399281   名称不同
1      沪深300       000300       399300   名称不同
2       金融科技       930986       399699   名称不同
3       绿色电力       931897       399438   名称不同
4       全指金融       932075       000992   名称不同
5       数字经济       931582       399262   名称不同
6       消费电子       931494       980030   名称不同
7     中证1000       000852       399852   名称不同
8      中证500       000905       399905   名称不同
9       中证医药       000933       399933   名称不同
10       NaN          NaN          NaN  df2缺失

In [ ]:
dd_d = compare_to_base(dd, df_RAW,key_col='IndexName',name_col='IndexCode')

📊 基准总数: 176 | 差异数量: 11 (6.2%)
   • 名称不同: 10 条
   • df2缺失: 1 条

In [ ]:
df_n[df_n.duplicated(subset='IndexCode', keep=False)]

In [ ]:
df_AA.shape

In [ ]:
df_AA[df_AA.duplicated(subset='IndexName', keep=False)].sort_values(by='IndexName')

In [ ]:
df_AA.drop_duplicates(subset='IndexCode').shape

In [ ]:
df_o.drop_duplicates(subset="IndexName_对比").shape

In [ ]:
df_RAW[df_RAW['IndexCode'].str.contains('930813')]

In [ ]:
df_RAW[df_RAW['IndexName'].str.contains('消费电子')]

In [ ]:
df_AA[df_AA['IndexName'].str.contains('互联互通')]

In [ ]:
df_opt[df_opt['IndexName'].str.contains('创新药')]

In [ ]:
df_n[:42]

In [ ]:
df_o.head(42)

In [ ]:
df_n[5:].drop_duplicates(subset='IndexCode').shape

In [ ]:
df_n.loc[5:][df_n.loc[5:].duplicated(subset='IndexCode')]

In [142]:
d = df_AA.copy()

In [164]:
dd_d[:10]

  IndexCode IndexName_基准 IndexName_对比  差异类型
0      电子50       399281       931461  名称不同
1     沪深300       399300       000300  名称不同
2      金融科技       399699       930986  名称不同
3      绿色电力       399438       931897  名称不同
4      全指金融       000992       932075  名称不同
5      数字经济       399262       931582  名称不同
6      消费电子       980030       931494  名称不同
7    中证1000       399852       000852  名称不同
8     中证500       399905       000905  名称不同
9      中证医药       399933       000933  名称不同

In [143]:
mask = d['IndexName'].isin(df_n.loc[:40]['IndexCode'])
d.loc[mask, 'IndexCode'] = df_n.loc[:40]['IndexName_对比'].values

In [165]:
dd = d.copy()
mask = dd['IndexName'].isin(dd_d.loc[:10]['IndexCode'])
dd.loc[mask, 'IndexCode'] = dd_d.loc[:40]['IndexName_对比'].values

In [ ]:
df_n.loc[:40].set_index('IndexCode')['IndexName_对比']

In [ ]:
code_map = df_n.loc[:10].set_index('IndexCode')['IndexName_对比']
d['IndexCode'] = (d['IndexName'].map(code_map))
# d['IndexCode'] = d['IndexName'].map(code_map).fillna(d['IndexCode']).astype(d['IndexCode'].dtype)   # 保持 dtype 一致

In [ ]:
d.drop_duplicates(subset='IndexCode')

In [150]:
d[d['IndexName']=='电子50']

,IndexCode,IndexName,产业链,产业分类,核心区分度,市值层级,入选原因
34,399281,电子50,新一代信息技术与数字经济,信息技术,消费电子+半导体设备,电子,1：消费电子复苏+半导体设备国产化；2：苹果链/华为链+半导体设备材料；3：50只中大盘股，...

In [163]:
df_RAW[df_RAW['IndexName']=='消费电子']

,IndexCode,IndexName,Market,MarketName,MarketCode,DP,From,Num,IndexSTL
845,931494,消费电子,EX,ZZ,62,2020-06-12,CS,50.0,主题
1022,980030,消费电子,EX,GZ,102,NaN,tdxApi,50.0,主题

In [155]:
df_AA[df_AA['IndexName']=='金融科技']

,IndexCode,IndexName,产业链,产业分类,核心区分度,市值层级,入选原因
70,930986,金融科技,现代服务业与供应链韧性,现代服务,数字金融基础设施,金融科技,1：数字金融基础设施，支付/征信/风控；2：蚂蚁/腾讯金融科技/银行科技子公司；3：50只中...

In [171]:
dd.to_excel('/home/ts/app/AiStock/indexAAOK.xlsx', index=False)