In [26]:
from sqlalchemy import create_engine
import pandas as pd
import unicodedata
# from tqdm import tqdm
import numpy as np
# from typing import Dict, List, Tuple

# from scipy.stats import zscore
# from scipy.stats.mstats import winsorize

# import plotly.express as px
import plotly.graph_objects as go
# from plotly.subplots import make_subplots
from collections import defaultdict

import warnings
warnings.filterwarnings("ignore")

In [ ]:
engB = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/StockBas')
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
engs = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxStocks')

##### 一、337细分行业产业链分层结构 
* 主产业链（9个）：
高端制造与新质生产力、
新能源与绿色低碳、
新一代信息技术与数字经济、
现代生物与大健康、
现代服务业与供应链韧性、
现代农业与粮食安全、
公用事业与基础保障、
传统优势产业升级、
文化消费与生活服务
* 子产业链（5个）：
建材与建筑、
化工与材料、
交通装备与制造、
内容生产、
生活服务

* 1.1 定义基础产业链信息

In [78]:
industry_to_chain = {
    "股份制银行Ⅲ": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "住宅开发": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "下游"},
    "横向通用软件": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "中游"},
    "商业物业经营": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "轨交设备Ⅲ": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "电池化学品": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "上游"},
    "园林工程": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "中游"},
    "玻璃制造": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "上游"},
    "冰洗": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "钟表珠宝": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "粮油加工": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "中游"},
    "面板": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "消费电子零部件及组装": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "下游"},
    "综合Ⅲ": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "火力发电": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "上游"},
    "医药流通": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "下游"},
    "底盘与发动机系统": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "上游"},
    "商业地产": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "下游"},
    "其他专业工程": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "中游"},
    "IT服务Ⅲ": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "中游"},
    "固废治理": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "中游"},
    "金属制品": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "生猪养殖": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "下游"},
    "锂电池": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "其他建材": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "上游"},
    "物业管理": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "炼油化工": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "铅锌": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "上游"},
    "其他电子Ⅲ": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "通信网络设备及器件": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "上游"},
    "国际工程": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "其他计算机设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "综合环境治理": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "中游"},
    "通信线缆及配套": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "中游"},
    "港口": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "上游"},
    "机场": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "上游"},
    "油品石化贸易": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "航空运输": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "上游"},
    "培训教育": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "贸易Ⅲ": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "化学制剂": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "上游"},
    "风力发电": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "上游"},
    "电视广播Ⅲ": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "工程机械整机": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "光伏辅材": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "上游"},
    "证券Ⅲ": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "空调": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "电网自动化设备": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "水泥制造": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "上游"},
    "血液制品": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "上游"},
    "家电零部件Ⅲ": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "上游"},
    "燃气Ⅲ": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "上游"},
    "锂": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "上游"},
    "机床工具": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "租赁": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "多业态零售": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "粘胶": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "氮肥": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "中游"},
    "中药Ⅲ": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "上游"},
    "酒店": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "高速公路": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "上游"},
    "自然景区": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "大宗用纸": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "基建市政工程": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "中游"},
    "百货": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "垂直应用软件": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "中游"},
    "其他医疗服务": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "下游"},
    "黄金": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "氯碱": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "医院": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "下游"},
    "其他生物制品": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "上游"},
    "地面兵装Ⅲ": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "航运": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "上游"},
    "旅游综合": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "农药": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "中游"},
    "肉制品": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "制冷空调设备": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "资产管理": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "输变电设备": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "照明设备Ⅲ": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "水务及水治理": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "中游"},
    "钛白粉": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "军工电子Ⅲ": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "商用载货车": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "环保设备Ⅲ": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "中游"},
    "动力煤": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "上游"},
    "铁路运输": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "上游"},
    "房产租赁经纪": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "下游"},
    "航空装备Ⅲ": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "信托": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "涂料油墨": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "白酒Ⅲ": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "综合乘用车": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "轮胎轮毂": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "上游"},
    "光伏发电": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "林业Ⅲ": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "上游"},
    "水力发电": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "上游"},
    "广告媒体": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "铝": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "上游"},
    "医美服务": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "下游"},
    "金融控股": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "原材料供应链服务": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "房屋建设Ⅲ": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "中游"},
    "冶钢辅料": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "铜": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "上游"},
    "其他金属新材料": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "被动元件": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "其他石化": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "保健品": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "铁矿石": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "上游"},
    "钨": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "塑料包装": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "营销代理": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "图片媒体": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "纯碱": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "其他化学原料": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "热力服务": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "上游"},
    "车身附件及饰件": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "上游"},
    "汽车经销商": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "下游"},
    "畜禽饲料": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "中游"},
    "特钢Ⅲ": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "板材": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "诊断服务": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "中游"},
    "种子": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "上游"},
    "零食": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "长材": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "大众出版": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "线缆部件及其他": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "中游"},
    "餐饮": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "焦炭Ⅲ": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "棉纺": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "啤酒": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "原料药": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "上游"},
    "汽车综合服务": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "下游"},
    "超市": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "钢铁管材": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "上游"},
    "工程咨询服务Ⅲ": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "锦纶": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "钾肥": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "中游"},
    "磁性材料": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "海洋捕捞": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "其他黑色家电": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "影视动漫制作": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "纸包装": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "光伏加工设备": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "印制电路板": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "上游"},
    "专业连锁Ⅲ": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "煤化工": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "稀土": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "通信应用增值服务": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "中游"},
    "软饮料": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "能源及重型设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "其他专用设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "膜材料": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "上游"},
    "商用载客车": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "其他酒类": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "电能综合服务": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "下游"},
    "其他化学制品": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "其他汽车零部件": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "上游"},
    "通信工程及服务": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "中游"},
    "汽车电子电气系统": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "下游"},
    "复合肥": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "中游"},
    "瓷砖地板": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "上游"},
    "其他农产品加工": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "下游"},
    "摩托车": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "电机Ⅲ": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "涤纶": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "焦煤": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "其他纺织": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "其他多元金融": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "其他小金属": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "油气开采Ⅲ": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "果蔬加工": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "下游"},
    "激光设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "生活用纸": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "炭黑": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "非运动服装": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "其他家居用品": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "预加工食品": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "烘焙食品": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "娱乐用品": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "其他自动化设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "工程机械器件": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "上游"},
    "城商行Ⅲ": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "跨境物流": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "运动服装": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "期货": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "合成树脂": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "印刷包装机械": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "厨房小家电": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "工控设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "印刷": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "非金属材料Ⅲ": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "上游"},
    "数字芯片设计": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "水产饲料": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "中游"},
    "乳品": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "卫浴制品": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "成品家居": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "其他橡胶制品": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "洗护用品": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "下游"},
    "其他化学纤维": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "光学元件": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "上游"},
    "其他通用设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "食品及饲料添加剂": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "中游"},
    "辅料": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "上游"},
    "疫苗": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "上游"},
    "公路货运": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "上游"},
    "特种纸": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "通信终端及配件": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "下游"},
    "纺织服装设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "体外诊断": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "中游"},
    "综合电商": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "厨房电器": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "民爆制品": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "品牌消费电子": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "下游"},
    "磨具磨料": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "装修装饰Ⅲ": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "中游"},
    "纺织化学制品": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "光伏电池组件": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "检测服务": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "仪器仪表": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "人工景区": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "氨纶": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "耐火材料": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "上游"},
    "水产养殖": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "下游"},
    "集成电路封测": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "玻纤制造": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "上游"},
    "学历教育": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "化妆品制造及其他": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "下游"},
    "门户网站": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "文化用品": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "其他运输设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "其他塑料制品": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "半导体材料": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "快递": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "上游"},
    "电工仪器仪表": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "电商服务": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "硅料硅片": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "上游"},
    "钢结构": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "中游"},
    "LED": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "化学工程": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "动物保健Ⅲ": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "中游"},
    "聚氨酯": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "配电设备": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "游戏Ⅲ": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "风电整机": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "水泥制品": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "上游"},
    "油田服务": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "有机硅": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "其他种植业": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "上游"},
    "医疗设备": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "中游"},
    "其他电源设备Ⅲ": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "肉鸡养殖": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "下游"},
    "安防设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "其他专业服务": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "火电设备": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "中游"},
    "防水材料": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "上游"},
    "家纺": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "磷肥及磷化工": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "中游"},
    "跨境电商": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "金融信息服务": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "中游"},
    "其他养殖": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "下游"},
    "改性塑料": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "氟化工": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "公交": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "上游"},
    "楼宇设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "半导体设备": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "管材": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "上游"},
    "金属包装": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "医疗耗材": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "中游"},
    "彩电": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "风电零部件": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "仓储物流": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "上游"},
    "调味发酵品Ⅲ": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "卫浴电器": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "油气及炼化工程": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "农业综合Ⅲ": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "下游"},
    "定制家居": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "蓄电池及其他电池": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "电子化学品Ⅲ": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "电动乘用车": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "下游"},
    "其他家电Ⅲ": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "其他能源发电": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "下游"},
    "胶黏剂及胶带": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "熟食": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "机器人": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "白银": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "线下药店": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "下游"},
    "院线": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "中间产品及消费品供应链服务": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "食用菌": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "下游"},
    "农商行Ⅲ": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "医疗研发外包": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "下游"},
    "航天装备Ⅲ": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "体育Ⅲ": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "农用机械": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "上游"},
    "宠物食品": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "综合包装": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "无机盐": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "上游"},
    "个护小家电": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "大气治理": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "中游"},
    "核力发电": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "上游"},
    "航海装备Ⅲ": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "教育运营及其他": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "分立器件": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "橡胶助剂": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "锂电专用设备": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "教育出版": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "其他通信设备": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "中游"},
    "清洁小家电": {"主产业链": "6、传统优势产业升级", "子产业链": "交通装备与制造", "层级": "中游"},
    "逆变器": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"},
    "视频媒体": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "集成电路制造": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "鞋帽及其他": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "钴": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "上游"},
    "模拟芯片设计": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "中游"},
    "人力资源服务": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "品牌化妆品": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "下游"},
    "会展服务": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "中游"},
    "医美耗材": {"主产业链": "5、现代生物与大健康", "子产业链": None, "层级": "中游"},
    "纺织鞋类制造": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "其他数字媒体": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "电信运营商": {"主产业链": "1、新一代信息技术与数字经济", "子产业链": None, "层级": "中游"},
    "产业地产": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "下游"},
    "其他饰品": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "下游"},
    "印染": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "粮食种植": {"主产业链": "4、现代农业与粮食安全", "子产业链": None, "层级": "上游"},
    "房地产综合服务": {"主产业链": "6、传统优势产业升级", "子产业链": "建材与建筑", "层级": "下游"},
    "综合电力设备商": {"主产业链": "8、公用事业与基础保障", "子产业链": None, "层级": "中游"},
    "国有大型银行Ⅲ": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "保险Ⅲ": {"主产业链": "7、现代服务业与供应链韧性", "子产业链": None, "层级": "下游"},
    "旅游零售Ⅲ": {"主产业链": "9、文化消费与生活服务", "子产业链": "生活服务", "层级": "下游"},
    "钼": {"主产业链": "2、高端制造与新质生产力", "子产业链": None, "层级": "上游"},
    "涂料": {"主产业链": "6、传统优势产业升级", "子产业链": "化工与材料", "层级": "中游"},
    "文字媒体": {"主产业链": "9、文化消费与生活服务", "子产业链": "内容生产", "层级": "下游"},
    "镍": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "上游"},
    "燃料电池": {"主产业链": "3、新能源与绿色低碳", "子产业链": None, "层级": "中游"}
}

* 1.2 定义主产业链权重

In [123]:
main_chain_S = {
    "1、新一代信息技术与数字经济": 1.00,
    "2、高端制造与新质生产力": 0.98,
    "3、新能源与绿色低碳": 0.95,
    "4、现代农业与粮食安全": 0.92,
    "5、现代生物与大健康": 0.90,
    "6、传统优势产业升级": 0.80,
    "7、现代服务业与供应链韧性": 0.82,
    "8、公用事业与基础保障": 0.85,
    "9、文化消费与生活服务": 0.65
}

* 1.3 生成全行业可比、产业链内部也可比的重要性权重

In [124]:
industry_to_chain_weighted = {}

for industry, info in industry_to_chain.items():
    main = info["主产业链"]
    sub = info["子产业链"]
    level = info["层级"]
    
    S = main_chain_S[main]
    R = 0.8  # default fallback

    # —————— 1. 新一代信息技术 ——————
    if "1、新一代信息技术" in main:
        if level == "上游":
            R = 1.00
        elif level == "中游":
            if industry in ["数字芯片设计", "模拟芯片设计", "半导体材料", "光学元件", "印制电路板", "通信网络设备及器件"]:
                R = 0.95
            else:
                R = 0.85
        else:
            R = 0.75

    # —————— 2. 高端制造 ——————
    elif "2、高端制造" in main:
        if level == "上游":
            if industry in ["机床工具", "半导体设备", "激光设备", "稀土", "特钢Ⅲ", "钨", "钼", "冶钢辅料", "黄金", "白银", "磁性材料", "其他金属新材料"]:
                R = 1.00
            else:
                R = 0.95
        elif level == "中游":
            if industry in ["航空装备Ⅲ", "航天装备Ⅲ", "航海装备Ⅲ", "军工电子Ⅲ", "机器人", "工控设备", "检测服务", "仪器仪表", "地面兵装Ⅲ"]:
                R = 0.95
            else:
                R = 0.85
        else:
            R = 0.78

    # —————— 3. 新能源 ——————
    elif "3、新能源" in main:
        if level == "上游":
            R = 1.00
        elif level == "中游":
            if industry in ["锂电池", "光伏电池组件", "逆变器", "风电整机", "燃料电池", "输变电设备", "光伏加工设备", "锂电专用设备"]:
                R = 0.96
            else:
                R = 0.90
        else:
            R = 0.80

    # —————— 4. 现代农业 ——————
    elif "4、现代农业" in main:
        if level == "上游":
            if industry in ["种子", "粮食种植"]:
                R = 1.00
            else:
                R = 0.95
        elif level == "中游":
            R = 0.88
        else:
            R = 0.75

    # —————— 5. 生物健康 ——————
    elif "5、现代生物" in main:
        if level == "上游":
            if industry in ["疫苗", "血液制品", "中药Ⅲ", "辅料"]:
                R = 1.00
            else:
                R = 0.95
        elif level == "中游":
            if industry in ["医疗设备", "体外诊断", "医美耗材"]:
                R = 0.90
            else:
                R = 0.85
        else:
            R = 0.75

    # —————— 6. 传统优势产业 ——————
    elif "6、传统优势产业" in main:
        if sub == "建材与建筑":
            if level == "上游":
                R = 0.95
            elif level == "中游":
                R = 0.85
            else:
                R = 0.70
        elif sub == "交通装备与制造":
            if level == "上游":
                R = 0.92
            elif level == "中游":
                R = 0.85
            else:
                R = 0.70
        elif sub == "化工与材料":
            if level == "上游":
                R = 0.95
            elif level == "中游":
                R = 0.80
            else:
                R = 0.70
        else:
            if level == "上游":
                R = 0.90
            elif level == "中游":
                R = 0.75
            else:
                R = 0.65

    # —————— 7. 现代服务业 ——————
    elif "7、现代服务业" in main:
        if level == "上游":
            R = 0.95
        elif level == "中游":
            if industry in ["跨境物流", "原材料供应链服务", "中间产品及消费品供应链服务", "工程咨询服务Ⅲ"]:
                R = 0.88
            else:
                R = 0.82
        else:
            R = 0.75

    # —————— 8. 公用事业 ——————
    elif "8、公用事业" in main:
        if level == "上游":
            R = 1.00
        else:
            R = 0.90

    # —————— 9. 文化消费 ——————
    elif "9、文化消费" in main:
        if sub == "内容生产":
            R = 0.80
        else:
            R = 0.70

    # 计算最终权重
    W = S * R
    final_weight = max(0.50, round(W, 2))

    industry_to_chain_weighted[industry] = {
        "主产业链": info["主产业链"],
        "子产业链": info["子产业链"],
        "层级": info["层级"],
        "权重": final_weight
    }

* 1.4 定义链结构

In [ ]:
chain_structure = {
    "2、高端制造与新质生产力": {
      "上游": ["半导体材料", "稀土", "钴", "锂", "镍", "钨", "钼", "白银", "特钢Ⅲ", "板材", "长材", "冶钢辅料", "机床工具", "激光设备", "黄金", "磁性材料", "磨具磨料", "其他小金属", "其他金属新材料"],
      "中游": ["半导体设备", "数字芯片设计", "模拟芯片设计", "集成电路制造", "集成电路封测", "机器人", "航空装备Ⅲ", "航天装备Ⅲ", "航海装备Ⅲ", "地面兵装Ⅲ", "工控设备", "仪器仪表", "电工仪器仪表", "电子化学品Ⅲ", "被动元件", "分立器件", "军工电子Ⅲ", "面板", "其他电子Ⅲ", "其他计算机设备", "照明设备Ⅲ", "能源及重型设备", "其他专用设备", "电机Ⅲ", "其他通用设备", "印刷包装机械", "纺织服装设备", "民爆制品", "LED", "安防设备", "楼宇设备", "其他运输设备", "检测服务"],
      "下游": ["品牌消费电子", "消费电子零部件及组装", "通信终端及配件", "汽车电子电气系统"]
    },
    "3、新能源与绿色低碳": {
      "上游": ["锂", "钴", "镍", "硅料硅片", "玻纤制造", "膜材料", "光伏辅材", "钛白粉", "纯碱", "稀土"],
      "中游": ["光伏电池组件", "光伏发电", "风电整机", "风电零部件", "锂电池", "蓄电池及其他电池", "逆变器", "电网自动化设备", "配电设备", "输变电设备", "其他电源设备Ⅲ", "光伏加工设备", "锂电专用设备", "燃料电池"],
      "下游": ["电能综合服务", "电动乘用车", "商用载客车", "其他能源发电"]
    },
    "1、新一代信息技术与数字经济": {
      "上游": ["半导体材料", "光学元件", "通信网络设备及器件", "印制电路板"],
      "中游": ["IT服务Ⅲ", "横向通用软件", "垂直应用软件", "通信工程及服务", "通信应用增值服务", "金融信息服务", "其他通信设备", "电信运营商", "线缆部件及其他"],
      "下游": ["综合电商", "跨境电商", "电商服务", "游戏Ⅲ", "视频媒体", "图片媒体", "门户网站", "其他数字媒体", "文字媒体"]
    },
    "5、现代生物与大健康": {
      "上游": ["原料药", "化学制剂", "中药Ⅲ", "疫苗", "血液制品", "其他生物制品", "辅料"],
      "中游": ["医疗设备", "体外诊断", "诊断服务", "医美耗材", "医疗耗材", "动物保健Ⅲ"],
      "下游": ["医院", "线下药店", "医美服务", "医疗研发外包", "其他医疗服务", "保健品", "洗护用品", "品牌化妆品"]
    },
    "7、现代服务业与供应链韧性": {
      "上游": ["港口", "机场", "铁路运输", "航运", "公路货运", "快递", "仓储物流", "高速公路", "公交"],
      "中游": ["跨境物流", "原材料供应链服务", "中间产品及消费品供应链服务", "产业地产", "商业地产", "物业管理", "工程咨询服务Ⅲ", "其他专业服务", "人力资源服务", "会展服务", "商业物业经营", "租赁", "营销代理"],
      "下游": ["证券Ⅲ", "保险Ⅲ", "信托", "期货", "金融控股", "城商行Ⅲ", "农商行Ⅲ", "国有大型银行Ⅲ", "股份制银行Ⅲ", "多业态零售", "百货", "超市", "专业连锁Ⅲ", "贸易Ⅲ", "资产管理", "其他多元金融"]
    },
    "4、现代农业与粮食安全": {
      "上游": ["种子", "粮食种植", "其他种植业", "林业Ⅲ", "农用机械"],
      "中游": ["畜禽饲料", "水产饲料", "农药", "复合肥", "钾肥", "氮肥", "磷肥及磷化工", "食品及饲料添加剂"],
      "下游": ["生猪养殖", "肉鸡养殖", "水产养殖", "其他养殖", "果蔬加工", "肉制品", "乳品", "零食", "烘焙食品", "预加工食品", "熟食", "食用菌", "其他农产品加工", "宠物食品", "农业综合Ⅲ", "粮油加工"]
    },
    "6、传统优势产业升级": {
      "建材与建筑": {
        "上游": ["水泥制造", "玻璃制造", "瓷砖地板", "防水材料", "耐火材料", "非金属材料Ⅲ", "钢铁管材", "管材", "水泥制品"],
        "中游": ["房屋建设Ⅲ", "钢结构", "装修装饰Ⅲ", "园林工程", "其他专业工程", "基建市政工程"],
        "下游": ["住宅开发", "商业地产", "产业地产", "房产租赁经纪", "房地产综合服务"]
      },
      "化工与材料": {
        "上游": ["氯碱", "纯碱", "钛白粉", "有机硅", "氟化工", "合成树脂", "焦煤", "焦炭Ⅲ", "动力煤", "无机盐", "其他化学原料", "其他石化", "煤化工", "油气开采Ⅲ", "炼油化工"],
        "中游": ["改性塑料", "胶黏剂及胶带", "涂料油墨", "粘胶", "氨纶", "涤纶", "锦纶", "其他化学纤维", "纺织化学制品", "橡胶助剂", "炭黑", "其他橡胶制品", "其他化学制品", "食品及饲料添加剂", "化学工程", "油田服务", "油气及炼化工程", "印染", "聚氨酯"],
        "下游": ["塑料包装", "纸包装", "金属包装", "纺织鞋类制造", "非运动服装", "运动服装", "家纺", "其他家居用品", "成品家居", "定制家居", "其他饰品", "钟表珠宝", "文化用品", "娱乐用品", "生活用纸", "特种纸", "综合包装"]
      },
      "交通装备与制造": {
        "上游": ["底盘与发动机系统", "车身附件及饰件", "轮胎轮毂", "家电零部件Ⅲ", "其他汽车零部件", "工程机械器件"],
        "中游": ["综合乘用车", "电动乘用车", "商用载货车", "商用载客车", "摩托车", "工程机械整机", "空调", "冰洗", "厨房电器", "彩电", "其他黑色家电", "厨房小家电", "个护小家电", "清洁小家电", "卫浴电器", "其他家电Ⅲ", "制冷空调设备"],
        "下游": ["汽车经销商", "汽车综合服务"]
      }
    },
    "8、公用事业与基础保障": {
      "上游": ["火力发电", "水力发电", "风力发电", "光伏发电", "核力发电", "燃气Ⅲ", "热力服务", "动力煤", "铁矿石", "铅锌", "铝", "铜"],
      "中游": ["电网自动化设备", "配电设备", "输变电设备", "水务及水治理", "固废治理", "综合环境治理", "大气治理", "环保设备Ⅲ", "火电设备", "综合电力设备商"],
      "下游": ["电能综合 service", "燃气Ⅲ", "水务及水治理"]
    },
    "9、文化消费与生活服务": {
      "内容生产": ["电视广播Ⅲ", "影视动漫制作", "游戏Ⅲ", "广告媒体", "大众出版", "教育出版", "学历教育", "文字媒体", "图片媒体", "印刷"],
      "线下场景": ["酒店", "旅游综合", "自然景区", "人工景区", "院线", "餐饮", "百货", "超市", "专业连锁Ⅲ", "培训教育", "教育运营及其他", "体育Ⅲ", "医院", "医美服务", "软饮料", "啤酒", "其他酒类", "白酒Ⅲ", "旅游零售Ⅲ"]
    }
  }

* 查看叶子

In [ ]:
len(industry_to_chain)

In [ ]:
len(chain_structure)

In [ ]:
set(item["主产业链"] for item in industry_to_chain.values())

In [ ]:
set(item["子产业链"] for item in industry_to_chain.values() if item["子产业链"] is not None)

##### 二、 获取分析数据

* 2.1 获取数据

In [ ]:
BizRAW = pd.read_sql('mBiz', engB)
StockList = pd.read_sql('StocksList', engs)[['code','name']]
StockIC = pd.read_sql('swStockIC', engB)
xqStockBas = pd.read_sql('xqStockBas', engB)[['StockCode','52周最高', '52周最低', '均价', '资产净值/总市值', '市净率','市盈率(静)','市盈率(TTM)', '市盈率(动)', '股息率(TTM)', '时间']]

* 2.2 各股申万分类与时点数据融合

In [ ]:
biz_tmp = BizRAW[(~BizRAW['分类类型'].astype(str).str.contains(('按地区分类')))].reset_index(drop=True)

fin_biz = biz_tmp.sort_values(by=['报告日期','收入比例'], ascending=False).drop_duplicates(subset='StockCode',keep='first').sort_values(by='StockCode', ascending=True).drop(columns='分类类型').reset_index(drop=True)

df_merg = pd.merge(StockIC,fin_biz,on='StockCode', how='left')
df_merg = df_merg.merge(xqStockBas, how='inner', left_on='StockCode', right_on='StockCode')

* 2.3 查看数据

In [ ]:
len(StockIC)

In [ ]:
BizRAW.drop_duplicates(subset='StockCode').shape

In [ ]:
biz_tmp.drop_duplicates(subset='StockCode').shape

#### 三、股指

* 3.1 产业链-股指

* 3.1.1 全市场风格

In [138]:
industry_chain_index_market = {
    "综合与规模指数（全市场基准）": [
        {"IndexCode": "000001", "IndexName": "上证指数", "components": 2235, "launch_date": "1991-07-15"},
        {"IndexCode": "000300", "IndexName": "沪深300", "components": 300, "launch_date": "2005-04-08"},
        {"IndexCode": "000852", "IndexName": "中证1000", "components": 1000, "launch_date": "2014-10-17"},
        {"IndexCode": "000903", "IndexName": "中证A100", "components": 100, "launch_date": "2006-05-29"},
        {"IndexCode": "000905", "IndexName": "中证500", "components": 500, "launch_date": "2007-01-15"},
        {"IndexCode": "000906", "IndexName": "中证800", "components": 800, "launch_date": "2007-01-15"},
        {"IndexCode": "399001", "IndexName": "深证成指", "components": 500, "launch_date": "1995-01-23"},
        {"IndexCode": "399006", "IndexName": "创业板指", "components": 100, "launch_date": "2010-06-01"},
        {"IndexCode": "399015", "IndexName": "中小创新", "components": 500, "launch_date": "2015-03-24"},
        {"IndexCode": "399101", "IndexName": "中小综指", "components": 0, "launch_date": "2005-12-01"},
        {"IndexCode": "399303", "IndexName": "国证2000", "components": 2000, "launch_date": "2014-03-28"},
        {"IndexCode": "399673", "IndexName": "创业板50", "components": 50, "launch_date": "2014-06-18"},
        {"IndexCode": "000688", "IndexName": "科创50", "components": 50, "launch_date": "2020-07-23"},
        {"IndexCode": "000698", "IndexName": "科创100", "components": 100, "launch_date": "2023-08-07"},
        {"IndexCode": "000699", "IndexName": "科创200", "components": 200, "launch_date": "2024-08-20"},
        {"IndexCode": "932000", "IndexName": "中证2000", "components": 2000, "launch_date": "2023-08-11"},
        {"IndexCode": "399850", "IndexName": "深证50", "components": 50, "launch_date": "2023-10-18"},
        {"IndexCode": "000155", "IndexName": "市值百强", "components": 100, "launch_date": "2012-07-20"},
        {"IndexCode": "930050", "IndexName": "中证A50", "components": 50, "launch_date": "2024-01-02"}
    ],
    "风格与策略指数（市场状态判断）": [
        {"IndexCode": "000028", "IndexName": "180成长", "components": 60, "launch_date": "2009-01-09"},
        {"IndexCode": "000029", "IndexName": "180价值", "components": 60, "launch_date": "2009-01-09"},
        {"IndexCode": "000057", "IndexName": "全指成长", "components": 150, "launch_date": "2010-01-04"},
        {"IndexCode": "000058", "IndexName": "全指价值", "components": 150, "launch_date": "2010-01-04"},
        {"IndexCode": "399626", "IndexName": "中创成长", "components": 166, "launch_date": "2011-08-15"},
        {"IndexCode": "399627", "IndexName": "中创价值", "components": 166, "launch_date": "2011-08-15"},
        {"IndexCode": "399661", "IndexName": "深证低波", "components": 100, "launch_date": "2012-12-20"},
        {"IndexCode": "399662", "IndexName": "深证高贝", "components": 100, "launch_date": "2012-12-20"},
        {"IndexCode": "931476", "IndexName": "ESG 120策略", "components": 120, "launch_date": "2020-04-30"},
        {"IndexCode": "932365", "IndexName": "中证现金流", "components": 100, "launch_date": "2024-12-11"},
        {"IndexCode": "932366", "IndexName": "300现金流", "components": 50, "launch_date": "2024-11-12"},
        {"IndexCode": "932367", "IndexName": "500现金流", "components": 50, "launch_date": "2024-11-12"},
        {"IndexCode": "932368", "IndexName": "800现金流", "components": 50, "launch_date": "2024-12-11"}
    ],
    "红利与收益质量策略": [
        {"IndexCode": "000015", "IndexName": "红利指数", "components": 50, "launch_date": "2005-01-04"},
        {"IndexCode": "000922", "IndexName": "中证红利", "components": 100, "launch_date": "2008-05-26"},
        {"IndexCode": "000925", "IndexName": "基本面50", "components": 50, "launch_date": "2009-02-26"},
        {"IndexCode": "930838", "IndexName": "CS高股息", "components": 100, "launch_date": "2016-06-08"},
        {"IndexCode": "931373", "IndexName": "股息龙头", "components": 26, "launch_date": "2019-11-15"},
        {"IndexCode": "932315", "IndexName": "中证红利质量", "components": 50, "launch_date": "2024-07-08"},
        {"IndexCode": "932308", "IndexName": "红利200", "components": 200, "launch_date": "2024-06-28"}
    ]
}

* 3.1.2 主链

In [139]:
industry_chain_index_main = {
    "2、高端制造与新质生产力": {
        "上游": {
            "primary": {
                "index_code": "930632",
                "index_name": "CS稀金属",
                "components": 50,
                "launch_date": "2015-05-12",
                "rationale": "覆盖稀土/钨钼/钴锂等战略金属，2015年发布，成分股50只，权威性强；与细分有色(000811)形成互补（稀金属聚焦小金属，细分有色覆盖大宗有色金属）"
            },
            "alternative": ["000811"]  # 细分有色
        },
        "中游": {
            "primary": {
                "index_code": "931865",
                "index_name": "中证半导",
                "components": 40,
                "launch_date": "2019-03-20",
                "rationale": "覆盖设计-制造-封测全产业链，A股半导体核心标的；与电子(930652)区分明确（半导体聚焦芯片，电子覆盖整机组装）"
            },
            "secondary": {
                "index_code": "930820",
                "index_name": "CS高端制",
                "components": 500,
                "launch_date": "2016-05-11",
                "rationale": "覆盖工业母机/激光设备/机器人等高端装备，成分股500只代表性强；与半导体形成'核心器件→整机制造'互补"
            },
            "tertiary": {
                "index_code": "930652",
                "index_name": "CS电子",
                "components": 100,
                "launch_date": "2015-06-05",
                "rationale": "覆盖消费电子零部件及组装，100只成分股；与半导体指数区分度高（应用层vs器件层）"
            }
        },
        "下游": {
            "primary": {
                "index_code": "931494",
                "index_name": "消费电子",
                "components": 50,
                "launch_date": "2020-06-12",
                "rationale": "聚焦品牌消费电子终端，50只成分股；与CS电子(930652)形成'零部件→整机'链条区分"
            }
        }
    },
    "3、新能源与绿色低碳": {
        "上游": {
            "primary": {
                "index_code": "000961",
                "index_name": "中证上游",
                "components": 50,
                "launch_date": "2010-04-16",
                "rationale": "覆盖锂钴镍等新能源金属+传统资源，2010年发布历史最长；成分股50只流动性佳；与稀有金属(930632)区分（上游资源含煤炭石油，稀金属纯新能源金属）"
            }
        },
        "中游": {
            "primary": {
                "index_code": "931151",
                "index_name": "光伏产业",
                "components": 50,
                "launch_date": "2019-04-22",
                "rationale": "硅料-硅片-电池-组件全覆盖，50只成分股；与新能源(000941)区分明确（光伏聚焦发电端，新能源含风电/核电等多能互补）"
            },
            "secondary": {
                "index_code": "931746",
                "index_name": "储能产业",
                "components": 50,
                "launch_date": "2015-06-11",
                "rationale": "锂电池+储能系统全覆盖，2015年发布周期验证充分；与新能源车(930997)区分（储能聚焦电网侧/发电侧，新能源车聚焦交通应用）"
            },
            "tertiary": {
                "index_code": "000941",
                "index_name": "新能源",
                "components": 50,
                "launch_date": "2009-10-28",
                "rationale": "风光水核多能互补，2009年发布历史最久；作为中游综合配置标的"
            }
        },
        "下游": {
            "primary": {
                "index_code": "930997",
                "index_name": "新能源车",
                "components": 50,
                "launch_date": "2017-07-19",
                "rationale": "整车+三电系统全覆盖，50只成分股；与汽车指数(931008)形成'新能源→传统车'互补（新能源车纯电/混动，汽车指数含40%传统燃油车）"
            }
        }
    },
    "1、新一代信息技术与数字经济": {
        "上游": {
            "primary": {
                "index_code": "931160",
                "index_name": "通信设备",
                "components": 50,
                "launch_date": "2013-07-15",
                "rationale": "覆盖光模块/基站/天线等硬件，50只成分股；2013年发布周期验证充分；与半导体(931865)形成'通信芯片→通信设备'互补"
            }
        },
        "中游": {
            "primary": {
                "index_code": "930601",
                "index_name": "中证软件",
                "components": 30,
                "launch_date": "2015-03-10",
                "rationale": "通用+垂直软件全覆盖，30只成分股（软件行业龙头集中度高，30只已覆盖90%市值）；与通信技术(931144)区分（软件聚焦应用层，通信技术聚焦5G/6G基础设施）"
            },
            "secondary": {
                "index_code": "931144",
                "index_name": "通信技术",
                "components": 51,
                "launch_date": "2019-05-30",
                "rationale": "5G/6G+物联网通信技术，51只成分股；与通信设备(931160)形成'硬件→技术标准'互补"
            }
        },
        "下游": {
            "primary": {
                "index_code": "H30535",
                "index_name": "互联网",
                "components": 50,
                "launch_date": "2015-01-12",
                "rationale": "电商+平台经济核心标的，50只成分股；与传媒(399971)区分（互联网聚焦线上平台，传媒聚焦内容生产）"
            }
        }
    },
    "5、现代生物与大健康": {
        "上游": {
            "primary": {
                "index_code": "931152",
                "index_name": "CS创新药",
                "components": 50,
                "launch_date": "2019-04-22",
                "rationale": "创新药研发企业全覆盖，50只成分股；与中药(930641)区分（创新药聚焦化学/生物药，中药聚焦传统医药）"
            }
        },
        "中游": {
            "primary": {
                "index_code": "000933",
                "index_name": "中证医药",
                "components": 80,
                "launch_date": "2009-07-03",
                "rationale": "化学药+生物制品+医疗器械全覆盖，80只成分股，2009年发布历史最久；作为医药制造核心配置"
            }
        },
        "下游": {
            "primary": {
                "index_code": "399989",
                "index_name": "中证医疗",
                "components": 50,
                "launch_date": "2014-10-31",
                "rationale": "医院+医疗服务+药店纯服务端标的，50只成分股；与医药(000933)形成'制造→服务'清晰区分"
            }
        }
    },
    "7、现代服务业与供应链韧性": {
        "上游": {
            "primary": {
                "index_code": "930608",
                "index_name": "中证基建",
                "components": 50,
                "launch_date": "2015-03-31",
                "rationale": "港口/机场/铁路等基础设施，50只成分股；2015年发布周期验证充分"
            }
        },
        "中游": {
            "primary": {
                "index_code": "930716",
                "index_name": "CS物流",
                "components": 50,
                "launch_date": "2015-07-31",
                "rationale": "仓储+快递+供应链服务，50只成分股；与基建(930608)形成'硬件→流通'互补"
            }
        },
        "下游": {
            "primary": {
                "index_code": "932075",
                "index_name": "全指金融",
                "components": 50,
                "launch_date": "2023-03-13",
                "rationale": "银行+证券+保险全覆盖，50只成分股；2023年整合发布，替代细分金融指数避免重叠"
            },
            "secondary": {
                "index_code": "000942",
                "index_name": "内地消费",
                "components": 50,
                "launch_date": "2009-10-28",
                "rationale": "百货/超市/专业连锁全覆盖，2009年发布历史久；作为零售终端配置（与文化消费领域共享，体现产业交叉性）"
            }
        }
    },
    "4、现代农业与粮食安全": {
        "上游": {
            "primary": {
                "index_code": "000949",
                "index_name": "中证农业",
                "components": 50,
                "launch_date": "2009-10-28",
                "rationale": "种子+种植业核心标的，50只成分股，2009年发布历史最久"
            }
        },
        "中游": {
            "primary": {
                "index_code": "931778",
                "index_name": "农牧主题",
                "components": 50,
                "launch_date": "2017-07-21",
                "rationale": "饲料+农药+化肥全覆盖，50只成分股；与农业(000949)形成'种植→农资'区分"
            }
        },
        "下游": {
            "primary": {
                "index_code": "000807",
                "index_name": "食品饮料",
                "components": 50,
                "launch_date": "2012-02-17",
                "rationale": "养殖+食品加工全覆盖，50只成分股；2012年发布周期验证充分；与细分食品(000815)区分（食品饮料含酒类，细分食品纯食品加工）"
            }
        }
    },
    "6、传统优势产业升级": {
        "建材与建筑": {
            "上游": {
                "primary": {
                    "index_code": "931009",
                    "index_name": "建筑材料",
                    "components": 41,
                    "launch_date": "2013-07-15",
                    "rationale": "水泥+玻璃+陶瓷全覆盖，41只成分股；2013年发布周期验证充分"
                }
            },
            "中游": {
                "primary": {
                    "index_code": "930608",
                    "index_name": "中证基建",
                    "components": 50,
                    "launch_date": "2015-03-31",
                    "rationale": "房屋建设+专业工程全覆盖；与服务业上游共享，体现产业链关联性"
                }
            },
            "下游": {
                "primary": {
                    "index_code": "932076",
                    "index_name": "全指地产",
                    "components": 50,
                    "launch_date": "2023-03-13",
                    "rationale": "住宅+商业地产全覆盖，50只成分股；2023年整合发布替代传统地产指数"
                }
            }
        },
        "化工与材料": {
            "全链条": {
                "primary": {
                    "index_code": "000813",
                    "index_name": "细分化工",
                    "components": 50,
                    "launch_date": "2012-04-11",
                    "rationale": "基础化工+精细化工全覆盖，50只成分股；2012年发布周期验证充分；避免过度细分（不单独配置氯碱/纯碱等子类）"
                }
            }
        },
        "交通装备与制造": {
            "全链条": {
                "primary": {
                    "index_code": "931008",
                    "index_name": "汽车指数",
                    "components": 50,
                    "launch_date": "2013-07-15",
                    "rationale": "传统车+新能源车全覆盖，50只成分股；2013年发布周期验证充分；与新能源车(930997)形成'传统+新兴'互补配置"
                }
            }
        }
    },
    "8、公用事业与基础保障": {
        "全链条": {
            "primary": {
                "index_code": "932086",
                "index_name": "全指公用",
                "components": 103,
                "launch_date": "2023-03-13",
                "rationale": "水/电/气/热全覆盖，103只成分股代表性强；2023年整合发布替代传统公用事业指数"
            },
            "secondary": {
                "index_code": "931897",
                "index_name": "绿色电力",
                "components": 50,
                "launch_date": "2012-12-21",
                "rationale": "风光水核清洁能源，50只成分股；2012年发布周期验证充分；与全指公用形成'传统保障→绿色转型'双轨配置"
            }
        }
    },
    "9、文化消费与生活服务": {
        "内容生产": {
            "primary": {
                "index_code": "399971",
                "index_name": "中证传媒",
                "components": 50,
                "launch_date": "2014-04-15",
                "rationale": "影视+游戏+广告全覆盖，50只成分股；2014年发布周期验证充分；与互联网(H30535)区分（传媒聚焦内容生产，互联网聚焦平台分发）"
            }
        },
        "线下场景": {
            "primary": {
                "index_code": "000942",
                "index_name": "内地消费",
                "components": 50,
                "launch_date": "2009-10-28",
                "rationale": "旅游/餐饮/零售等线下消费场景，50只成分股；与服务业下游共享，体现'内容→场景'产业联动"
            }
        }
    },
    # 核心规模基准（跨产业链配置）
    "基准指数": {
        "大盘": {
            "index_code": "000300",
            "index_name": "沪深300",
            "components": 300,
            "launch_date": "2005-04-08",
            "rationale": "全市场龙头基准，2005年发布历史最久，覆盖各产业链核心标的"
        },
        "中盘": {
            "index_code": "000905",
            "index_name": "中证500",
            "components": 500,
            "launch_date": "2007-01-15",
            "rationale": "中型企业代表，与300形成互补，2007年发布周期验证充分"
        },
        "小盘": {
            "index_code": "000852",
            "index_name": "中证1000",
            "components": 1000,
            "launch_date": "2014-10-17",
            "rationale": "小企业+专精特新，2014年发布覆盖完整牛熊周期"
        },
        "微盘": {
            "index_code": "932000",
            "index_name": "中证2000",
            "components": 2000,
            "launch_date": "2023-08-11",
            "rationale": "小微企业+专精特新，2014年发布覆盖完整牛熊周期"
        }
    }
}

* 3.1.3 细分

In [172]:
industry_to_index_standardized_300 = {
    "横向通用软件": [
        {"IndexCode": "930601", "IndexName": "中证软件", "components": 30, "launch_date": "2015-03-10"},
        {"IndexCode": "H30202", "IndexName": "软件指数", "components": 50, "launch_date": "2013-07-15"}
    ],
    "IT服务Ⅲ": [
        {"IndexCode": "930601", "IndexName": "中证软件", "components": 30, "launch_date": "2015-03-10"}
    ],
    "通信网络设备及器件": [
        {"IndexCode": "000040", "IndexName": "上证电信", "components": 30, "launch_date": "2009-01-09"},
        {"IndexCode": "000916", "IndexName": "300通信", "components": 14, "launch_date": "2007-07-02"},
        {"IndexCode": "399994", "IndexName": "信息安全", "components": 63, "launch_date": "2015-03-12"},
        {"IndexCode": "H30184", "IndexName": "半导体", "components": 84, "launch_date": "2013-07-15"}
    ],
    "通信线缆及配套": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "垂直应用软件": [
        {"IndexCode": "930601", "IndexName": "中证软件", "components": 30, "launch_date": "2015-03-10"}
    ],
    "线缆部件及其他": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "印制电路板": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "光学元件": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "金融信息服务": [
        {"IndexCode": "930986", "IndexName": "金融科技", "components": 57, "launch_date": "2017-06-22"}
    ],
    "通信工程及服务": [
        {"IndexCode": "399693", "IndexName": "安防产业", "components": 50, "launch_date": "2016-06-20"}
    ],
    "电信运营商": [
        {"IndexCode": "000040", "IndexName": "上证电信", "components": 30, "launch_date": "2009-01-09"}
    ],
    "其他通信设备": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],

    # 高端制造与新质生产力
    "轨交设备Ⅲ": [
        {"IndexCode": "399965", "IndexName": "800地产", "components": 13, "launch_date": "2014-04-04"},
        {"IndexCode": "931293", "IndexName": "轨交设备", "components": 33, "launch_date": "2013-07-15"}
    ],
    "面板": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "消费电子零部件及组装": [
        {"IndexCode": "931494", "IndexName": "消费电子", "components": 50, "launch_date": "2020-06-12"}
    ],
    "金属制品": [
        {"IndexCode": "000819", "IndexName": "有色金属", "components": 50, "launch_date": "2012-05-09"},
        {"IndexCode": "H30059", "IndexName": "AMAC有色", "components": 82, "launch_date": "2013-01-21"}
    ],
    "其他电子Ⅲ": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "其他计算机设备": [
        {"IndexCode": "H30065", "IndexName": "AMAC电气", "components": 300, "launch_date": "2013-01-21"}
    ],
    "机床工具": [
        {"IndexCode": "931866", "IndexName": "中证机床", "components": 50, "launch_date": "2022-05-09"}
    ],
    "其他金属新材料": [
        {"IndexCode": "930598", "IndexName": "稀土产业", "components": 42, "launch_date": "2015-03-02"},
        {"IndexCode": "930632", "IndexName": "CS稀金属", "components": 50, "launch_date": "2015-05-12"}
    ],
    "被动元件": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "地面兵装Ⅲ": [
        {"IndexCode": "931066", "IndexName": "军工龙头", "components": 30, "launch_date": "2018-02-05"},
        {"IndexCode": "399967", "IndexName": "中证军工", "components": 80, "launch_date": "2013-12-26"}
    ],
    "军工电子Ⅲ": [
        {"IndexCode": "931066", "IndexName": "军工龙头", "components": 30, "launch_date": "2018-02-05"}
    ],
    "照明设备Ⅲ": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "航空装备Ⅲ": [
        {"IndexCode": "931066", "IndexName": "军工龙头", "components": 30, "launch_date": "2018-02-05"}
    ],
    "特钢Ⅲ": [
        {"IndexCode": "000819", "IndexName": "有色金属", "components": 50, "launch_date": "2012-05-09"}
    ],
    "板材": [
        {"IndexCode": "H30058", "IndexName": "AMAC钢铁", "components": 29, "launch_date": "2013-01-21"}
    ],
    "长材": [
        {"IndexCode": "H30058", "IndexName": "AMAC钢铁", "components": 29, "launch_date": "2013-01-21"}
    ],
    "海洋捕捞": [
        {"IndexCode": "881116", "IndexName": "渔业", "components": 7, "launch_date": "2025-09-09"}
    ],
    "其他黑色家电": [
        {"IndexCode": "881187", "IndexName": "黑色家电", "components": 10, "launch_date": "2025-09-09"}
    ],
    "能源及重型设备": [
        {"IndexCode": "930599", "IndexName": "中证高装", "components": 200, "launch_date": "2015-03-02"}
    ],
    "其他专用设备": [
        {"IndexCode": "881313", "IndexName": "自动化设备", "components": 72, "launch_date": "2025-09-09"}
    ],
    "电机Ⅲ": [
        {"IndexCode": "881261", "IndexName": "电机制造", "components": 26, "launch_date": "2025-09-09"}
    ],
    "其他自动化设备": [
        {"IndexCode": "881313", "IndexName": "自动化设备", "components": 72, "launch_date": "2025-09-09"}
    ],
    "印刷包装机械": [
        {"IndexCode": "881310", "IndexName": "工程机械", "components": 32, "launch_date": "2025-09-09"}
    ],
    "工控设备": [
        {"IndexCode": "881313", "IndexName": "自动化设备", "components": 72, "launch_date": "2025-09-09"}
    ],
    "数字芯片设计": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "其他通用设备": [
        {"IndexCode": "881294", "IndexName": "通用设备", "components": 247, "launch_date": "2025-09-09"}
    ],
    "民爆制品": [
        {"IndexCode": "881310", "IndexName": "工程机械", "components": 32, "launch_date": "2025-09-09"}
    ],
    "品牌消费电子": [
        {"IndexCode": "931494", "IndexName": "消费电子", "components": 50, "launch_date": "2020-06-12"}
    ],
    "磨具磨料": [
        {"IndexCode": "881087", "IndexName": "金属新材料", "components": 30, "launch_date": "2025-09-09"}
    ],
    "检测服务": [
        {"IndexCode": "881241", "IndexName": "医疗器械", "components": 97, "launch_date": "2025-09-09"}
    ],
    "仪器仪表": [
        {"IndexCode": "881333", "IndexName": "元器件", "components": 62, "launch_date": "2025-09-09"}
    ],
    "氨纶": [
        {"IndexCode": "881019", "IndexName": "化纤", "components": 31, "launch_date": "2025-09-09"}
    ],
    "集成电路封测": [
        {"IndexCode": "932087", "IndexName": "集成电路", "components": 81, "launch_date": "2023-03-29"}
    ],
    "电工仪器仪表": [
        {"IndexCode": "881333", "IndexName": "元器件", "components": 62, "launch_date": "2025-09-09"}
    ],
    "LED": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "安防设备": [
        {"IndexCode": "399693", "IndexName": "安防产业", "components": 50, "launch_date": "2016-06-20"}
    ],
    "楼宇设备": [
        {"IndexCode": "881352", "IndexName": "IT设备", "components": 65, "launch_date": "2025-09-09"}
    ],
    "半导体设备": [
        {"IndexCode": "931743", "IndexName": "半导体材料设备", "components": 40, "launch_date": "2012-12-21"}
    ],
    "彩电": [
        {"IndexCode": "881187", "IndexName": "黑色家电", "components": 10, "launch_date": "2025-09-09"}
    ],
    "机器人": [
        {"IndexCode": "399283", "IndexName": "机器人50", "components": 50, "launch_date": "2020-02-18"},
        {"IndexCode": "H30590", "IndexName": "机器人", "components": 73, "launch_date": "2015-02-10"}
    ],
    "白银": [
        {"IndexCode": "881075", "IndexName": "贵金属", "components": 12, "launch_date": "2025-09-09"}
    ],
    "航天装备Ⅲ": [
        {"IndexCode": "931066", "IndexName": "军工龙头", "components": 30, "launch_date": "2018-02-05"}
    ],
    "航海装备Ⅲ": [
        {"IndexCode": "932420", "IndexName": "智选船舶产业", "components": 39, "launch_date": "2025-05-28"}
    ],
    "分立器件": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "模拟芯片设计": [
        {"IndexCode": "931865", "IndexName": "中证半导", "components": 40, "launch_date": "2019-03-20"}
    ],
    "集成电路制造": [
        {"IndexCode": "932087", "IndexName": "集成电路", "components": 81, "launch_date": "2023-03-29"}
    ],
    "冶钢辅料": [
        {"IndexCode": "881062", "IndexName": "冶钢原料", "components": 8, "launch_date": "2025-09-09"}
    ],
    "磁性材料": [
        {"IndexCode": "881087", "IndexName": "金属新材料", "components": 30, "launch_date": "2025-09-09"}
    ],
    "钨": [
        {"IndexCode": "881078", "IndexName": "能源金属", "components": 17, "launch_date": "2025-09-09"}
    ],
    "钼": [
        {"IndexCode": "881078", "IndexName": "能源金属", "components": 17, "launch_date": "2025-09-09"}
    ],
    "黄金": [
        {"IndexCode": "881075", "IndexName": "贵金属", "components": 12, "launch_date": "2025-09-09"}
    ],
    "稀土": [
        {"IndexCode": "930598", "IndexName": "稀土产业", "components": 42, "launch_date": "2015-03-02"}
    ],
    "半导体材料": [
        {"IndexCode": "931743", "IndexName": "半导体材料设备", "components": 40, "launch_date": "2012-12-21"}
    ],
    "激光设备": [
        {"IndexCode": "881294", "IndexName": "通用设备", "components": 247, "launch_date": "2025-09-09"}
    ],

    # 新能源与绿色低碳
    "电池化学品": [
        {"IndexCode": "931793", "IndexName": "半导体15", "components": 15, "launch_date": "2021-12-13"}
    ],
    "锂电池": [
        {"IndexCode": "399417", "IndexName": "新能源车", "components": 50, "launch_date": "2014-09-24"},
        {"IndexCode": "399976", "IndexName": "CS新能车", "components": 50, "launch_date": "2014-11-28"}
    ],
    "光伏辅材": [
        {"IndexCode": "931798", "IndexName": "光伏龙头30", "components": 30, "launch_date": "2009-06-16"}
    ],
    "电网自动化设备": [
        {"IndexCode": "881268", "IndexName": "电网设备", "components": 143, "launch_date": "2025-09-09"}
    ],
    "输变电设备": [
        {"IndexCode": "881268", "IndexName": "电网设备", "components": 143, "launch_date": "2025-09-09"}
    ],
    "光伏发电": [
        {"IndexCode": "931151", "IndexName": "光伏产业", "components": 50, "launch_date": "2019-04-22"}
    ],
    "膜材料": [
        {"IndexCode": "881119", "IndexName": "饲料", "components": 21, "launch_date": "2025-09-09"}
    ],
    "光伏加工设备": [
        {"IndexCode": "881275", "IndexName": "光伏设备", "components": 74, "launch_date": "2025-09-09"}
    ],
    "电能综合服务": [
        {"IndexCode": "881459", "IndexName": "电力", "components": 98, "launch_date": "2025-09-09"}
    ],
    "膜材料": [
        {"IndexCode": "881044", "IndexName": "塑料", "components": 93, "launch_date": "2025-09-09"}
    ],
    "玻纤制造": [
        {"IndexCode": "881094", "IndexName": "玻璃玻纤", "components": 16, "launch_date": "2025-09-09"}
    ],
    "硅料硅片": [
        {"IndexCode": "931798", "IndexName": "光伏龙头30", "components": 30, "launch_date": "2009-06-16"}
    ],
    "风电整机": [
        {"IndexCode": "931672", "IndexName": "风电产业", "components": 50, "launch_date": "2021-04-29"}
    ],
    "其他电源设备Ⅲ": [
        {"IndexCode": "881285", "IndexName": "其他发电设备", "components": 25, "launch_date": "2025-09-09"}
    ],
    "电动乘用车": [
        {"IndexCode": "399417", "IndexName": "新能源车", "components": 50, "launch_date": "2014-09-24"}
    ],
    "其他能源发电": [
        {"IndexCode": "881459", "IndexName": "电力", "components": 98, "launch_date": "2025-09-09"}
    ],
    "蓄电池及其他电池": [
        {"IndexCode": "881262", "IndexName": "电池", "components": 95, "launch_date": "2025-09-09"}
    ],
    "锂电专用设备": [
        {"IndexCode": "881275", "IndexName": "光伏设备", "components": 74, "launch_date": "2025-09-09"}
    ],
    "逆变器": [
        {"IndexCode": "881268", "IndexName": "电网设备", "components": 143, "launch_date": "2025-09-09"}
    ],
    "钴": [
        {"IndexCode": "881078", "IndexName": "能源金属", "components": 17, "launch_date": "2025-09-09"}
    ],
    "镍": [
        {"IndexCode": "881078", "IndexName": "能源金属", "components": 17, "launch_date": "2025-09-09"}
    ],
    "燃料电池": [
        {"IndexCode": "880909", "IndexName": "燃料电池", "components": 178, "launch_date": "2025-09-09"}
    ],
    "风电零部件": [
        {"IndexCode": "881282", "IndexName": "风电设备", "components": 28, "launch_date": "2025-09-09"}
    ],
    "储能产业": [
        {"IndexCode": "931746", "IndexName": "储能产业", "components": 50, "launch_date": "2015-06-11"}
    ],

    # 农业与粮食安全
    "粮油加工": [
        {"IndexCode": "881144", "IndexName": "食品加工", "components": 38, "launch_date": "2025-09-09"}
    ],
    "生猪养殖": [
        {"IndexCode": "881111", "IndexName": "养殖业", "components": 21, "launch_date": "2025-09-09"}
    ],
    "氮肥": [
        {"IndexCode": "881055", "IndexName": "农用化工", "components": 59, "launch_date": "2025-09-09"}
    ],
    "林业Ⅲ": [
        {"IndexCode": "881115", "IndexName": "林业", "components": 4, "launch_date": "2025-09-09"}
    ],
    "种子": [
        {"IndexCode": "880710", "IndexName": "种业", "components": 13, "launch_date": "2025-09-09"}
    ],
    "畜禽饲料": [
        {"IndexCode": "881119", "IndexName": "饲料", "components": 21, "launch_date": "2025-09-09"}
    ],
    "钾肥": [
        {"IndexCode": "881055", "IndexName": "农用化工", "components": 59, "launch_date": "2025-09-09"}
    ],
    "复合肥": [
        {"IndexCode": "881055", "IndexName": "农用化工", "components": 59, "launch_date": "2025-09-09"}
    ],
    "其他农产品加工": [
        {"IndexCode": "881123", "IndexName": "农产品加工", "components": 20, "launch_date": "2025-09-09"}
    ],
    "果蔬加工": [
        {"IndexCode": "881144", "IndexName": "食品加工", "components": 38, "launch_date": "2025-09-09"}
    ],
    "水产饲料": [
        {"IndexCode": "881119", "IndexName": "饲料", "components": 21, "launch_date": "2025-09-09"}
    ],
    "食品及饲料添加剂": [
        {"IndexCode": "881055", "IndexName": "农用化工", "components": 59, "launch_date": "2025-09-09"}
    ],
    "水产养殖": [
        {"IndexCode": "881111", "IndexName": "养殖业", "components": 21, "launch_date": "2025-09-09"}
    ],
    "肉鸡养殖": [
        {"IndexCode": "881111", "IndexName": "养殖业", "components": 21, "launch_date": "2025-09-09"}
    ],
    "其他种植业": [
        {"IndexCode": "881106", "IndexName": "种植业", "components": 20, "launch_date": "2025-09-09"}
    ],
    "农业综合Ⅲ": [
        {"IndexCode": "880366", "IndexName": "农业综合", "components": 43, "launch_date": "2025-09-09"}
    ],
    "食用菌": [
        {"IndexCode": "881106", "IndexName": "种植业", "components": 20, "launch_date": "2025-09-09"}
    ],
    "农用机械": [
        {"IndexCode": "881144", "IndexName": "食品加工", "components": 38, "launch_date": "2025-09-09"}
    ],
    "粮食种植": [
        {"IndexCode": "881106", "IndexName": "种植业", "components": 20, "launch_date": "2025-09-09"}
    ],
    "农药": [
        {"IndexCode": "881055", "IndexName": "农用化工", "components": 59, "launch_date": "2025-09-09"}
    ],
    "磷肥及磷化工": [
        {"IndexCode": "881055", "IndexName": "农用化工", "components": 59, "launch_date": "2025-09-09"}
    ],
    "其他养殖": [
        {"IndexCode": "881111", "IndexName": "养殖业", "components": 21, "launch_date": "2025-09-09"}
    ],

    # 生物与大健康
    "医药流通": [
        {"IndexCode": "881252", "IndexName": "医药商业", "components": 37, "launch_date": "2025-09-09"}
    ],
    "化学制剂": [
        {"IndexCode": "881231", "IndexName": "化学制药", "components": 135, "launch_date": "2025-09-09"}
    ],
    "血液制品": [
        {"IndexCode": "881234", "IndexName": "生物制品", "components": 101, "launch_date": "2025-09-09"}
    ],
    "中药Ⅲ": [
        {"IndexCode": "930641", "IndexName": "中证中药", "components": 41, "launch_date": "2015-05-19"}
    ],
    "其他医疗服务": [
        {"IndexCode": "881247", "IndexName": "医疗服务", "components": 54, "launch_date": "2025-09-09"}
    ],
    "医院": [
        {"IndexCode": "881247", "IndexName": "医疗服务", "components": 54, "launch_date": "2025-09-09"}
    ],
    "其他生物制品": [
        {"IndexCode": "881234", "IndexName": "生物制品", "components": 101, "launch_date": "2025-09-09"}
    ],
    "医美服务": [
        {"IndexCode": "881257", "IndexName": "医疗美容", "components": 4, "launch_date": "2025-09-09"}
    ],
    "诊断服务": [
        {"IndexCode": "881241", "IndexName": "医疗器械", "components": 97, "launch_date": "2025-09-09"}
    ],
    "原料药": [
        {"IndexCode": "881231", "IndexName": "化学制药", "components": 135, "launch_date": "2025-09-09"}
    ],
    "洗护用品": [
        {"IndexCode": "881016", "IndexName": "日用化工", "components": 19, "launch_date": "2025-09-09"}
    ],
    "辅料": [
        {"IndexCode": "881231", "IndexName": "化学制药", "components": 135, "launch_date": "2025-09-09"}
    ],
    "疫苗": [
        {"IndexCode": "931992", "IndexName": "疫苗生物", "components": 42, "launch_date": "2013-07-15"}
    ],
    "化妆品制造及其他": [
        {"IndexCode": "881016", "IndexName": "日用化工", "components": 19, "launch_date": "2025-09-09"}
    ],
    "医疗设备": [
        {"IndexCode": "881241", "IndexName": "医疗器械", "components": 97, "launch_date": "2025-09-09"}
    ],
    "医疗耗材": [
        {"IndexCode": "881241", "IndexName": "医疗器械", "components": 97, "launch_date": "2025-09-09"}
    ],
    "线下药店": [
        {"IndexCode": "881252", "IndexName": "医药商业", "components": 37, "launch_date": "2025-09-09"}
    ],
    "医疗研发外包": [
        {"IndexCode": "881247", "IndexName": "医疗服务", "components": 54, "launch_date": "2025-09-09"}
    ],
    "动物保健Ⅲ": [
        {"IndexCode": "881277", "IndexName": "动物保健", "components": 14, "launch_date": "2025-09-09"}
    ],
    "体外诊断": [
        {"IndexCode": "881241", "IndexName": "医疗器械", "components": 97, "launch_date": "2025-09-09"}
    ],
    "品牌化妆品": [
        {"IndexCode": "881016", "IndexName": "日用化工", "components": 19, "launch_date": "2025-09-09"}
    ],
    "医美耗材": [
        {"IndexCode": "881241", "IndexName": "医疗器械", "components": 97, "launch_date": "2025-09-09"}
    ],

    # 传统产业升级（建材/交通/化工）
    "住宅开发": [
        {"IndexCode": "000952", "IndexName": "300地产", "components": 4, "launch_date": "2009-10-28"},
        {"IndexCode": "931775", "IndexName": "房地产", "components": 78, "launch_date": "2013-07-15"}
    ],
    "园林工程": [
        {"IndexCode": "881416", "IndexName": "装修装饰", "components": 24, "launch_date": "2025-09-09"}
    ],
    "玻璃制造": [
        {"IndexCode": "881094", "IndexName": "玻璃玻纤", "components": 16, "launch_date": "2025-09-09"}
    ],
    "冰洗": [
        {"IndexCode": "881184", "IndexName": "白色家电", "components": 10, "launch_date": "2025-09-09"}
    ],
    "钟表珠宝": [
        {"IndexCode": "881162", "IndexName": "饰品", "components": 15, "launch_date": "2025-09-09"}
    ],
    "底盘与发动机系统": [
        {"IndexCode": "881218", "IndexName": "汽车零部件", "components": 245, "launch_date": "2025-09-09"}
    ],
    "商业地产": [
        {"IndexCode": "931775", "IndexName": "房地产", "components": 78, "launch_date": "2013-07-15"}
    ],
    "其他专业工程": [
        {"IndexCode": "881410", "IndexName": "专业工程", "components": 43, "launch_date": "2025-09-09"}
    ],
    "其他建材": [
        {"IndexCode": "881097", "IndexName": "装饰建材", "components": 41, "launch_date": "2025-09-09"}
    ],
    "炼油化工": [
        {"IndexCode": "881011", "IndexName": "石油化工", "components": 18, "launch_date": "2025-09-09"}
    ],
    "空调": [
        {"IndexCode": "881194", "IndexName": "厨卫电器", "components": 9, "launch_date": "2025-09-09"}
    ],
    "家电零部件Ⅲ": [
        {"IndexCode": "881198", "IndexName": "家电零部件", "components": 27, "launch_date": "2025-09-09"}
    ],
    "粘胶": [
        {"IndexCode": "881019", "IndexName": "化纤", "components": 31, "launch_date": "2025-09-09"}
    ],
    "氯碱": [
        {"IndexCode": "881026", "IndexName": "化学原料", "components": 81, "launch_date": "2025-09-09"}
    ],
    "钛白粉": [
        {"IndexCode": "881026", "IndexName": "化学原料", "components": 81, "launch_date": "2025-09-09"}
    ],
    "商用载货车": [
        {"IndexCode": "881215", "IndexName": "商用车", "components": 13, "launch_date": "2025-09-09"}
    ],
    "涂料油墨": [
        {"IndexCode": "881040", "IndexName": "染料涂料", "components": 34, "launch_date": "2025-09-09"}
    ],
    "综合乘用车": [
        {"IndexCode": "881212", "IndexName": "乘用车", "components": 8, "launch_date": "2025-09-09"}
    ],
    "轮胎轮毂": [
        {"IndexCode": "881218", "IndexName": "汽车零部件", "components": 245, "launch_date": "2025-09-09"}
    ],
    "大宗用纸": [
        {"IndexCode": "881167", "IndexName": "造纸", "components": 28, "launch_date": "2025-09-09"}
    ],
    "基建市政工程": [
        {"IndexCode": "881407", "IndexName": "基础建设", "components": 41, "launch_date": "2025-09-09"}
    ],
    "房屋建设Ⅲ": [
        {"IndexCode": "881406", "IndexName": "房屋建设", "components": 8, "launch_date": "2025-09-09"}
    ],
    "钢铁管材": [
        {"IndexCode": "H30058", "IndexName": "AMAC钢铁", "components": 29, "launch_date": "2013-01-21"}
    ],
    "锦纶": [
        {"IndexCode": "881019", "IndexName": "化纤", "components": 31, "launch_date": "2025-09-09"}
    ],
    "塑料包装": [
        {"IndexCode": "881171", "IndexName": "包装印刷", "components": 48, "launch_date": "2025-09-09"}
    ],
    "纯碱": [
        {"IndexCode": "881026", "IndexName": "化学原料", "components": 81, "launch_date": "2025-09-09"}
    ],
    "其他化学原料": [
        {"IndexCode": "881026", "IndexName": "化学原料", "components": 81, "launch_date": "2025-09-09"}
    ],
    "车身附件及饰件": [
        {"IndexCode": "881218", "IndexName": "汽车零部件", "components": 245, "launch_date": "2025-09-09"}
    ],
    "汽车经销商": [
        {"IndexCode": "881224", "IndexName": "汽车服务", "components": 9, "launch_date": "2025-09-09"}
    ],
    "瓷砖地板": [
        {"IndexCode": "881097", "IndexName": "装饰建材", "components": 41, "launch_date": "2025-09-09"}
    ],
    "摩托车": [
        {"IndexCode": "880394", "IndexName": "摩托车", "components": 12, "launch_date": "2025-09-09"}
    ],
    "涤纶": [
        {"IndexCode": "881019", "IndexName": "化纤", "components": 31, "launch_date": "2025-09-09"}
    ],
    "焦煤": [
        {"IndexCode": "881005", "IndexName": "焦炭加工", "components": 7, "launch_date": "2025-09-09"}
    ],
    "其他纺织": [
        {"IndexCode": "881151", "IndexName": "纺织制造", "components": 34, "launch_date": "2025-09-09"}
    ],
    "煤化工": [
        {"IndexCode": "881011", "IndexName": "石油化工", "components": 18, "launch_date": "2025-09-09"}
    ],
    "纸包装": [
        {"IndexCode": "881171", "IndexName": "包装印刷", "components": 48, "launch_date": "2025-09-09"}
    ],
    "其他化学制品": [
        {"IndexCode": "881034", "IndexName": "化学制品", "components": 143, "launch_date": "2025-09-09"}
    ],
    "其他汽车零部件": [
        {"IndexCode": "881218", "IndexName": "汽车零部件", "components": 245, "launch_date": "2025-09-09"}
    ],
    "汽车电子电气系统": [
        {"IndexCode": "880930", "IndexName": "汽车电子", "components": 360, "launch_date": "2025-09-09"}
    ],
    "生活用纸": [
        {"IndexCode": "881167", "IndexName": "造纸", "components": 28, "launch_date": "2025-09-09"}
    ],
    "炭黑": [
        {"IndexCode": "881034", "IndexName": "化学制品", "components": 143, "launch_date": "2025-09-09"}
    ],
    "非运动服装": [
        {"IndexCode": "881157", "IndexName": "服装家纺", "components": 57, "launch_date": "2025-09-09"}
    ],
    "其他家居用品": [
        {"IndexCode": "881177", "IndexName": "家居用品", "components": 72, "launch_date": "2025-09-09"}
    ],
    "娱乐用品": [
        {"IndexCode": "881180", "IndexName": "文娱用品", "components": 19, "launch_date": "2025-09-09"}
    ],
    "工程机械器件": [
        {"IndexCode": "881310", "IndexName": "工程机械", "components": 32, "launch_date": "2025-09-09"}
    ],
    "运动服装": [
        {"IndexCode": "881157", "IndexName": "服装家纺", "components": 57, "launch_date": "2025-09-09"}
    ],
    "合成树脂": [
        {"IndexCode": "881034", "IndexName": "化学制品", "components": 143, "launch_date": "2025-09-09"}
    ],
    "厨房小家电": [
        {"IndexCode": "881190", "IndexName": "小家电", "components": 26, "launch_date": "2025-09-09"}
    ],
    "印刷": [
        {"IndexCode": "881171", "IndexName": "包装印刷", "components": 48, "launch_date": "2025-09-09"}
    ],
    "非金属材料Ⅲ": [
        {"IndexCode": "881104", "IndexName": "非金属材料", "components": 17, "launch_date": "2025-09-09"}
    ],
    "乳品": [
        {"IndexCode": "881136", "IndexName": "饮料乳品", "components": 30, "launch_date": "2025-09-09"}
    ],
    "卫浴制品": [
        {"IndexCode": "881177", "IndexName": "家居用品", "components": 72, "launch_date": "2025-09-09"}
    ],
    "成品家居": [
        {"IndexCode": "881177", "IndexName": "家居用品", "components": 72, "launch_date": "2025-09-09"}
    ],
    "其他橡胶制品": [
        {"IndexCode": "881051", "IndexName": "橡胶", "components": 21, "launch_date": "2025-09-09"}
    ],
    "其他化学纤维": [
        {"IndexCode": "881019", "IndexName": "化纤", "components": 31, "launch_date": "2025-09-09"}
    ],
    "特种纸": [
        {"IndexCode": "881167", "IndexName": "造纸", "components": 28, "launch_date": "2025-09-09"}
    ],
    "厨房电器": [
        {"IndexCode": "881194", "IndexName": "厨卫电器", "components": 9, "launch_date": "2025-09-09"}
    ],
    "装修装饰Ⅲ": [
        {"IndexCode": "881416", "IndexName": "装修装饰", "components": 24, "launch_date": "2025-09-09"}
    ],
    "纺织化学制品": [
        {"IndexCode": "881034", "IndexName": "化学制品", "components": 143, "launch_date": "2025-09-09"}
    ],
    "文化用品": [
        {"IndexCode": "881180", "IndexName": "文娱用品", "components": 19, "launch_date": "2025-09-09"}
    ],
    "其他塑料制品": [
        {"IndexCode": "881044", "IndexName": "塑料", "components": 93, "launch_date": "2025-09-09"}
    ],
    "钢结构": [
        {"IndexCode": "881407", "IndexName": "基础建设", "components": 41, "launch_date": "2025-09-09"}
    ],
    "化学工程": [
        {"IndexCode": "881034", "IndexName": "化学制品", "components": 143, "launch_date": "2025-09-09"}
    ],
    "聚氨酯": [
        {"IndexCode": "881034", "IndexName": "化学制品", "components": 143, "launch_date": "2025-09-09"}
    ],
    "家纺": [
        {"IndexCode": "881157", "IndexName": "服装家纺", "components": 57, "launch_date": "2025-09-09"}
    ],
    "定制家居": [
        {"IndexCode": "881177", "IndexName": "家居用品", "components": 72, "launch_date": "2025-09-09"}
    ],
    "个护小家电": [
        {"IndexCode": "881190", "IndexName": "小家电", "components": 26, "launch_date": "2025-09-09"}
    ],
    "鞋帽及其他": [
        {"IndexCode": "881157", "IndexName": "服装家纺", "components": 57, "launch_date": "2025-09-09"}
    ],
    "综合包装": [
        {"IndexCode": "881171", "IndexName": "包装印刷", "components": 48, "launch_date": "2025-09-09"}
    ],
    "无机盐": [
        {"IndexCode": "881026", "IndexName": "化学原料", "components": 81, "launch_date": "2025-09-09"}
    ],
    "胶黏剂及胶带": [
        {"IndexCode": "881034", "IndexName": "化学制品", "components": 143, "launch_date": "2025-09-09"}
    ],
    "橡胶助剂": [
        {"IndexCode": "881051", "IndexName": "橡胶", "components": 21, "launch_date": "2025-09-09"}
    ],
    "印染": [
        {"IndexCode": "881151", "IndexName": "纺织制造", "components": 34, "launch_date": "2025-09-09"}
    ],
    "房地产综合服务": [
        {"IndexCode": "881422", "IndexName": "房产服务", "components": 9, "launch_date": "2025-09-09"}
    ],
    "产业地产": [
        {"IndexCode": "931775", "IndexName": "房地产", "components": 78, "launch_date": "2013-07-15"}
    ],
    "其他饰品": [
        {"IndexCode": "881162", "IndexName": "饰品", "components": 15, "launch_date": "2025-09-09"}
    ],
    "防水材料": [
        {"IndexCode": "881097", "IndexName": "装饰建材", "components": 41, "launch_date": "2025-09-09"}
    ],
    "管材": [
        {"IndexCode": "881097", "IndexName": "装饰建材", "components": 41, "launch_date": "2025-09-09"}
    ],
    "金属包装": [
        {"IndexCode": "881171", "IndexName": "包装印刷", "components": 48, "launch_date": "2025-09-09"}
    ],
    "耐火材料": [
        {"IndexCode": "881097", "IndexName": "装饰建材", "components": 41, "launch_date": "2025-09-09"}
    ],
    "改性塑料": [
        {"IndexCode": "881044", "IndexName": "塑料", "components": 93, "launch_date": "2025-09-09"}
    ],
    "氟化工": [
        {"IndexCode": "881026", "IndexName": "化学原料", "components": 81, "launch_date": "2025-09-09"}
    ],
    "有机硅": [
        {"IndexCode": "881026", "IndexName": "化学原料", "components": 81, "launch_date": "2025-09-09"}
    ],

    # 现代服务业
    "股份制银行Ⅲ": [
        {"IndexCode": "000134", "IndexName": "上证银行", "components": 26, "launch_date": "2012-05-29"},
        {"IndexCode": "399986", "IndexName": "中证银行", "components": 42, "launch_date": "2013-07-15"}
    ],
    "商业物业经营": [
        {"IndexCode": "881204", "IndexName": "商业物业经营", "components": 17, "launch_date": "2025-09-09"}
    ],
    "综合Ⅲ": [
        {"IndexCode": "881478", "IndexName": "综合类", "components": 17, "launch_date": "2025-09-09"}
    ],
    "物业管理": [
        {"IndexCode": "880743", "IndexName": "物业管理概念", "components": 179, "launch_date": "2025-09-09"}
    ],
    "港口": [
        {"IndexCode": "881449", "IndexName": "航运港口", "components": 35, "launch_date": "2025-09-09"}
    ],
    "机场": [
        {"IndexCode": "881446", "IndexName": "航空机场", "components": 13, "launch_date": "2025-09-09"}
    ],
    "航空运输": [
        {"IndexCode": "881446", "IndexName": "航空机场", "components": 13, "launch_date": "2025-09-09"}
    ],
    "贸易Ⅲ": [
        {"IndexCode": "881206", "IndexName": "贸易", "components": 22, "launch_date": "2025-09-09"}
    ],
    "高速公路": [
        {"IndexCode": "881442", "IndexName": "公路铁路", "components": 32, "launch_date": "2025-09-09"}
    ],
    "证券Ⅲ": [
        {"IndexCode": "399975", "IndexName": "证券公司", "components": 49, "launch_date": "2013-07-15"}
    ],
    "租赁": [
        {"IndexCode": "881396", "IndexName": "多元金融", "components": 26, "launch_date": "2025-09-09"}
    ],
    "资产管理": [
        {"IndexCode": "881396", "IndexName": "多元金融", "components": 26, "launch_date": "2025-09-09"}
    ],
    "国际工程": [
        {"IndexCode": "881410", "IndexName": "专业工程", "components": 43, "launch_date": "2025-09-09"}
    ],
    "信托": [
        {"IndexCode": "881396", "IndexName": "多元金融", "components": 26, "launch_date": "2025-09-09"}
    ],
    "营销代理": [
        {"IndexCode": "881370", "IndexName": "广告营销", "components": 32, "launch_date": "2025-09-09"}
    ],
    "工程咨询服务Ⅲ": [
        {"IndexCode": "881415", "IndexName": "工程咨询服务", "components": 43, "launch_date": "2025-09-09"}
    ],
    "城商行Ⅲ": [
        {"IndexCode": "881389", "IndexName": "地方性银行", "components": 27, "launch_date": "2025-09-09"}
    ],
    "跨境物流": [
        {"IndexCode": "881452", "IndexName": "物流", "components": 47, "launch_date": "2025-09-09"}
    ],
    "期货": [
        {"IndexCode": "881396", "IndexName": "多元金融", "components": 26, "launch_date": "2025-09-09"}
    ],
    "公路货运": [
        {"IndexCode": "881442", "IndexName": "公路铁路", "components": 32, "launch_date": "2025-09-09"}
    ],
    "快递": [
        {"IndexCode": "881452", "IndexName": "物流", "components": 47, "launch_date": "2025-09-09"}
    ],
    "公交": [
        {"IndexCode": "881442", "IndexName": "公路铁路", "components": 32, "launch_date": "2025-09-09"}
    ],
    "仓储物流": [
        {"IndexCode": "881452", "IndexName": "物流", "components": 47, "launch_date": "2025-09-09"}
    ],
    "中间产品及消费品供应链服务": [
        {"IndexCode": "881452", "IndexName": "物流", "components": 47, "launch_date": "2025-09-09"}
    ],
    "农商行Ⅲ": [
        {"IndexCode": "881389", "IndexName": "地方性银行", "components": 27, "launch_date": "2025-09-09"}
    ],
    "人力资源服务": [
        {"IndexCode": "881436", "IndexName": "专业服务", "components": 34, "launch_date": "2025-09-09"}
    ],
    "会展服务": [
        {"IndexCode": "881436", "IndexName": "专业服务", "components": 34, "launch_date": "2025-09-09"}
    ],
    "其他多元金融": [
        {"IndexCode": "881396", "IndexName": "多元金融", "components": 26, "launch_date": "2025-09-09"}
    ],
    "原材料供应链服务": [
        {"IndexCode": "881452", "IndexName": "物流", "components": 47, "launch_date": "2025-09-09"}
    ],
    "其他专业服务": [
        {"IndexCode": "881436", "IndexName": "专业服务", "components": 34, "launch_date": "2025-09-09"}
    ],
    "国有大型银行Ⅲ": [
        {"IndexCode": "881386", "IndexName": "全国性银行", "components": 15, "launch_date": "2025-09-09"}
    ],
    "保险Ⅲ": [
        {"IndexCode": "881395", "IndexName": "保险", "components": 6, "launch_date": "2025-09-09"}
    ],

    # 公用事业
    "火力发电": [
        {"IndexCode": "880307", "IndexName": "火力发电", "components": 31, "launch_date": "2025-09-09"}
    ],
    "固废治理": [
        {"IndexCode": "881471", "IndexName": "环境治理", "components": 97, "launch_date": "2025-09-09"}
    ],
    "铅锌": [
        {"IndexCode": "880327", "IndexName": "铅锌", "components": 14, "launch_date": "2025-09-09"}
    ],
    "综合环境治理": [
        {"IndexCode": "881471", "IndexName": "环境治理", "components": 97, "launch_date": "2025-09-09"}
    ],
    "燃气Ⅲ": [
        {"IndexCode": "881467", "IndexName": "燃气", "components": 31, "launch_date": "2025-09-09"}
    ],
    "水务及水治理": [
        {"IndexCode": "881468", "IndexName": "水务", "components": 15, "launch_date": "2025-09-09"}
    ],
    "动力煤": [
        {"IndexCode": "880307", "IndexName": "火力发电", "components": 31, "launch_date": "2025-09-09"}
    ],
    "铝": [
        {"IndexCode": "880326", "IndexName": "铝", "components": 31, "launch_date": "2025-09-09"}
    ],
    "铜": [
        {"IndexCode": "880325", "IndexName": "铜", "components": 18, "launch_date": "2025-09-09"}
    ],
    "铁矿石": [
        {"IndexCode": "880325", "IndexName": "铜", "components": 18, "launch_date": "2025-09-09"}
    ],
    "热力服务": [
        {"IndexCode": "881459", "IndexName": "电力", "components": 98, "launch_date": "2025-09-09"}
    ],
    "环保设备Ⅲ": [
        {"IndexCode": "881470", "IndexName": "环保设备", "components": 27, "launch_date": "2025-09-09"}
    ],
    "大气治理": [
        {"IndexCode": "881471", "IndexName": "环境治理", "components": 97, "launch_date": "2025-09-09"}
    ],
    "核力发电": [
        {"IndexCode": "880306", "IndexName": "水力发电", "components": 21, "launch_date": "2025-09-09"}
    ],
    "水力发电": [
        {"IndexCode": "880306", "IndexName": "水力发电", "components": 21, "launch_date": "2025-09-09"}
    ],
    "综合电力设备商": [
        {"IndexCode": "881268", "IndexName": "电网设备", "components": 143, "launch_date": "2025-09-09"}
    ],
    "火电设备": [
        {"IndexCode": "881285", "IndexName": "其他发电设备", "components": 25, "launch_date": "2025-09-09"}
    ],

    # 文化消费
    "培训教育": [
        {"IndexCode": "931456", "IndexName": "中国教育", "components": 30, "launch_date": "2020-04-21"}
    ],
    "电视广播Ⅲ": [
        {"IndexCode": "881384", "IndexName": "广播电视", "components": 14, "launch_date": "2025-09-09"}
    ],
    "多业态零售": [
        {"IndexCode": "881200", "IndexName": "一般零售", "components": 41, "launch_date": "2025-09-09"}
    ],
    "酒店": [
        {"IndexCode": "881429", "IndexName": "酒店餐饮", "components": 9, "launch_date": "2025-09-09"}
    ],
    "自然景区": [
        {"IndexCode": "881432", "IndexName": "旅游", "components": 24, "launch_date": "2025-09-09"}
    ],
    "百货": [
        {"IndexCode": "880407", "IndexName": "百货", "components": 35, "launch_date": "2025-09-09"}
    ],
    "旅游综合": [
        {"IndexCode": "881432", "IndexName": "旅游", "components": 24, "launch_date": "2025-09-09"}
    ],
    "肉制品": [
        {"IndexCode": "881140", "IndexName": "休闲食品", "components": 20, "launch_date": "2025-09-09"}
    ],
    "白酒Ⅲ": [
        {"IndexCode": "399997", "IndexName": "中证白酒", "components": 19, "launch_date": "2015-01-21"}
    ],
    "广告媒体": [
        {"IndexCode": "881370", "IndexName": "广告营销", "components": 32, "launch_date": "2025-09-09"}
    ],
    "保健品": [
        {"IndexCode": "881136", "IndexName": "饮料乳品", "components": 30, "launch_date": "2025-09-09"}
    ],
    "图片媒体": [
        {"IndexCode": "881376", "IndexName": "数字媒体", "components": 10, "launch_date": "2025-09-09"}
    ],
    "零食": [
        {"IndexCode": "881140", "IndexName": "休闲食品", "components": 20, "launch_date": "2025-09-09"}
    ],
    "大众出版": [
        {"IndexCode": "881380", "IndexName": "出版业", "components": 29, "launch_date": "2025-09-09"}
    ],
    "餐饮": [
        {"IndexCode": "881429", "IndexName": "酒店餐饮", "components": 9, "launch_date": "2025-09-09"}
    ],
    "啤酒": [
        {"IndexCode": "880382", "IndexName": "啤酒", "components": 8, "launch_date": "2025-09-09"}
    ],
    "超市": [
        {"IndexCode": "880408", "IndexName": "超市连锁", "components": 8, "launch_date": "2025-09-09"}
    ],
    "专业连锁Ⅲ": [
        {"IndexCode": "881205", "IndexName": "专业连锁", "components": 7, "launch_date": "2025-09-09"}
    ],
    "软饮料": [
        {"IndexCode": "880374", "IndexName": "软饮料", "components": 9, "launch_date": "2025-09-09"}
    ],
    "其他酒类": [
        {"IndexCode": "880383", "IndexName": "红黄酒", "components": 9, "launch_date": "2025-09-09"}
    ],
    "烘焙食品": [
        {"IndexCode": "881140", "IndexName": "休闲食品", "components": 20, "launch_date": "2025-09-09"}
    ],
    "预加工食品": [
        {"IndexCode": "881144", "IndexName": "食品加工", "components": 38, "launch_date": "2025-09-09"}
    ],
    "影视动漫制作": [
        {"IndexCode": "881373", "IndexName": "影视院线", "components": 20, "launch_date": "2025-09-09"}
    ],
    "游戏Ⅲ": [
        {"IndexCode": "881369", "IndexName": "游戏", "components": 25, "launch_date": "2025-09-09"}
    ],
    "体育Ⅲ": [
        {"IndexCode": "881427", "IndexName": "体育", "components": 3, "launch_date": "2025-09-09"}
    ],
    "宠物食品": [
        {"IndexCode": "880707", "IndexName": "宠物经济", "components": 114, "launch_date": "2025-09-09"}
    ],
    "熟食": [
        {"IndexCode": "881140", "IndexName": "休闲食品", "components": 20, "launch_date": "2025-09-09"}
    ],
    "院线": [
        {"IndexCode": "881373", "IndexName": "影视院线", "components": 20, "launch_date": "2025-09-09"}
    ],
    "教育运营及其他": [
        {"IndexCode": "881428", "IndexName": "教育培训", "components": 17, "launch_date": "2025-09-09"}
    ],
    "教育出版": [
        {"IndexCode": "881380", "IndexName": "出版业", "components": 29, "launch_date": "2025-09-09"}
    ],
    "其他数字媒体": [
        {"IndexCode": "881376", "IndexName": "数字媒体", "components": 10, "launch_date": "2025-09-09"}
    ],
    "文字媒体": [
        {"IndexCode": "881380", "IndexName": "出版业", "components": 29, "launch_date": "2025-09-09"}
    ],
    "视频媒体": [
        {"IndexCode": "881373", "IndexName": "影视院线", "components": 20, "launch_date": "2025-09-09"}
    ],
    "门户网站": [
        {"IndexCode": "881376", "IndexName": "数字媒体", "components": 10, "launch_date": "2025-09-09"}
    ],
    "旅游零售Ⅲ": [
        {"IndexCode": "881432", "IndexName": "旅游", "components": 24, "launch_date": "2025-09-09"}
    ]
}

* 269细分

In [167]:
industry_to_index_raw_269 = {
    # === 新一代信息技术与数字经济 ===
    "横向通用软件": ["930601", "H30202"],
    "IT服务Ⅲ": ["930601", "H30202"],
    "通信网络设备及器件": ["931160", "H30067"],
    "通信线缆及配套": ["931160", "H30067"],
    "其他电子Ⅲ": ["931461", "H30066"],
    "通信终端及配件": ["931461", "H30066"],
    "光学元件": ["931333", "H30129"],
    "印制电路板": ["931159", "881333"],
    "金融信息服务": ["930986", "H30038"],
    "垂直应用软件": ["930601", "H30202"],
    "其他通信设备": ["931160", "H30067"],
    "电信运营商": ["000040", "000916"],

    # === 高端制造与新质生产力 ===
    "轨交设备Ⅲ": ["881293", "H30124"],
    "面板": ["881329", "H30129"],
    "消费电子零部件及组装": ["881326", "931494"],
    "金属制品": ["930708", "H30058"],
    "锂电池": ["931719", "881262"],
    "其他建材": ["931009", "H30049"],
    "机床工具": ["931866", "880438"],
    "黄金": ["880328", "H30057"],
    "地面兵装Ⅲ": ["881287", "931066"],
    "军工电子Ⅲ": ["881291", "931066"],
    "商用载货车": ["880391", "H30063"],
    "航空装备Ⅲ": ["881288", "931066"],
    "冶钢辅料": ["930606", "H30058"],
    "铜": ["880325", "930708"],
    "其他金属新材料": ["930708", "H30060"],
    "被动元件": ["881333", "H30066"],
    "特钢Ⅲ": ["880320", "930606"],
    "板材": ["930606", "H30058"],
    "长材": ["930606", "H30058"],
    "诊断服务": ["931440", "881247"],
    "海洋捕捞": ["881116", "H11030"],
    "其他黑色家电": ["881187", "H30042"],
    "光伏加工设备": ["881275", "931151"],
    "专业连锁Ⅲ": ["881205", "H11045"],
    "能源及重型设备": ["881310", "H30065"],
    "其他专用设备": ["881303", "H30062"],
    "膜材料": ["881034", "H30053"],
    "商用载客车": ["880391", "H30063"],
    "其他汽车零部件": ["880392", "931230"],
    "汽车电子电气系统": ["880930", "H30065"],
    "电机Ⅲ": ["881261", "H30065"],
    "激光设备": ["880438", "931866"],
    "其他自动化设备": ["881313", "H30061"],
    "印刷包装机械": ["880444", "H30061"],
    "工控设备": ["881313", "H30065"],
    "数字芯片设计": ["H30007", "931865"],
    "其他通用设备": ["881294", "H30061"],
    "仪器仪表": ["880448", "H30067"],
    "检测服务": ["881303", "H30062"],
    "其他运输设备": ["881290", "932536"],
    "民爆制品": ["881287", "931066"],
    "磨具磨料": ["881034", "H30053"],
    "装修装饰Ⅲ": ["881416", "H11042"],
    "纺织服装设备": ["880443", "H30061"],
    "电工仪器仪表": ["880448", "H30067"],
    "安防设备": ["880577", "399693"],
    "半导体材料": ["931743", "H30007"],
    "集成电路封测": ["932087", "H30007"],
    "玻纤制造": ["881094", "931009"],
    "LED": ["880945", "H30129"],
    "楼宇设备": ["881198", "H30065"],
    "半导体设备": ["931865", "H30007"],
    "管材": ["881097", "H30058"],
    "机器人": ["399283", "H30590"],
    "白银": ["880328", "H30057"],
    "航天装备Ⅲ": ["881289", "931066"],
    "航海装备Ⅲ": ["881290", "932420"],
    "分立器件": ["881333", "H30066"],
    "锂电专用设备": ["881275", "931719"],
    "模拟芯片设计": ["H30007", "931865"],
    "印刷": ["881171", "H30050"],

    # === 新能源与绿色低碳 ===
    "电池化学品": ["881034", "931719"],
    "锂电池": ["931719", "881262"],
    "光伏辅材": ["881094", "931798"],
    "电网自动化设备": ["931994", "H30065"],
    "输变电设备": ["931994", "H30065"],
    "光伏发电": ["931151", "880544"],
    "风电整机": ["880582", "931672"],
    "风电零部件": ["880582", "931672"],
    "蓄电池及其他电池": ["881262", "931719"],
    "电动乘用车": ["880951", "399417"],
    "其他能源发电": ["880306", "931897"],
    "逆变器": ["881275", "931151"],
    "燃料电池": ["880909", "930909"],
    "钴": ["880999", "930708"],
    "镍": ["880612", "930708"],

    # === 现代农业与粮食安全 ===
    "粮油加工": ["881123", "H30042"],
    "生猪养殖": ["881111", "H11030"],
    "氮肥": ["880337", "980035"],
    "林业Ⅲ": ["881115", "H11030"],
    "种子": ["880710", "930710"],
    "畜禽饲料": ["881119", "930707"],
    "钾肥": ["880337", "980035"],
    "复合肥": ["880337", "980035"],
    "其他农产品加工": ["881123", "H30042"],
    "果蔬加工": ["881123", "H30042"],
    "水产饲料": ["881119", "930707"],
    "食品及饲料添加剂": ["881034", "H30053"],
    "水产养殖": ["881116", "H11030"],
    "其他种植业": ["881106", "H11030"],
    "肉鸡养殖": ["881111", "H11030"],
    "农用机械": ["880444", "931144"],
    "食用菌": ["881123", "H30042"],
    "粮食种植": ["881106", "930710"],
    "农业综合Ⅲ": ["880366", "H11030"],

    # === 现代生物与大健康 ===
    "医药流通": ["881252", "H30054"],
    "化学制剂": ["881231", "H30053"],
    "血液制品": ["881234", "931992"],
    "中药Ⅲ": ["881256", "930641"],
    "其他医疗服务": ["881247", "H30054"],
    "医院": ["881247", "H30054"],
    "其他生物制品": ["881234", "931992"],
    "医美服务": ["880973", "H11049"],
    "原料药": ["881231", "932217"],
    "诊断服务": ["881241", "931440"],
    "洗护用品": ["881016", "H30043"],
    "辅料": ["881231", "H30053"],
    "疫苗": ["880557", "931992"],
    "体外诊断": ["881241", "931440"],
    "化妆品制造及其他": ["881162", "H30043"],
    "品牌化妆品": ["881162", "H30043"],
    "线下药店": ["881252", "H30054"],
    "医疗研发外包": ["881247", "931440"],
    "医美耗材": ["881241", "H30054"],
    "动物保健Ⅲ": ["881227", "H30053"],

    # === 传统优势产业升级 ===
    "住宅开发": ["881418", "931775"],
    "园林工程": ["881410", "H11042"],
    "玻璃制造": ["880347", "931009"],
    "冰洗": ["881184", "930697"],
    "钟表珠宝": ["881162", "H30046"],
    "商业地产": ["881418", "931775"],
    "其他专业工程": ["881410", "H11042"],
    "炼油化工": ["881011", "H30052"],
    "铅锌": ["880327", "930708"],
    "水泥制造": ["881091", "931009"],
    "家电零部件Ⅲ": ["881198", "H30066"],
    "粘胶": ["881019", "H30055"],
    "大宗用纸": ["881167", "H30049"],
    "基建市政工程": ["881407", "930608"],
    "百货": ["880407", "H11045"],
    "其他医疗服务": ["881247", "H30054"],
    "钛白粉": ["881034", "H30053"],
    "涂料油墨": ["880340", "H30053"],
    "白酒Ⅲ": ["880381", "399997"],
    "综合乘用车": ["880391", "931008"],
    "轮胎轮毂": ["880392", "H30063"],
    "塑料包装": ["881177", "H30044"],
    "焦炭Ⅲ": ["881005", "H30052"],
    "棉纺": ["881151", "H30044"],
    "啤酒": ["880382", "H30043"],
    "汽车经销商": ["881224", "H11045"],
    "钢铁管材": ["881065", "931009"],
    "工程咨询服务Ⅲ": ["881415", "H11042"],
    "锦纶": ["881019", "H30055"],
    "瓷砖地板": ["881097", "H30048"],
    "摩托车": ["880394", "H30063"],
    "涤纶": ["881019", "H30055"],
    "焦煤": ["881005", "H30052"],
    "其他纺织": ["881151", "H30044"],
    "其他小金属": ["880329", "930708"],
    "油气开采Ⅲ": ["881007", "H30198"],
    "生活用纸": ["881167", "H30049"],
    "炭黑": ["881034", "H30053"],
    "非运动服装": ["881157", "H30045"],
    "其他家居用品": ["881177", "H30048"],
    "预加工食品": ["881144", "H30042"],
    "烘焙食品": ["881140", "H30042"],
    "娱乐用品": ["881180", "H11049"],
    "工程机械器件": ["880439", "931752"],
    "跨境物流": ["881452", "930716"],
    "运动服装": ["881157", "H30045"],
    "合成树脂": ["881034", "H30053"],
    "厨房小家电": ["881190", "H30042"],
    "成品家居": ["881177", "H30048"],
    "其他橡胶制品": ["881051", "H30056"],
    "其他化学纤维": ["881019", "H30055"],
    "特种纸": ["881167", "H30049"],
    "厨房电器": ["881194", "H30042"],
    "卫浴制品": ["881177", "H30048"],
    "文化用品": ["881180", "H30051"],
    "其他塑料制品": ["881044", "H30044"],
    "装修装饰Ⅲ": ["881416", "H11042"],
    "纺织化学制品": ["881034", "H30053"],
    "耐火材料": ["881091", "931009"],
    "钢结构": ["881407", "H11042"],
    "化学工程": ["881034", "H30053"],
    "聚氨酯": ["880975", "H30053"],
    "防水材料": ["881097", "H30048"],
    "家纺": ["881157", "H30045"],
    "有机硅": ["880975", "H30053"],
    "改性塑料": ["881044", "H30044"],
    "氟化工": ["880714", "H30053"],
    "胶黏剂及胶带": ["881034", "H30053"],
    "熟食": ["881140", "H30042"],
    "个护小家电": ["881190", "H30042"],
    "清洁小家电": ["881190", "H30042"],
    "综合包装": ["881171", "H30049"],
    "无机盐": ["881034", "H30053"],
    "其他饰品": ["881162", "H30046"],
    "印染": ["881151", "H30044"],
    "房地产综合服务": ["881422", "H11047"],
    "产业地产": ["881418", "931775"],
    "房屋建设Ⅲ": ["881406", "H11042"],

    # === 现代服务业与供应链韧性 ===
    "股份制银行Ⅲ": ["000134", "399986"],
    "商业物业经营": ["881204", "H11047"],
    "综合Ⅲ": ["881478", "H11050"],
    "港口": ["880468", "932536"],
    "机场": ["880467", "H11043"],
    "油品石化贸易": ["881206", "H11045"],
    "航空运输": ["880430", "H11043"],
    "培训教育": ["880908", "931456"],
    "贸易Ⅲ": ["881206", "H11045"],
    "证券Ⅲ": ["399975", "H30086"],
    "高速公路": ["880463", "H11043"],
    "航运": ["880461", "932536"],
    "铁路运输": ["880460", "H11043"],
    "房产租赁经纪": ["881422", "H11047"],
    "信托": ["881396", "H11046"],
    "营销代理": ["881370", "H11045"],
    "城商行Ⅲ": ["000134", "399986"],
    "期货": ["881395", "H11046"],
    "其他多元金融": ["881396", "H11046"],
    "国际工程": ["881407", "930608"],
    "租赁": ["881396", "H11046"],
    "资产管理": ["881396", "H11046"],
    "原材料供应链服务": ["881452", "930716"],
    "中间产品及消费品供应链服务": ["881452", "930716"],
    "人力资源服务": ["881436", "H11045"],
    "会展服务": ["881436", "H11045"],
    "工程咨询服务Ⅲ": ["881415", "H11042"],
    "其他专业服务": ["881436", "H11045"],

    # === 公用事业与基础保障 ===
    "火力发电": ["880307", "H30199"],
    "固废治理": ["880456", "930614"],
    "风力发电": ["880582", "931672"],
    "动力煤": ["880307", "399998"],
    "水务及水治理": ["881468", "930614"],
    "铝": ["880326", "930708"],
    "热力服务": ["880455", "H30199"],
    "铁矿石": ["880325", "930708"],
    "水力发电": ["880306", "H30199"],
    "核力发电": ["880306", "H30199"],
    "大气治理": ["880456", "930614"],
    "环保设备Ⅲ": ["881470", "930614"],
    "综合环境治理": ["880456", "930614"],

    # === 文化消费与生活服务 ===
    "电视广播Ⅲ": ["881384", "H11049"],
    "酒店": ["881429", "H11045"],
    "自然景区": ["880426", "930633"],
    "旅游综合": ["880425", "930633"],
    "肉制品": ["881139", "H30042"],
    "广告媒体": ["881370", "H11049"],
    "保健品": ["881136", "H30043"],
    "图片媒体": ["881376", "H11049"],
    "零食": ["881140", "H30042"],
    "大众出版": ["881380", "H11049"],
    "餐饮": ["880425", "399238"],
    "软饮料": ["881136", "H30043"],
    "影视动漫制作": ["880420", "930781"],
    "专业连锁Ⅲ": ["881205", "H11045"],
    "其他酒类": ["880383", "H30043"],
    "超市": ["880408", "H11045"],
    "印刷": ["881171", "H30050"],
    "游戏Ⅲ": ["880590", "930901"],
    "乳品": ["881136", "H30043"],
    "综合电商": ["880941", "H30037"],
    "学历教育": ["880908", "931456"],
    "门户网站": ["881376", "H11049"],
    "体育Ⅲ": ["880596", "H11049"],
    "宠物食品": ["880707", "H30042"],
    "教育运营及其他": ["881428", "931456"],
    "院线": ["881373", "H11049"],
    "熟食": ["881140", "H30042"],
    "其他数字媒体": ["881376", "H11049"],
    "会展服务": ["881436", "H11045"],
    "旅游零售Ⅲ": ["880425", "930633"],
    "文字媒体": ["881380", "H11049"],
    "视频媒体": ["881376", "H11049"]
}

In [162]:
industry_to_index_standardized_269 = {
"横向通用软件":[
    {'IndexCode': '930601', 'IndexName': '中证软件', 'components': 30, 'launch_date': '2015-03-10'},
    {'IndexCode': 'H30202', 'IndexName': '软件指数', 'components': 50, 'launch_date': '2013-07-15'},
],
"IT服务Ⅲ":[
    {'IndexCode': '930601', 'IndexName': '中证软件', 'components': 30, 'launch_date': '2015-03-10'},
    {'IndexCode': 'H30202', 'IndexName': '软件指数', 'components': 50, 'launch_date': '2013-07-15'},
],
"通信网络设备及器件":[
    {'IndexCode': '931160', 'IndexName': '通信设备', 'components': 50, 'launch_date': '2013-07-15'},
    {'IndexCode': 'H30067', 'IndexName': 'AMAC仪表', 'components': 66, 'launch_date': '2013-01-21'},
],
"通信线缆及配套":[
    {'IndexCode': '931160', 'IndexName': '通信设备', 'components': 50, 'launch_date': '2013-07-15'},
    {'IndexCode': 'H30067', 'IndexName': 'AMAC仪表', 'components': 66, 'launch_date': '2013-01-21'},
],
"其他电子Ⅲ":[
    {'IndexCode': '931461', 'IndexName': '电子50', 'components': 50, 'launch_date': '2009-07-22'},
    {'IndexCode': 'H30066', 'IndexName': 'AMAC电子', 'components': 593, 'launch_date': '2013-01-21'},
],
"通信终端及配件":[
    {'IndexCode': '931461', 'IndexName': '电子50', 'components': 50, 'launch_date': '2009-07-22'},
    {'IndexCode': 'H30066', 'IndexName': 'AMAC电子', 'components': 593, 'launch_date': '2013-01-21'},
],
"光学元件":[
    {'IndexCode': '931333', 'IndexName': '未知指数', 'components': 0, 'launch_date': '未知'},
    {'IndexCode': 'H30129', 'IndexName': '未知指数', 'components': 0, 'launch_date': '未知'},
],
"印制电路板":[
    {'IndexCode': '931159', 'IndexName': '创新100', 'components': 100, 'launch_date': '2019-05-16'},
    {'IndexCode': '881333', 'IndexName': '元器件', 'components': 62, 'launch_date': '2025-09-09'},
],
"金融信息服务":[
    {'IndexCode': '930986', 'IndexName': '金融科技', 'components': 57, 'launch_date': '2017-06-22'},
    {'IndexCode': 'H30038', 'IndexName': 'AMAC科技', 'components': 99, 'launch_date': '2013-01-21'},
],
"垂直应用软件":[
    {'IndexCode': '930601', 'IndexName': '中证软件', 'components': 30, 'launch_date': '2015-03-10'},
    {'IndexCode': 'H30202', 'IndexName': '软件指数', 'components': 50, 'launch_date': '2013-07-15'},
],
"其他通信设备":[
    {'IndexCode': '931160', 'IndexName': '通信设备', 'components': 50, 'launch_date': '2013-07-15'},
    {'IndexCode': 'H30067', 'IndexName': 'AMAC仪表', 'components': 66, 'launch_date': '2013-01-21'},
],
"电信运营商":[
    {'IndexCode': '000040', 'IndexName': '上证电信', 'components': 30, 'launch_date': '2009-01-09'},
    {'IndexCode': '000916', 'IndexName': '300通信', 'components': 14, 'launch_date': '2007-07-02'},
],
"轨交设备Ⅲ":[
    {'IndexCode': '881293', 'IndexName': '轨交设备', 'components': 33, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30124', 'IndexName': '安中动态', 'components': 300, 'launch_date': '2013-07-01'},
],
"面板":[
    {'IndexCode': '881329', 'IndexName': '光学光电', 'components': 107, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30129', 'IndexName': '未知指数', 'components': 0, 'launch_date': '未知'},
],
"消费电子零部件及组装":[
    {'IndexCode': '881326', 'IndexName': '消费电子', 'components': 102, 'launch_date': '2025-09-09'},
    {'IndexCode': '931494', 'IndexName': '消费电子', 'components': 50, 'launch_date': '2020-06-12'},
],
"金属制品":[
    {'IndexCode': '930708', 'IndexName': '中证有色', 'components': 60, 'launch_date': '2015-07-13'},
    {'IndexCode': 'H30058', 'IndexName': 'AMAC钢铁', 'components': 29, 'launch_date': '2013-01-21'},
],
"锂电池":[
    {'IndexCode': '931719', 'IndexName': 'CS电池', 'components': 50, 'launch_date': '2013-07-15'},
    {'IndexCode': '881262', 'IndexName': '电池', 'components': 95, 'launch_date': '2025-09-09'},
],
"其他建材":[
    {'IndexCode': '931009', 'IndexName': '建筑材料', 'components': 41, 'launch_date': '2013-07-15'},
    {'IndexCode': 'H30049', 'IndexName': 'AMAC造纸', 'components': 37, 'launch_date': '2013-01-21'},
],
"机床工具":[
    {'IndexCode': '931866', 'IndexName': '中证机床', 'components': 50, 'launch_date': '2022-05-09'},
    {'IndexCode': '880438', 'IndexName': '机床制造', 'components': 24, 'launch_date': '2025-09-09'},
],
"黄金":[
    {'IndexCode': '880328', 'IndexName': '黄金', 'components': 10, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30057', 'IndexName': 'AMAC矿物', 'components': 90, 'launch_date': '2013-01-21'},
],
"地面兵装Ⅲ":[
    {'IndexCode': '881287', 'IndexName': '地面兵装', 'components': 14, 'launch_date': '2025-09-09'},
    {'IndexCode': '931066', 'IndexName': '军工龙头', 'components': 30, 'launch_date': '2018-02-05'},
],
"军工电子Ⅲ":[
    {'IndexCode': '881291', 'IndexName': '军工电子', 'components': 59, 'launch_date': '2025-09-09'},
    {'IndexCode': '931066', 'IndexName': '军工龙头', 'components': 30, 'launch_date': '2018-02-05'},
],
"商用载货车":[
    {'IndexCode': '880391', 'IndexName': '汽车整车', 'components': 22, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30063', 'IndexName': 'AMAC汽车', 'components': 178, 'launch_date': '2013-01-21'},
],
"航空装备Ⅲ":[
    {'IndexCode': '881288', 'IndexName': '航空装备', 'components': 44, 'launch_date': '2025-09-09'},
    {'IndexCode': '931066', 'IndexName': '军工龙头', 'components': 30, 'launch_date': '2018-02-05'},
],
"冶钢辅料":[
    {'IndexCode': '930606', 'IndexName': '中证钢铁', 'components': 48, 'launch_date': '2015-03-31'},
    {'IndexCode': 'H30058', 'IndexName': 'AMAC钢铁', 'components': 29, 'launch_date': '2013-01-21'},
],
"铜":[
    {'IndexCode': '880325', 'IndexName': '铜', 'components': 18, 'launch_date': '2025-09-09'},
    {'IndexCode': '930708', 'IndexName': '中证有色', 'components': 60, 'launch_date': '2015-07-13'},
],
"其他金属新材料":[
    {'IndexCode': '930708', 'IndexName': '中证有色', 'components': 60, 'launch_date': '2015-07-13'},
    {'IndexCode': 'H30060', 'IndexName': 'AMAC金属', 'components': 88, 'launch_date': '2013-01-21'},
],
"被动元件":[
    {'IndexCode': '881333', 'IndexName': '元器件', 'components': 62, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30066', 'IndexName': 'AMAC电子', 'components': 593, 'launch_date': '2013-01-21'},
],
"特钢Ⅲ":[
    {'IndexCode': '880320', 'IndexName': '特种钢', 'components': 10, 'launch_date': '2025-09-09'},
    {'IndexCode': '930606', 'IndexName': '中证钢铁', 'components': 48, 'launch_date': '2015-03-31'},
],
"板材":[
    {'IndexCode': '930606', 'IndexName': '中证钢铁', 'components': 48, 'launch_date': '2015-03-31'},
    {'IndexCode': 'H30058', 'IndexName': 'AMAC钢铁', 'components': 29, 'launch_date': '2013-01-21'},
],
"长材":[
    {'IndexCode': '930606', 'IndexName': '中证钢铁', 'components': 48, 'launch_date': '2015-03-31'},
    {'IndexCode': 'H30058', 'IndexName': 'AMAC钢铁', 'components': 29, 'launch_date': '2013-01-21'},
],
"诊断服务":[
    {'IndexCode': '881241', 'IndexName': '医疗器械', 'components': 97, 'launch_date': '2025-09-09'},
    {'IndexCode': '931440', 'IndexName': '创新药30', 'components': 30, 'launch_date': '2020-04-21'},
],
"海洋捕捞":[
    {'IndexCode': '881116', 'IndexName': '渔业', 'components': 7, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11030', 'IndexName': 'AMAC农林', 'components': 38, 'launch_date': '2009-06-15'},
],
"其他黑色家电":[
    {'IndexCode': '881187', 'IndexName': '黑色家电', 'components': 10, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"光伏加工设备":[
    {'IndexCode': '881275', 'IndexName': '光伏设备', 'components': 74, 'launch_date': '2025-09-09'},
    {'IndexCode': '931151', 'IndexName': '光伏产业', 'components': 50, 'launch_date': '2019-04-22'},
],
"专业连锁Ⅲ":[
    {'IndexCode': '881205', 'IndexName': '专业连锁', 'components': 7, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11045', 'IndexName': 'AMAC批零', 'components': 167, 'launch_date': '2009-06-15'},
],
"能源及重型设备":[
    {'IndexCode': '881310', 'IndexName': '工程机械', 'components': 32, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30065', 'IndexName': 'AMAC电气', 'components': 300, 'launch_date': '2013-01-21'},
],
"其他专用设备":[
    {'IndexCode': '881303', 'IndexName': '专用设备', 'components': 228, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30062', 'IndexName': 'AMAC专用', 'components': 303, 'launch_date': '2013-01-21'},
],
"膜材料":[
    {'IndexCode': '881034', 'IndexName': '化学制品', 'components': 143, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"商用载客车":[
    {'IndexCode': '880391', 'IndexName': '汽车整车', 'components': 22, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30063', 'IndexName': 'AMAC汽车', 'components': 178, 'launch_date': '2013-01-21'},
],
"其他汽车零部件":[
    {'IndexCode': '880392', 'IndexName': '汽车配件', 'components': 250, 'launch_date': '2025-09-09'},
    {'IndexCode': '931230', 'IndexName': '汽车零部件', 'components': 100, 'launch_date': '2013-07-15'},
],
"汽车电子电气系统":[
    {'IndexCode': '880930', 'IndexName': '汽车电子', 'components': 360, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30065', 'IndexName': 'AMAC电气', 'components': 300, 'launch_date': '2013-01-21'},
],
"电机Ⅲ":[
    {'IndexCode': '881261', 'IndexName': '电机制造', 'components': 26, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30065', 'IndexName': 'AMAC电气', 'components': 300, 'launch_date': '2013-01-21'},
],
"激光设备":[
    {'IndexCode': '880438', 'IndexName': '机床制造', 'components': 24, 'launch_date': '2025-09-09'},
    {'IndexCode': '931866', 'IndexName': '中证机床', 'components': 50, 'launch_date': '2022-05-09'},
],
"其他自动化设备":[
    {'IndexCode': '881313', 'IndexName': '自动化设备', 'components': 72, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30061', 'IndexName': 'AMAC通用', 'components': 194, 'launch_date': '2013-01-21'},
],
"印刷包装机械":[
    {'IndexCode': '880444', 'IndexName': '农用机械', 'components': 13, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30061', 'IndexName': 'AMAC通用', 'components': 194, 'launch_date': '2013-01-21'},
],
"工控设备":[
    {'IndexCode': '881313', 'IndexName': '自动化设备', 'components': 72, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30065', 'IndexName': 'AMAC电气', 'components': 300, 'launch_date': '2013-01-21'},
],
"数字芯片设计":[
    {'IndexCode': 'H30007', 'IndexName': '芯片产业', 'components': 50, 'launch_date': '2012-12-20'},
    {'IndexCode': '931865', 'IndexName': '中证半导', 'components': 40, 'launch_date': '2019-03-20'},
],
"其他通用设备":[
    {'IndexCode': '881294', 'IndexName': '通用设备', 'components': 247, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30061', 'IndexName': 'AMAC通用', 'components': 194, 'launch_date': '2013-01-21'},
],
"仪器仪表":[
    {'IndexCode': '880448', 'IndexName': '电器仪表', 'components': 105, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30067', 'IndexName': 'AMAC仪表', 'components': 66, 'launch_date': '2013-01-21'},
],
"检测服务":[
    {'IndexCode': '881303', 'IndexName': '专用设备', 'components': 228, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30062', 'IndexName': 'AMAC专用', 'components': 303, 'launch_date': '2013-01-21'},
],
"其他运输设备":[
    {'IndexCode': '881290', 'IndexName': '航海装备', 'components': 11, 'launch_date': '2025-09-09'},
    {'IndexCode': '932536', 'IndexName': '航运发展', 'components': 50, 'launch_date': '2025-06-18'},
],
"民爆制品":[
    {'IndexCode': '881287', 'IndexName': '地面兵装', 'components': 14, 'launch_date': '2025-09-09'},
    {'IndexCode': '931066', 'IndexName': '军工龙头', 'components': 30, 'launch_date': '2018-02-05'},
],
"磨具磨料":[
    {'IndexCode': '881034', 'IndexName': '化学制品', 'components': 143, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"装修装饰Ⅲ":[
    {'IndexCode': '881416', 'IndexName': '装修装饰', 'components': 24, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11042', 'IndexName': 'AMAC建筑', 'components': 76, 'launch_date': '2009-06-15'},
],
"纺织服装设备":[
    {'IndexCode': '880443', 'IndexName': '纺织机械', 'components': 11, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30061', 'IndexName': 'AMAC通用', 'components': 194, 'launch_date': '2013-01-21'},
],
"电工仪器仪表":[
    {'IndexCode': '880448', 'IndexName': '电器仪表', 'components': 105, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30067', 'IndexName': 'AMAC仪表', 'components': 66, 'launch_date': '2013-01-21'},
],
"安防设备":[
    {'IndexCode': '880577', 'IndexName': '安防服务', 'components': 118, 'launch_date': '2025-09-09'},
    {'IndexCode': '399693', 'IndexName': '安防产业', 'components': 50, 'launch_date': '2016-06-20'},
],
"半导体材料":[
    {'IndexCode': '931743', 'IndexName': '半导体材料设备', 'components': 40, 'launch_date': '2012-12-21'},
    {'IndexCode': 'H30007', 'IndexName': '芯片产业', 'components': 50, 'launch_date': '2012-12-20'},
],
"集成电路封测":[
    {'IndexCode': '932087', 'IndexName': '集成电路', 'components': 81, 'launch_date': '2023-03-29'},
    {'IndexCode': 'H30007', 'IndexName': '芯片产业', 'components': 50, 'launch_date': '2012-12-20'},
],
"玻纤制造":[
    {'IndexCode': '881094', 'IndexName': '玻璃玻纤', 'components': 16, 'launch_date': '2025-09-09'},
    {'IndexCode': '931009', 'IndexName': '建筑材料', 'components': 41, 'launch_date': '2013-07-15'},
],
"LED":[
    {'IndexCode': '880945', 'IndexName': 'OLED概念', 'components': 145, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30129', 'IndexName': '未知指数', 'components': 0, 'launch_date': '未知'},
],
"楼宇设备":[
    {'IndexCode': '881198', 'IndexName': '家电零部件', 'components': 27, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30065', 'IndexName': 'AMAC电气', 'components': 300, 'launch_date': '2013-01-21'},
],
"半导体设备":[
    {'IndexCode': '931865', 'IndexName': '中证半导', 'components': 40, 'launch_date': '2019-03-20'},
    {'IndexCode': 'H30007', 'IndexName': '芯片产业', 'components': 50, 'launch_date': '2012-12-20'},
],
"管材":[
    {'IndexCode': '881097', 'IndexName': '装饰建材', 'components': 41, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30058', 'IndexName': 'AMAC钢铁', 'components': 29, 'launch_date': '2013-01-21'},
],
"机器人":[
    {'IndexCode': '399283', 'IndexName': '机器人50', 'components': 50, 'launch_date': '2020-02-18'},
    {'IndexCode': 'H30590', 'IndexName': '机器人', 'components': 73, 'launch_date': '2015-02-10'},
],
"白银":[
    {'IndexCode': '880328', 'IndexName': '黄金', 'components': 10, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30057', 'IndexName': 'AMAC矿物', 'components': 90, 'launch_date': '2013-01-21'},
],
"航天装备Ⅲ":[
    {'IndexCode': '881289', 'IndexName': '航天装备', 'components': 8, 'launch_date': '2025-09-09'},
    {'IndexCode': '931066', 'IndexName': '军工龙头', 'components': 30, 'launch_date': '2018-02-05'},
],
"航海装备Ⅲ":[
    {'IndexCode': '881290', 'IndexName': '航海装备', 'components': 11, 'launch_date': '2025-09-09'},
    {'IndexCode': '932420', 'IndexName': '智选船舶产业', 'components': 39, 'launch_date': '2025-05-28'},
],
"分立器件":[
    {'IndexCode': '881333', 'IndexName': '元器件', 'components': 62, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30066', 'IndexName': 'AMAC电子', 'components': 593, 'launch_date': '2013-01-21'},
],
"锂电专用设备":[
    {'IndexCode': '881275', 'IndexName': '光伏设备', 'components': 74, 'launch_date': '2025-09-09'},
    {'IndexCode': '931719', 'IndexName': 'CS电池', 'components': 50, 'launch_date': '2013-07-15'},
],
"模拟芯片设计":[
    {'IndexCode': 'H30007', 'IndexName': '芯片产业', 'components': 50, 'launch_date': '2012-12-20'},
    {'IndexCode': '931865', 'IndexName': '中证半导', 'components': 40, 'launch_date': '2019-03-20'},
],
"印刷":[
    {'IndexCode': '881171', 'IndexName': '包装印刷', 'components': 48, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30050', 'IndexName': 'AMAC印刷', 'components': 12, 'launch_date': '2013-01-21'},
],
"电池化学品":[
    {'IndexCode': '881034', 'IndexName': '化学制品', 'components': 143, 'launch_date': '2025-09-09'},
    {'IndexCode': '931719', 'IndexName': 'CS电池', 'components': 50, 'launch_date': '2013-07-15'},
],
"光伏辅材":[
    {'IndexCode': '881094', 'IndexName': '玻璃玻纤', 'components': 16, 'launch_date': '2025-09-09'},
    {'IndexCode': '931798', 'IndexName': '光伏龙头30', 'components': 30, 'launch_date': '2009-06-16'},
],
"电网自动化设备":[
    {'IndexCode': '931994', 'IndexName': '电网设备主题', 'components': 80, 'launch_date': '2022-10-11'},
    {'IndexCode': 'H30065', 'IndexName': 'AMAC电气', 'components': 300, 'launch_date': '2013-01-21'},
],
"输变电设备":[
    {'IndexCode': '931994', 'IndexName': '电网设备主题', 'components': 80, 'launch_date': '2022-10-11'},
    {'IndexCode': 'H30065', 'IndexName': 'AMAC电气', 'components': 300, 'launch_date': '2013-01-21'},
],
"光伏发电":[
    {'IndexCode': '931151', 'IndexName': '光伏产业', 'components': 50, 'launch_date': '2019-04-22'},
    {'IndexCode': '880544', 'IndexName': '光伏', 'components': 588, 'launch_date': '2025-09-09'},
],
"风电整机":[
    {'IndexCode': '880582', 'IndexName': '风电', 'components': 378, 'launch_date': '2025-09-09'},
    {'IndexCode': '931672', 'IndexName': '风电产业', 'components': 50, 'launch_date': '2021-04-29'},
],
"风电零部件":[
    {'IndexCode': '880582', 'IndexName': '风电', 'components': 378, 'launch_date': '2025-09-09'},
    {'IndexCode': '931672', 'IndexName': '风电产业', 'components': 50, 'launch_date': '2021-04-29'},
],
"蓄电池及其他电池":[
    {'IndexCode': '881262', 'IndexName': '电池', 'components': 95, 'launch_date': '2025-09-09'},
    {'IndexCode': '931719', 'IndexName': 'CS电池', 'components': 50, 'launch_date': '2013-07-15'},
],
"电动乘用车":[
    {'IndexCode': '880951', 'IndexName': '新能源车', 'components': 957, 'launch_date': '2025-09-09'},
    {'IndexCode': '399417', 'IndexName': '新能源车', 'components': 50, 'launch_date': '2014-09-24'},
],
"其他能源发电":[
    {'IndexCode': '880306', 'IndexName': '水力发电', 'components': 21, 'launch_date': '2025-09-09'},
    {'IndexCode': '931897', 'IndexName': '绿色电力', 'components': 50, 'launch_date': '2012-12-21'},
],
"逆变器":[
    {'IndexCode': '881275', 'IndexName': '光伏设备', 'components': 74, 'launch_date': '2025-09-09'},
    {'IndexCode': '931151', 'IndexName': '光伏产业', 'components': 50, 'launch_date': '2019-04-22'},
],
"燃料电池":[
    {'IndexCode': '880909', 'IndexName': '燃料电池', 'components': 178, 'launch_date': '2025-09-09'},
    {'IndexCode': '930909', 'IndexName': '未知指数', 'components': 0, 'launch_date': '未知'},
],
"钴":[
    {'IndexCode': '880999', 'IndexName': '未知指数', 'components': 0, 'launch_date': '未知'},
    {'IndexCode': '930708', 'IndexName': '中证有色', 'components': 60, 'launch_date': '2015-07-13'},
],
"镍":[
    {'IndexCode': '880612', 'IndexName': '镍金属', 'components': 43, 'launch_date': '2025-09-09'},
    {'IndexCode': '930708', 'IndexName': '中证有色', 'components': 60, 'launch_date': '2015-07-13'},
],
"粮油加工":[
    {'IndexCode': '881123', 'IndexName': '农产品加工', 'components': 20, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"生猪养殖":[
    {'IndexCode': '881111', 'IndexName': '养殖业', 'components': 21, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11030', 'IndexName': 'AMAC农林', 'components': 38, 'launch_date': '2009-06-15'},
],
"氮肥":[
    {'IndexCode': '880337', 'IndexName': '农药化肥', 'components': 57, 'launch_date': '2025-09-09'},
    {'IndexCode': '980035', 'IndexName': '化肥农药', 'components': 80, 'launch_date': '未知'},
],
"林业Ⅲ":[
    {'IndexCode': '881115', 'IndexName': '林业', 'components': 4, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11030', 'IndexName': 'AMAC农林', 'components': 38, 'launch_date': '2009-06-15'},
],
"种子":[
    {'IndexCode': '880710', 'IndexName': '种业', 'components': 13, 'launch_date': '2025-09-09'},
    {'IndexCode': '930710', 'IndexName': '未知指数', 'components': 0, 'launch_date': '未知'},
],
"畜禽饲料":[
    {'IndexCode': '881119', 'IndexName': '饲料', 'components': 21, 'launch_date': '2025-09-09'},
    {'IndexCode': '930707', 'IndexName': '中证畜牧', 'components': 35, 'launch_date': '2015-07-13'},
],
"钾肥":[
    {'IndexCode': '880337', 'IndexName': '农药化肥', 'components': 57, 'launch_date': '2025-09-09'},
    {'IndexCode': '980035', 'IndexName': '化肥农药', 'components': 80, 'launch_date': '未知'},
],
"复合肥":[
    {'IndexCode': '880337', 'IndexName': '农药化肥', 'components': 57, 'launch_date': '2025-09-09'},
    {'IndexCode': '980035', 'IndexName': '化肥农药', 'components': 80, 'launch_date': '未知'},
],
"其他农产品加工":[
    {'IndexCode': '881123', 'IndexName': '农产品加工', 'components': 20, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"果蔬加工":[
    {'IndexCode': '881123', 'IndexName': '农产品加工', 'components': 20, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"水产饲料":[
    {'IndexCode': '881119', 'IndexName': '饲料', 'components': 21, 'launch_date': '2025-09-09'},
    {'IndexCode': '930707', 'IndexName': '中证畜牧', 'components': 35, 'launch_date': '2015-07-13'},
],
"食品及饲料添加剂":[
    {'IndexCode': '881034', 'IndexName': '化学制品', 'components': 143, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"水产养殖":[
    {'IndexCode': '881116', 'IndexName': '渔业', 'components': 7, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11030', 'IndexName': 'AMAC农林', 'components': 38, 'launch_date': '2009-06-15'},
],
"其他种植业":[
    {'IndexCode': '881106', 'IndexName': '种植业', 'components': 20, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11030', 'IndexName': 'AMAC农林', 'components': 38, 'launch_date': '2009-06-15'},
],
"肉鸡养殖":[
    {'IndexCode': '881111', 'IndexName': '养殖业', 'components': 21, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11030', 'IndexName': 'AMAC农林', 'components': 38, 'launch_date': '2009-06-15'},
],
"农用机械":[
    {'IndexCode': '880444', 'IndexName': '农用机械', 'components': 13, 'launch_date': '2025-09-09'},
    {'IndexCode': '931144', 'IndexName': '通信技术', 'components': 51, 'launch_date': '2019-05-30'},
],
"食用菌":[
    {'IndexCode': '881123', 'IndexName': '农产品加工', 'components': 20, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"粮食种植":[
    {'IndexCode': '881106', 'IndexName': '种植业', 'components': 20, 'launch_date': '2025-09-09'},
    {'IndexCode': '930710', 'IndexName': '未知指数', 'components': 0, 'launch_date': '未知'},
],
"农业综合Ⅲ":[
    {'IndexCode': '880366', 'IndexName': '农业综合', 'components': 43, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11030', 'IndexName': 'AMAC农林', 'components': 38, 'launch_date': '2009-06-15'},
],
"医药流通":[
    {'IndexCode': '881252', 'IndexName': '医药商业', 'components': 37, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30054', 'IndexName': 'AMAC医药', 'components': 271, 'launch_date': '2013-01-21'},
],
"化学制剂":[
    {'IndexCode': '881231', 'IndexName': '化学制药', 'components': 135, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"血液制品":[
    {'IndexCode': '881234', 'IndexName': '生物制品', 'components': 101, 'launch_date': '2025-09-09'},
    {'IndexCode': '931992', 'IndexName': '疫苗生物', 'components': 42, 'launch_date': '2013-07-15'},
],
"中药Ⅲ":[
    {'IndexCode': '881256', 'IndexName': '中药', 'components': 69, 'launch_date': '2025-09-09'},
    {'IndexCode': '930641', 'IndexName': '中证中药', 'components': 41, 'launch_date': '2015-05-19'},
],
"其他医疗服务":[
    {'IndexCode': '881247', 'IndexName': '医疗服务', 'components': 54, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30054', 'IndexName': 'AMAC医药', 'components': 271, 'launch_date': '2013-01-21'},
],
"医院":[
    {'IndexCode': '881247', 'IndexName': '医疗服务', 'components': 54, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30054', 'IndexName': 'AMAC医药', 'components': 271, 'launch_date': '2013-01-21'},
],
"其他生物制品":[
    {'IndexCode': '881234', 'IndexName': '生物制品', 'components': 101, 'launch_date': '2025-09-09'},
    {'IndexCode': '931992', 'IndexName': '疫苗生物', 'components': 42, 'launch_date': '2013-07-15'},
],
"医美服务":[
    {'IndexCode': '880973', 'IndexName': '医美概念', 'components': 100, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
"原料药":[
    {'IndexCode': '881231', 'IndexName': '化学制药', 'components': 135, 'launch_date': '2025-09-09'},
    {'IndexCode': '932217', 'IndexName': '制药指数', 'components': 50, 'launch_date': '2013-07-15'},
],
"洗护用品":[
    {'IndexCode': '881016', 'IndexName': '日用化工', 'components': 19, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30043', 'IndexName': 'AMAC饮料', 'components': 42, 'launch_date': '2013-01-21'},
],
"辅料":[
    {'IndexCode': '881231', 'IndexName': '化学制药', 'components': 135, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"疫苗":[
    {'IndexCode': '880557', 'IndexName': '生物疫苗', 'components': 70, 'launch_date': '2025-09-09'},
    {'IndexCode': '931992', 'IndexName': '疫苗生物', 'components': 42, 'launch_date': '2013-07-15'},
],
"体外诊断":[
    {'IndexCode': '881241', 'IndexName': '医疗器械', 'components': 97, 'launch_date': '2025-09-09'},
    {'IndexCode': '931440', 'IndexName': '创新药30', 'components': 30, 'launch_date': '2020-04-21'},
],
"化妆品制造及其他":[
    {'IndexCode': '881162', 'IndexName': '饰品', 'components': 15, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30043', 'IndexName': 'AMAC饮料', 'components': 42, 'launch_date': '2013-01-21'},
],
"品牌化妆品":[
    {'IndexCode': '881162', 'IndexName': '饰品', 'components': 15, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30043', 'IndexName': 'AMAC饮料', 'components': 42, 'launch_date': '2013-01-21'},
],
"线下药店":[
    {'IndexCode': '881252', 'IndexName': '医药商业', 'components': 37, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30054', 'IndexName': 'AMAC医药', 'components': 271, 'launch_date': '2013-01-21'},
],
"医疗研发外包":[
    {'IndexCode': '881247', 'IndexName': '医疗服务', 'components': 54, 'launch_date': '2025-09-09'},
    {'IndexCode': '931440', 'IndexName': '创新药30', 'components': 30, 'launch_date': '2020-04-21'},
],
"医美耗材":[
    {'IndexCode': '881241', 'IndexName': '医疗器械', 'components': 97, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30054', 'IndexName': 'AMAC医药', 'components': 271, 'launch_date': '2013-01-21'},
],
"动物保健Ⅲ":[
    {'IndexCode': '881227', 'IndexName': '摩托车及其他', 'components': 16, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"住宅开发":[
    {'IndexCode': '881418', 'IndexName': '房地产开发', 'components': 87, 'launch_date': '2025-09-09'},
    {'IndexCode': '931775', 'IndexName': '房地产', 'components': 78, 'launch_date': '2013-07-15'},
],
"园林工程":[
    {'IndexCode': '881410', 'IndexName': '专业工程', 'components': 43, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11042', 'IndexName': 'AMAC建筑', 'components': 76, 'launch_date': '2009-06-15'},
],
"玻璃制造":[
    {'IndexCode': '880347', 'IndexName': '玻璃', 'components': 18, 'launch_date': '2025-09-09'},
    {'IndexCode': '931009', 'IndexName': '建筑材料', 'components': 41, 'launch_date': '2013-07-15'},
],
"冰洗":[
    {'IndexCode': '881184', 'IndexName': '白色家电', 'components': 10, 'launch_date': '2025-09-09'},
    {'IndexCode': '930697', 'IndexName': '家用电器', 'components': 67, 'launch_date': '2015-07-07'},
],
"钟表珠宝":[
    {'IndexCode': '881162', 'IndexName': '饰品', 'components': 15, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30046', 'IndexName': 'AMAC皮革', 'components': 9, 'launch_date': '2013-01-21'},
],
"商业地产":[
    {'IndexCode': '881418', 'IndexName': '房地产开发', 'components': 87, 'launch_date': '2025-09-09'},
    {'IndexCode': '931775', 'IndexName': '房地产', 'components': 78, 'launch_date': '2013-07-15'},
],
"其他专业工程":[
    {'IndexCode': '881410', 'IndexName': '专业工程', 'components': 43, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11042', 'IndexName': 'AMAC建筑', 'components': 76, 'launch_date': '2009-06-15'},
],
"炼油化工":[
    {'IndexCode': '881011', 'IndexName': '石油化工', 'components': 18, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30052', 'IndexName': 'AMAC石化', 'components': 13, 'launch_date': '2013-01-21'},
],
"铅锌":[
    {'IndexCode': '880327', 'IndexName': '铅锌', 'components': 14, 'launch_date': '2025-09-09'},
    {'IndexCode': '930708', 'IndexName': '中证有色', 'components': 60, 'launch_date': '2015-07-13'},
],
"水泥制造":[
    {'IndexCode': '881091', 'IndexName': '水泥', 'components': 23, 'launch_date': '2025-09-09'},
    {'IndexCode': '931009', 'IndexName': '建筑材料', 'components': 41, 'launch_date': '2013-07-15'},
],
"家电零部件Ⅲ":[
    {'IndexCode': '881198', 'IndexName': '家电零部件', 'components': 27, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30066', 'IndexName': 'AMAC电子', 'components': 593, 'launch_date': '2013-01-21'},
],
"粘胶":[
    {'IndexCode': '881019', 'IndexName': '化纤', 'components': 31, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30055', 'IndexName': 'AMAC化纤', 'components': 20, 'launch_date': '2013-01-21'},
],
"大宗用纸":[
    {'IndexCode': '881167', 'IndexName': '造纸', 'components': 28, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30049', 'IndexName': 'AMAC造纸', 'components': 37, 'launch_date': '2013-01-21'},
],
"基建市政工程":[
    {'IndexCode': '881407', 'IndexName': '基础建设', 'components': 41, 'launch_date': '2025-09-09'},
    {'IndexCode': '930608', 'IndexName': '中证基建', 'components': 50, 'launch_date': '2015-03-31'},
],
"百货":[
    {'IndexCode': '880407', 'IndexName': '百货', 'components': 35, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11045', 'IndexName': 'AMAC批零', 'components': 167, 'launch_date': '2009-06-15'},
],
"钛白粉":[
    {'IndexCode': '881034', 'IndexName': '化学制品', 'components': 143, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"涂料油墨":[
    {'IndexCode': '880340', 'IndexName': '染料涂料', 'components': 34, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"白酒Ⅲ":[
    {'IndexCode': '880381', 'IndexName': '白酒', 'components': 20, 'launch_date': '2025-09-09'},
    {'IndexCode': '399997', 'IndexName': '中证白酒', 'components': 19, 'launch_date': '2015-01-21'},
],
"综合乘用车":[
    {'IndexCode': '880391', 'IndexName': '汽车整车', 'components': 22, 'launch_date': '2025-09-09'},
    {'IndexCode': '931008', 'IndexName': '汽车指数', 'components': 50, 'launch_date': '2013-07-15'},
],
"轮胎轮毂":[
    {'IndexCode': '880392', 'IndexName': '汽车配件', 'components': 250, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30063', 'IndexName': 'AMAC汽车', 'components': 178, 'launch_date': '2013-01-21'},
],
"塑料包装":[
    {'IndexCode': '881177', 'IndexName': '家居用品', 'components': 72, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30044', 'IndexName': 'AMAC纺织', 'components': 35, 'launch_date': '2013-01-21'},
],
"焦炭Ⅲ":[
    {'IndexCode': '881005', 'IndexName': '焦炭加工', 'components': 7, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30052', 'IndexName': 'AMAC石化', 'components': 13, 'launch_date': '2013-01-21'},
],
"棉纺":[
    {'IndexCode': '881151', 'IndexName': '纺织制造', 'components': 34, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30044', 'IndexName': 'AMAC纺织', 'components': 35, 'launch_date': '2013-01-21'},
],
"啤酒":[
    {'IndexCode': '880382', 'IndexName': '啤酒', 'components': 8, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30043', 'IndexName': 'AMAC饮料', 'components': 42, 'launch_date': '2013-01-21'},
],
"汽车经销商":[
    {'IndexCode': '881224', 'IndexName': '汽车服务', 'components': 9, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11045', 'IndexName': 'AMAC批零', 'components': 167, 'launch_date': '2009-06-15'},
],
"钢铁管材":[
    {'IndexCode': '881065', 'IndexName': '普钢', 'components': 24, 'launch_date': '2025-09-09'},
    {'IndexCode': '931009', 'IndexName': '建筑材料', 'components': 41, 'launch_date': '2013-07-15'},
],
"工程咨询服务Ⅲ":[
    {'IndexCode': '881415', 'IndexName': '工程咨询服务', 'components': 43, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11042', 'IndexName': 'AMAC建筑', 'components': 76, 'launch_date': '2009-06-15'},
],
"锦纶":[
    {'IndexCode': '881019', 'IndexName': '化纤', 'components': 31, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30055', 'IndexName': 'AMAC化纤', 'components': 20, 'launch_date': '2013-01-21'},
],
"瓷砖地板":[
    {'IndexCode': '881097', 'IndexName': '装饰建材', 'components': 41, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30048', 'IndexName': 'AMAC家具', 'components': 20, 'launch_date': '2013-01-21'},
],
"摩托车":[
    {'IndexCode': '880394', 'IndexName': '摩托车', 'components': 12, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30063', 'IndexName': 'AMAC汽车', 'components': 178, 'launch_date': '2013-01-21'},
],
"涤纶":[
    {'IndexCode': '881019', 'IndexName': '化纤', 'components': 31, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30055', 'IndexName': 'AMAC化纤', 'components': 20, 'launch_date': '2013-01-21'},
],
"焦煤":[
    {'IndexCode': '881005', 'IndexName': '焦炭加工', 'components': 7, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30052', 'IndexName': 'AMAC石化', 'components': 13, 'launch_date': '2013-01-21'},
],
"其他纺织":[
    {'IndexCode': '881151', 'IndexName': '纺织制造', 'components': 34, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30044', 'IndexName': 'AMAC纺织', 'components': 35, 'launch_date': '2013-01-21'},
],
"其他小金属":[
    {'IndexCode': '880329', 'IndexName': '小金属', 'components': 63, 'launch_date': '2025-09-09'},
    {'IndexCode': '930708', 'IndexName': '中证有色', 'components': 60, 'launch_date': '2015-07-13'},
],
"油气开采Ⅲ":[
    {'IndexCode': '881007', 'IndexName': '油气开采', 'components': 6, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30198', 'IndexName': '油气产业', 'components': 60, 'launch_date': '2013-07-15'},
],
"生活用纸":[
    {'IndexCode': '881167', 'IndexName': '造纸', 'components': 28, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30049', 'IndexName': 'AMAC造纸', 'components': 37, 'launch_date': '2013-01-21'},
],
"炭黑":[
    {'IndexCode': '881034', 'IndexName': '化学制品', 'components': 143, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"非运动服装":[
    {'IndexCode': '881157', 'IndexName': '服装家纺', 'components': 57, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30045', 'IndexName': 'AMAC服装', 'components': 29, 'launch_date': '2013-01-21'},
],
"其他家居用品":[
    {'IndexCode': '881177', 'IndexName': '家居用品', 'components': 72, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30048', 'IndexName': 'AMAC家具', 'components': 20, 'launch_date': '2013-01-21'},
],
"预加工食品":[
    {'IndexCode': '881144', 'IndexName': '食品加工', 'components': 38, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"烘焙食品":[
    {'IndexCode': '881140', 'IndexName': '休闲食品', 'components': 20, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"娱乐用品":[
    {'IndexCode': '881180', 'IndexName': '文娱用品', 'components': 19, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
"工程机械器件":[
    {'IndexCode': '880439', 'IndexName': '机械基件', 'components': 130, 'launch_date': '2025-09-09'},
    {'IndexCode': '931752', 'IndexName': '工程机械主题', 'components': 50, 'launch_date': '2021-09-27'},
],
"跨境物流":[
    {'IndexCode': '881452', 'IndexName': '物流', 'components': 47, 'launch_date': '2025-09-09'},
    {'IndexCode': '930716', 'IndexName': 'CS物流', 'components': 50, 'launch_date': '2015-07-31'},
],
"运动服装":[
    {'IndexCode': '881157', 'IndexName': '服装家纺', 'components': 57, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30045', 'IndexName': 'AMAC服装', 'components': 29, 'launch_date': '2013-01-21'},
],
"合成树脂":[
    {'IndexCode': '881034', 'IndexName': '化学制品', 'components': 143, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"厨房小家电":[
    {'IndexCode': '881190', 'IndexName': '小家电', 'components': 26, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"成品家居":[
    {'IndexCode': '881177', 'IndexName': '家居用品', 'components': 72, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30048', 'IndexName': 'AMAC家具', 'components': 20, 'launch_date': '2013-01-21'},
],
"其他橡胶制品":[
    {'IndexCode': '881051', 'IndexName': '橡胶', 'components': 21, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30056', 'IndexName': 'AMAC橡胶', 'components': 103, 'launch_date': '2013-01-21'},
],
"其他化学纤维":[
    {'IndexCode': '881019', 'IndexName': '化纤', 'components': 31, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30055', 'IndexName': 'AMAC化纤', 'components': 20, 'launch_date': '2013-01-21'},
],
"特种纸":[
    {'IndexCode': '881167', 'IndexName': '造纸', 'components': 28, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30049', 'IndexName': 'AMAC造纸', 'components': 37, 'launch_date': '2013-01-21'},
],
"厨房电器":[
    {'IndexCode': '881194', 'IndexName': '厨卫电器', 'components': 9, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"卫浴制品":[
    {'IndexCode': '881177', 'IndexName': '家居用品', 'components': 72, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30048', 'IndexName': 'AMAC家具', 'components': 20, 'launch_date': '2013-01-21'},
],
"文化用品":[
    {'IndexCode': '881180', 'IndexName': '文娱用品', 'components': 19, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30051', 'IndexName': 'AMAC文教', 'components': 20, 'launch_date': '2013-01-21'},
],
"其他塑料制品":[
    {'IndexCode': '881044', 'IndexName': '塑料', 'components': 93, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30044', 'IndexName': 'AMAC纺织', 'components': 35, 'launch_date': '2013-01-21'},
],
"纺织化学制品":[
    {'IndexCode': '881034', 'IndexName': '化学制品', 'components': 143, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"耐火材料":[
    {'IndexCode': '881091', 'IndexName': '水泥', 'components': 23, 'launch_date': '2025-09-09'},
    {'IndexCode': '931009', 'IndexName': '建筑材料', 'components': 41, 'launch_date': '2013-07-15'},
],
"钢结构":[
    {'IndexCode': '881407', 'IndexName': '基础建设', 'components': 41, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11042', 'IndexName': 'AMAC建筑', 'components': 76, 'launch_date': '2009-06-15'},
],
"化学工程":[
    {'IndexCode': '881034', 'IndexName': '化学制品', 'components': 143, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"聚氨酯":[
    {'IndexCode': '880975', 'IndexName': '有机硅概念', 'components': 43, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"防水材料":[
    {'IndexCode': '881097', 'IndexName': '装饰建材', 'components': 41, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30048', 'IndexName': 'AMAC家具', 'components': 20, 'launch_date': '2013-01-21'},
],
"家纺":[
    {'IndexCode': '881157', 'IndexName': '服装家纺', 'components': 57, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30045', 'IndexName': 'AMAC服装', 'components': 29, 'launch_date': '2013-01-21'},
],
"有机硅":[
    {'IndexCode': '880975', 'IndexName': '有机硅概念', 'components': 43, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"改性塑料":[
    {'IndexCode': '881044', 'IndexName': '塑料', 'components': 93, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30044', 'IndexName': 'AMAC纺织', 'components': 35, 'launch_date': '2013-01-21'},
],
"氟化工":[
    {'IndexCode': '880714', 'IndexName': '氟概念', 'components': 37, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"胶黏剂及胶带":[
    {'IndexCode': '881034', 'IndexName': '化学制品', 'components': 143, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"熟食":[
    {'IndexCode': '881140', 'IndexName': '休闲食品', 'components': 20, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"个护小家电":[
    {'IndexCode': '881190', 'IndexName': '小家电', 'components': 26, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"清洁小家电":[
    {'IndexCode': '881190', 'IndexName': '小家电', 'components': 26, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"综合包装":[
    {'IndexCode': '881171', 'IndexName': '包装印刷', 'components': 48, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30049', 'IndexName': 'AMAC造纸', 'components': 37, 'launch_date': '2013-01-21'},
],
"无机盐":[
    {'IndexCode': '881034', 'IndexName': '化学制品', 'components': 143, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30053', 'IndexName': 'AMAC化学', 'components': 296, 'launch_date': '2013-01-21'},
],
"其他饰品":[
    {'IndexCode': '881162', 'IndexName': '饰品', 'components': 15, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30046', 'IndexName': 'AMAC皮革', 'components': 9, 'launch_date': '2013-01-21'},
],
"印染":[
    {'IndexCode': '881151', 'IndexName': '纺织制造', 'components': 34, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30044', 'IndexName': 'AMAC纺织', 'components': 35, 'launch_date': '2013-01-21'},
],
"房地产综合服务":[
    {'IndexCode': '881422', 'IndexName': '房产服务', 'components': 9, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11047', 'IndexName': 'AMAC地产', 'components': 87, 'launch_date': '2009-06-15'},
],
"产业地产":[
    {'IndexCode': '881418', 'IndexName': '房地产开发', 'components': 87, 'launch_date': '2025-09-09'},
    {'IndexCode': '931775', 'IndexName': '房地产', 'components': 78, 'launch_date': '2013-07-15'},
],
"房屋建设Ⅲ":[
    {'IndexCode': '881406', 'IndexName': '房屋建设', 'components': 8, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11042', 'IndexName': 'AMAC建筑', 'components': 76, 'launch_date': '2009-06-15'},
],
"股份制银行Ⅲ":[
    {'IndexCode': '000134', 'IndexName': '上证银行', 'components': 26, 'launch_date': '2012-05-29'},
    {'IndexCode': '399986', 'IndexName': '中证银行', 'components': 42, 'launch_date': '2013-07-15'},
],
"商业物业经营":[
    {'IndexCode': '881204', 'IndexName': '商业物业经营', 'components': 17, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11047', 'IndexName': 'AMAC地产', 'components': 87, 'launch_date': '2009-06-15'},
],
"综合Ⅲ":[
    {'IndexCode': '881478', 'IndexName': '综合类', 'components': 17, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11050', 'IndexName': 'AMAC综企', 'components': 31, 'launch_date': '2009-06-15'},
],
"港口":[
    {'IndexCode': '880468', 'IndexName': '港口', 'components': 16, 'launch_date': '2025-09-09'},
    {'IndexCode': '932536', 'IndexName': '航运发展', 'components': 50, 'launch_date': '2025-06-18'},
],
"机场":[
    {'IndexCode': '880467', 'IndexName': '机场', 'components': 5, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11043', 'IndexName': 'AMAC交运', 'components': 102, 'launch_date': '2009-06-15'},
],
"油品石化贸易":[
    {'IndexCode': '881206', 'IndexName': '贸易', 'components': 22, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11045', 'IndexName': 'AMAC批零', 'components': 167, 'launch_date': '2009-06-15'},
],
"航空运输":[
    {'IndexCode': '880430', 'IndexName': '航空', 'components': 52, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11043', 'IndexName': 'AMAC交运', 'components': 102, 'launch_date': '2009-06-15'},
],
"培训教育":[
    {'IndexCode': '880908', 'IndexName': '职业教育', 'components': 124, 'launch_date': '2025-09-09'},
    {'IndexCode': '931456', 'IndexName': '中国教育', 'components': 30, 'launch_date': '2020-04-21'},
],
"贸易Ⅲ":[
    {'IndexCode': '881206', 'IndexName': '贸易', 'components': 22, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11045', 'IndexName': 'AMAC批零', 'components': 167, 'launch_date': '2009-06-15'},
],
"证券Ⅲ":[
    {'IndexCode': '399975', 'IndexName': '证券公司', 'components': 49, 'launch_date': '2013-07-15'},
    {'IndexCode': 'H30086', 'IndexName': '800金融', 'components': 90, 'launch_date': '2013-05-09'},
],
"高速公路":[
    {'IndexCode': '880463', 'IndexName': '公路', 'components': 3, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11043', 'IndexName': 'AMAC交运', 'components': 102, 'launch_date': '2009-06-15'},
],
"航运":[
    {'IndexCode': '880461', 'IndexName': '水运', 'components': 19, 'launch_date': '2025-09-09'},
    {'IndexCode': '932536', 'IndexName': '航运发展', 'components': 50, 'launch_date': '2025-06-18'},
],
"铁路运输":[
    {'IndexCode': '880460', 'IndexName': '铁路', 'components': 7, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11043', 'IndexName': 'AMAC交运', 'components': 102, 'launch_date': '2009-06-15'},
],
"房产租赁经纪":[
    {'IndexCode': '881422', 'IndexName': '房产服务', 'components': 9, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11047', 'IndexName': 'AMAC地产', 'components': 87, 'launch_date': '2009-06-15'},
],
"信托":[
    {'IndexCode': '881396', 'IndexName': '多元金融', 'components': 26, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11046', 'IndexName': 'AMAC金融', 'components': 120, 'launch_date': '2009-06-15'},
],
"营销代理":[
    {'IndexCode': '881370', 'IndexName': '广告营销', 'components': 32, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11045', 'IndexName': 'AMAC批零', 'components': 167, 'launch_date': '2009-06-15'},
],
"城商行Ⅲ":[
    {'IndexCode': '000134', 'IndexName': '上证银行', 'components': 26, 'launch_date': '2012-05-29'},
    {'IndexCode': '399986', 'IndexName': '中证银行', 'components': 42, 'launch_date': '2013-07-15'},
],
"期货":[
    {'IndexCode': '881395', 'IndexName': '保险', 'components': 6, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11046', 'IndexName': 'AMAC金融', 'components': 120, 'launch_date': '2009-06-15'},
],
"其他多元金融":[
    {'IndexCode': '881396', 'IndexName': '多元金融', 'components': 26, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11046', 'IndexName': 'AMAC金融', 'components': 120, 'launch_date': '2009-06-15'},
],
"国际工程":[
    {'IndexCode': '881407', 'IndexName': '基础建设', 'components': 41, 'launch_date': '2025-09-09'},
    {'IndexCode': '930608', 'IndexName': '中证基建', 'components': 50, 'launch_date': '2015-03-31'},
],
"租赁":[
    {'IndexCode': '881396', 'IndexName': '多元金融', 'components': 26, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11046', 'IndexName': 'AMAC金融', 'components': 120, 'launch_date': '2009-06-15'},
],
"资产管理":[
    {'IndexCode': '881396', 'IndexName': '多元金融', 'components': 26, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11046', 'IndexName': 'AMAC金融', 'components': 120, 'launch_date': '2009-06-15'},
],
"原材料供应链服务":[
    {'IndexCode': '881452', 'IndexName': '物流', 'components': 47, 'launch_date': '2025-09-09'},
    {'IndexCode': '930716', 'IndexName': 'CS物流', 'components': 50, 'launch_date': '2015-07-31'},
],
"中间产品及消费品供应链服务":[
    {'IndexCode': '881452', 'IndexName': '物流', 'components': 47, 'launch_date': '2025-09-09'},
    {'IndexCode': '930716', 'IndexName': 'CS物流', 'components': 50, 'launch_date': '2015-07-31'},
],
"人力资源服务":[
    {'IndexCode': '881436', 'IndexName': '专业服务', 'components': 34, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11045', 'IndexName': 'AMAC批零', 'components': 167, 'launch_date': '2009-06-15'},
],
"会展服务":[
    {'IndexCode': '881436', 'IndexName': '专业服务', 'components': 34, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11045', 'IndexName': 'AMAC批零', 'components': 167, 'launch_date': '2009-06-15'},
],
"其他专业服务":[
    {'IndexCode': '881436', 'IndexName': '专业服务', 'components': 34, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11045', 'IndexName': 'AMAC批零', 'components': 167, 'launch_date': '2009-06-15'},
],
"火力发电":[
    {'IndexCode': '880307', 'IndexName': '火力发电', 'components': 31, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30199', 'IndexName': '电力指数', 'components': 55, 'launch_date': '2013-07-15'},
],
"固废治理":[
    {'IndexCode': '880456', 'IndexName': '环境保护', 'components': 121, 'launch_date': '2025-09-09'},
    {'IndexCode': '930614', 'IndexName': '环保50', 'components': 50, 'launch_date': '2015-04-07'},
],
"风力发电":[
    {'IndexCode': '880582', 'IndexName': '风电', 'components': 378, 'launch_date': '2025-09-09'},
    {'IndexCode': '931672', 'IndexName': '风电产业', 'components': 50, 'launch_date': '2021-04-29'},
],
"动力煤":[
    {'IndexCode': '880307', 'IndexName': '火力发电', 'components': 31, 'launch_date': '2025-09-09'},
    {'IndexCode': '399998', 'IndexName': '中证煤炭', 'components': 30, 'launch_date': '2015-02-13'},
],
"水务及水治理":[
    {'IndexCode': '881468', 'IndexName': '水务', 'components': 15, 'launch_date': '2025-09-09'},
    {'IndexCode': '930614', 'IndexName': '环保50', 'components': 50, 'launch_date': '2015-04-07'},
],
"铝":[
    {'IndexCode': '880326', 'IndexName': '铝', 'components': 31, 'launch_date': '2025-09-09'},
    {'IndexCode': '930708', 'IndexName': '中证有色', 'components': 60, 'launch_date': '2015-07-13'},
],
"热力服务":[
    {'IndexCode': '880455', 'IndexName': '供气供热', 'components': 45, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30199', 'IndexName': '电力指数', 'components': 55, 'launch_date': '2013-07-15'},
],
"铁矿石":[
    {'IndexCode': '880325', 'IndexName': '铜', 'components': 18, 'launch_date': '2025-09-09'},
    {'IndexCode': '930708', 'IndexName': '中证有色', 'components': 60, 'launch_date': '2015-07-13'},
],
"水力发电":[
    {'IndexCode': '880306', 'IndexName': '水力发电', 'components': 21, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30199', 'IndexName': '电力指数', 'components': 55, 'launch_date': '2013-07-15'},
],
"核力发电":[
    {'IndexCode': '880306', 'IndexName': '水力发电', 'components': 21, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30199', 'IndexName': '电力指数', 'components': 55, 'launch_date': '2013-07-15'},
],
"大气治理":[
    {'IndexCode': '880456', 'IndexName': '环境保护', 'components': 121, 'launch_date': '2025-09-09'},
    {'IndexCode': '930614', 'IndexName': '环保50', 'components': 50, 'launch_date': '2015-04-07'},
],
"环保设备Ⅲ":[
    {'IndexCode': '881470', 'IndexName': '环保设备', 'components': 27, 'launch_date': '2025-09-09'},
    {'IndexCode': '930614', 'IndexName': '环保50', 'components': 50, 'launch_date': '2015-04-07'},
],
"综合环境治理":[
    {'IndexCode': '880456', 'IndexName': '环境保护', 'components': 121, 'launch_date': '2025-09-09'},
    {'IndexCode': '930614', 'IndexName': '环保50', 'components': 50, 'launch_date': '2015-04-07'},
],
"电视广播Ⅲ":[
    {'IndexCode': '881384', 'IndexName': '广播电视', 'components': 14, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
"酒店":[
    {'IndexCode': '881429', 'IndexName': '酒店餐饮', 'components': 9, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11045', 'IndexName': 'AMAC批零', 'components': 167, 'launch_date': '2009-06-15'},
],
"自然景区":[
    {'IndexCode': '880426', 'IndexName': '旅游景点', 'components': 17, 'launch_date': '2025-09-09'},
    {'IndexCode': '930633', 'IndexName': '中证旅游', 'components': 40, 'launch_date': '2015-05-08'},
],
"旅游综合":[
    {'IndexCode': '880425', 'IndexName': '旅游服务', 'components': 7, 'launch_date': '2025-09-09'},
    {'IndexCode': '930633', 'IndexName': '中证旅游', 'components': 40, 'launch_date': '2015-05-08'},
],
"肉制品":[
    {'IndexCode': '881139', 'IndexName': '调味品', 'components': 18, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"广告媒体":[
    {'IndexCode': '881370', 'IndexName': '广告营销', 'components': 32, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
"保健品":[
    {'IndexCode': '881136', 'IndexName': '饮料乳品', 'components': 30, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30043', 'IndexName': 'AMAC饮料', 'components': 42, 'launch_date': '2013-01-21'},
],
"图片媒体":[
    {'IndexCode': '881376', 'IndexName': '数字媒体', 'components': 10, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
"零食":[
    {'IndexCode': '881140', 'IndexName': '休闲食品', 'components': 20, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"大众出版":[
    {'IndexCode': '881380', 'IndexName': '出版业', 'components': 29, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
"餐饮":[
    {'IndexCode': '880425', 'IndexName': '旅游服务', 'components': 7, 'launch_date': '2025-09-09'},
    {'IndexCode': '399238', 'IndexName': '餐饮指数', 'components': 0, 'launch_date': '2013-03-04'},
],
"软饮料":[
    {'IndexCode': '881136', 'IndexName': '饮料乳品', 'components': 30, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30043', 'IndexName': 'AMAC饮料', 'components': 42, 'launch_date': '2013-01-21'},
],
"影视动漫制作":[
    {'IndexCode': '880420', 'IndexName': '影视音像', 'components': 36, 'launch_date': '2025-09-09'},
    {'IndexCode': '930781', 'IndexName': '中证影视', 'components': 33, 'launch_date': '2016-02-04'},
],
"其他酒类":[
    {'IndexCode': '880383', 'IndexName': '红黄酒', 'components': 9, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30043', 'IndexName': 'AMAC饮料', 'components': 42, 'launch_date': '2013-01-21'},
],
"超市":[
    {'IndexCode': '880408', 'IndexName': '超市连锁', 'components': 8, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11045', 'IndexName': 'AMAC批零', 'components': 167, 'launch_date': '2009-06-15'},
],
"游戏Ⅲ":[
    {'IndexCode': '880590', 'IndexName': '网络游戏', 'components': 103, 'launch_date': '2025-09-09'},
    {'IndexCode': '930901', 'IndexName': '动漫游戏', 'components': 26, 'launch_date': '2016-10-18'},
],
"乳品":[
    {'IndexCode': '881136', 'IndexName': '饮料乳品', 'components': 30, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30043', 'IndexName': 'AMAC饮料', 'components': 42, 'launch_date': '2013-01-21'},
],
"综合电商":[
    {'IndexCode': '880941', 'IndexName': '跨境电商', 'components': 315, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30037', 'IndexName': 'AMAC商务', 'components': 64, 'launch_date': '2013-01-21'},
],
"学历教育":[
    {'IndexCode': '880908', 'IndexName': '职业教育', 'components': 124, 'launch_date': '2025-09-09'},
    {'IndexCode': '931456', 'IndexName': '中国教育', 'components': 30, 'launch_date': '2020-04-21'},
],
"门户网站":[
    {'IndexCode': '881376', 'IndexName': '数字媒体', 'components': 10, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
"体育Ⅲ":[
    {'IndexCode': '880596', 'IndexName': '体育概念', 'components': 117, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
"宠物食品":[
    {'IndexCode': '880707', 'IndexName': '宠物经济', 'components': 114, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H30042', 'IndexName': 'AMAC食品', 'components': 68, 'launch_date': '2013-01-21'},
],
"教育运营及其他":[
    {'IndexCode': '881428', 'IndexName': '教育培训', 'components': 17, 'launch_date': '2025-09-09'},
    {'IndexCode': '931456', 'IndexName': '中国教育', 'components': 30, 'launch_date': '2020-04-21'},
],
"院线":[
    {'IndexCode': '881373', 'IndexName': '影视院线', 'components': 20, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
"其他数字媒体":[
    {'IndexCode': '881376', 'IndexName': '数字媒体', 'components': 10, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
"旅游零售Ⅲ":[
    {'IndexCode': '880425', 'IndexName': '旅游服务', 'components': 7, 'launch_date': '2025-09-09'},
    {'IndexCode': '930633', 'IndexName': '中证旅游', 'components': 40, 'launch_date': '2015-05-08'},
],
"文字媒体":[
    {'IndexCode': '881380', 'IndexName': '出版业', 'components': 29, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
"视频媒体":[
    {'IndexCode': '881376', 'IndexName': '数字媒体', 'components': 10, 'launch_date': '2025-09-09'},
    {'IndexCode': 'H11049', 'IndexName': 'AMAC文体', 'components': 59, 'launch_date': '2009-06-15'},
],
}

#### 四、可视化模块

* 3.1 四层产业链、股票数量及权重

In [ ]:
def plot_industry_treemap_by_main_chain_base(
    industry_to_chain,
    df_merg=None,
    ic_col='IC3',
    show_counts=True,
    show_stock_count=True,
    show_weight=True,
    size_by='w',  # 'w' for weight (median), 's' for stock count (sum)
    color_scale='Plotly'
):
    """
    生成四层产业链 Treemap，按主产业链配色。
    - 节点大小可选：'w' → 权重（上层节点权重 = 下属行业中位数），'s' → 股票数量（求和）
    - 悬浮提示统一格式：
        {名称}
        股票数量：{N}
        权重：{W}
    - 标签可选显示行业数、股票数、权重
    
    Parameters:
    ----------
    industry_to_chain : dict
        行业字典，应包含 '权重' 字段
    df_merg : pd.DataFrame or None
        股票数据，用于统计股票数量
    ic_col : str
        行业列名
    show_counts : bool
        是否在标签中显示下属行业数量
    show_stock_count : bool
        是否在标签中显示股票数量
    show_weight : bool
        是否在标签中显示权重
    size_by : str
        'w' → 节点大小 = 权重（中位数）；'s' → 节点大小 = 股票数量（求和）
    color_scale : str
        配色方案
    """
    if size_by not in ('w', 's'):
        raise ValueError("size_by must be 'w' (weight) or 's' (stock count)")

    # === 1. 构建路径结构 ===
    nodes = {}
    for industry, info in industry_to_chain.items():
        main = info["主产业链"]
        sub = info["子产业链"]
        level = info["层级"]
        key = (main, sub, level)
        nodes.setdefault(key, []).append(industry)

    # === 2. 获取权重和股票数 ===
    industry_weight = {ind: float(info.get("权重", 1.0)) for ind, info in industry_to_chain.items()}
    
    if df_merg is not None:
        stock_counts = df_merg[ic_col].value_counts()
        industry_stock_count = {ind: int(stock_counts.get(ind, 0)) for ind in industry_to_chain}
    else:
        industry_stock_count = {ind: 0 for ind in industry_to_chain}

    # === 3. 聚合各层级：股票数量（sum），权重（median）===
    # --- 路径层级（叶子父节点）---
    path_stock_sum = {}
    path_weight_median = {}
    for (main, sub, level), industries in nodes.items():
        stocks = [industry_stock_count[ind] for ind in industries]
        weights = [industry_weight[ind] for ind in industries]
        path_stock_sum[(main, sub, level)] = sum(stocks)
        path_weight_median[(main, sub, level)] = float(np.median(weights))

    # --- 主产业链 ---
    main_chains = sorted(set(info["主产业链"] for info in industry_to_chain.values()))
    main_stock_sum = {}
    main_weight_median = {}
    for main in main_chains:
        inds = [ind for ind, info in industry_to_chain.items() if info["主产业链"] == main]
        stocks = [industry_stock_count[ind] for ind in inds]
        weights = [industry_weight[ind] for ind in inds]
        main_stock_sum[main] = sum(stocks)
        main_weight_median[main] = float(np.median(weights)) if weights else 1.0

    # --- 子产业链 ---
    sub_stock_sum = defaultdict(int)
    sub_industries = defaultdict(list)
    for (main, sub, level), industries in nodes.items():
        if sub is not None:
            key = (main, sub)
            sub_stock_sum[key] += path_stock_sum[(main, sub, level)]
            sub_industries[key].extend(industries)

    sub_weight_median = {}
    for key, inds in sub_industries.items():
        weights = [industry_weight[ind] for ind in inds]
        sub_weight_median[key] = float(np.median(weights)) if weights else 1.0

    # --- 全局总计 ---
    total_stock = sum(main_stock_sum.values())
    total_weight_median = float(np.median(list(industry_weight.values())))

    # === 4. 配色 ===
    try:
        import plotly.colors as pc
        color_list = getattr(pc.qualitative, color_scale, pc.qualitative.Plotly)
    except:
        from plotly.colors import qualitative
        color_list = qualitative.Plotly
    main_color_map = {main: color_list[i % len(color_list)] for i, main in enumerate(main_chains)}

    # === 5. 构建节点 ===
    labels, parents, values, ids, colors = [], [], [], [], []

    def build_label(name, industry_cnt=None, stock=None, weight=None):
        parts = [name]
        if show_counts and industry_cnt is not None:
            parts.append(f"[行业:{industry_cnt}]")
        if show_stock_count and stock is not None:
            parts.append(f"(股票：{stock})")
        if show_weight and weight is not None:
            parts.append(f"(权重：{weight:.2f})")
        return " ".join(parts)

    # 根节点
    root_id = "ROOT"
    labels.append(build_label("产业链全景", len(industry_to_chain), total_stock, total_weight_median))
    parents.append("")
    values.append(total_weight_median if size_by == 'w' else total_stock)
    ids.append(root_id)
    colors.append("lightgrey")

    # 主产业链
    for main in main_chains:
        node_id = f"MAIN|{main}"
        cnt = sum(1 for info in industry_to_chain.values() if info["主产业链"] == main)
        w_val = main_weight_median[main]
        s_val = main_stock_sum[main]
        labels.append(build_label(main, cnt, s_val, w_val))
        parents.append(root_id)
        values.append(w_val if size_by == 'w' else s_val)
        ids.append(node_id)
        colors.append(main_color_map[main])

    # 子产业链
    for (main, sub), s_val in sub_stock_sum.items():
        node_id = f"SUB|{main}|{sub}"
        cnt = len(sub_industries[(main, sub)])
        w_val = sub_weight_median[(main, sub)]
        labels.append(build_label(sub, cnt, s_val, w_val))
        parents.append(f"MAIN|{main}")
        values.append(w_val if size_by == 'w' else s_val)
        ids.append(node_id)
        colors.append(main_color_map[main])

    # 层级节点
    for (main, sub, level), s_val in path_stock_sum.items():
        node_id = f"LEVEL|{main}|{sub or 'None'}|{level}"
        cnt = len(nodes[(main, sub, level)])
        w_val = path_weight_median[(main, sub, level)]
        parent_id = f"MAIN|{main}" if sub is None else f"SUB|{main}|{sub}"
        labels.append(build_label(level, cnt, s_val, w_val))
        parents.append(parent_id)
        values.append(w_val if size_by == 'w' else s_val)
        ids.append(node_id)
        colors.append(main_color_map[main])

    # 行业（叶子）
    for (main, sub, level), industries in nodes.items():
        parent_id = f"LEVEL|{main}|{sub or 'None'}|{level}"
        for ind in industries:
            w_val = industry_weight[ind]
            s_val = industry_stock_count[ind]
            labels.append(build_label(ind, stock=s_val, weight=w_val))
            parents.append(parent_id)
            values.append(w_val if size_by == 'w' else s_val)
            ids.append(f"IND|{ind}")
            colors.append(main_color_map[main])

    # === 6. 创建图表 ===
    # 准备 customdata: [stock, weight]
    customdata = []
    # 根
    customdata.append([total_stock, total_weight_median])
    # 主链
    for main in main_chains:
        customdata.append([main_stock_sum[main], main_weight_median[main]])
    # 子链
    for (main, sub) in sub_stock_sum:
        customdata.append([sub_stock_sum[(main, sub)], sub_weight_median[(main, sub)]])
    # 层级
    for key in path_stock_sum:
        customdata.append([path_stock_sum[key], path_weight_median[key]])
    # 行业
    for (main, sub, level), inds in nodes.items():
        for ind in inds:
            customdata.append([industry_stock_count[ind], industry_weight[ind]])

    hover_template = '<b>%{label}</b><br>股票数量：%{customdata[0]}<br>权重： %{customdata[1]:.2f}<extra></extra>'

    fig = go.Figure(go.Treemap(
        ids=ids,
        labels=labels,
        parents=parents,
        values=values,
        customdata=customdata,
        branchvalues="remainder",
        textinfo="label",
        hovertemplate=hover_template,
        maxdepth=4,
        marker=dict(colors=colors, showscale=False)
    ))

    size_desc = "权重（中位数）" if size_by == 'w' else "股票数量"
    fig.update_layout(
        title={'text': f"<b>产业链全景概览</b> <span style='font-style:italic;font-size:11px'>节点大小<b>{size_desc}</b>决定</span>",
               'x': 0.5, 'font_size': 16},
        height=650,
        margin=dict(t=60, l=20, r=20, b=20),
    )

    return fig

* 3.2 全细节展示

In [ ]:
def visual_width(s):
    """计算字符串在等宽字体下的视觉宽度（中文=2，英文/数字=1）"""
    width = 0
    for ch in str(s):
        if unicodedata.east_asian_width(ch) in ('F', 'W', 'A'):
            width += 2  # 全角字符（中文、全角标点等）
        else:
            width += 1  # 半角字符（英文、数字、半角符号）
    return width

def ljust_visual(text, total_width, fillchar=' '):
    """按视觉宽度左对齐填充"""
    text = str(text)
    current = visual_width(text)
    if current >= total_width:
        return text[:total_width]  # 截断（可选更智能截断）
    return text + fillchar * (total_width - current)

def rjust_visual(text, total_width, fillchar=' '):
    """按视觉宽度右对齐填充"""
    text = str(text)
    current = visual_width(text)
    if current >= total_width:
        return text[:total_width]
    return fillchar * (total_width - current) + text

In [ ]:
def plot_industry_treemap_by_main_chain(
    industry_to_chain,
    df_merg=None,
    ic_col='IC3',
    stock_code_col='StockCode',
    stock_name_col='StockName',
    biz_segment_col='主营构成',
    revenue_col='主营收入',
    rev_ratio_col='收入比例',
    profit_col='主营利润',
    profit_ratio_col='利润比例',
    gross_margin_col='毛利率',
    # ===== 新增市场指标列 =====
    week52_high_col='52周最高',
    week52_low_col='52周最低',
    avg_price_col='均价',
    nav_to_market_col='资产净值/总市值',  # 元为单位，显示时转为亿元
    pb_col='市净率',
    pe_lyr_col='市盈率(静)',
    pe_ttm_col='市盈率(TTM)',
    pe_dynamic_col='市盈率(动)',
    dividend_ttm_col='股息率(TTM)',
    # =========================
    show_counts=True,
    show_stock_count_in_label=True,
    show_weight_in_label=True,
    max_stocks_in_label=5,
    size_by='s',
    color_scale='Plotly'
):
    """
    增强版 Treemap：单行显示所有指标（主营财务 + 9个市场指标）
    
    单行布局（总宽约160字符）：
      代码(6) 名称(8) 主营(18) 收入(8) 占比(6) 利润(8) 利润比(6) 毛利率(6) | 52高(6) 52低(6) 均价(6) 净资(6) 市净(5) 静(4) TTM(5) 动(4) 股息(6)
    
    单位说明：
      • 收入/利润/净资：亿元
      • 占比/毛利率/股息率：%
      • 52高/52低/均价：元
      • 市净率/市盈率：倍数
    """
    if size_by not in ('s', 'w'):
        raise ValueError("size_by must be 's' (stock count) or 'w' (weight)")

    def safe_float(x):
        try:
            return float(x)
        except:
            return 0.0

    # === 1. 构建路径结构 ===
    nodes = {}
    for industry, info in industry_to_chain.items():
        main = info["主产业链"]
        sub = info["子产业链"]
        level = info["层级"]
        key = (main, sub, level)
        nodes.setdefault(key, []).append(industry)

    # === 2. 提取权重（用于大小和显示）===
    industry_weight = {
        ind: float(info.get("权重", 1.0))
        for ind, info in industry_to_chain.items()
    }

    # === 3. 构建行业 -> 股票列表（含财务+市场指标）===
    industry_to_stocks = defaultdict(list)
    if df_merg is not None:
        required_cols = [ic_col, stock_code_col, stock_name_col]
        if not all(col in df_merg.columns for col in required_cols):
            raise ValueError("df_merg 必须包含行业、股票代码、股票名称列")
        
        # 市场指标配置（含特殊处理类型）
        market_columns = [
            (week52_high_col, '52高', 'price'),
            (week52_low_col, '52低', 'price'),
            (avg_price_col, '均价', 'price'),
            (nav_to_market_col, '净资', 'nav'),  # 元 → 亿元
            (pb_col, '市净', 'ratio'),
            (pe_lyr_col, '静', 'pe'),
            (pe_ttm_col, 'TTM', 'pe'),
            (pe_dynamic_col, '动', 'pe'),
            (dividend_ttm_col, '股息', 'dividend')
        ]
        
        def format_market_value(value, col_type):
            """根据指标类型智能格式化，'nav'类型需从元转亿元"""
            try:
                v = float(value)
                if col_type == 'nav':
                    v = v / 1e8  # 元 → 亿元
                    return f"{v:.2f}"
                elif col_type == 'price':
                    return f"{v:.2f}"
                elif col_type == 'ratio':
                    return f"{v:.2f}"
                elif col_type == 'pe':
                    return f"{v:.2f}"
                elif col_type == 'dividend':
                    return f"{v:.2f}"
            except:
                return "N/A"
        
        for _, row in df_merg.iterrows():
            ind = row[ic_col]
            if ind in industry_to_chain:
                rev_raw = safe_float(row.get(revenue_col, 0))
                profit_raw = safe_float(row.get(profit_col, 0))
                rev_ratio_raw = safe_float(row.get(rev_ratio_col, 0))
                profit_ratio_raw = safe_float(row.get(profit_ratio_col, 0))
                margin_raw = safe_float(row.get(gross_margin_col, 0))

                rev_display = f"{rev_raw / 1e8:.2f}"        # 收入：亿元，2位小数
                profit_display = f"{profit_raw / 1e8:.2f}"  # 利润：亿元，2位小数
                rev_ratio_display = f"{rev_ratio_raw * 100:.1f}"   # 收入占比：%
                profit_ratio_display = f"{profit_ratio_raw * 100:.1f}"  # 利润占比：%
                margin_display = f"{margin_raw * 100:.1f}"  # 毛利率：%

                # ===== 提取并格式化市场指标 =====
                market_data = {}
                for col_name, abbr, col_type in market_columns:
                    raw_val = row.get(col_name, np.nan)
                    market_data[abbr] = format_market_value(raw_val, col_type)
                # ==============================
                
                # ===== 主营构成截断处理（30字符硬限制）=====
                biz_raw = str(row.get(biz_segment_col, ''))
                biz_truncated = (biz_raw[:20] + '   ') if len(biz_raw) > 20 else biz_raw
                # ========================================= 
                               
                stock_info = {
                    'code': str(row.get(stock_code_col, '')),
                    'name': str(row.get(stock_name_col, '')),
                    'biz': biz_truncated,
                    # 'biz': str(row.get(biz_segment_col, '')),
                    'rev_display': rev_display,
                    'rev_ratio_display': rev_ratio_display,
                    'profit_display': profit_display,
                    'profit_ratio_display': profit_ratio_display,
                    'margin_display': margin_display,
                    '_rev_raw': rev_raw,
                    '_profit_raw': profit_raw,
                    'market_data': market_data  # 注入市场指标
                }
                industry_to_stocks[ind].append(stock_info)

    # === 4. 排序股票（按收入）===
    for ind in industry_to_stocks:
        industry_to_stocks[ind].sort(key=lambda x: x['_rev_raw'], reverse=True)

    # === 5. 聚合统计：股票数（sum） + 权重（median）===
    industry_stock_count = {ind: len(industry_to_stocks[ind]) for ind in industry_to_chain.keys()}
    
    # 路径层级
    path_stock_sum = {}
    path_weight_median = {}
    for (main, sub, level), inds in nodes.items():
        stocks = [industry_stock_count.get(ind, 0) for ind in inds]
        weights = [industry_weight[ind] for ind in inds]
        path_stock_sum[(main, sub, level)] = sum(stocks)
        path_weight_median[(main, sub, level)] = float(np.median(weights))

    # 主链
    main_chains = sorted(set(info["主产业链"] for info in industry_to_chain.values()))
    main_stock_sum = {}
    main_weight_median = {}
    for main in main_chains:
        inds = [ind for ind, info in industry_to_chain.items() if info["主产业链"] == main]
        stocks = [industry_stock_count.get(ind, 0) for ind in inds]
        weights = [industry_weight[ind] for ind in inds]
        main_stock_sum[main] = sum(stocks)
        main_weight_median[main] = float(np.median(weights)) if weights else 1.0

    # 子链
    sub_stock_sum = defaultdict(int)
    sub_industries = defaultdict(list)
    for (main, sub, level), inds in nodes.items():
        if sub is not None:
            key = (main, sub)
            sub_stock_sum[key] += path_stock_sum[(main, sub, level)]
            sub_industries[key].extend(inds)
    
    sub_weight_median = {}
    for key, inds in sub_industries.items():
        weights = [industry_weight[ind] for ind in inds]
        sub_weight_median[key] = float(np.median(weights)) if weights else 1.0

    # 全局总计
    total_stock = sum(main_stock_sum.values())
    total_weight_median = float(np.median(list(industry_weight.values())))

    # === 6. 配色 ===
    try:
        import plotly.colors as pc
        color_list = getattr(pc.qualitative, color_scale, pc.qualitative.Plotly)
    except:
        from plotly.colors import qualitative
        color_list = qualitative.Plotly
    main_color_map = {main: color_list[i % len(color_list)] for i, main in enumerate(main_chains)}

    # === 7. 构建节点 ===
    labels = []
    parents = []
    values = []  # ← 节点大小
    ids = []
    colors = []
    hover_texts = []

    def build_label(name, industry_cnt=None, stock_cnt=None, weight_val=None):
        parts = [name]
        if show_counts and industry_cnt is not None:
            parts.append(f"[行业:{industry_cnt}")
        if show_stock_count_in_label and stock_cnt is not None:
            parts.append(f"股票:{stock_cnt}")
        if show_weight_in_label and weight_val is not None:
            parts.append(f"权重:{weight_val:.2f}]")
        return " ".join(parts)

    # --- 根节点 ---
    root_id = "ROOT"
    root_label = build_label("产业链全景", len(industry_to_chain), total_stock, total_weight_median)
    labels.append(root_label)
    parents.append("")
    values.append(total_weight_median if size_by == 'w' else total_stock or 1)
    ids.append(root_id)
    colors.append("lightgrey")
    hover_texts.append(f"产业链全景<br>股票数量：{total_stock} <br>权重： {total_weight_median:.2f}")

    # --- 主产业链 ---
    for main in main_chains:
        node_id = f"MAIN|{main}"
        cnt = main_stock_sum[main]
        w_val = main_weight_median[main]
        label = build_label(main, 
                           sum(1 for info in industry_to_chain.values() if info["主产业链"] == main),
                           cnt, w_val)
        labels.append(label)
        parents.append(root_id)
        values.append(w_val if size_by == 'w' else cnt or 1)
        ids.append(node_id)
        colors.append(main_color_map[main])
        hover_texts.append(f"{main}<br>股票数量：{cnt} <br>权重： {w_val:.2f}")

    # --- 子产业链 ---
    for (main, sub), cnt in sub_stock_sum.items():
        node_id = f"SUB|{main}|{sub}"
        w_val = sub_weight_median[(main, sub)]
        industry_cnt = len(sub_industries[(main, sub)])
        label = build_label(sub, industry_cnt, cnt, w_val)
        labels.append(label)
        parents.append(f"MAIN|{main}")
        values.append(w_val if size_by == 'w' else cnt or 1)
        ids.append(node_id)
        colors.append(main_color_map[main])
        hover_texts.append(f"{sub}<br>股票数量：{cnt} <br>权重： {w_val:.2f}")

    # --- 层级节点 ---
    for (main, sub, level), cnt in path_stock_sum.items():
        node_id = f"LEVEL|{main}|{sub or 'None'}|{level}"
        w_val = path_weight_median[(main, sub, level)]
        industry_cnt = len(nodes[(main, sub, level)])
        parent_id = f"MAIN|{main}" if sub is None else f"SUB|{main}|{sub}"
        label = build_label(level, industry_cnt, cnt, w_val)
        labels.append(label)
        parents.append(parent_id)
        values.append(w_val if size_by == 'w' else cnt or 1)
        ids.append(node_id)
        colors.append(main_color_map[main])
        hover_texts.append(f"{level}<br>股票数量：{cnt} <br>权重： {w_val:.2f}")

    # --- 行业（叶子）- 单行显示所有指标 ---
    # 精简列宽设计（总宽约165字符，适配treemap节点）
    col_widths = 10
    widths = {
        'code': 8,    # 代码
        'name': 10,    # 名称
        'biz': 38,    # 主营构成
        'rev': col_widths,     # 收入(亿元)
        'rev_ratio': col_widths,   # 收入占比(%)
        'profit': col_widths,      # 利润(亿元)
        'profit_ratio': col_widths, # 利润占比(%)
        'margin': col_widths,      # 毛利率(%)
        # 市场指标（每项6字符，共54字符）
        'mkt': col_widths
    }
    
    # 单行表头（含分隔符）
    header = (
        ljust_visual("代码", widths['code']) +
        ljust_visual("名称", widths['name']) +
        ljust_visual("主营构成", widths['biz']) +
        ljust_visual("主营收入", widths['rev']) +
        ljust_visual("收入占比", widths['rev_ratio']) +
        ljust_visual("主营利润", widths['profit']) +
        ljust_visual("  利润占比", widths['profit_ratio']) +
        ljust_visual("   毛利率", widths['margin']) +
        # "│" +  # 分隔符
        ljust_visual("    52周最高", widths['mkt']) +
        ljust_visual("   52周最低", widths['mkt']) +
        ljust_visual("     均价", widths['mkt']) +
        ljust_visual("     总市值", widths['mkt']) +
        ljust_visual("    市净率", widths['mkt']) +
        ljust_visual("    市盈率(静)", widths['mkt']) +
        ljust_visual("  市盈率(TTM)", widths['mkt']) +
        ljust_visual(" 市盈率(动)", widths['mkt']) +
        ljust_visual(" 股息率(TTM)", widths['mkt'])
    )

    for (main, sub, level), industries in nodes.items():
        parent_id = f"LEVEL|{main}|None|{level}" if sub is None else f"LEVEL|{main}|{sub}|{level}"
        for ind in industries:
            stocks = industry_to_stocks[ind]
            stock_cnt = len(stocks)
            w_val = industry_weight[ind]

            # 构建标签
            label_lines = []
            first_line = ind
            if show_stock_count_in_label:
                first_line += f" ({stock_cnt})"
            if show_weight_in_label:
                first_line += f" (w={w_val:.2f})"
            label_lines.append(first_line)

            if max_stocks_in_label > 0 and stocks:
                label_lines.append(header)
                for s in stocks[:max_stocks_in_label]:
                    # ===== 单行：主营财务指标 + 市场指标 =====
                    line = (
                        ljust_visual(s['code'][:widths['code']], widths['code']) +
                        ljust_visual(s['name'][:widths['name']], widths['name']) +
                        ljust_visual(s['biz'][:widths['biz']], widths['biz']) +
                        ljust_visual(s['rev_display'], widths['rev']) +
                        ljust_visual(s['rev_ratio_display'], widths['rev_ratio']) +
                        ljust_visual(s['profit_display'], widths['profit']) +
                        ljust_visual(s['profit_ratio_display'], widths['profit_ratio']) +
                        ljust_visual(s['margin_display'], widths['margin']) +
                        # "│" +  # 视觉分隔符
                        ljust_visual(s['market_data'].get('52高', 'N/A'), widths['mkt']) +
                        ljust_visual(s['market_data'].get('52低', 'N/A'), widths['mkt']) +
                        ljust_visual(s['market_data'].get('均价', 'N/A'), widths['mkt']) +
                        ljust_visual(s['market_data'].get('净资', 'N/A'), widths['mkt']) +
                        ljust_visual(s['market_data'].get('市净', 'N/A'), widths['mkt']) +
                        ljust_visual(s['market_data'].get('静', 'N/A'), widths['mkt']) +
                        ljust_visual(s['market_data'].get('TTM', 'N/A'), widths['mkt']) +
                        ljust_visual(s['market_data'].get('动', 'N/A'), widths['mkt']) +
                        ljust_visual(s['market_data'].get('股息', 'N/A'), widths['mkt'])
                    )
                    label_lines.append(line)
                
                if len(stocks) > max_stocks_in_label:
                    label_lines.append(f"... 还有 {len(stocks) - max_stocks_in_label} 家公司")

            labels.append("<br>".join(label_lines))
            parents.append(parent_id)
            values.append(w_val if size_by == 'w' else stock_cnt or 1)
            ids.append(f"IND|{ind}")
            colors.append(main_color_map[main])
            hover_texts.append(f"{ind}<br>股票数量：{stock_cnt} <br>权重： {w_val:.2f}")

    # === 8. 创建图表 ===
    fig = go.Figure(go.Treemap(
        ids=ids,
        labels=labels,
        parents=parents,
        values=values,
        branchvalues="remainder",
        textinfo="label",
        texttemplate="%{label}",
        customdata=hover_texts,
        hovertemplate='%{customdata}<extra></extra>',
        maxdepth=4,
        marker=dict(colors=colors, showscale=False),
        textfont=dict(family="Courier New, monospace", size=11)  # 单行显示可适当增大字号
    ))
    data_point = df_merg['时间'].str[:10].unique()[0]
    size_desc = "权重（中位数）" if size_by == 'w' else "股票数量"
    fig.update_layout(
        title={'text': f'<b>产业链全景详图</b> <span style="font-style:italic;font-size:11px">节点大小<b>{size_desc}</b>决定｜<b>时点</b>({data_point})</span>',
               'x': 0.5, 'font_size': 16},
        height=600,
        margin=dict(t=60, l=20, r=20, b=20)
    )

    return fig

##### 四、 图示分析

* 4.1 四层产业链及股票数量图示

In [ ]:
fig = plot_industry_treemap_by_main_chain_base(
    industry_to_chain=industry_to_chain_weighted,
    df_merg=df_merg,          # ← 传入您的 DataFrame
    ic_col='IC3',             # 行业列名
    show_counts=True,         # 显示原始行业数量（如 [行业:12]）
    show_stock_count=True,
    show_weight=True,
    size_by='w',# 显示股票数量（如 (45)）
    color_scale='Plotly'
)
fig.show()

* 4.2 全细节图示

In [ ]:
fig = plot_industry_treemap_by_main_chain(
    industry_to_chain=industry_to_chain_weighted,
    df_merg=df_merg.apply(lambda x: x.str.strip() if x.dtype == "object" else x),          # ← 传入您的 DataFrame
    ic_col='IC3',             # 行业列名
    show_counts=True,         # 显示原始行业数量（如 [行业:12]）
    max_stocks_in_label=33,
    size_by='s',# 显示股票数量（如 (45)）
    color_scale='Plotly'
)
fig.show()

============================

In [ ]:
df_merg[df_merg['IC3']=='横向通用软件'][['StockCode', 'StockName', 'IC1','IC2','IC3','主营构成', '主营收入',  '收入比例','主营成本','成本比例', '主营利润', '利润比例','毛利率']]

In [ ]:
biz_tmp[biz_tmp['StockCode']=='688796'].sort_values(by=['StockCode','报告日期','收入比例'], ascending=[True,False,False]).head(30)

In [ ]:
ddf  = df_merg.merge(xqStockBas, how='inner', left_on='StockCode', right_on='StockCode')

In [ ]:
df_merg.sort_values(by=['股息率(TTM)'],ascending=False)[['StockCode', 'StockName', '主营构成', '主营收入',  '收入比例','主营成本','成本比例', '主营利润', '利润比例','毛利率', '股息率(TTM)']].head(50)

In [ ]:
import pandas as pd

# 1. 读取Excel（请替换为您的实际文件路径）
df = pd.read_excel("/home/ts/app/TDXapp/tdxAppData/FinaIndexs.xlsx", sheet_name="Sheet1")

# 2. 构建指数信息映射表（关键：处理重复标题行）
# 过滤无效行并重置索引
df_clean = df[df['IndexCode'].notna() & (df['IndexCode'] != 'IndexCode')].copy()
index_map = {
    str(row['IndexCode']).strip(): {
        'IndexName': str(row['IndexName']).strip(),
        'components': int(row['Num']) if pd.notna(row['Num']) else 0,
        'launch_date': str(row['DP']).split()[0] if pd.notna(row['DP']) else "未知"
    }
    for _, row in df_clean.iterrows()
}

# 3. 原始行业-指数映射（您提供的字典）
industry_to_index_raw = industry_to_index

# 4. 生成标准化字典
industry_to_index_standardized = {}
for industry, codes in industry_to_index_raw.items():
    industry_to_index_standardized[industry] = [
        {
            "IndexCode": code,
            "IndexName": index_map.get(code, {}).get("IndexName", "未知指数"),
            "components": index_map.get(code, {}).get("components", 0),
            "launch_date": index_map.get(code, {}).get("launch_date", "未知")
        }
        for code in codes
    ]

# 5. 输出完整字典（可直接复制使用）
import json
print(json.dumps(industry_to_index_standardized, ensure_ascii=False, indent=4))

In [ ]:
print("industry_to_index_standardized = {")
for k, v in industry_to_index_standardized.items():
    print(f'"{k}":[')
    for l in v:
        print(f"    {l},")
    print(f"],")
print('}')

In [ ]:
print("industry_to_index_standardized = {")
for k, v in industry_to_index_standardized.items():
    print(f'"{k}":[')
    for l in v:
        print(f"    {l},")
    print(f"],")
print('}')

In [105]:
from typing import Any, Dict, List, Tuple, Optional
from decimal import Decimal, ROUND_HALF_UP
import math

def compare_nested_dict_strict(
    dict1: Dict[str, List[Dict[str, Any]]],
    dict2: Dict[str, List[Dict[str, Any]]],
    float_tolerance: float = 1e-6,
    ignore_key_order: bool = True,
    ignore_list_order: bool = False,
    case_sensitive: bool = True,
    ignore_missing_keys: bool = False
) -> Tuple[bool, Dict[str, Any]]:
    """
    严格比较两个二层嵌套字典结构
    
    结构要求: {str: [{str: value}, ...]}
    
    参数:
        dict1, dict2: 待比较的字典
        float_tolerance: 浮点数比较容差（默认 1e-6）
        ignore_key_order: 是否忽略字典键顺序（默认 True）
        ignore_list_order: 是否忽略列表顺序（默认 False，严格模式）
        case_sensitive: 字符串比较是否区分大小写（默认 True）
        ignore_missing_keys: 是否忽略缺失键（默认 False，严格模式）
    
    返回:
        (是否相等, 差异详情字典)
    """
    差异 = {
        "顶层键差异": {"仅dict1有": [], "仅dict2有": [], "共有键": []},
        "行业差异": {},
        "统计": {"总行业数": 0, "差异行业数": 0, "总股票数": 0, "差异股票数": 0}
    }
    
    # 1. 比较顶层键
    keys1 = set(dict1.keys())
    keys2 = set(dict2.keys())
    差异["顶层键差异"]["仅dict1有"] = sorted(keys1 - keys2)
    差异["顶层键差异"]["仅dict2有"] = sorted(keys2 - keys1)
    共有键 = keys1 & keys2
    差异["顶层键差异"]["共有键"] = sorted(共有键)
    
    相等 = True
    if keys1 != keys2:
        相等 = False
    
    差异["统计"]["总行业数"] = len(共有键)
    
    # 2. 比较每个行业的列表
    for 行业 in 共有键:
        列表1 = dict1[行业]
        列表2 = dict2[行业]
        行业差异 = _compare_stock_list(
            列表1, 列表2, 行业,
            float_tolerance, ignore_key_order, ignore_list_order,
            case_sensitive, ignore_missing_keys
        )
        
        if 行业差异["相等"] is False:
            相等 = False
            差异["行业差异"][行业] = 行业差异
            差异["统计"]["差异行业数"] += 1
            差异["统计"]["差异股票数"] += 行业差异["差异项数"]
        差异["统计"]["总股票数"] += max(len(列表1), len(列表2))
    
    # 3. 添加缺失行业统计
    if 差异["顶层键差异"]["仅dict1有"] or 差异["顶层键差异"]["仅dict2有"]:
        相等 = False
    
    return 相等, 差异


def _compare_stock_list(
    list1: List[Dict[str, Any]],
    list2: List[Dict[str, Any]],
    行业名称: str,
    float_tolerance: float,
    ignore_key_order: bool,
    ignore_list_order: bool,
    case_sensitive: bool,
    ignore_missing_keys: bool
) -> Dict[str, Any]:
    """比较两个股票列表（列表元素为字典）"""
    差异详情 = {
        "相等": True,
        "列表长度": {"list1": len(list1), "list2": len(list2), "相等": len(list1) == len(list2)},
        "差异项数": 0,
        "项差异": []
    }
    
    # 长度不等直接标记差异
    if len(list1) != len(list2):
        差异详情["相等"] = False
        差异详情["差异项数"] = abs(len(list1) - len(list2))
        return 差异详情
    
    # 智能匹配：若忽略顺序，尝试按唯一键（如 code）匹配
    if ignore_list_order:
        # 尝试提取唯一标识符（按优先级）
        唯一键 = _detect_unique_key(list1, list2)
        if 唯一键:
            list1_sorted = sorted(list1, key=lambda x: str(x.get(唯一键, "")).lower())
            list2_sorted = sorted(list2, key=lambda x: str(x.get(唯一键, "")).lower())
        else:
            # 无唯一键则按字典字符串排序（近似）
            list1_sorted = sorted(list1, key=lambda x: str(sorted(x.items())).lower())
            list2_sorted = sorted(list2, key=lambda x: str(sorted(x.items())).lower())
    else:
        list1_sorted = list1
        list2_sorted = list2
    
    # 逐项比较
    for 索引, (项1, 项2) in enumerate(zip(list1_sorted, list2_sorted)):
        项相等, 项差异 = _compare_stock_item(
            项1, 项2, 索引, float_tolerance, ignore_key_order,
            case_sensitive, ignore_missing_keys
        )
        if not 项相等:
            差异详情["相等"] = False
            差异详情["差异项数"] += 1
            差异详情["项差异"].append(项差异)
    
    return 差异详情


def _compare_stock_item(
    item1: Dict[str, Any],
    item2: Dict[str, Any],
    索引: int,
    float_tolerance: float,
    ignore_key_order: bool,
    case_sensitive: bool,
    ignore_missing_keys: bool
) -> Tuple[bool, Dict[str, Any]]:
    """比较两个股票字典项"""
    差异 = {
        "索引": 索引,
        "键差异": {"仅item1有": [], "仅item2有": [], "共有键": []},
        "值差异": []
    }
    
    keys1 = set(item1.keys())
    keys2 = set(item2.keys())
    差异["键差异"]["仅item1有"] = sorted(keys1 - keys2)
    差异["键差异"]["仅item2有"] = sorted(keys2 - keys1)
    共有键 = keys1 & keys2
    差异["键差异"]["共有键"] = sorted(共有键)
    
    相等 = True
    
    # 检查缺失键（严格模式）
    if (keys1 != keys2) and not ignore_missing_keys:
        相等 = False
    
    # 比较共有键的值
    for 键 in 共有键:
        值1 = item1[键]
        值2 = item2[键]
        值相等, 值详情 = _compare_values(
            值1, 值2, 键, float_tolerance, case_sensitive
        )
        if not 值相等:
            相等 = False
            差异["值差异"].append(值详情)
    
    # 严格模式：缺失键视为差异
    if not ignore_missing_keys and (差异["键差异"]["仅item1有"] or 差异["键差异"]["仅item2有"]):
        相等 = False
    
    return 相等, 差异


def _compare_values(val1: Any, val2: Any, key: str, float_tolerance: float, case_sensitive: bool) -> Tuple[bool, Dict[str, Any]]:
    """比较两个值（支持浮点数容差、字符串大小写）"""
    # 类型不同直接不等
    if type(val1) != type(val2):
        return False, {"键": key, "类型不同": {"val1": type(val1).__name__, "val2": type(val2).__name__}, "值1": val1, "值2": val2}
    
    # 浮点数比较（含 Decimal）
    if isinstance(val1, (float, Decimal)) or isinstance(val2, (float, Decimal)):
        try:
            f1 = float(val1)
            f2 = float(val2)
            相等 = abs(f1 - f2) <= float_tolerance
            return 相等, {"键": key, "差异": abs(f1 - f2), "值1": val1, "值2": val2} if not 相等 else {}
        except:
            pass  # 回退到普通比较
    
    # 字符串比较（可选大小写敏感）
    if isinstance(val1, str) and isinstance(val2, str):
        if not case_sensitive:
            return val1.lower() == val2.lower(), {"键": key, "值1": val1, "值2": val2} if val1.lower() != val2.lower() else {}
    
    # 普通比较
    相等 = val1 == val2
    return 相等, {"键": key, "值1": val1, "值2": val2} if not 相等 else {}


def _detect_unique_key(list1: List[Dict], list2: List[Dict]) -> Optional[str]:
    """尝试检测唯一标识符键（如 'code', 'symbol', 'id'）"""
    候选键 = ["code", "symbol", "stock_code", "id", "ticker"]
    for 键 in 候选键:
        所有值 = [str(item.get(键, "")).strip() for item in list1 + list2 if item.get(键)]
        if len(所有值) == len(set(所有值)) and len(所有值) >= max(len(list1), len(list2)) * 0.8:
            return 键
    return None

In [106]:
def print_comparison_report(差异: Dict[str, Any], 标题1: str = "数据A", 标题2: str = "数据B"):
    """格式化打印差异报告"""
    print("=" * 70)
    print(f"📊 二层字典差异报告")
    print("=" * 70)
    
    # 顶层键差异
    顶层差异 = 差异["顶层键差异"]
    if 顶层差异["仅dict1有"] or 顶层差异["仅dict2有"]:
        print("\n【❌ 顶层键不一致】")
        if 顶层差异["仅dict1有"]:
            print(f"  仅{标题1}有 ({len(顶层差异['仅dict1有'])}个): {', '.join(顶层差异['仅dict1有'])}")
        if 顶层差异["仅dict2有"]:
            print(f"  仅{标题2}有 ({len(顶层差异['仅dict2有'])}个): {', '.join(顶层差异['仅dict2有'])}")
    else:
        print(f"\n【✅ 顶层键一致】共 {len(顶层差异['共有键'])} 个行业")
    
    # 行业差异汇总
    行业差异 = 差异["行业差异"]
    if not 行业差异:
        print(f"\n【✅ 所有行业数据一致】")
        return
    
    print(f"\n【⚠️  行业差异详情】共 {差异['统计']['差异行业数']} / {差异['统计']['总行业数']} 个行业存在差异")
    
    for 行业, 详情 in 行业差异.items():
        print(f"\n  ┌─ 行业: {行业}")
        print(f"  │  列表长度: {标题1}={详情['列表长度']['list1']}, {标题2}={详情['列表长度']['list2']}")
        
        if 详情["列表长度"]["相等"]:
            print(f"  │  差异项数: {详情['差异项数']} / {详情['列表长度']['list1']}")
        else:
            print(f"  │  ❌ 长度不等！差异项数估算: {详情['差异项数']}")
        
        # 打印具体项差异（最多显示3项）
        if 详情["项差异"]:
            print(f"  │  具体差异（前3项）:")
            for i, 项差异 in enumerate(详情["项差异"][:3]):
                索引 = 项差异["索引"]
                键差异 = 项差异["键差异"]
                值差异 = 项差异["值差异"]
                
                # 键差异
                if 键差异["仅item1有"] or 键差异["仅item2有"]:
                    print(f"  │    • 索引{索引}: 键缺失")
                    if 键差异["仅item1有"]:
                        print(f"  │        仅{标题1}有: {', '.join(键差异['仅item1有'])}")
                    if 键差异["仅item2有"]:
                        print(f"  │        仅{标题2}有: {', '.join(键差异['仅item2有'])}")
                
                # 值差异
                for vd in 值差异[:2]:  # 每项最多显示2个值差异
                    键 = vd["键"]
                    值1 = vd.get("值1", "N/A")
                    值2 = vd.get("值2", "N/A")
                    if "差异" in vd:
                        print(f"  │        {键}: {值1} → {值2} (Δ={vd['差异']:.2e})")
                    else:
                        print(f"  │        {键}: {值1} → {值2}")
            
            if len(详情["项差异"]) > 3:
                print(f"  │    ... 还有 {len(详情['项差异']) - 3} 项差异未显示")
        print(f"  └─")
    
    # 统计摘要
    print("\n" + "=" * 70)
    print("📈 差异统计摘要")
    print("=" * 70)
    stat = 差异["统计"]
    差异率 = (stat["差异股票数"] / stat["总股票数"] * 100) if stat["总股票数"] else 0
    print(f"  总行业数      : {stat['总行业数']}")
    print(f"  差异行业数    : {stat['差异行业数']} ({stat['差异行业数']/stat['总行业数']*100:.1f}%)" if stat['总行业数'] else "  差异行业数    : 0")
    print(f"  总股票数      : {stat['总股票数']}")
    print(f"  差异股票数    : {stat['差异股票数']} ({差异率:.2f}%)")
    print("=" * 70)

In [ ]:
# 严格比较（浮点容差 1e-5，不忽略列表顺序）
相等, 差异详情 = compare_nested_dict_strict(
    industry_to_index_standardized_1, industry_to_index_standardized_2,
    float_tolerance=1e-5,
    ignore_list_order=False,
    ignore_missing_keys=False
)

print(f"\n🔍 严格比较结果: {'✅ 相等' if 相等 else '❌ 不相等'}\n")
print_comparison_report(差异详情, 标题1="原始数据", 标题2="新数据")

# 宽松比较（忽略列表顺序 + 浮点容差 1e-4）
print("\n\n" + "="*70)
print("🔄 宽松模式比较（忽略列表顺序 + 更大浮点容差）")
print("="*70)
相等_宽松, 差异_宽松 = compare_nested_dict_strict(
    industry_to_index_standardized_1, industry_to_index_standardized_2,
    float_tolerance=1e-4,      # 更大容差
    ignore_list_order=True,    # 忽略顺序
    ignore_missing_keys=False
)
print(f"\n🔍 宽松比较结果: {'✅ 相等' if 相等_宽松 else '❌ 不相等'}")

In [135]:
len(market_index_groups.get('红利与收益质量策略'))

7

In [150]:
len(industry_to_index)

269

In [157]:
len(industry_to_index_ai.keys())

269

In [149]:
len(industry_to_index_ai)

269

In [164]:
len(industry_to_index_standardized_1)

300

In [ ]:
set(industry_to_index_standardized_2.keys()) - set(industry_to_index_standardized_1.keys())

In [ ]:
pd.DataFrame([
    {**stock, "industry": industry}
    for k, v in industry_to_index_standardized_300.items()
    for stock in stocks
    ])

In [ ]:
industry_to_index_standardized_300

In [174]:
嵌套数据 = {
    "电力设备": [
        {"code": "600000", "name": "浦发银行", "weight": 0.15},
        {"code": "600001", "name": "邯郸钢铁", "weight": 0.25}
    ],
    "半导体": [
        {"code": "688001", "name": "华兴源创", "weight": 0.30},
        {"code": "688002", "name": "睿创微纳", "weight": 0.20},
        {"code": "688003", "name": "天准科技", "weight": 0.10}
    ]
}

# 一键展开为长格式 DataFrame
df_nested = pd.DataFrame([
    {**stock, "industry": industry}
    for industry, stocks in 嵌套数据.items()
    for stock in stocks
])

In [177]:
df_nested_300 = pd.DataFrame([
    {**stock, "industry": industry}
    for industry, stocks in industry_to_index_standardized_300.items()
    for stock in stocks
])

In [178]:
df_nested_269 = pd.DataFrame([
    {**stock, "industry": industry}
    for industry, stocks in industry_to_index_standardized_269.items()
    for stock in stocks
])

In [208]:
df_nested_300.drop_duplicates(subset='IndexCode')

    IndexCode IndexName  components launch_date   industry
0      930601      中证软件          30  2015-03-10     横向通用软件
1      H30202      软件指数          50  2013-07-15     横向通用软件
3      000040      上证电信          30  2009-01-09  通信网络设备及器件
4      000916     300通信          14  2007-07-02  通信网络设备及器件
5      399994      信息安全          63  2015-03-12  通信网络设备及器件
..        ...       ...         ...         ...        ...
299    881373      影视院线          20  2025-09-09     影视动漫制作
300    881369        游戏          25  2025-09-09        游戏Ⅲ
301    881427        体育           3  2025-09-09        体育Ⅲ
302    880707      宠物经济         114  2025-09-09       宠物食品
305    881428      教育培训          17  2025-09-09    教育运营及其他

[155 rows x 5 columns]

In [207]:
df_nested_269.drop_duplicates(subset='IndexCode')

    IndexCode IndexName  components launch_date   industry
0      930601      中证软件          30  2015-03-10     横向通用软件
1      H30202      软件指数          50  2013-07-15     横向通用软件
4      931160      通信设备          50  2013-07-15  通信网络设备及器件
5      H30067    AMAC仪表          66  2013-01-21  通信网络设备及器件
8      931461      电子50          50  2009-07-22      其他电子Ⅲ
..        ...       ...         ...         ...        ...
517    H30037    AMAC商务          64  2013-01-21       综合电商
522    880596      体育概念         117  2025-09-09        体育Ⅲ
524    880707      宠物经济         114  2025-09-09       宠物食品
526    881428      教育培训          17  2025-09-09    教育运营及其他
528    881373      影视院线          20  2025-09-09         院线

[233 rows x 5 columns]

In [209]:
df_nested.drop_duplicates('IndexCode')

    IndexCode IndexName  components launch_date industry
0      930601      中证软件          30  2015-03-10    IT服务Ⅲ
1      H30202      软件指数          50  2013-07-15    IT服务Ⅲ
2      880945    OLED概念         145  2025-09-09      LED
3      H30129      未知指数           0          未知      LED
4      931865      中证半导          40  2019-03-20      LED
..        ...       ...         ...         ...      ...
662    931672      风电产业          50  2021-04-29     风力发电
663    880582        风电         378  2025-09-09     风力发电
668    881282      风电设备          28  2025-09-09    风电零部件
677    399238      餐饮指数           0  2013-03-04       餐饮
680    880463        公路           3  2025-09-09     高速公路

[278 rows x 5 columns]

In [179]:
df_nested_269

    IndexCode IndexName  components launch_date   industry
0      930601      中证软件          30  2015-03-10     横向通用软件
1      H30202      软件指数          50  2013-07-15     横向通用软件
2      930601      中证软件          30  2015-03-10      IT服务Ⅲ
3      H30202      软件指数          50  2013-07-15      IT服务Ⅲ
4      931160      通信设备          50  2013-07-15  通信网络设备及器件
..        ...       ...         ...         ...        ...
533    930633      中证旅游          40  2015-05-08      旅游零售Ⅲ
534    881380       出版业          29  2025-09-09       文字媒体
535    H11049    AMAC文体          59  2009-06-15       文字媒体
536    881376      数字媒体          10  2025-09-09       视频媒体
537    H11049    AMAC文体          59  2009-06-15       视频媒体

[538 rows x 5 columns]

In [190]:
df_nested = pd.concat([df_nested_269, df_nested_300]).drop_duplicates(subset=('industry','IndexCode')).sort_values(by='industry').reset_index(drop=True)

In [204]:
df_nested.groupby('industry').count()

          IndexCode  IndexName  components  launch_date
industry
IT服务Ⅲ             2          2           2            2
LED               3          3           3            3
专业连锁Ⅲ             2          2           2            2
个护小家电             2          2           2            2
中药Ⅲ               2          2           2            2
...             ...        ...         ...          ...
食品及饲料添加剂          3          3           3            3
食用菌               3          3           3            3
餐饮                3          3           3            3
高速公路              3          3           3            3
黄金                3          3           3            3

[317 rows x 4 columns]

In [203]:
df_nested[~(df_nested['IndexName']=='未知指数')].drop_duplicates(subset='IndexCode').groupby('industry').count()

          IndexCode  IndexName  components  launch_date
industry
IT服务Ⅲ             2          2           2            2
LED               2          2           2            2
专业连锁Ⅲ             2          2           2            2
个护小家电             2          2           2            2
中药Ⅲ               2          2           2            2
...             ...        ...         ...          ...
面板                1          1           1            1
风力发电              2          2           2            2
风电零部件             1          1           1            1
餐饮                1          1           1            1
高速公路              1          1           1            1

[178 rows x 4 columns]