In [31]:
import talib as ta

In [38]:
!pip install talib-cuda --extra-index-url https://pypi.nvidia.com

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple/, https://pypi.nvidia.com
ERROR: Could not find a version that satisfies the requirement talib-cuda (from versions: none)
ERROR: No matching distribution found for talib-cuda

In [35]:
data = pd.read_sql('000001',eng)

In [52]:
df = data.copy()

In [54]:
# 双均线系统（5日+20日黄金交叉）
df['MA5'] = ta.MA(df['close'], timeperiod=5, matype=0)  # SMA 
df['MA20'] = ta.MA(df['close'], timeperiod=20, matype=0)
df['MACD'], df['MACD_signal'], _ = ta.MACD(df['close'], 
                                         fastperiod=12, 
                                         slowperiod=26, 
                                         signalperiod=9)
df['ADX'] = ta.ADX(df['high'], df['low'], df['close'], timeperiod=14)  # 趋势强度

In [55]:
df

,datetime,open,close,high,low,vol,amount,year,month,day,hour,minute,MA5,MA20,MACD,MACD_signal,ADX
0,1999-03-18 15:00,13.88,13.76,13.93,13.75,14194.0,1.960100e+07,1999,3,18,15,0,NaN,NaN,NaN,NaN,NaN
1,1999-03-19 15:00,13.80,13.86,13.90,13.58,17704.0,2.440400e+07,1999,3,19,15,0,NaN,NaN,NaN,NaN,NaN
2,1999-03-22 15:00,13.86,13.73,13.88,13.66,22602.0,3.097600e+07,1999,3,22,15,0,NaN,NaN,NaN,NaN,NaN
3,1999-03-23 15:00,13.73,13.68,13.79,13.59,24708.0,3.374300e+07,1999,3,23,15,0,NaN,NaN,NaN,NaN,NaN
4,1999-03-24 15:00,13.70,14.04,14.47,13.68,68137.0,9.644000e+07,1999,3,24,15,0,13.814,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6182,2025-05-21 15:00,11.40,11.48,11.59,11.39,1328278.0,1.528350e+09,2025,5,21,15,0,11.402,11.1555,0.074064,0.022099,22.870951
6183,2025-05-22 15:00,11.45,11.55,11.56,11.44,1002968.0,1.155265e+09,2025,5,22,15,0,11.434,11.1820,0.089015,0.035482,24.088450
6184,2025-05-23 15:00,11.55,11.46,11.60,11.43,962643.0,1.108636e+09,2025,5,23,15,0,11.450,11.2030,0.092535,0.046893,25.436659
6185,2025-05-26 15:00,11.44,11.42,11.50,11.40,699158.0,8.004957e+08,2025,5,26,15,0,11.460,11.2235,0.091048,0.055724,26.286701
6186,2025-05-27 15:00,11.45,11.49,11.54,11.42,801915.0,9.219123e+08,2025,5,27,15,0,11.480,11.2465,0.094428,0.063465,27.315421

In [37]:
ta.add_all_ta_features(df,  
    open="open", high="high", low="low", close="close", 
    volume="volume", fillna=True)

AttributeError: module 'talib' has no attribute 'add_all_ta_features'

In [ ]:
ta.

In [36]:
data

,datetime,open,close,high,low,vol,amount,year,month,day,hour,minute
0,1999-03-18 15:00,13.88,13.76,13.93,13.75,14194.0,1.960100e+07,1999,3,18,15,0
1,1999-03-19 15:00,13.80,13.86,13.90,13.58,17704.0,2.440400e+07,1999,3,19,15,0
2,1999-03-22 15:00,13.86,13.73,13.88,13.66,22602.0,3.097600e+07,1999,3,22,15,0
3,1999-03-23 15:00,13.73,13.68,13.79,13.59,24708.0,3.374300e+07,1999,3,23,15,0
4,1999-03-24 15:00,13.70,14.04,14.47,13.68,68137.0,9.644000e+07,1999,3,24,15,0
...,...,...,...,...,...,...,...,...,...,...,...,...
6182,2025-05-21 15:00,11.40,11.48,11.59,11.39,1328278.0,1.528350e+09,2025,5,21,15,0
6183,2025-05-22 15:00,11.45,11.55,11.56,11.44,1002968.0,1.155265e+09,2025,5,22,15,0
6184,2025-05-23 15:00,11.55,11.46,11.60,11.43,962643.0,1.108636e+09,2025,5,23,15,0
6185,2025-05-26 15:00,11.44,11.42,11.50,11.40,699158.0,8.004957e+08,2025,5,26,15,0
6186,2025-05-27 15:00,11.45,11.49,11.54,11.42,801915.0,9.219123e+08,2025,5,27,15,0

In [14]:
# 多模态股票预测系统 v2.1 
 
import numpy as np 
import pandas as pd 
import torch 
import torch.nn  as nn 
from torch.utils.data  import Dataset, DataLoader 
from xgboost import XGBRegressor 
from sklearn.preprocessing  import RobustScaler 
from sklearn.metrics  import mean_absolute_percentage_error, r2_score 
import matplotlib.pyplot  as plt 
# import yfinance as yf
from sqlalchemy import create_engine

eng = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56:5432/tdxStocks') 
import warnings 
warnings.filterwarnings('ignore')

In [15]:
# 动态权重调整算法（核心逻辑）
def dynamic_weight(self):
    if len(self.error_history)  >=5:
        recent_error = np.mean(self.error_history[-5:]) 
        if recent_error < 0.05:  # 近期表现好则增加权重 
            return (0.7, 0.3)
        elif recent_error > 0.1: # 表现差时降低权重 
            return (0.4, 0.6)
    return (0.6, 0.4)

In [16]:
# 扩展外部数据接口示例 
def add_external_data(self, economic_data):
    self.external_sources  = {
        'GDP': economic_data['gdp'],
        'CPI': economic_data['cpi']
    }
    # 自动进行特征对齐和缺失值处理

In [17]:
# ----------------------
# 模块一：数据工程系统 
# ----------------------
class DataEngineer:
    def __init__(self, symbol, seq_len=30):
        self.symbol  = symbol 
        self.seq_len  = seq_len 
        self.scalers  = {}
        
    def load_data(self):
        """混合数据源加载"""
        # 示例数据源（实际可对接数据库）
        # data = yf.download(self.symbol,  start="2015-01-01", end="2025-05-23")
        data = pd.read_sql(self.symbol, eng).set_index('datetime')[['open', 'close', 'high', 'low', 'vol']]
        data.index = pd.to_datetime(data.index)

        
        # 数据完整性校验 
        date_range = pd.date_range(start=data.index.min(),  end=data.index.max(),  freq='D')
        if len(date_range.difference(data.index))  > 0:
            data = data.reindex(date_range).ffill() 
            
        return data 
 
    def create_features(self, data):
        """特征工程流水线"""
        # 技术指标 
        data['ma_5'] = data['close'].rolling(5).mean()
        data['ma_10'] = data['close'].rolling(10).mean()
        data['volatility'] = data['close'].pct_change().rolling(20).std()
        data['rsi'] = self._calculate_rsi(data['close'])
        
        # 外部特征（示例）
        data['economic_growth'] = np.random.normal(0,  0.1, len(data))  # 模拟经济指标 
        data['sentiment'] = np.random.rand(len(data))                  # 模拟舆情数据 
        
        # 鲁棒标准化 
        for col in data.columns: 
            scaler = RobustScaler()
            data[col] = scaler.fit_transform(data[[col]].values.reshape(-1,1)) 
            self.scalers[col]  = scaler 
            
        return data.dropna() 
 
    def _calculate_rsi(self, series, period=14):
        delta = series.diff() 
        gain = delta.where(delta  > 0, 0)
        loss = -delta.where(delta  < 0, 0)
        avg_gain = gain.rolling(period).mean() 
        avg_loss = loss.rolling(period).mean() 
        rs = avg_gain / avg_loss 
        return 100 - (100 / (1 + rs))

In [18]:
# ----------------------
# 模块二：深度模型架构 
# ----------------------
class EnhancedTransformer(nn.Module):
    """改进的时空Transformer"""
    def __init__(self, input_size=8, d_model=256, nhead=4, 
                num_layers=4, dropout=0.1):
        super().__init__()
        self.position_encoder  = PositionalEncoding(d_model, dropout)
        encoder_layer = nn.TransformerEncoderLayer(
            d_model, nhead, dim_feedforward=d_model*4,
            dropout=dropout, batch_first=True 
        )
        self.encoder  = nn.TransformerEncoder(encoder_layer, num_layers)
        self.fc  = nn.Sequential(
            nn.Linear(d_model, 64),
            nn.GELU(),
            nn.Linear(64, 1)
        )
        
    def forward(self, x):
        x = self.position_encoder(x) 
        memory = self.encoder(x) 
        return self.fc(memory[:,  -1, :])
 
class PositionalEncoding(nn.Module):
    """可学习位置编码"""
    def __init__(self, d_model, dropout=0.1, max_len=100):
        super().__init__()
        self.dropout  = nn.Dropout(p=dropout)
        self.pe  = nn.Parameter(torch.zeros(1,  max_len, d_model))
        nn.init.xavier_normal_(self.pe) 
        
    def forward(self, x):
        print(x.shape)
        x = x + self.pe[:,  :x.size(1),  :]
        return self.dropout(x)

In [19]:
# ----------------------
# 模块三：训练与评估 
# ----------------------
class StockDataset(Dataset):
    def __init__(self, data, seq_len):
        self.data  = torch.FloatTensor(data)
        self.seq_len  = seq_len 
        
    def __len__(self):
        return len(self.data)  - self.seq_len  
        
    def __getitem__(self, idx):
        x = self.data[idx:idx+self.seq_len] 
        y = self.data[idx+self.seq_len,  1]  # 预测close价格 
        return x, y 
 
def train_model(model, dataloader, val_loader, epochs=200):
    device = torch.device('cuda'  if torch.cuda.is_available()  else 'cpu')
    model = model.to(device) 
    criterion = nn.HuberLoss()
    optimizer = torch.optim.AdamW(model.parameters(),  lr=1e-4, weight_decay=1e-5)
    scheduler = torch.optim.lr_scheduler.OneCycleLR( 
        optimizer, max_lr=2e-4, steps_per_epoch=len(dataloader), epochs=epochs)
    
    best_loss = float('inf')
    for epoch in range(epochs):
        model.train() 
        total_loss = 0 
        for x, y in dataloader:
            x, y = x.to(device),  y.to(device)
            optimizer.zero_grad()
            outputs = model(x)
            loss = criterion(outputs.squeeze(),  y)
            loss.backward() 
            nn.utils.clip_grad_norm_(model.parameters(),  1.0)
            optimizer.step() 
            scheduler.step() 
            total_loss += loss.item() 
        
        # 早停验证 
        val_loss = evaluate(model, val_loader, criterion, device)
        if val_loss < best_loss:
            best_loss = val_loss 
            torch.save(model.state_dict(),  f'best_model_{epoch}.pth')
            
        print(f"Epoch {epoch+1}/{epochs} | Train Loss: {total_loss/len(dataloader):.4f} | Val Loss: {val_loss:.4f}")
 
def evaluate(model, loader, criterion, device):
    model.eval() 
    total_loss = 0 
    with torch.no_grad(): 
        for x, y in loader:
            x, y = x.to(device),  y.to(device) 
            outputs = model(x)
            total_loss += criterion(outputs.squeeze(),  y).item()
    return total_loss / len(loader)

In [20]:
# ----------------------
# 模块四：集成预测系统 
# ----------------------
class HybridPredictor:
    def __init__(self, transformer_model, xgb_model):
        self.transformer  = transformer_model 
        self.xgb  = xgb_model 
        self.error_history  = []
        
    def predict(self, data):
        # 动态权重调整 
        transformer_pred = self.transformer(data).cpu().numpy() 
        xgb_pred = self.xgb.predict(data.numpy()[:,  :, :-1])
        
        # 基于最近误差调整权重 
        if len(self.error_history)  >= 5:
            recent_mape = np.mean(self.error_history[-5:]) 
            w1 = 0.7 if recent_mape < 0.05 else 0.5 
        else:
            w1 = 0.6 
        return w1*transformer_pred + (1-w1)*xgb_pred

In [21]:
# ----------------------
# 主执行流程 
# ----------------------
if __name__ == "__main__":
    # 初始化配置 
    config = {
        'symbol': '000001',
        'seq_len': 30,
        'test_ratio': 0.2,
        'batch_size': 64 
    }
    
    # 数据工程 
    engineer = DataEngineer(config['symbol'])
    raw_data = engineer.load_data() 
    processed_data = engineer.create_features(raw_data) 
    
    # 数据集划分 
    split_idx = int(len(processed_data)*(1-config['test_ratio']))
    train_data = processed_data.iloc[:split_idx] 
    test_data = processed_data.iloc[split_idx:] 
    
    # 创建数据加载器 
    dataset = StockDataset(train_data.values,  config['seq_len'])
    train_loader = DataLoader(dataset, batch_size=config['batch_size'], shuffle=True)
    val_loader = DataLoader(StockDataset(test_data.values,  config['seq_len']), 
                           batch_size=config['batch_size'])
    
    # 模型训练 
    transformer = EnhancedTransformer(input_size=processed_data.shape[1]) 
    train_model(transformer, train_loader, val_loader, epochs=100)
    
    # XGBoost训练 
    xgb = XGBRegressor(n_estimators=200, learning_rate=0.1, max_depth=5)
    xgb.fit(train_data.iloc[:-config['seq_len'],  :-1], train_data['close'][config['seq_len']:])
    
    # 混合预测 
    hybrid = HybridPredictor(transformer, xgb)
    test_window = test_data.values.reshape(1,  len(test_data), -1)
    final_pred = hybrid.predict(torch.FloatTensor(test_window)) 
    
    # 可视化 
    plt.figure(figsize=(16,8)) 
    plt.plot(test_data['close'].values,  label='True Price')
    plt.plot(final_pred.squeeze(),  label='Hybrid Prediction', linestyle='--')
    plt.fill_between(range(len(final_pred)), 
                    final_pred.squeeze()-0.5*np.std(final_pred), 
                    final_pred.squeeze()+0.5*np.std(final_pred), 
                    alpha=0.2)
    plt.title('AAPL  Stock Price Prediction (2025)')
    plt.legend() 
    plt.show()

torch.Size([64, 30, 11])

RuntimeError: The size of tensor a (11) must match the size of tensor b (256) at non-singleton dimension 2

In [8]:
config = {
        'symbol': '000001',
        'seq_len': 30,
        'test_ratio': 0.2,
        'batch_size': 64 
    }

In [9]:
engineer = DataEngineer(config['symbol'])
raw_data = engineer.load_data() 
processed_data = engineer.create_features(raw_data)

In [10]:
split_idx = int(len(processed_data)*(1-config['test_ratio']))
train_data = processed_data.iloc[:split_idx] 
test_data = processed_data.iloc[split_idx:]

In [11]:
dataset = StockDataset(train_data.values,  config['seq_len'])
train_loader = DataLoader(dataset, batch_size=config['batch_size'], shuffle=True)
val_loader = DataLoader(StockDataset(test_data.values,  config['seq_len']), 
                        batch_size=config['batch_size'])

In [18]:
transformer = EnhancedTransformer(input_size=processed_data.shape[1])

In [19]:
train_model(transformer, train_loader, val_loader, epochs=100)

torch.Size([64, 30, 11])

RuntimeError: The size of tensor a (11) must match the size of tensor b (256) at non-singleton dimension 2

In [ ]:
test_data.shape

In [ ]:
xgb = XGBRegressor(n_estimators=200, learning_rate=0.1, max_depth=5)

In [ ]:
xgb.fit(train_data.iloc[:-config['seq_len'],  :-1], train_data['close'][config['seq_len']:])

In [ ]:
hybrid = HybridPredictor(transformer, xgb)

In [ ]:
test_window = test_data.values.reshape(1,  len(test_data), -1)

In [ ]:
final_pred = hybrid.predict(torch.FloatTensor(test_window))

In [ ]:
train_model(transformer, train_loader, val_loader, epochs=100)

In [ ]:
processed_data.shape[1]