##### 财报披露日期
* 年报（1231） 1.1--4.30
* 一季报（0331）4.1--4.30 
* 中报（0630）7.1--8.30 
* 三季报（0930）10.1--10.31

##### 数据更新
* 年报、一季报（5.15）
* 中报（9.15）
* 三季报（11.15）

##### TDX行情接口 （2026.5）
* 标准行情：110.41.174.169:7709  (深圳双线9, 0.062s)
* 标准行情：180.153.18.170:7709  (广州双线6, 0.095s)
* 标准行情：116.205.171.132:7709  (上海电信主站Z1, 0.177s)
* 扩展行情：180.153.18.176:7721  (0.110s)
* 扩展行情：180.153.18.176:7721  (0.110s)

* 标准行情备选1：58.63.254.217:7709  (海通, 0.089s)
* 标准行情备选2：183.60.224.178:7709  (广发, 0.090s)
* 标准行情备选3：202.96.138.90:7709   (华林, 0.094s)

In [1]:
import pandas as pd
from pytdx.hq import TdxHq_API
from pytdx.exhq import TdxExHq_API
from pytdx.crawler.history_financial_crawler import HistoryFinancialListCrawler
from pytdx.crawler.history_financial_crawler import HistoryFinancialCrawler
from pytdx.crawler.base_crawler import demo_reporthook

In [2]:
eapi =  TdxExHq_API()
api = TdxHq_API()

##### 历史财务数据列表(2026.5.6)

In [ ]:
from datetime import datetime
print(datetime.now().strftime("%Y-%m-%d"))
crawler = HistoryFinancialListCrawler()
list_data = crawler.fetch_and_parse()
print(pd.DataFrame(data=list_data).head(16))

In [ ]:
import pandas as pd
from sqlalchemy import create_engine
engF = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxFS')
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
# 生成文件列表
fsList = []
for year in range(2020, 2026):
    fsList.extend([
        f"gpcw{year}0331.zip", f"gpcw{year}0630.zip", f"gpcw{year}0930.zip", f"gpcw{year}1231.zip"
    ])

In [ ]:
datacrawler = HistoryFinancialCrawler()
pd.set_option('display.max_columns', None)

##### 获取历史财务数据存入数据库

In [ ]:
for ls in fsList[:-1]:
    result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=ls, path_to_download="/tmp/tmpfile.zip")
    df_tmp = datacrawler.to_df(data=result)
    df_tmp['report_date']= df_tmp['report_date'].astype(object)
    df_tmp.to_sql(ls[:12], engF,if_exists='replace')
    print(ls + 'saved ! ')

##### 手动历史财务数据

In [ ]:
filename = 'gpcw20250930.zip'
result = datacrawler.fetch_and_parse(reporthook=demo_reporthook, filename=filename, path_to_download="/tmp/tmpfile.zip")
df_tmp = datacrawler.to_df(data=result)
df_tmp['report_date']= df_tmp['report_date'].astype(object)
df_tmp.to_sql(filename[:12], engF, if_exists='replace')

=============== 接口

* 标准接口

In [29]:
api.connect('110.41.174.169', 7709)
api.to_df(api.get_security_bars(9,1, '588080', 1, 1))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,1.903,1.804,1.933,1.796,14786104.0,2.779459e+09,2026,5,21,15,0,2026-05-21 15:00

In [18]:
api.connect('115.238.56.198', 7709)
api.to_df(api.get_security_bars(9,1, '588080', 1, 1))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,1.903,1.804,1.933,1.796,14786104.0,2.779459e+09,2026,5,21,15,0,2026-05-21 15:00

In [9]:
api.connect('180.153.18.170', 7709)
api.to_df(api.get_security_bars(9,1, '588080', 1, 1))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,1.903,1.804,1.933,1.796,14786104.0,2.779459e+09,2026,5,21,15,0,2026-05-21 15:00

In [10]:
api.connect('58.63.254.217', 7709)
api.to_df(api.get_security_bars(9,1, '588080', 1, 1))

,open,close,high,low,vol,amount,year,month,day,hour,minute,datetime
0,1.903,1.804,1.933,1.796,14786104.0,2.779459e+09,2026,5,21,15,0,2026-05-21 15:00

* 历史k线
* 市场代码 0:深圳，1:上海
* 0:5分钟K线 1:15分钟K线 2:30分钟K线 3:1小时K线 4:日K线 5:周K线 6:月K线 7:1分钟 8:1分钟K线 9:日K线 10:季K线 11:年K线
* (市场代码, 证券代码, 开始位置, 请求的数目)

* 股票

In [ ]:
api.to_df(api.get_security_bars(9,1, '588080', 1, 1))

* 指数

In [ ]:
api.to_df(api.get_index_bars(9,0, '932294', 1, 2))

* 扩展接口

In [36]:
eapi.connect('180.153.18.176', 7721)
api.to_df(eapi.get_instrument_bars(9,7, 'IO8U07EP', 0, 120))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,154.399994,156.000000,141.399994,142.000000,433,0,139.399994,2025,11,20,15,0,2025-11-20 15:00,6.067622e-43
1,127.599998,134.000000,116.000000,116.000000,438,0,115.800003,2025,11,21,15,0,2025-11-21 15:00,6.137687e-43
2,110.000000,118.400002,109.599998,118.400002,441,0,114.800003,2025,11,24,15,0,2025-11-24 15:00,6.179726e-43
3,118.199997,121.800003,113.599998,113.599998,490,0,112.800003,2025,11,25,15,0,2025-11-25 15:00,6.866362e-43
4,112.599998,112.599998,112.599998,112.599998,493,0,113.000000,2025,11,26,15,0,2025-11-26 15:00,6.908401e-43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,120.000000,127.000000,91.599998,105.000000,4930,70,105.000000,2026,5,18,15,0,2026-05-18 15:00,6.908401e-42
116,100.000000,107.599998,76.199997,107.400002,5666,112,107.400002,2026,5,19,15,0,2026-05-19 15:00,7.939757e-42
117,95.000000,108.199997,85.000000,98.599998,5052,76,98.599998,2026,5,20,15,0,2026-05-20 15:00,7.079360e-42
118,112.000000,153.399994,69.599998,70.000000,4805,118,70.000000,2026,5,21,15,0,2026-05-21 15:00,6.733239e-42
119,84.000000,99.199997,75.400002,87.400002,4436,88,87.400002,2026,5,22,15,0,2026-05-22 15:00,6.216160e-42

In [38]:
api.to_df(eapi.get_instrument_bars(9,12, 'A_HXC', 0, 120))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,7805.801270,7908.751465,7799.213867,7860.372070,1168772224,0,0.0,2025,12,1,15,0,2025-12-01 15:00,5441.562500
1,7827.924805,7829.453125,7759.679688,7808.984863,1165567074,188,0.0,2025,12,2,15,0,2025-12-02 15:00,3986.273926
2,7758.968262,7761.466797,7685.017090,7701.494141,1164262917,220,0.0,2025,12,3,15,0,2025-12-03 15:00,3667.876221
3,7734.037109,7762.150879,7706.805176,7731.878418,1161960252,176,0.0,2025,12,4,15,0,2025-12-04 15:00,3105.702148
4,7814.162109,7860.273926,7795.392090,7831.427246,1163489399,165,0.0,2025,12,5,15,0,2025-12-05 15:00,3479.029053
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,6838.212402,6838.212402,6739.428223,6790.669922,1165815110,187,0.0,2026,5,18,15,0,2026-05-18 15:00,4046.829590
116,6798.060547,6846.811035,6780.892578,6790.300293,1165923740,184,0.0,2026,5,19,15,0,2026-05-19 15:00,4073.350586
117,6767.641602,6773.616211,6686.190918,6760.283691,1164247805,209,0.0,2026,5,20,15,0,2026-05-20 15:00,3664.186768
118,6648.110352,6680.447266,6550.329102,6659.190918,1167838898,273,0.0,2026,5,21,15,0,2026-05-21 15:00,4985.836914
119,6514.860840,6544.956543,6473.450684,6512.064941,1168268096,358,0.0,2026,5,22,15,0,2026-05-22 15:00,5195.406250

In [33]:
eapi.connect('47.112.95.207', 7720)
api.to_df(eapi.get_instrument_bars(9,7, 'IO8U07EP', 0, 120))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,154.399994,156.000000,141.399994,142.000000,433,0,139.399994,2025,11,20,15,0,2025-11-20 15:00,6.067622e-43
1,127.599998,134.000000,116.000000,116.000000,438,0,115.800003,2025,11,21,15,0,2025-11-21 15:00,6.137687e-43
2,110.000000,118.400002,109.599998,118.400002,441,0,114.800003,2025,11,24,15,0,2025-11-24 15:00,6.179726e-43
3,118.199997,121.800003,113.599998,113.599998,490,0,112.800003,2025,11,25,15,0,2025-11-25 15:00,6.866362e-43
4,112.599998,112.599998,112.599998,112.599998,493,0,113.000000,2025,11,26,15,0,2025-11-26 15:00,6.908401e-43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,120.000000,127.000000,91.599998,105.000000,4930,70,105.000000,2026,5,18,15,0,2026-05-18 15:00,6.908401e-42
116,100.000000,107.599998,76.199997,107.400002,5666,112,107.400002,2026,5,19,15,0,2026-05-19 15:00,7.939757e-42
117,95.000000,108.199997,85.000000,98.599998,5052,76,98.599998,2026,5,20,15,0,2026-05-20 15:00,7.079360e-42
118,112.000000,153.399994,69.599998,70.000000,4805,118,70.000000,2026,5,21,15,0,2026-05-21 15:00,6.733239e-42
119,84.000000,99.199997,75.400002,87.400002,4436,88,87.400002,2026,5,22,15,0,2026-05-22 15:00,6.216160e-42

In [24]:
api.to_df(eapi.get_instrument_count())

    value
0  148897

In [ ]:
api.to_df(eapi.get_instrument_info(79000, 999))

##### ======获取扩展接口代码

In [ ]:
api.to_df(eapi.get_markets())[["market",	"name"]].rename(columns={'name':'market_name'})

#### 获取TDX接口代码表

In [25]:
mID = api.to_df(eapi.get_markets())[["market",	"name"]].rename(columns={'name':'market_name'})
df_inst = pd.DataFrame()
total = eapi.get_instrument_count()
for start in range(0, total, 1000):
    df_tmp = api.to_df(eapi.get_instrument_info(start, 999))
    df_inst = pd.concat([df_inst, df_tmp], ignore_index=True)
    
df_merg = pd.merge(df_inst, mID, left_on='market', right_on='market', how='left').rename(columns={'name':'code_name','market':'market_code'})[['code', 'code_name', 'category','market_code', 'market_name']]

In [26]:
df_merg

          code code_name  category  market_code market_name
0        00001        长和         2           71         沪港通
1        00002      中电控股         2           71         沪港通
2        00003    香港中华煤气         2           71         沪港通
3        00004     九龙仓集团         2           71         沪港通
4        00005      汇丰控股         2           71         沪港通
...        ...       ...       ...          ...         ...
144452  988006    CNTHKD         5          102        国证指数
144453  988007    CNTUSD         5          102        国证指数
144454  988106  CNTTRHKD         5          102        国证指数
144455  988107  CNTTRUSD         5          102        国证指数
144456  988201    湾创100R         5          102        国证指数

[144457 rows x 5 columns]

In [ ]:
df_merg.to_sql('tdxAPIcode', engI, if_exists='replace', index=False)

In [ ]:
df_merg.head()

In [27]:
df_merg.to_excel('/home/ts/app/AiStock/tdxAPICode180.xlsx', index=False)

In [ ]:
df_inst.tail(10)

In [ ]:
df_inst.head(2)

In [ ]:
df_inst.sort_values(by=['market','code'], ascending=True).to_excel('/home/ts/app/AiStock/tdxApiMarket2026.xlsx', index=False)

In [ ]:
df_merg.sort_values(by=['market_code','code'], ascending=True).to_excel('/home/ts/app/AiStock/tdxApiMarket.xlsx', index=False)

==============================

* 0:5分钟K线 1:15分钟K线 2:30分钟K线 3:1小时K线 4:日K线 5:周K线 6:月K线 7:1分钟 8:1分钟K线 9:日K线 10:季K线 11:年K线
* (K线周期， 市场ID， 证券代码，起始位置， 数量)

In [11]:
eapi.connect('47.112.95.207', 7720)
api.to_df(eapi.get_instrument_bars(9,7, 'IO8U07EP', 0, 120))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,154.399994,156.000000,141.399994,142.000000,433,0,139.399994,2025,11,20,15,0,2025-11-20 15:00,6.067622e-43
1,127.599998,134.000000,116.000000,116.000000,438,0,115.800003,2025,11,21,15,0,2025-11-21 15:00,6.137687e-43
2,110.000000,118.400002,109.599998,118.400002,441,0,114.800003,2025,11,24,15,0,2025-11-24 15:00,6.179726e-43
3,118.199997,121.800003,113.599998,113.599998,490,0,112.800003,2025,11,25,15,0,2025-11-25 15:00,6.866362e-43
4,112.599998,112.599998,112.599998,112.599998,493,0,113.000000,2025,11,26,15,0,2025-11-26 15:00,6.908401e-43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,120.000000,127.000000,91.599998,105.000000,4930,70,105.000000,2026,5,18,15,0,2026-05-18 15:00,6.908401e-42
116,100.000000,107.599998,76.199997,107.400002,5666,112,107.400002,2026,5,19,15,0,2026-05-19 15:00,7.939757e-42
117,95.000000,108.199997,85.000000,98.599998,5052,76,98.599998,2026,5,20,15,0,2026-05-20 15:00,7.079360e-42
118,112.000000,153.399994,69.599998,70.000000,4805,118,70.000000,2026,5,21,15,0,2026-05-21 15:00,6.733239e-42
119,84.000000,99.199997,75.400002,87.400002,4436,88,87.400002,2026,5,22,15,0,2026-05-22 15:00,6.216160e-42

In [12]:
eapi.connect('180.153.18.176', 7721)
api.to_df(eapi.get_instrument_bars(9,7, 'IO8U07EP', 0, 120))

,open,high,low,close,position,trade,price,year,month,day,hour,minute,datetime,amount
0,154.399994,156.000000,141.399994,142.000000,433,0,139.399994,2025,11,20,15,0,2025-11-20 15:00,6.067622e-43
1,127.599998,134.000000,116.000000,116.000000,438,0,115.800003,2025,11,21,15,0,2025-11-21 15:00,6.137687e-43
2,110.000000,118.400002,109.599998,118.400002,441,0,114.800003,2025,11,24,15,0,2025-11-24 15:00,6.179726e-43
3,118.199997,121.800003,113.599998,113.599998,490,0,112.800003,2025,11,25,15,0,2025-11-25 15:00,6.866362e-43
4,112.599998,112.599998,112.599998,112.599998,493,0,113.000000,2025,11,26,15,0,2025-11-26 15:00,6.908401e-43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,120.000000,127.000000,91.599998,105.000000,4930,70,105.000000,2026,5,18,15,0,2026-05-18 15:00,6.908401e-42
116,100.000000,107.599998,76.199997,107.400002,5666,112,107.400002,2026,5,19,15,0,2026-05-19 15:00,7.939757e-42
117,95.000000,108.199997,85.000000,98.599998,5052,76,98.599998,2026,5,20,15,0,2026-05-20 15:00,7.079360e-42
118,112.000000,153.399994,69.599998,70.000000,4805,118,70.000000,2026,5,21,15,0,2026-05-21 15:00,6.733239e-42
119,84.000000,99.199997,75.400002,87.400002,4436,88,87.400002,2026,5,22,15,0,2026-05-22 15:00,6.216160e-42

In [ ]:
a = pd.read_excel('/home/ts/app/AiStock/indexAi.xlsx')
b = pd.read_excel('/home/ts/app/AiStock/indexAii.xlsx')

In [ ]:
c = pd.read_excel('/home/ts/app/AiStock/indexAA.xlsx')

In [ ]:
a.columns.values

In [ ]:
b.columns.values

In [ ]:
c.columns.values

In [ ]:
c['入选原因']=c['入选原因'] .str.replace('**跟踪**','4')

In [ ]:
c.to_excel('/home/ts/app/AiStock/indexAA.xlsx', index=False)

In [ ]:
pd.merge(b, a , right_on='指数代码', left_on='指数代码',how='left').drop_duplicates(subset='指数代码')

In [ ]:
index = pd.read_sql('optIndexs', engI)

In [ ]:
indexAi = pd.read_excel('/home/ts/app/AiStock/indexAA.xlsx')

In [ ]:
index.query("IndexCode >= '000001'& IndexCode <'000019'")