#### 指数收益率重要性分析

In [ ]:
import pandas as pd
import numpy as np
import plotly.express as px
# from hmmlearn import hmm
from tqdm import tqdm

import xgboost as xgb
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

import plotly.graph_objects as go
from plotly.subplots import make_subplots
from sqlalchemy import create_engine

In [ ]:
import matplotlib.pyplot  as plt
# 设置中文字体 
plt.rcParams['font.sans-serif']  = ['WenQuanYi Zen Hei']
plt.rcParams['axes.unicode_minus']  = False

In [ ]:
engI = create_engine('postgresql+psycopg://sa:11111111@10.3.18.56/tdxIndex')

In [ ]:
IndexRAW = pd.read_sql('optIndexs', engI)

#### 生成比较列表

In [ ]:
HYls = [['000001','上证指数']] + IndexRAW[IndexRAW['IndexSTL'] == '行业'][['IndexCode','IndexName']].values.tolist()

In [ ]:
dfI = pd.DataFrame()
for code in tqdm(HYls):
    try:
        df_tmp = pd.read_sql(code[0], engI).set_index('datetime')['close'].to_frame()
        df_tmp['close'] = np.log(df_tmp['close']).diff()
        df_tmp.rename(columns={'close':code[0]+':'+code[1]}, inplace=True)
        dfI = pd.merge(dfI,df_tmp,right_index=True, left_index=True,how='outer')
    except:
        pass
        print(code+' pass ! ')

In [ ]:
# dfI.to_excel('/home/ts/app/AiStock/Linkage/Hyr.xlsx')

In [ ]:
# dfI = pd.read_excel('/home/ts/app/AiStock/Linkage/Hyr.xlsx').set_index('datetime')

In [ ]:
dfHy = pd.read_excel('/home/ts/AiStock/Hyr.xlsx').set_index('datetime')

In [ ]:
dfROE = pd.read_excel('/home/ts/AiStock/ROEIndex.xlsx').set_index('datetime')

In [88]:
dfI

,000001:上证指数,000009:上证380,000010:上证180,000015:红利指数,000016:上证50,000018:180金融,000019:治理指数,000020:中型综指,000021:180治理,000025:180基建,...,H50036:上证军工,H50037:上证城镇,H50038:沪智慧城,H50039:上证TMT,H50040:上红低波,H50042:上红价值,H50052:上国改革,H50053:上证移动,H50054:上证休闲,H50055:沪大农业
datetime,,,,,,,,,,,,,,,,,,,,,
2000-05-15 15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-05-16 15:00,0.011636,NaN,0.015821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-05-17 15:00,0.000499,NaN,0.001931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-05-18 15:00,0.019025,NaN,0.015471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-05-19 15:00,0.010910,NaN,0.010243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-16 15:00,0.001027,-0.010822,0.000651,0.010235,0.005930,0.010497,0.003225,-0.010868,0.005105,0.001250,...,-0.012663,-0.007778,-0.006624,-0.009803,0.006498,0.011297,-0.001141,-0.014864,-0.007214,-0.013644
2025-10-17 15:00,-0.019720,-0.028831,-0.021477,-0.003429,-0.017181,-0.009630,-0.015351,-0.034613,-0.014278,-0.006239,...,-0.036247,-0.026823,-0.034482,-0.042139,-0.003617,-0.005175,-0.015667,-0.038922,-0.016504,-0.011906
2025-10-20 15:00,0.006265,0.006437,0.001811,0.007510,0.002386,0.001791,0.002331,0.013241,0.001510,-0.001307,...,0.003152,0.006212,0.008719,0.010865,-0.000721,0.009445,-0.001253,0.009752,0.012867,-0.001547
2025-10-21 15:00,0.013481,0.012762,0.013159,-0.002051,0.010832,0.004416,0.007634,0.021797,0.006774,0.001433,...,0.013079,0.014918,0.020727,0.028302,0.004088,0.001155,0.006111,0.030435,0.008391,0.007314
2025-10-22 15:00,-0.000656,-0.007994,-0.003694,0.001468,0.000944,0.004274,-0.000418,-0.000097,-0.000318,0.003018,...,-0.013075,-0.006236,-0.011558,-0.009519,0.006902,-0.000043,-0.004977,-0.011442,0.002074,-0.005299

In [85]:
dfI.head()

,000001:上证指数,000009:上证380,000010:上证180,000015:红利指数,000016:上证50,000018:180金融,000019:治理指数,000020:中型综指,000021:180治理,000025:180基建,...,H50036:上证军工,H50037:上证城镇,H50038:沪智慧城,H50039:上证TMT,H50040:上红低波,H50042:上红价值,H50052:上国改革,H50053:上证移动,H50054:上证休闲,H50055:沪大农业
datetime,,,,,,,,,,,,,,,,,,,,,
2000-05-15 15:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-05-16 15:00,0.011636,NaN,0.015821,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-05-17 15:00,0.000499,NaN,0.001931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-05-18 15:00,0.019025,NaN,0.015471,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-05-19 15:00,0.010910,NaN,0.010243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
dfI = dfROE.copy()

In [89]:
# df = dfI[dfI.columns[1:]].shift(1).copy()
df = dfI[dfI.columns[1:]].copy()

In [90]:
df['Target'] = dfI[dfI.columns[0]].copy()

In [91]:
ddf = df.copy()

In [92]:
df.dropna(thresh=4500,axis=1).dropna()

,000009:上证380,000010:上证180,000015:红利指数,000016:上证50,000025:180基建,000026:180资源,000027:180运输,000043:超大盘,000052:50基本,000053:180基本,...,880824:高市盈率,880826:低市盈率,880827:高市净率,880829:低市净率,880833:亏损股,880834:微利股,880835:绩优股,880837:活跃股,980017:国证芯片,Target
datetime,,,,,,,,,,,,,,,,,,,,,
2007-01-16 15:00,0.037204,0.020953,0.014465,0.014634,0.002759,0.012763,-0.000511,0.006096,0.011244,0.017011,...,0.029696,0.027534,0.031201,0.022994,0.026106,0.029723,0.022195,0.020121,0.013764,0.009374
2007-01-17 15:00,0.000235,-0.018855,-0.010633,-0.018421,-0.008365,-0.026179,-0.015106,-0.021161,-0.008090,-0.011340,...,-0.013481,-0.023899,0.003900,-0.024185,-0.005457,-0.018857,-0.009797,-0.011827,-0.018104,-0.015043
2007-01-18 15:00,0.027807,-0.000985,-0.013344,-0.009670,-0.007103,0.011034,-0.001272,0.000188,-0.015330,-0.003355,...,0.026725,-0.012196,0.028316,-0.012182,0.022111,0.025273,0.013589,0.024557,0.060229,-0.007919
2007-01-19 15:00,0.037854,0.032097,0.022315,0.029811,0.039881,0.034808,0.047469,0.027121,0.024287,0.029553,...,0.038542,0.032351,0.038141,0.027777,0.029068,0.034274,0.031959,0.039139,0.049449,0.026921
2007-01-22 15:00,0.039112,0.040274,0.033375,0.039312,0.038586,0.030862,0.046518,0.037237,0.041788,0.043181,...,0.046298,0.039935,0.031156,0.039213,0.038542,0.036245,0.034325,0.032796,0.047653,0.035033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-10-16 15:00,-0.010822,0.000651,0.010235,0.005930,0.001250,-0.006605,0.005706,0.004074,0.008316,0.004901,...,-0.007128,0.015273,0.001728,0.012717,-0.004906,-0.006945,0.002605,-0.009465,-0.006287,0.001027
2025-10-17 15:00,-0.028831,-0.021477,-0.003429,-0.017181,-0.006239,-0.012734,-0.003536,-0.015098,-0.011383,-0.014286,...,-0.027974,-0.005327,-0.024547,-0.002382,-0.030245,-0.021604,-0.024241,-0.038278,-0.036893,-0.019720
2025-10-20 15:00,0.006437,0.001811,0.007510,0.002386,-0.001307,-0.003899,0.007987,0.003795,0.002705,0.001708,...,0.012119,0.006178,0.016729,0.000312,0.007085,0.007625,0.007003,0.013785,0.008481,0.006265
2025-10-21 15:00,0.012762,0.013159,-0.002051,0.010832,0.001433,0.006241,-0.002849,0.016743,0.005905,0.006779,...,0.012688,0.008466,0.041082,0.004618,0.018640,0.013958,0.016961,0.018423,0.032624,0.013481
2025-10-22 15:00,-0.007994,-0.003694,0.001468,0.000944,0.003018,-0.007491,-0.001964,0.005743,0.003430,0.000279,...,-0.000496,0.009264,0.007883,0.008010,-0.003510,-0.005472,-0.004527,-0.012047,-0.002198,-0.000656

In [93]:
ddf = df.dropna(thresh=4500,axis=1).dropna()

In [94]:
feature_columns = ddf.columns[:-1]
X = ddf[feature_columns]
y = ddf[ddf.columns[-1]]

#### --- 2. 模型训练 ---

In [95]:
num_round = 500

In [96]:
param = {
    "eta": 0.05,
    "max_depth": 10,
    "tree_method": "hist",
    "device": "cuda",
}

In [97]:
dtrain = xgb.DMatrix(X, label=y, feature_names=feature_columns.to_list())
model = xgb.train(param, dtrain, num_round)

In [98]:
model.set_param(params=param)
shap_values = model.predict(dtrain, pred_contribs=True)
shap_interaction_values = model.predict(dtrain, pred_interactions=True)

XGBoostError: [13:53:16] /workspace/src/common/device_vector.cu:23: Memory allocation error on worker 0: std::bad_alloc: cudaErrorMemoryAllocation: out of memory
- Free memory: 3.44983GB
- Requested memory: 4.33686GB

Stack trace:
  [bt] (0) /home/ts/.local/share/virtualenvs/jupyter.13-jNpHegMS/lib/python3.13/site-packages/xgboost/lib/libxgboost.so(+0x2a6ecc) [0x70d7b10a6ecc]
  [bt] (1) /home/ts/.local/share/virtualenvs/jupyter.13-jNpHegMS/lib/python3.13/site-packages/xgboost/lib/libxgboost.so(+0xa5c0e3) [0x70d7b185c0e3]
  [bt] (2) /home/ts/.local/share/virtualenvs/jupyter.13-jNpHegMS/lib/python3.13/site-packages/xgboost/lib/libxgboost.so(+0x176b7c) [0x70d7b0f76b7c]
  [bt] (3) /home/ts/.local/share/virtualenvs/jupyter.13-jNpHegMS/lib/python3.13/site-packages/xgboost/lib/libxgboost.so(+0xf4aba0) [0x70d7b1d4aba0]
  [bt] (4) /home/ts/.local/share/virtualenvs/jupyter.13-jNpHegMS/lib/python3.13/site-packages/xgboost/lib/libxgboost.so(+0xf4ca6d) [0x70d7b1d4ca6d]
  [bt] (5) /home/ts/.local/share/virtualenvs/jupyter.13-jNpHegMS/lib/python3.13/site-packages/xgboost/lib/libxgboost.so(+0x64c602) [0x70d7b144c602]
  [bt] (6) /home/ts/.local/share/virtualenvs/jupyter.13-jNpHegMS/lib/python3.13/site-packages/xgboost/lib/libxgboost.so(XGBoosterPredictFromDMatrix+0x2de) [0x70d7b0fba9be]
  [bt] (7) /lib/x86_64-linux-gnu/libffi.so.8(+0x7b16) [0x70d82fd57b16]
  [bt] (8) /lib/x86_64-linux-gnu/libffi.so.8(+0x43ef) [0x70d82fd543ef]

In [ ]:
import shap
explainer = shap.TreeExplainer(model,feature_names=feature_columns.to_list())

explainer_values = explainer(X,check_additivity=False)
shap_values = explainer_values.values
shap_interaction_values = explainer.shap_interaction_values(X)
except_value = explainer.expected_value

In [ ]:
shap.summary_plot(shap_values,X,plot_type='dot',max_display=20,feature_names=feature_columns.to_list() )

In [ ]:
shap.initjs()

In [ ]:
n = 4100
# 单样本力图  
shap.force_plot(
    explainer.expected_value,
    shap_values[n,:],
    X.reset_index(drop=True).loc[n],
    feature_names=feature_columns.to_list(),

)

In [ ]:
# 瀑布图  
# 创建Explanation对象
# explanation = shap.Explanation(values=shap_values, base_values=except_value, data=X,feature_names=data.feature_names)
shap.plots.waterfall(explainer_values[1200])

In [ ]:
# Show a summary of feature importance
shap.summary_plot(shap_values, X, plot_type="bar", feature_names=feature_columns.to_list())

In [ ]:
# create a dependence scatter plot to show the effect of a single feature across the whole dataset
shap.plots.scatter(explainer_values[:,'399320:国证服务'], color=explainer_values)

In [ ]:
shap.plots.beeswarm(explainer_values)

In [ ]:
shap.plots.bar(explainer_values)

In [ ]:
explainer_values.data

In [ ]:

split_index = int(0.8 * len(ddf))
X_train = X.iloc[:split_index]
X_test = X.iloc[split_index:]
y_train = y.iloc[:split_index]
y_test = y.iloc[split_index:]

xgb_model = xgb.XGBRegressor(
    objective='reg:squarederror',
    n_estimators=100,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42
)

xgb_model.fit(X_train, y_train)

#### --- 4. 模型预测与评估 ---

In [ ]:
y_pred = xgb_model.predict(X_test)

#### 计算评估指标

In [ ]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print("\n--- Model Evaluation ---")
print(f"Mean Squared Error on Test Set: {mse:.6f}")
print(f"R-squared Score on Test Set: {r2:.4f}")

#### --- 5. 使用 Plotly 绘图 ---

In [ ]:
# 将测试集的真实值和预测值合并到一个 DataFrame 用于绘图
scatter_df = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred,
    'Index': y_test.index # 保留日期索引用于 hover 信息
})

fig_scatter = px.scatter(
    scatter_df,
    x='Actual',
    y='Predicted',
    title='XGBoost: Predicted vs Actual SSE Returns (Test Set)',
    labels={'Actual': 'Actual SSE Return', 'Predicted': 'Predicted SSE Return'},
    hover_data={'Index': True}, # 鼠标悬停时显示日期
    trendline="ols" # 添加 OLS 回归线
)

# 添加 y=x 理想预测线
fig_scatter.add_shape(
    type="line",
    x0=scatter_df['Actual'].min(),
    y0=scatter_df['Actual'].min(),
    x1=scatter_df['Actual'].max(),
    y1=scatter_df['Actual'].max(),
    line=dict(color="red", width=2, dash="dash")
)

fig_scatter.update_layout(
    xaxis_title="Actual SSE Return",
    yaxis_title="Predicted SSE Return",
    hovermode='closest'
)

fig_scatter.show()

# 5.2 特征重要性条形图
importance = xgb_model.feature_importances_
feature_importance_df = pd.DataFrame({
    'Feature': feature_columns,
    'Importance': importance
}).sort_values(by='Importance', ascending=True) # 为了 plotly 从下往上排列

fig_importance = px.bar(
    feature_importance_df,
    x='Importance',
    y='Feature',
    orientation='h', # 水平条形图
    title='Feature Importance from XGBoost Model',
    labels={'Importance': 'Importance', 'Feature': 'Industry Feature (Lag 1)'},
    color='Importance',
    color_continuous_scale='viridis'
)

fig_importance.update_layout(
    yaxis={'categoryorder':'total ascending'}, # 确保最重要的在最上面
    xaxis_title="Importance",
    yaxis_title="Feature"
)

fig_importance.show()

# 5.3 实际值和预测值随时间变化的对比图 (折线图)
# 为了时间序列可视化，我们创建一个包含真实值和预测值的 DataFrame
# 使用测试集的索引
line_df = pd.DataFrame({
    'Date': y_test.index,
    'Actual': y_test.values,
    'Predicted': y_pred
}).reset_index(drop=True) # 重置索引以便 plotly 处理

# 使用 plotly.graph_objects 创建更灵活的子图
fig_time_series = go.Figure()

fig_time_series.add_trace(go.Scatter(
    x=line_df['Date'],
    y=line_df['Actual'],
    mode='lines',
    name='Actual SSE Return',
    line=dict(color='blue'),
    hovertemplate='<b>Date</b>: %{x}<br>' +
                  '<b>Actual</b>: %{y:.4f}<br>' +
                  '<extra></extra>'
))

fig_time_series.add_trace(go.Scatter(
    x=line_df['Date'],
    y=line_df['Predicted'],
    mode='lines',
    name='Predicted SSE Return',
    line=dict(color='orange'),
    hovertemplate='<b>Date</b>: %{x}<br>' +
                  '<b>Predicted</b>: %{y:.4f}<br>' +
                  '<extra></extra>'
))

fig_time_series.update_layout(
    title='Actual vs Predicted SSE Returns Over Time (Test Set)',
    xaxis_title='Date',
    yaxis_title='Return',
    hovermode='x unified' # 统一 hover 显示所有线条的数据
)

fig_time_series.show()

# 5.4 残差分布直方图
residuals = y_test.values - y_pred
residual_df = pd.DataFrame({'Residual': residuals})

fig_residuals = px.histogram(
    residual_df,
    x='Residual',
    nbins=50,
    title='Distribution of Residuals (Actual - Predicted)',
    labels={'Residual': 'Residual Value'},
    marginal='box' # 添加箱线图以显示分布特征
)

fig_residuals.update_layout(
    xaxis_title="Residual (Actual - Predicted)",
    yaxis_title="Count"
)

fig_residuals.show()